function M_k_q_rwlM____ = innerproduct_q_k_stretch_quad_stack____0(n_k_p_r,n_w_,n_M,M_k_q__,l_max);
n_w_max = max(n_w_);
n_w_sum = sum(n_w_);
M_k_q___ = zeros(n_w_sum,1+2*l_max,n_M);
for nM=0:n_M-1;
ic=0;
for nk_p_r=0:n_k_p_r-1;
for nw=0:n_w_(1+nk_p_r)-1;
n_w_t = floor(1.0d0*n_w_(1+nk_p_r)/2.0d0);
for l_val=-l_max:+l_max;
nwc = nw;
if (nwc>=n_w_t); nwc = nwc - n_w_(1+nk_p_r); end;%if;
flag_ict_overflow = 0;
nwd = nwc + l_val;
if (abs(nwd)<n_w_t); nwt = periodize(nwd,0,n_w_(1+nk_p_r));  else; nwt = 0; flag_ict_overflow = 1; end;%if;
ict = ic-nw+nwt;
if (flag_ict_overflow==0); M_k_q___(1+ic,1+l_max+l_val,1+nM) = M_k_q__(1+ict,1+nM); end;%if;
end;%for l_val=-l_max:+l_max;
ic = ic + 1;
end;%for nw=0:n_w_(1+nk_p_r)-1;
end;%for nk_p_r=0:n_k_p_r-1;
end;%for nM=0:n_M-1;
%%%%%%%%;
M_k_q_rwlM____ = reshape(innerproduct_q_k_stretch_quad_stack__0(n_k_p_r,n_w_/(2*pi),n_w_,(1+2*l_max)*n_M,reshape(M_k_q___,[n_w_sum,(1+2*l_max)*n_M])),[n_k_p_r,n_w_max,1+2*l_max,n_M]);
