function output = interp1_0(n_x,min_x,max_x,F_,x_loc);
% assumes regular grid for x;
% periodic boundary conditions;
x_loc = periodize(x_loc,min_x,max_x);
nx_d = n_x*(x_loc-min_x)/(max_x-min_x);
nx_pre = floor(nx_d);
dx_pre = abs(nx_pre - nx_d);
nx_pos = ceil(nx_d);
dx_pos = abs(nx_pos - nx_d);
if (nx_pos>=n_x);
nx_pos = nx_pos - n_x;
end;%if;
d_pre = (dx_pre);
d_pos = (dx_pos);
A = d_pre;
B = d_pos;
if (A+B<=0);
output = F_(1+nx_pre);
 else;
alpha = A/(A+B);
beta = B/(A+B);
output = beta*F_(1+nx_pre) + alpha*F_(1+nx_pos);
end;%if;
