%function test_arc_rotation_0();

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% generate image/template F ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
tic;
ng = 128; max_x_c = 1; max_k_c = ng/max_x_c; max_k_p = max_k_c/2;
% realspace carte grid ; 
grid_x_c_ = linspace(0,max_x_c,ng+1); grid_x_c_ = grid_x_c_(1:end-1); d_x_c = mean(diff(grid_x_c_));
% freqspace carte grid ; 
grid_k_c_ = (0:ng-1)/max_x_c; d_k_c = mean(diff(grid_k_c_));
% xxxxspace qring grid ;
grid_k_q_ = (0:ng-1) ; max_q = ng; qlim = [-2,+2]; grid_k_q2_ = grid_k_q_; grid_k_q2_(ng/2:end) = grid_k_q2_(ng/2:end)-ng;
% realspace carte meshgrid ;
[X_x_c_,Y_x_c_] = meshgrid(grid_x_c_,grid_x_c_); X_x_c_(:,ng/2+1:end) = X_x_c_(:,ng/2+1:end)-max_x_c; Y_x_c_(ng/2+1:end,:) = Y_x_c_(ng/2+1:end,:)-max_x_c;
R_x_c_ = sqrt(X_x_c_.^2 + Y_x_c_.^2); W_x_c_ = atan2(Y_x_c_,X_x_c_);
% freqspace carte meshgrid ;
[X_k_c_,Y_k_c_] = meshgrid(grid_k_c_,grid_k_c_); X_k_c_(:,ng/2+1:end) = X_k_c_(:,ng/2+1:end)-max_k_c; Y_k_c_(ng/2+1:end,:) = Y_k_c_(ng/2+1:end,:)-max_k_c;
R_k_c_ = sqrt(X_k_c_.^2 + Y_k_c_.^2); W_k_c_ = atan2(Y_k_c_,X_k_c_);
% realspace polar meshgrid ;
grid_x_r_ = linspace(0,max_x_c/2,ng+1); grid_x_r_ = grid_x_r_(1:end-1); grid_x_w_ = linspace(0,2*pi,ng+1); grid_x_w_ = grid_x_w_(1:end-1); 
[R_x_p_,W_x_p_] = meshgrid(grid_x_r_,grid_x_w_);
% freqspace polar meshgrid ;
grid_k_r_ = linspace(0,max_k_p,ng+1); grid_k_r_ = grid_k_r_(1:end-1); d_k_r = mean(diff(grid_k_r_));
grid_k_w_ = linspace(0,2*pi,ng+1); grid_k_w_ = grid_k_w_(1:end-1); d_k_w = mean(diff(grid_k_w_));
[R_k_p_,W_k_p_] = meshgrid(grid_k_r_,grid_k_w_);
X_k_p_ = R_k_p_.*cos(W_k_p_); Y_k_p_ = R_k_p_.*sin(W_k_p_);
% set up image/template on realspace carte meshgrid ;
n_F = 16; tmp_R_ = linspace(0.125,0.25,n_F); tmp_W_min = pi/4; tmp_W_max = 3*pi/4; tmp_dW = -1*pi/4;
F_x_c_ = zeros(ng,ng);
G_x_c_ = zeros(ng,ng);
for nF=1:4:n_F;
F_x_c_ = F_x_c_ + ( (R_x_c_>tmp_R_(nF+0)) & (R_x_c_<tmp_R_(nF+1)) & (W_x_c_>tmp_W_min) & (W_x_c_<tmp_W_max) );
G_x_c_ = G_x_c_ + ( (R_x_c_>tmp_R_(nF+0)) & (R_x_c_<tmp_R_(nF+1)) & (W_x_c_>tmp_W_min + tmp_dW) & (W_x_c_<tmp_W_max + tmp_dW) );
end;%for nF=1:n_F;
% Now translate F and G by the center of F ;
%tmp_delta_ = [0,0];
tmp_delta_ = [0,-2*pi*mean(tmp_R_)];
F_x_c_ = real(ifft2(fft2(F_x_c_).*exp(-i*(X_k_c_*tmp_delta_(1) + Y_k_c_*tmp_delta_(2)))));
G_x_c_ = real(ifft2(fft2(G_x_c_).*exp(-i*(X_k_c_*tmp_delta_(1) + Y_k_c_*tmp_delta_(2)))));
% Now center intensity (remove mean) ;
F_x_c_ = F_x_c_ - mean(F_x_c_(:));
G_x_c_ = G_x_c_ - mean(G_x_c_(:));
Flim_x = max(0,mean(F_x_c_(:)) + 1.0*std(F_x_c_(:))*[-1,+1]);
Glim_x = max(0,mean(G_x_c_(:)) + 1.0*std(G_x_c_(:))*[-1,+1]);
disp(sprintf(' %% calculating F_x_c_ G_x_c_: time %f',toc));

flag_disp=0;
if flag_disp;
subplot(1,2,1);imagesc(recenter2(real(F_x_c_)),Flim_x);title('real(F_x_c_)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);
subplot(1,2,2);imagesc(recenter2(real(G_x_c_)),Glim_x);title('real(G_x_c_)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);
return;
end;% if flag_disp;

tic;
grid_x_p_ = grid_x_r_;
n_x_r = length(grid_x_p_);
n_x_w_ = max(6,ceil(2*pi*grid_x_p_*n_x_r)); n_x_A = sum(n_x_w_); n_x_w_max = max(n_x_w_);
F_x_p_ = interp_c_to_p(ng,max_x_c,ng,max_x_c,F_x_c_,n_x_r,grid_x_p_,n_x_w_,n_x_A);
G_x_p_ = interp_c_to_p(ng,max_x_c,ng,max_x_c,G_x_c_,n_x_r,grid_x_p_,n_x_w_,n_x_A);
disp(sprintf(' %% calculating F_x_p_ G_x_p_: time %s',toc));
flag_disp=0;
if flag_disp;
subplot(2,2,1);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,real(F_x_p_),Flim_x,colormap(colormap_beach(64)));
subplot(2,2,2);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,real(G_x_p_),Glim_x,colormap(colormap_beach(64)));
subplot(2,2,3);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,imag(F_x_p_),Flim_x,colormap(colormap_beach(64)));
subplot(2,2,4);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,imag(G_x_p_),Glim_x,colormap(colormap_beach(64)));
return;
end;%if flag_disp;

tic;
l2_F_x_c = sum(abs(F_x_c_(:)).^2)*d_x_c*d_x_c;
% calculate image/template values on freqspace carte meshgrid ;
F_k_c_ = fft2(F_x_c_) * d_x_c*d_x_c; Flim_k  = mean(abs(F_k_c_(:))) + 1.0*std(abs(F_k_c_(:)))*[-1,+1];
l2_F_k_c = sum(abs(F_k_c_(:)).^2)*d_k_c*d_k_c;
F_tmp = ifft2(F_k_c_)./d_x_c./d_x_c; l2_F_tmp = sum(abs(F_tmp(:)).^2)*d_x_c*d_x_c;
disp(sprintf(' %% l2_F_x_c %f l2_F_k_c %f',l2_F_x_c,l2_F_k_c));
Flim_x = max(0,mean(abs(F_x_c_(:))) + 1.0*std(abs(F_x_c_(:)))*[-1,+1]);
l2_G_x_c = sum(abs(G_x_c_(:)).^2)*d_x_c*d_x_c;
% calculate image/template values on freqspace carte meshgrid ;
G_k_c_ = fft2(G_x_c_) * d_x_c*d_x_c; Glim_k  = mean(abs(G_k_c_(:))) + 1.0*std(abs(G_k_c_(:)))*[-1,+1];
l2_G_k_c = sum(abs(G_k_c_(:)).^2)*d_k_c*d_k_c;
G_tmp = ifft2(G_k_c_)./d_x_c./d_x_c; l2_G_tmp = sum(abs(G_tmp(:)).^2)*d_x_c*d_x_c;
disp(sprintf(' %% l2_G_x_c %f l2_G_k_c %f',l2_G_x_c,l2_G_k_c));
Glim_x = max(0,mean(abs(G_x_c_(:))) + 1.0*std(abs(G_x_c_(:)))*[-1,+1]);
disp(sprintf(' %% calculating F_k_c_ G_k_c_: time %f',toc));

tic;
grid_k_p_ = grid_k_r_;
n_k_r = length(grid_k_p_);
n_k_w_ = max(6,ceil(2*pi*grid_k_p_)); n_k_A = sum(n_k_w_); n_k_w_max = max(n_k_w_);
F_k_p_ = interp_c_to_p(ng,max_k_c,ng,max_k_c,F_k_c_,n_k_r,grid_k_p_,n_k_w_,n_k_A);
G_k_p_ = interp_c_to_p(ng,max_k_c,ng,max_k_c,G_k_c_,n_k_r,grid_k_p_,n_k_w_,n_k_A);
disp(sprintf(' %% calculating F_k_p_ G_k_p_: time %f',toc));
flag_disp=0;
if flag_disp;
subplot(2,2,1);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,real(F_k_p_),Flim_k,colormap(colormap_beach(64)));
subplot(2,2,2);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,real(G_k_p_),Glim_k,colormap(colormap_beach(64)));
subplot(2,2,3);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,imag(F_k_p_),Flim_k,colormap(colormap_beach(64)));
subplot(2,2,4);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,imag(G_k_p_),Glim_k,colormap(colormap_beach(64)));
return;
end;%if flag_disp;

tic;
F_k_q_ = interp_p_to_q(n_k_r,n_k_w_,n_k_A,F_k_p_);
G_k_q_ = interp_p_to_q(n_k_r,n_k_w_,n_k_A,G_k_p_);
C_q_ = innerproduct_q_k_only(n_k_r,grid_k_p_,n_k_w_,n_k_A,F_k_q_,G_k_q_)*n_k_r*2*pi;
disp(sprintf(' %% calculating C_q_: time %f',toc));
C_p_ = real(ifft(C_q_));
gamma_ = linspace(0,2*pi,n_k_w_(end)+1); gamma_ = gamma_(1:end-1);
flag_disp=0;
if flag_disp;
plot(gamma_,C_p_); xlabel('gamma'); ylabel('X(gamma)');
return;
end;%if flag_disp;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% Calculating C_F__(gamma_z,delta_x,delta_y) = < R_{gamma_z}(T_{delta_x,delta_y}(F)) , G >
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
tic;
N_pixels = 5.0; N_pixels_in = N_pixels; K_max = max_k_p; eps_target = 0.00001; l_max = 35;
[n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_] = gen_Jsvd_2(K_max,N_pixels,eps_target,l_max);
half_diameter_x_c = max_x_c/2; 
n_delta_x = 65; n_delta_y = 65;
[delta_x_,delta_y_] = get_delta_0(N_pixels_in,n_x_r,half_diameter_x_c,n_delta_x,n_delta_y);
Z_F_svdd_ = innerproduct_q_k_svdd_1(1,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,n_delta_x,delta_x_,n_delta_y,delta_y_,l_max);
G_k_q_ = interp_p_to_q(n_k_r,n_k_w_,n_k_A,G_k_p_);
disp(sprintf(' %% precomputation for C_q__: time %f',toc));
tic;
Z_F_svds_ = innerproduct_q_k_svds_1(1,n_svd_r,svd_r_,n_svd_l,svd_l_,svd_s_,svd_V_r_,n_k_r,grid_k_p_,n_k_w_,n_k_A,F_k_q_,G_k_q_);
disp(sprintf(' %% evaluating integrals associated with Z_F_svds_: time %f',toc));
tic;
for nl=0:n_svd_l-1;
Z_F_svds_(1+nl,:) = ifft(Z_F_svds_(1+nl,:))*n_k_r*2*pi;
end;%for nl=0:n_svd_l-1;
disp(sprintf(' %% performing fft associated with Z_F_svds_: time %f',toc));
n_gamma_z = max(n_k_w_);
gamma_z_ = get_gamma_0(n_gamma_z) + 1*3*pi/4;
C_q__ = transpose(Z_F_svdd_)*Z_F_svds_;
disp(sprintf(' %% performing matrix-matrix product to produce C_q__: time %f',toc));
tic;
C_F__ = zeros(n_gamma_z,n_delta_x,n_delta_y);
for ndx=0:n_delta_x-1; delta_x = delta_x_(1+ndx);
for ndy=0:n_delta_y-1; delta_y = delta_y_(1+ndy);
T_q_ = C_q__(1 + ndx + ndy*n_delta_x,:);
for ngz=0:n_gamma_z-1; gamma_z = gamma_z_(1+ngz);
C_F__(1+ngz,1+ndx,1+ndy) = interp1_0(n_k_w_max,0,2*pi,T_q_,gamma_z);
end;%for ngz=0:n_gamma_z-1; gamma_z = gamma_z_(1+ngz);
end;%for ndy=0:n_delta_y-1; delta_y = delta_y_(1+ndy);
end;%for ndx=0:n_delta_x-1; delta_x = delta_x_(1+ndx);
disp(sprintf(' %% interpolating C_q__ to calculate C_F__: time %f',toc));

flag_disp=0;
if flag_disp;
n_gamma = length(gamma_);
prows = 4;pcols = 6;
n_gamma_sample_ = max(1,min(n_gamma,floor(n_gamma*linspace(0,1,prows*pcols))));
Clim_ = [min(real(C_F__(:))),max(real(C_F__(:)))];
for ngamma_sample=1:length(n_gamma_sample_);
n_gamma_sample = n_gamma_sample_(ngamma_sample);
subplot(prows,pcols,ngamma_sample);
imagesc(real(squeeze(C_F__(n_gamma_sample,:,:))),Clim_); set(gca,'XTick',[],'YTick',[]); title(sprintf('gamma %0.2f',gamma_(n_gamma_sample)));
end;%for ngamma_sample=1:length(n_gamma_sample_);
end;%if flag_disp;

flag_disp=1;
if flag_disp;
n_gamma = length(gamma_);
prows = 7; pcols = 11; xgap = 1+floor(n_delta_x/8); ygap = 1+floor(n_delta_y/8);
gamma_sample_ = linspace(-pi,+pi,prows*pcols);
Clim_ = [min(real(C_F__(:))),max(real(C_F__(:)))]; Clim_(1) = Clim_(1) - diff(Clim_)/64;
C_F_ = zeros(xgap + prows*(n_delta_x+xgap),ygap + pcols*(n_delta_y+ygap)) + Clim_(1);
n_gamma_sample_ = zeros(prows*pcols,1);
for ngamma_sample=1:length(gamma_sample_);
tmp_ = gamma_ - gamma_sample_(ngamma_sample); for nl=1:length(tmp_); tmp_(nl) = periodize(tmp_(nl),-pi,+pi); end;
[~,n_gamma_sample_(ngamma_sample)] = min(abs(tmp_));
end;%for ngamma_sample=1:length(gamma_sample_);
prow = 0; pcol = 0;
for ngamma_sample=1:length(gamma_sample_);
n_gamma_sample = n_gamma_sample_(ngamma_sample);
C_F_(xgap + prow*(n_delta_x+xgap) + (1:n_delta_x),ygap + pcol*(n_delta_y+ygap) + (1:n_delta_y)) = real(squeeze(C_F__(n_gamma_sample,:,:)));
pcol = pcol + 1;
if pcol==pcols; pcol=0; prow = prow+1; end;
end;%for ngamma_sample=1:length(gamma_sample_);
c_ = colormap_beach(64); c_(1,:) = [1,1,1];
imagesc(C_F_,Clim_); set(gca,'XTick',[],'YTick',[]);
colormap(c_);
end;%if flag_disp;
