% compares the result of interp1_0 and interp1_nufft. ;
rng(1);
n_x = 8;
x_ = transpose(linspace(0,2*pi,n_x+1)); x_ = x_(1:end-1);
n_y = 1024;
y_ = transpose(linspace(0,2*pi,n_y+1)); y_ = y_(1:end-1);
n_z = 128;
z_ = 2*pi*rand(n_z,1);
%%%%%%%%;
%s = @(x_) sin(x_);
s = @(x_) sin(x_) + cos(2*x_) + sin(3*x_) + 0.1*cos(5*x_);
f_ = s(x_);
g_ = s(y_);
f1_ = zeros(n_z,1);
for nz=0:n_z-1;
f1_(1+nz) = interp1_0(n_x,0,2*pi,f_,z_(1+nz));
end;%for nz=0:n_z-1;
f2_ = real(interp1_nufft(n_x,0,2*pi,f_,z_));
subplot(1,2,1);
plot(x_,f_,'ko',y_,g_,'k-',z_,f1_,'ro',z_,f2_,'go');
xlabel('x'); ylabel('f'); title('compare interp1_0 and interp1_nufft','interpreter','none'); legend({'f','g','linear','nufft'});
title('sin series (with high-freq. modes)');
%%%%%%%%;
s = @(x_) sin(x_) + cos(2*x_) + sin(3*x_) + exp(-(x_-pi).^2/(2*(pi/2)^2));
f_ = s(x_);
g_ = s(y_);
f1_ = zeros(n_z,1);
for nz=0:n_z-1;
f1_(1+nz) = interp1_0(n_x,0,2*pi,f_,z_(1+nz));
end;%for nz=0:n_z-1;
f2_ = real(interp1_nufft(n_x,0,2*pi,f_,z_));
subplot(1,2,2);
plot(x_,f_,'ko',y_,g_,'k-',z_,f1_,'ro',z_,f2_,'go');
xlabel('x'); ylabel('f'); title('compare interp1_0 and interp1_nufft','interpreter','none'); legend({'f','g','linear','nufft'});
title('nonperiodic function');
%%%%%%%%;
set(gcf,'Position',1+[0,0,1024,512*2]);
