%function test_arc_rotation_0();

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% generate fnctn F ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
tic;
ng = 128; max_x_c = 1; max_k_c = ng/max_x_c; max_k_p = max_k_c/2;
% realspace carte grid ; 
grid_x_c_ = linspace(0,max_x_c,ng+1); grid_x_c_ = grid_x_c_(1:end-1); d_x_c = mean(diff(grid_x_c_));
% freqspace carte grid ; 
grid_k_c_ = (0:ng-1)/max_x_c; d_k_c = mean(diff(grid_k_c_));
% xxxxspace qring grid ;
grid_k_q_ = (0:ng-1) ; max_q = ng; qlim = [-2,+2]; grid_k_q2_ = grid_k_q_; grid_k_q2_(ng/2:end) = grid_k_q2_(ng/2:end)-ng;
% realspace carte meshgrid ;
[X_x_c_,Y_x_c_] = meshgrid(grid_x_c_,grid_x_c_); X_x_c_(:,ng/2+1:end) = X_x_c_(:,ng/2+1:end)-max_x_c; Y_x_c_(ng/2+1:end,:) = Y_x_c_(ng/2+1:end,:)-max_x_c;
R_x_c_ = sqrt(X_x_c_.^2 + Y_x_c_.^2); W_x_c_ = atan2(Y_x_c_,X_x_c_);
% freqspace carte meshgrid ;
[X_k_c_,Y_k_c_] = meshgrid(grid_k_c_,grid_k_c_); X_k_c_(:,ng/2+1:end) = X_k_c_(:,ng/2+1:end)-max_k_c; Y_k_c_(ng/2+1:end,:) = Y_k_c_(ng/2+1:end,:)-max_k_c;
R_k_c_ = sqrt(X_k_c_.^2 + Y_k_c_.^2); W_k_c_ = atan2(Y_k_c_,X_k_c_);
% realspace polar meshgrid ;
grid_x_r_ = linspace(0,max_x_c/2,ng+1); grid_x_r_ = grid_x_r_(1:end-1); grid_x_w_ = linspace(0,2*pi,ng+1); grid_x_w_ = grid_x_w_(1:end-1); 
[R_x_p_,W_x_p_] = meshgrid(grid_x_r_,grid_x_w_);
% freqspace polar meshgrid ;
grid_k_r_ = linspace(0,max_k_p,ng+1); grid_k_r_ = grid_k_r_(1:end-1); d_k_r = mean(diff(grid_k_r_));
grid_k_w_ = linspace(0,2*pi,ng+1); grid_k_w_ = grid_k_w_(1:end-1); d_k_w = mean(diff(grid_k_w_));
[R_k_p_,W_k_p_] = meshgrid(grid_k_r_,grid_k_w_);
X_k_p_ = R_k_p_.*cos(W_k_p_); Y_k_p_ = R_k_p_.*sin(W_k_p_);
% set up fnctn on realspace carte meshgrid ;
n_F = 16; tmp_R_ = linspace(0.125,0.25,n_F); tmp_W_min = pi/4; tmp_W_max = 3*pi/4; tmp_dW = -1*pi/4;
F_x_c_ = zeros(ng,ng);
G_x_c_ = zeros(ng,ng);
for nF=1:4:n_F;
F_x_c_ = F_x_c_ + ( (R_x_c_>tmp_R_(nF+0)) & (R_x_c_<tmp_R_(nF+1)) & (W_x_c_>tmp_W_min) & (W_x_c_<tmp_W_max) );
G_x_c_ = G_x_c_ + ( (R_x_c_>tmp_R_(nF+0)) & (R_x_c_<tmp_R_(nF+1)) & (W_x_c_>tmp_W_min + tmp_dW) & (W_x_c_<tmp_W_max + tmp_dW) );
end;%for nF=1:n_F;
% Now translate F and G by the center of F ;
%tmp_delta_ = [0,0];
tmp_delta_ = [0,-2*pi*mean(tmp_R_)];
F_x_c_ = real(ifft2(fft2(F_x_c_).*exp(-i*(X_k_c_*tmp_delta_(1) + Y_k_c_*tmp_delta_(2)))));
G_x_c_ = real(ifft2(fft2(G_x_c_).*exp(-i*(X_k_c_*tmp_delta_(1) + Y_k_c_*tmp_delta_(2)))));
% Now center intensity (remove mean) ;
F_x_c_ = F_x_c_ - mean(F_x_c_(:));
G_x_c_ = G_x_c_ - mean(G_x_c_(:));
Flim_x = max(0,mean(F_x_c_(:)) + 1.0*std(F_x_c_(:))*[-1,+1]);
Glim_x = max(0,mean(G_x_c_(:)) + 1.0*std(G_x_c_(:))*[-1,+1]);
disp(sprintf(' %% generate fnctn %f',toc));

flag_disp=0;
if flag_disp;
subplot(1,2,1);imagesc(recenter2(real(F_x_c_)),Flim_x);title('real(F_x_c_)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);
subplot(1,2,2);imagesc(recenter2(real(G_x_c_)),Glim_x);title('real(G_x_c_)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c_(1),grid_x_c_(end/2+1),floor(10*grid_x_c_(end))/10]-max_x_c/2);
return;
end;% if flag_disp;

flag_disp=0;
if flag_disp;
tic;
grid_x_p_ = grid_x_r_;
n_x_r = length(grid_x_p_);
n_x_w_ = max(6,ceil(2*pi*grid_x_p_*n_x_r)); n_x_A = sum(n_x_w_); n_x_w_max = max(n_x_w_);
F_x_p_ = interp_c_to_p(ng,max_x_c,ng,max_x_c,F_x_c_,n_x_r,grid_x_p_,n_x_w_,n_x_A);
G_x_p_ = interp_c_to_p(ng,max_x_c,ng,max_x_c,G_x_c_,n_x_r,grid_x_p_,n_x_w_,n_x_A);
disp(sprintf(' %% F_x_p_ G_x_p_ %s',toc));
subplot(2,2,1);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,real(F_x_p_),Flim_x,colormap(colormap_beach(64)));
subplot(2,2,2);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,real(G_x_p_),Glim_x,colormap(colormap_beach(64)));
subplot(2,2,3);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,imag(F_x_p_),Flim_x,colormap(colormap_beach(64)));
subplot(2,2,4);imagesc_p(n_x_r,grid_x_p_,n_x_w_,n_x_A,imag(G_x_p_),Glim_x,colormap(colormap_beach(64)));
return;
end;%if flag_disp;

tic;
l2_F_x_c = sum(abs(F_x_c_(:)).^2)*d_x_c*d_x_c;
% calculate fnctn values on freqspace carte meshgrid ;
F_k_c_ = fft2(F_x_c_) * d_x_c*d_x_c; Flim_k  = mean(abs(F_k_c_(:))) + 1.0*std(abs(F_k_c_(:)))*[-1,+1];
l2_F_k_c = sum(abs(F_k_c_(:)).^2)*d_k_c*d_k_c;
F_tmp = ifft2(F_k_c_)./d_x_c./d_x_c; l2_F_tmp = sum(abs(F_tmp(:)).^2)*d_x_c*d_x_c;
disp(sprintf(' %% l2_F_x_c %f l2_F_k_c %f',l2_F_x_c,l2_F_k_c));
Flim_x = max(0,mean(abs(F_x_c_(:))) + 1.0*std(abs(F_x_c_(:)))*[-1,+1]);
l2_G_x_c = sum(abs(G_x_c_(:)).^2)*d_x_c*d_x_c;
% calculate fnctn values on freqspace carte meshgrid ;
G_k_c_ = fft2(G_x_c_) * d_x_c*d_x_c; Glim_k  = mean(abs(G_k_c_(:))) + 1.0*std(abs(G_k_c_(:)))*[-1,+1];
l2_G_k_c = sum(abs(G_k_c_(:)).^2)*d_k_c*d_k_c;
G_tmp = ifft2(G_k_c_)./d_x_c./d_x_c; l2_G_tmp = sum(abs(G_tmp(:)).^2)*d_x_c*d_x_c;
disp(sprintf(' %% l2_G_x_c %f l2_G_k_c %f',l2_G_x_c,l2_G_k_c));
Glim_x = max(0,mean(abs(G_x_c_(:))) + 1.0*std(abs(G_x_c_(:)))*[-1,+1]);
disp(sprintf(' %% F_k_c_ G_k_c_ %f',toc));

tic;
grid_k_p_ = grid_k_r_;
n_k_r = length(grid_k_p_);
n_k_w_ = max(6,ceil(2*pi*grid_k_p_)); n_k_A = sum(n_k_w_); n_k_w_max = max(n_k_w_);
F_k_p_ = interp_c_to_p(ng,max_k_c,ng,max_k_c,F_k_c_,n_k_r,grid_k_p_,n_k_w_,n_k_A);
G_k_p_ = interp_c_to_p(ng,max_k_c,ng,max_k_c,G_k_c_,n_k_r,grid_k_p_,n_k_w_,n_k_A);
disp(sprintf(' %% F_k_p_ G_k_p_ %f',toc));
flag_disp=0;
if flag_disp;
subplot(2,2,1);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,real(F_k_p_),Flim_k,colormap(colormap_beach(64)));
subplot(2,2,2);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,real(G_k_p_),Glim_k,colormap(colormap_beach(64)));
subplot(2,2,3);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,imag(F_k_p_),Flim_k,colormap(colormap_beach(64)));
subplot(2,2,4);imagesc_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,imag(G_k_p_),Glim_k,colormap(colormap_beach(64)));
return;
end;%if flag_disp;

flag_disp=1;
if flag_disp;
tic;
F_k_q_ = interp_p_to_q(n_k_r,n_k_w_,n_k_A,F_k_p_);
G_k_q_ = interp_p_to_q(n_k_r,n_k_w_,n_k_A,G_k_p_);
C_q_ = innerproduct_q_k_only(n_k_r,grid_k_p_,n_k_w_,n_k_A,F_k_q_,G_k_q_)*n_k_r*2*pi;
disp(sprintf(' %% C_q_ %f',toc));
C_p_ = real(ifft(C_q_));
gamma_ = linspace(0,2*pi,n_k_w_(end)+1); gamma_ = gamma_(1:end-1);
plot(gamma_,C_p_); xlabel('gamma'); ylabel('X(gamma)');
return;
end;%if flag_disp;

flag_disp=1;
if flag_disp;
tic;
n_gamma = 129;
gamma_ = linspace(-pi,+pi,n_gamma);
C_p_ = zeros(n_gamma,1);
for ngamma=1:n_gamma;
gamma = gamma_(ngamma);
C_p_(ngamma) = innerproduct_p(n_k_r,grid_k_p_,n_k_w_,n_k_A,rotate_p_to_p(n_k_r,n_k_w_,n_k_A,F_k_p_,gamma),G_k_p_);
end;%for ngamma=1:n_gamma;
disp(sprintf(' %% C_p_ %f',toc));
plot(gamma_,C_p_); xlabel('gamma'); ylabel('X(gamma)');
return;
end;%if flag_disp;

