Z_M_svdd_ = MDA_read_c16('./dir_mda/Z_M_svdd_.mda');
S_q__ = MDA_read_c16('./dir_mda/S_q__nS0_0.mda');
Z_T_R_CTF_M_q__ = MDA_read_c16('./dir_mda/Z_T_R_CTF_M_q__nS0_0_nM0_0.mda');
S_x_Z_T_R_CTF_M_q__ = MDA_read_c16('./dir_mda/S_x_Z_T_R_CTF_M_q__nS0_0_nS1_0_nM0_0_nM1_0.mda');
F_S_Z_T_R_CTF_M_q__ = MDA_read_c16('./dir_mda/F_S_Z_T_R_CTF_M_q__nS0_0_nS1_0_nM0_0_nM1_0.mda');
Z_M_svdd_F_S_Z_T_R_CTF_M_q__ = MDA_read_c16('./dir_mda/Z_M_svdd_F_S_Z_T_R_CTF_M_q__nS0_0_nS1_0_nM0_0_nM1_0.mda');
% load from previous run. ;
S_x_T_T_R_CTF_M_q__ = MDA_read_c16('./dir_mda/S_x_T_T_R_CTF_M_q__nS0_0_nS1_0_nM0_0_nM1_0.mda');
n_svd_l = size(Z_M_svdd_,1);
n_delta = size(Z_M_svdd_,2);
n_r = size(S_q__,1);
n_S = size(S_q__,2);
n_w_max = size(S_q__,3);
assert(size(Z_T_R_CTF_M_q__,1)==n_r);
n_transf = size(Z_T_R_CTF_M_q__,2);
n_M = size(Z_T_R_CTF_M_q__,3);
assert(size(Z_T_R_CTF_M_q__,4)==n_w_max);
assert(size(S_x_Z_T_R_CTF_M_q__,1)==n_S);
assert(size(S_x_Z_T_R_CTF_M_q__,2)==n_transf);
assert(size(S_x_Z_T_R_CTF_M_q__,3)==n_M);
assert(size(S_x_Z_T_R_CTF_M_q__,4)==n_w_max);
assert(size(F_S_Z_T_R_CTF_M_q__,1)==n_transf);
assert(size(F_S_Z_T_R_CTF_M_q__,2)==n_S);
assert(size(F_S_Z_T_R_CTF_M_q__,3)==n_M);
assert(size(F_S_Z_T_R_CTF_M_q__,4)==n_w_max);
n_delta = size(Z_M_svdd_F_S_Z_T_R_CTF_M_q__,1);
assert(size(Z_M_svdd_F_S_Z_T_R_CTF_M_q__,2)==n_S);
assert(size(Z_M_svdd_F_S_Z_T_R_CTF_M_q__,3)==n_M);
assert(size(Z_M_svdd_F_S_Z_T_R_CTF_M_q__,4)==n_w_max);
% load from previous run. ;
assert(size(S_x_T_T_R_CTF_M_q__,1)==n_S);
assert(size(S_x_T_T_R_CTF_M_q__,2)==n_delta);
assert(size(S_x_T_T_R_CTF_M_q__,3)==n_M);
assert(size(S_x_T_T_R_CTF_M_q__,4)==n_w_max);

E1_ = zeros(n_S*n_M,n_w_max);
E2_ = zeros(n_S*n_M,n_w_max);
E3_ = zeros(n_S*n_M,n_w_max);
for nw_max=0:n_w_max-1;
for nM=0:n_M-1;
for nS=0:n_S-1;
S_q_ = squeeze(S_q__(:,1+nS,1+nw_max));
Z_T_R_CTF_M_q_ = squeeze(Z_T_R_CTF_M_q__(:,:,1+nM,1+nw_max));
tmp_ = transpose(S_q_)*Z_T_R_CTF_M_q_;
E1 = norm(tmp_,'fro');
S_x_Z_T_R_CTF_M_q_ = squeeze(S_x_Z_T_R_CTF_M_q__(1+nS,:,1+nM,1+nw_max));
E2 = norm(S_x_Z_T_R_CTF_M_q_,'fro');
E3 = norm(S_x_Z_T_R_CTF_M_q_ - tmp_,'fro')/E1;
E1_(1+nS+nM*n_S,1+nw_max) = E1;
E2_(1+nS+nM*n_S,1+nw_max) = E2;
E3_(1+nS+nM*n_S,1+nw_max) = E3;
end;%for nS=0:n_S-1;
end; %for nM=0:n_M-1;
end; %for nw_max=0:n_w_max-1;

figure(1);
subplot(1,3,1); imagesc(log10(E1_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(S_q_*Z_T_R_CTF_M_q))','Interpreter','none');
subplot(1,3,2); imagesc(log10(E2_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(S_x_Z_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,3); imagesc(log10(E3_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(difference))','Interpreter','none');
set(gcf,'Position',1+[0,0,1024*1.5,512]);

E4_ = zeros(n_transf,n_S*n_M);
for nM=0:n_M-1;
for nS=0:n_S-1;
for ntransf=0:n_transf-1;
tmp0_ = squeeze(S_x_Z_T_R_CTF_M_q__(1+nS,1+ntransf,1+nM,:));
tmp1_ = ifft(tmp0_)*n_w_max;
tmp2_ = squeeze(F_S_Z_T_R_CTF_M_q__(1+ntransf,1+nS,1+nM,:));
E4 = norm(tmp1_ - tmp2_,'fro')./norm(tmp1_,'fro');
E4_(1+ntransf,1+nS+nM*n_S) = E4;
end;%for ntransf=0:n_transf-1;
end;%for nS=0:n_S-1;
end; %for nM=0:n_M-1;

figure(2);
subplot(1,1,1); imagesc(log10(E4_)); colorbar; 
xlabel('nS,nM');ylabel('ntransf');
title('log10(norm(ifft(S_x_Z_T_R_CTF_M_q__)*n_w_max - F_S_Z_T_R_CTF_M_q__))','Interpreter','none');
set(gcf,'Position',1+[0,0,1024,1024]);

E5_ = zeros(n_S*n_M,n_w_max);
E6_ = zeros(n_S*n_M,n_w_max);
E7_ = zeros(n_S*n_M,n_w_max);
for nw_max=0:n_w_max-1;
for nM=0:n_M-1;
for nS=0:n_S-1;
F_S_Z_T_R_CTF_M_q_ = squeeze(F_S_Z_T_R_CTF_M_q__(:,1+nS,1+nM,1+nw_max));
tmp0_ = transpose(Z_M_svdd_)*F_S_Z_T_R_CTF_M_q_;
tmp1_ = squeeze(Z_M_svdd_F_S_Z_T_R_CTF_M_q__(:,1+nS,1+nM,1+nw_max));
E5 = norm(tmp0_,'fro');
E6 = norm(tmp1_,'fro');
E7 = norm(tmp0_ - tmp1_,'fro')/E5;
E5_(1+nS+nM*n_S,1+nw_max) = E5;
E6_(1+nS+nM*n_S,1+nw_max) = E6;
E7_(1+nS+nM*n_S,1+nw_max) = E7;
end;%for nS=0:n_S-1;
end; %for nM=0:n_M-1;
end; %for nw_max=0:n_w_max-1;

figure(3);
subplot(1,3,1); imagesc(log10(E5_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(Z_M_svdd_*F_S_Z_T_R_CTF_M_q__))','Interpreter','none');
subplot(1,3,2); imagesc(log10(E6_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,3); imagesc(log10(E7_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(difference))','Interpreter','none');
set(gcf,'Position',1+[0,0,1024*1.5,512]);

F_S_T_T_R_CTF_M_q__ = zeros(n_delta,n_S,n_M,n_w_max);
for ndelta=0:n_delta-1;
for nM=0:n_M-1;
for nS=0:n_S-1;
tmp0_ = squeeze(S_x_T_T_R_CTF_M_q__(1+nS,1+ndelta,1+nM,:));
tmp1_ = ifft(tmp0_)*n_w_max;
F_S_T_T_R_CTF_M_q__(1+ndelta,1+nS,1+nM,:) = tmp1_;
end;%for nS=0:n_S-1;
end;%for nM=0:n_M-1;
end; %for ndelta=0:n_delta-1;

E8_ = zeros(n_S*n_M,n_w_max);
E9_ = zeros(n_S*n_M,n_w_max);
EA_ = zeros(n_S*n_M,n_w_max);
for nw_max=0:n_w_max-1;
for nM=0:n_M-1;
for nS=0:n_S-1;
F_S_T_T_R_CTF_M_q_ = squeeze(F_S_T_T_R_CTF_M_q__(:,1+nS,1+nM,1+nw_max));
Z_M_svdd_F_S_Z_T_R_CTF_M_q_ = squeeze(Z_M_svdd_F_S_Z_T_R_CTF_M_q__(:,1+nS,1+nM,1+nw_max));
E8 = norm(F_S_T_T_R_CTF_M_q_,'fro');
E9 = norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_,'fro');
EA = norm(F_S_T_T_R_CTF_M_q_ - Z_M_svdd_F_S_Z_T_R_CTF_M_q_,'fro')/E8;
E8_(1+nS+nM*n_S,1+nw_max) = E8;
E9_(1+nS+nM*n_S,1+nw_max) = E9;
EA_(1+nS+nM*n_S,1+nw_max) = EA;
end;%for nS=0:n_S-1;
end; %for nM=0:n_M-1;
end; %for nw_max=0:n_w_max-1;

figure(4);
subplot(1,3,1); imagesc(log10(E8_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(F_S_T_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,2); imagesc(log10(E9_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,3); imagesc(log10(EA_)); colorbar; 
xlabel('nw');ylabel('nS,nM');
title('log10(norm(difference))','Interpreter','none');
set(gcf,'Position',1+[0,0,1024*1.5,512]);

E8_ = zeros(n_delta,n_S*n_M);
E9_ = zeros(n_delta,n_S*n_M);
EA_ = zeros(n_delta,n_S*n_M);
for nM=0:n_M-1;
for nS=0:n_S-1;
for ndelta=0:n_delta-1;
F_S_T_T_R_CTF_M_q_ = squeeze(F_S_T_T_R_CTF_M_q__(1+ndelta,1+nS,1+nM,:));
Z_M_svdd_F_S_Z_T_R_CTF_M_q_ = squeeze(Z_M_svdd_F_S_Z_T_R_CTF_M_q__(1+ndelta,1+nS,1+nM,:));
E8 = norm(F_S_T_T_R_CTF_M_q_,'fro');
E9 = norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_,'fro');
EA = norm(F_S_T_T_R_CTF_M_q_ - Z_M_svdd_F_S_Z_T_R_CTF_M_q_,'fro')/E8;
E8_(1+ndelta,1+nS+nM*n_S) = E8;
E9_(1+ndelta,1+nS+nM*n_S) = E9;
EA_(1+ndelta,1+nS+nM*n_S) = EA;
end; %for ndelta=0:n_delta-1;
end;%for nS=0:n_S-1;
end; %for nM=0:n_M-1;

figure(5);
subplot(1,3,1); imagesc(log10(E8_)); colorbar; 
ylabel('ndelta');xlabel('nS,nM');
title('log10(norm(F_S_T_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,2); imagesc(log10(E9_)); colorbar; 
ylabel('ndelta');xlabel('nS,nM');
title('log10(norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,3); imagesc(log10(EA_)); colorbar; 
ylabel('ndelta');xlabel('nS,nM');
title('log10(norm(difference))','Interpreter','none');
set(gcf,'Position',1+[0,0,1024*1.5,512]);

n_delta_x = sqrt(n_delta);
n_delta_y = sqrt(n_delta);
EB_ = zeros(n_delta_x,n_delta_y);
EC_ = zeros(n_delta_x,n_delta_y);
ED_ = zeros(n_delta_x,n_delta_y);
for ndelta_x=0:n_delta_x-1;
for ndelta_y=0:n_delta_y-1;
ndelta = ndelta_x+ndelta_y*n_delta_x;
F_S_T_T_R_CTF_M_q_ = squeeze(F_S_T_T_R_CTF_M_q__(1+ndelta,:,:,:));
Z_M_svdd_F_S_Z_T_R_CTF_M_q_ = squeeze(Z_M_svdd_F_S_Z_T_R_CTF_M_q__(1+ndelta,:,:,:));
EB = norm(F_S_T_T_R_CTF_M_q_(:),'fro');
EC = norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_(:),'fro');
ED = norm(F_S_T_T_R_CTF_M_q_(:) - Z_M_svdd_F_S_Z_T_R_CTF_M_q_(:),'fro')/EB;
EB_(1+ndelta_x,1+ndelta_y) = EB;
EC_(1+ndelta_x,1+ndelta_y) = EC;
ED_(1+ndelta_x,1+ndelta_y) = ED;
end;%for ndelta_y=0:n_delta_y-1;
end;%for ndelta_x=0:n_delta_x-1;

figure(7);
subplot(1,3,1); imagesc(log10(EB_)); colorbar; 
xlabel('ndelta_y');ylabel('ndelta_x');
title('log10(norm(F_S_T_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,2); imagesc(log10(EC_)); colorbar; 
xlabel('ndelta_y');ylabel('ndelta_x');
title('log10(norm(Z_M_svdd_F_S_Z_T_R_CTF_M_q_))','Interpreter','none');
subplot(1,3,3); imagesc(log10(ED_)); colorbar; 
xlabel('ndelta_y');ylabel('ndelta_x');
title('log10(norm(difference))','Interpreter','none');
set(gcf,'Position',1+[0,0,1024*1.5,512]);

