function ...
[ ...
 parameter ...
,a_UCTF_UX_Y_ync__ ...
,Residual_wnM__ ...
] = ...
a_UCTF_UX_Y_wrap_ync__0( ...
 parameter ...
,pm_n_k_p_r ...
,pm_l_max_ ...
,pm_n_w_ ...
,n_M ...
,UX_M_k_p_wnM__ ...
,n_CTF_rank ...
,VSCTF_Mc__ ...
,euler_polar_a_ ...
,euler_azimu_b_ ...
,euler_gamma_z_ ...
,image_I_value_ ...
);
%%%%%%%%;
% calls either qbp_pm or cg_lsq_pm. ;
%%%%%%%%;

if nargin<1;
%%%%%%%%;
% First define integral of <f,f>. ;
%%%%%%%%;
h2d_ = @(kd) 4*pi^2*(besselj(0,kd) + besselj(2,kd)); % calculates <f_j,f_k>, normalized so that <f,f> = (4*pi^2);
dh2d_ = @(kd) 4*pi^3*(besselj(-1,kd) - besselj(+3,kd));
h3d_ = @(kd) 4*pi*( sin(kd) - (kd).*cos(kd) ) ./ kd.^3 ; % calculates <f_j,f_k>, normalized so that <f,f> = 4*pi/3;
dh3d_ = @(kd) 12*pi*( (kd.^2/3 - 1) .* sin(kd) + (kd).*cos(kd) ) ./ kd.^4 ;
%%%%%%%%;
verbose=1;
k_p_r_max = 48/(2*pi); k_eq_d = 1.0/(2*pi); TorL = 'L';
if (verbose); disp(sprintf(' %% [testing a_UCTF_UX_Y_wrqp_ync__0.m]')); end;
%%%%%%%%;
tmp_t = tic();
[ ...
 n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_all_ ...
,k_c_1_all_ ...
,k_c_2_all_ ...
,J_node_ ...
,J_weight_ ...
,J_chebfun_ ...
,J_polyval_ ...
] = ...
sample_sphere_7( ...
 verbose ...
,k_p_r_max ...
,k_eq_d ...
,TorL ...
) ;
tmp_t = toc(tmp_t); if (verbose>1); disp(sprintf(' %% sample_sphere_7: %0.2fs',tmp_t)); end;
if (verbose); disp(sprintf(' %% k_p_r_max %0.2f k_eq_d %0.2f n_k_all %d n_k_p_r %d',k_p_r_max,k_eq_d,n_k_all,n_k_p_r)); end;
%%%%%%%%;
l_max_upb = 36;
l_max_ = zeros(n_k_p_r,1);
for nk_p_r=0:n_k_p_r-1;
l_max_(1+nk_p_r) = max(0,min(l_max_upb,1+ceil(2*pi*k_p_r_(1+nk_p_r))));
end;%for nk_p_r=0:n_k_p_r-1;
n_lm_ = (l_max_+1).^2;
n_lm_max = max(n_lm_);
n_lm_sum = sum(n_lm_);
n_lm_csum_ = cumsum([0;n_lm_]);
l_max_max = max(l_max_); dWtdkd__l_max_max = 2*l_max_max;
m_max_ = -l_max_max : +l_max_max;
n_m_max = length(m_max_);
%%%%%%%%;
delta_orig_ = [+0.12;-0.3;+0.23];
a_k_p_orig_ = exp(+2*pi*i*(k_c_0_all_*delta_orig_(1+0) + k_c_1_all_*delta_orig_(1+1) + k_c_2_all_*delta_orig_(1+2)));
%%%%%%%%;
delta_orig_r012 = sqrt(delta_orig_(1+0)^2 + delta_orig_(1+1)^2 + delta_orig_(1+2)^2);
delta_orig_r01 = sqrt(delta_orig_(1+0)^2 + delta_orig_(1+1)^2);
delta_orig_polar_a = atan2(delta_orig_r01,delta_orig_(1+2));
delta_orig_azimu_b = atan2(delta_orig_(1+1),delta_orig_(1+0));
delta_Ylm_ = get_Ylm__(1+l_max_max,0:l_max_max,1,delta_orig_azimu_b,delta_orig_polar_a);
a_k_Y_form_ = zeros(n_lm_sum,1);
na=0;
for nk_p_r=0:n_k_p_r-1;
k_p_r = k_p_r_(1+nk_p_r);
l_max = l_max_(1+nk_p_r);
for l_val=0:l_max;
tmp_x = 2*pi*k_p_r*delta_orig_r012;
tmp_jl = besselj(l_val+0.5,tmp_x)*sqrt(pi/(2*tmp_x));
for m_val=-l_val:+l_val;
a_k_Y_form_(1+na) = 4*pi * i^l_val * tmp_jl * conj(delta_Ylm_{1+l_val}(1+m_val+l_val));
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
end;%for nk_p_r=0:n_k_p_r-1;
assert(na==n_lm_sum);
%%%%%%%%;
% a_k_Y_form_ represents a_k_p_orig_. ;
%%%%%%%%;
n_w_max = 160;
template_k_eq_d = -1;
viewing_k_eq_d = k_eq_d*8;
tmp_t = tic();
[ ...
 S_k_p__ ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_all_ ...
,n_viewing_all ...
,viewing_azimu_b_all_ ...
,viewing_polar_a_all_ ...
,viewing_weight_all_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,template_k_c_0__ ...
,template_k_c_1__ ...
,template_k_c_2__ ...
] = ...
get_template_1( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_form_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_max*ones(n_k_p_r,1) ...
);
tmp_t = toc(tmp_t); if (verbose>1); disp(sprintf(' %% get_template_1: %0.2fs',tmp_t)); end;
if (verbose); disp(sprintf(' %% n_viewing_all %d n_viewing_polar_a %d n_w_max %d',n_viewing_all,n_viewing_polar_a,max(n_w_))); end;
n_S = n_viewing_all; n_w_max = max(n_w_); n_w_sum = sum(n_w_); n_w_csum_ = cumsum([0;n_w_]);
%%%%%%%%;
% now extract the last few shells. ;
% Assume that UX__ = eye(n_shell). ;
%%%%%%%%;
n_shell = 4;
n_M = n_S;
n_CTF_rank = 3; %<-- Note that below we allow the second and third CTF modes to be large; this violates the qbp assumption. ;
rng(0); [tmp_Q_,~] = qr(randn(n_CTF_rank)); tmp_f_ = 1+rand(n_M,1);
VSCTF_Mc__ = zeros(n_M,n_CTF_rank);
VSCTF_Mc__ = tmp_f_*tmp_Q_(1,:);
UX_M_k_p_wnM__ = bsxfun(@times,S_k_p__( 1 + n_w_csum_(1+n_k_p_r-n_shell) + [0:n_w_max*n_shell-1] , 1:n_M ),transpose(tmp_f_));
%%%%%%%%;
a_UCTF_UX_Y_form_ync__ = zeros(n_lm_max*n_shell,n_CTF_rank);
na=0;
for nshell=0:n_shell-1;
nk_p_r = n_k_p_r - n_shell + nshell;
k_p_r = k_p_r_(1+nk_p_r);
l_max = l_max_max;
for l_val=0:l_max;
tmp_x = 2*pi*k_p_r*delta_orig_r012;
tmp_jl = besselj(l_val+0.5,tmp_x)*sqrt(pi/(2*tmp_x));
for m_val=-l_val:+l_val;
a_UCTF_UX_Y_form_ync__(1+na,1) = 4*pi * i^l_val * tmp_jl * conj(delta_Ylm_{1+l_val}(1+m_val+l_val));
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
end;%for nshell=0:n_shell-1;
assert(na==n_lm_max*n_shell);
a_UCTF_UX_Y_form_ync__ = a_UCTF_UX_Y_form_ync__*tmp_Q_;
%%%%%%%%;
pm_n_k_p_r = n_shell;
pm_l_max_ = l_max_max*ones(pm_n_k_p_r,1);
pm_n_w_ = n_w_max*ones(pm_n_k_p_r,1);
pm_n_w_sum = sum(pm_n_w_);
euler_polar_a_ = viewing_polar_a_all_;
euler_azimu_b_ = viewing_azimu_b_all_;
rng(0);
euler_gamma_z_ = 2*pi*rand(n_M,1);
image_I_value_ = ones(n_M,1);
for nM=0:n_M-1;
UX_M_k_p_wnM__(:,1+nM) = rotate_p_to_p_fftw(pm_n_k_p_r,pm_n_w_,pm_n_w_sum,UX_M_k_p_wnM__(:,1+nM),+euler_gamma_z_(1+nM));
end;%for nM=0:n_M-1;
%%%%%%%%;
tmp_t = tic();
parameter = struct('type','parameter');
parameter.flag_qbp_vs_lsq = 0;
[ ...
 parameter ...
,a_UCTF_UX_Y_0lsq_ync__ ...
,Residual_wnM__ ...
] = ...
a_UCTF_UX_Y_wrap_ync__0( ...
 parameter ...
,pm_n_k_p_r ...
,pm_l_max_ ...
,pm_n_w_ ...
,n_M ...
,UX_M_k_p_wnM__ ...
,n_CTF_rank ...
,VSCTF_Mc__ ...
,euler_polar_a_ ...
,euler_azimu_b_ ...
,euler_gamma_z_ ...
,image_I_value_ ...
);
tmp_t = toc(tmp_t);
if (verbose); disp(sprintf(' %% lsq: %.6fs',tmp_t)); end;
%%%%%%%%;
disp(sprintf(' %% a_UCTF_UX_Y_form_ync__ vs a_UCTF_UX_Y_0lsq_ync__: %0.16f',fnorm(a_UCTF_UX_Y_form_ync__ - a_UCTF_UX_Y_0lsq_ync__)/fnorm(a_UCTF_UX_Y_form_ync__)));
disp(sprintf(' %% Residual_wnM__ vs UX_M_k_p_wnM__: %0.16f',fnorm(Residual_wnM__)/fnorm(bsxfun(@times,UX_M_k_p_wnM__,transpose(image_I_value_)))));
disp(sprintf(' %% corr(a_UCTF_UX_Y_form_ync__,a_UCTF_UX_Y_0lsq_ync__): %0.16f',corr(a_UCTF_UX_Y_form_ync__(:),a_UCTF_UX_Y_0lsq_ync__(:))));
%%%%%%%%;
tmp_t = tic();
parameter = struct('type','parameter');
parameter.flag_qbp_vs_lsq = 1;
[ ...
 parameter ...
,a_UCTF_UX_Y_0qbp_ync__ ...
] = ...
a_UCTF_UX_Y_wrap_ync__0( ...
 parameter ...
,pm_n_k_p_r ...
,pm_l_max_ ...
,pm_n_w_ ...
,n_M ...
,UX_M_k_p_wnM__ ...
,n_CTF_rank ...
,VSCTF_Mc__ ...
,euler_polar_a_ ...
,euler_azimu_b_ ...
,euler_gamma_z_ ...
,image_I_value_ ...
);
tmp_t = toc(tmp_t);
if (verbose); disp(sprintf(' %% qbp: %.6fs',tmp_t)); end;
%%%%%%%%;
disp(sprintf(' %% a_UCTF_UX_Y_form_ync__ vs a_UCTF_UX_Y_0qbp_ync__: %0.16f',fnorm(a_UCTF_UX_Y_form_ync__ - a_UCTF_UX_Y_0qbp_ync__)/fnorm(a_UCTF_UX_Y_form_ync__)));
disp(sprintf(' %% corr(a_UCTF_UX_Y_form_ync__,a_UCTF_UX_Y_0qbp_ync__): %0.16f',corr(a_UCTF_UX_Y_form_ync__(:),a_UCTF_UX_Y_0qbp_ync__(:))));
%%%%%%%%;
disp('returning'); return;
end;% if nargin<1;

verbose=0;
if (verbose>0); disp(sprintf(' %% [entering a_UCTF_UX_Y_wrap_ync__0]')); end;

if isempty(parameter);
parameter = struct('type','parameter');
end;%if isempty(parameter);
%%%%%%%%;
if (~isfield(parameter,'flag_qbp_vs_lsq')); parameter.flag_qbp_vs_lsq = 0; end; %<-- parameter_bookmark. ;
if (~isfield(parameter,'flag_I_value_vs_1')); parameter.I_value_vs_1 = 0; end; %<-- parameter_bookmark. ;
flag_qbp_vs_lsq = parameter.flag_qbp_vs_lsq;
flag_I_value_vs_1 = parameter.I_value_vs_1;

if (flag_I_value_vs_1==0); image_I_value_ = ones(n_M,1); end;
pm_n_w_sum = sum(pm_n_w_);

if (flag_qbp_vs_lsq==1);
Residual_wnM__ = zeros(pm_n_w_sum,n_M);
tmp_t = tic();
[ ...
 parameter ...
,a_UCTF_UX_Y_ync__ ... 
] = ...
qbp_pm_1( ...
 parameter ...
,pm_n_k_p_r ...
,pm_l_max_ ...
,pm_n_w_ ...
,n_M ...
,UX_M_k_p_wnM__ ...
,n_CTF_rank ...
,VSCTF_Mc__ ...
,euler_polar_a_ ...
,euler_azimu_b_ ...
,euler_gamma_z_ ...
,image_I_value_ ...
);
tmp_t = toc(tmp_t); if (verbose>1); disp(sprintf(' %% qbp_pm_1 for a_UCTF_UX_Y_ync__: %0.3fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'qbp_pm_1',tmp_t);
end;%if (flag_qbp_vs_lsq==0);
%%%%%%%%;
if (flag_qbp_vs_lsq==0);
tmp_t = tic();
[ ...
 parameter ...
,a_UCTF_UX_Y_ync__ ... 
,Residual_wnM__ ...
] = ...
cg_lsq_pm_2( ...
 parameter ...
,pm_n_k_p_r ...
,pm_l_max_ ...
,pm_n_w_ ...
,n_M ...
,UX_M_k_p_wnM__ ...
,n_CTF_rank ...
,VSCTF_Mc__ ...
,euler_polar_a_ ...
,euler_azimu_b_ ...
,euler_gamma_z_ ...
,image_I_value_ ...
);
tmp_t = toc(tmp_t); if (verbose>1); disp(sprintf(' %% cg_lsq_pm_2 for a_UCTF_UX_Y_ync__: %0.3fs',tmp_t)); end;
parameter = parameter_timing_update(parameter,'cg_lsq_pm_2',tmp_t);
end;%if (flag_qbp_vs_lsq==0);
%%%%%%%%;

if (verbose>0); disp(sprintf(' %% [finished a_UCTF_UX_Y_wrap_ync__0]')); end;
