function ...
[ ...
 parameter ...
] = ...
ampmut_align_to_reference_0( ...
 parameter ...
,l_max_max ...
,pm_n_UX_rank ...
,a_CTF_avg_UX_Y_true_ ...
,n_M ...
,euler_polar_a_true_ ...
,euler_azimu_b_true_ ...
,euler_gamma_z_true_ ...
,image_delta_x_true_ ...
,image_delta_y_true_ ...
,n_iteration ...
,a_CTF_avg_UX_Y_calc__ ...
,euler_polar_a_calc__ ...
,euler_azimu_b_calc__ ...
,euler_gamma_z_calc__ ...
,image_delta_x_calc__ ...
,image_delta_y_calc__ ...
);

verbose=2;
if (verbose); disp(sprintf(' %% [entering ampmut_align_to_reference_0]')); end;
if isempty(parameter);
parameter = struct('type','parameter');
end;%if isempty(parameter);

pm_n_k_p_r = pm_n_UX_rank;
pm_k_p_r_ = ones(pm_n_k_p_r,1);
pm_k_p_r_max = 1;
pm_l_max_ = l_max_max*ones(pm_n_k_p_r,1);
pm_n_lm_ = (1+pm_l_max_).^2; pm_n_lm_sum = sum(pm_n_lm_);
pm_weight_3d_k_p_r_ = ones(pm_n_k_p_r,1);
pm_weight_2d_k_p_r_ = ones(pm_n_k_p_r,1);
a_CTF_avg_UX_Y_flip_ = flipY(pm_n_k_p_r,pm_l_max_,a_CTF_avg_UX_Y_true_);
delta_sigma = 1.0 * std([image_delta_x_true_(1:n_M);image_delta_y_true_(1:n_M)],1); %<-- no reduction. ;
dscale = 2.5;

c2d_euler__ = colormap_polar_a_azimu_b_2d(+euler_polar_a_true_(1:n_M),+euler_azimu_b_true_(1:n_M),0.35);
markersize_euler = 25;
c2d_delta__ = colormap_gaussian_2d(+image_delta_x_true_(1:n_M),+image_delta_y_true_(1:n_M),dscale*delta_sigma,0.35);
markersize_delta = 25;
figure(3); clf; figbig; 
p_row = 4; p_col = 3*ceil((1+n_iteration)/p_row); np=0;
%%%%%%%%;
subplot(p_row,p_col,1+np+[0,1]); np=np+2;
hold on;
patch(2*pi*[+0;+1;+1;+0],1*pi*[+0;+0;+1;+1],0.65*[1,1,1],'EdgeColor','none');
scatter(0*pi+euler_azimu_b_true_(1:n_M),1*pi-euler_polar_a_true_(1:n_M),markersize_euler,c2d_euler__(1:n_M,:),'filled');
hold off;
axisnotick;
axis([0,2*pi,0,1*pi]); axis equal; xlabel('azimu_b'); ylabel('polar_a'); title('true view');
%%%%%%%%;
subplot(p_row,p_col,1+np); np=np+1;
hold on;
patch(dscale*delta_sigma*[-1;+1;+1;-1],dscale*delta_sigma*[-1;-1;+1;+1],'k');
scatter(+image_delta_x_true_(1:n_M),+image_delta_y_true_(1:n_M),markersize_delta,c2d_delta__(1:n_M,:),'filled');
hold off;
axisnotick;
axis(dscale*delta_sigma*[-1,+1,-1,+1]); axis square; xlabel('dx'); ylabel('dy'); title('true delta');
%%%%%%%%;
for niteration=0:n_iteration-1;
%%%%%%%%;
N_wavelength = 0.0;
[ ...
 X_best_orig ...
,polar_a_best_orig ...
,azimu_b_best_orig ...
,gamma_z_best_orig ...
,delta_best_orig_ ...
,a_k_Y_best_orig_ ...
,b_k_Y_best_orig_ ...
] = ...
register_spharm_to_spharm_wigner_1( ...
 pm_n_k_p_r ...
,pm_k_p_r_ ...
,pm_k_p_r_max ...
,pm_weight_3d_k_p_r_ ...
,N_wavelength ...
,pm_l_max_ ...
,a_CTF_avg_UX_Y_true_ ...
,a_CTF_avg_UX_Y_calc__(:,1+niteration) ...
);
[ ...
 X_best_flip ...
,polar_a_best_flip ...
,azimu_b_best_flip ...
,gamma_z_best_flip ...
,delta_best_flip_ ...
,a_k_Y_best_flip_ ...
,b_k_Y_best_flip_ ...
] = ...
register_spharm_to_spharm_wigner_1( ...
 pm_n_k_p_r ...
,pm_k_p_r_ ...
,pm_k_p_r_max ...
,pm_weight_3d_k_p_r_ ...
,N_wavelength ...
,pm_l_max_ ...
,a_CTF_avg_UX_Y_flip_ ...
,flipY(pm_n_k_p_r,pm_l_max_,a_CTF_avg_UX_Y_calc__(:,1+niteration)) ...
);
%%%%%%%%;
if (X_best_orig>=X_best_flip);
flip_flag = 0;
X_best = X_best_orig;
polar_a_best = polar_a_best_orig;
azimu_b_best = azimu_b_best_orig;
gamma_z_best = gamma_z_best_orig;
delta_best_ = delta_best_orig_;
a_k_Y_best_ = a_k_Y_best_orig_;
b_k_Y_best_ = b_k_Y_best_orig_;
end;%if (X_best_orig>=X_best_flip);
if (X_best_orig< X_best_flip);
flip_flag = 1;
X_best = X_best_flip;
polar_a_best = polar_a_best_flip;
azimu_b_best = azimu_b_best_flip;
gamma_z_best = gamma_z_best_flip;
delta_best_ = delta_best_flip_;
a_k_Y_best_ = a_k_Y_best_flip_;
b_k_Y_best_ = b_k_Y_best_flip_;
end;%if (X_best_orig< X_best_flip);
euler_best_ = [+azimu_b_best,+polar_a_best,+gamma_z_best];
R_best_ = euler_to_R(euler_best_);
%%%%%%%%;
tmp_euler_azimu_b_ = euler_azimu_b_calc__(:,1+niteration);
tmp_euler_polar_a_ = euler_polar_a_calc__(:,1+niteration);
tmp_k_c_0_ = sin(tmp_euler_polar_a_).*cos(tmp_euler_azimu_b_);
tmp_k_c_1_ = sin(tmp_euler_polar_a_).*sin(tmp_euler_azimu_b_);
tmp_k_c_2_ = cos(tmp_euler_polar_a_);
tmp__ = inv(R_best_) * transpose([tmp_k_c_0_(:) , tmp_k_c_1_(:) , tmp_k_c_2_(:)]);
tmp_k_c_0_(:) = transpose(tmp__(1+0,:));
tmp_k_c_1_(:) = transpose(tmp__(1+1,:));
tmp_k_c_2_(:) = transpose(tmp__(1+2,:));
tmp_k_c_01_ = sqrt(tmp_k_c_0_.^2 + tmp_k_c_1_.^2);
tmp_euler_azimu_b_ = periodize(atan2(tmp_k_c_1_,tmp_k_c_0_),0,2*pi);
tmp_euler_polar_a_ = atan2(tmp_k_c_01_,tmp_k_c_2_);
tmp_euler_azimu_b_dif_ = pi/1 + periodize((0*pi+transpose(euler_azimu_b_true_(1:n_M))) - (0*pi+tmp_euler_azimu_b_),-pi,+pi);
tmp_euler_polar_a_dif_ = pi/2 + (1*pi-transpose(euler_polar_a_true_(1:n_M))) - (1*pi-tmp_euler_polar_a_);
%%%%%%%%;
subplot(p_row,p_col,1+np+[0,1]); np=np+2; cla;
hold on;
patch(2*pi*[+0;+1;+1;+0],1*pi*[+0;+0;+1;+1],0.65*[1,1,1],'EdgeColor','none');
scatter(0*pi+tmp_euler_azimu_b_,1*pi-tmp_euler_polar_a_,markersize_euler,c2d_euler__(1:n_M,:),'filled');
hold off;
axisnotick;
axis([0,2*pi,0,1*pi]); axis equal; xlabel('azimu_b'); ylabel('polar_a');
title(sprintf('%d (flip %d) X %0.2f',niteration,flip_flag,X_best));
%%%%%%%%;
subplot(p_row,p_col,1+np); np=np+1;
hold on;
patch(dscale*delta_sigma*[-1;+1;+1;-1],dscale*delta_sigma*[-1;-1;+1;+1],'k');
scatter(+image_delta_x_calc__(1:n_M,1+niteration),+image_delta_y_calc__(1:n_M,1+niteration),markersize_delta,c2d_delta__(1:n_M,:),'filled');
hold off;
axisnotick;
axis(dscale*delta_sigma*[-1,+1,-1,+1]); axis square; xlabel('dx'); ylabel('dy'); 
title(sprintf('%d (delta)',niteration));
%%%%%%%%;
drawnow();
end;%for niteration=0:n_iteration-1;

if (verbose); disp(sprintf(' %% [finished ampmut_align_to_reference_0]')); end;
