function ...
At_UX_wMn__ ...
= ...
cg_lsq_pm_At_wrap_0( ...
 n_CTF_rank ...
,n_M ...
,VSCTF_wMc__ ...
,pm_n_k_p_r ...
,pm_n_w_ ...
,pm_l_max_ ...
,UX_wMn__ ...
,tensor_from_scatter__ ...
,n_polar_a ...
,n_azimu_b ...
,legendre_evaluate_mlj___ ...
,expil__ ...
,expi__ ...
);
pm_n_w_max = max(pm_n_w_(1:pm_n_k_p_r));
pm_n_w_sum = sum(pm_n_w_(1:pm_n_k_p_r));
pm_n_w_csum_ = cumsum([0;pm_n_w_(1:pm_n_k_p_r)]);
pm_l_max_max = max(pm_l_max_);
pm_n_lm_ = (1+pm_l_max_(1:pm_n_k_p_r)).^2;
pm_n_lm_max = max(pm_n_lm_(1:pm_n_k_p_r));
pm_n_lm_sum = sum(pm_n_lm_(1:pm_n_k_p_r));
pm_n_lm_csum_ = cumsum([0;pm_n_lm_(1:pm_n_k_p_r)]);
At_UX_wMn__ = zeros(pm_n_lm_max*n_CTF_rank,pm_n_k_p_r);
for pm_nk_p_r=0:pm_n_k_p_r-1;
At_UX_wMn__(:,1+pm_nk_p_r) = ...
cg_lsq_pm_At_0( ...
 n_CTF_rank ...
,n_M ...
,VSCTF_wMc__ ...
,pm_n_w_max ...
,pm_l_max_max ...
,UX_wMn__(:,1+pm_nk_p_r) ...
,tensor_from_scatter__ ...
,n_polar_a ...
,n_azimu_b ...
,legendre_evaluate_mlj___ ...
,expil__ ...
,expi__ ...
);
end;%for pm_nk_p_r=0:pm_n_k_p_r-1;

