function ...
[ ... 
 a_x_u_xxx_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_spharm_to_x_c_4( ...
 k_eq_d ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_yk_ ...
,half_diameter_x_c ...
,n_x_u_pack ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);

flag_verbose=0;
if (flag_verbose); disp(sprintf(' %% [entering convert_spharm_to_x_c_4]')); end;

na=0;
if (nargin<1+na); k_eq_d = []; end; na=na+1;
if (nargin<1+na); n_k_p_r = []; end; na=na+1;
if (nargin<1+na); k_p_r_ = []; end; na=na+1;
if (nargin<1+na); k_p_r_max = []; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_r_ = []; end; na=na+1;
if (nargin<1+na); l_max_ = []; end; na=na+1;
if (nargin<1+na); a_k_Y_yk_ = []; end; na=na+1;
if (nargin<1+na); half_diameter_x_c = []; end; na=na+1;
if (nargin<1+na); n_x_u_pack = []; end; na=na+1;
if (nargin<1+na); Ylm_uklma___=[]; end; na=na+1;

if isempty(half_diameter_x_c); half_diameter_x_c = 1.0; end;
if isempty(n_x_u_pack); n_x_u_pack = 64; end;

diameter_x_c = 2.0d0*half_diameter_x_c;
x_p_r_max = half_diameter_x_c;
x_u_0_ = linspace(-x_p_r_max,+x_p_r_max,n_x_u_pack);
x_u_1_ = linspace(-x_p_r_max,+x_p_r_max,n_x_u_pack);
x_u_2_ = linspace(-x_p_r_max,+x_p_r_max,n_x_u_pack);
[x_u_0___,x_u_1___,x_u_2___] = ndgrid(x_u_0_,x_u_1_,x_u_2_); n_xxx_u = n_x_u_pack^3;
X_u_weight_ = (2*x_p_r_max/n_x_u_pack)^3;
a_x_u_xxx_ = zeros(n_xxx_u,1);

[ ...
 n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,tmp_n_k_p_r ...
,tmp_k_p_r_ ...
,tmp_weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,J_node_ ...
,J_weight_ ...
,J_chebfun_ ...
,J_polyval_ ...
] = ...
sample_sphere_7( ...
 flag_verbose ...
,k_p_r_max ...
,k_eq_d ...
,'L' ...
,1 ...
) ; %<-- sum(weight_3d_k_p_r_)*(4*pi) = (4/3)*pi*k_p_r_max^3 --> sum(weight_3d_k_p_r_) = (1/3)*k_p_r_max^3 ;

flag_continue = ...
( ...
( fnorm(tmp_n_k_p_r - n_k_p_r) < 1e-6 ) ...
& ...
( fnorm(tmp_k_p_r_ - k_p_r_) < 1e-6 ) ...
& ...
( fnorm(tmp_weight_3d_k_p_r_ - weight_3d_k_p_r_) < 1e-6 ) ...
);
if flag_continue==0;
disp(sprintf(' %% Warning, incompatible grids generated in convert_spharm_to_x_c_4'));
end;%if flag_continue==0;

if flag_continue==1;
if (flag_verbose); disp(sprintf(' %% compatible grids generated in convert_spharm_to_x_c_4')); end;

flag_Ylm_create = 0; 
if isempty(Ylm_uklma___);
flag_Ylm_create=1;
[ ...
 Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
get_Ylm_condense_wrap_0( ...
 flag_verbose ...
,n_qk ...
,n_qk_csum_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,n_k_p_r ...
,l_max_ ...
);
end;%if isempty(Ylm_uklma___);

%%%%%%%%;
tmp_t = tic;
[a_k_p_qk_] = ...
convert_spharm_to_k_p_4( ...
 flag_verbose ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% a_k_Y_yk_ --> a_k_p_qk_ time %0.2fs',tmp_t)); end;
%%%%%%%%;
eta = pi/k_p_r_max; tmp_t = tic;
a_x_u_xxx_ = ...
xxnufft3d3( ...
 n_qk ...
,2*pi*k_c_0_qk_*eta ...
,2*pi*k_c_1_qk_*eta ...
,2*pi*k_c_2_qk_*eta ...
,a_k_p_qk_.*(2*pi)^3.*weight_3d_k_p_qk_ ...
,+1 ...
,1e-12 ...
,n_xxx_u ...
,x_u_0___(:)/eta ...
,x_u_1___(:)/eta ...
,x_u_2___(:)/eta ...
)/sqrt(2*pi)/sqrt(2*pi)/sqrt(2*pi);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% nufft3d3: a_x_u_xxx_ time %0.2fs',tmp_t)); end;
%%%%%%%%;

end;%if flag_continue==1;

if (flag_verbose); disp(sprintf(' %% [finished convert_spharm_to_x_c_4]')); end;
