%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
for ntype=0:16-1;
tab=0;
if ntype==tab; tmp_k_Y_quad_yk_ = a_k_Y_quad_yk_; tmp_k_p_quad_ = a_k_p_quad_; tmp_str = 'a'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = a_restore_C2M0_k_Y_yk_; tmp_k_p_quad_ = a_restore_C2M0_k_p_quad_; tmp_str = 'a_restore_C2M0'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = a_restore_C1M1_k_Y_yk_; tmp_k_p_quad_ = a_restore_C1M1_k_p_quad_; tmp_str = 'a_restore_C1M1'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = a_restore_C0M2_k_Y_yk_; tmp_k_p_quad_ = a_restore_C0M2_k_p_quad_; tmp_str = 'a_restore_C0M2'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dtau_a_restore_C2M0_k_Y_yk_; tmp_k_p_quad_ = dtau_a_restore_C2M0_k_p_quad_; tmp_str = 'dtau_a_restore_C2M0'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dtau_a_restore_C1M1_k_Y_yk_; tmp_k_p_quad_ = dtau_a_restore_C1M1_k_p_quad_; tmp_str = 'dtau_a_restore_C1M1'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dtau_a_restore_C0M2_k_Y_yk_; tmp_k_p_quad_ = dtau_a_restore_C0M2_k_p_quad_; tmp_str = 'dtau_a_restore_C0M2'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dtau_dtau_a_restore_C2M0_k_Y_yk_; tmp_k_p_quad_ = dtau_dtau_a_restore_C2M0_k_p_quad_; tmp_str = 'dtau_dtau_a_restore_C2M0'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dtau_dtau_a_restore_C1M1_k_Y_yk_; tmp_k_p_quad_ = dtau_dtau_a_restore_C1M1_k_p_quad_; tmp_str = 'dtau_dtau_a_restore_C1M1'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dtau_dtau_a_restore_C0M2_k_Y_yk_; tmp_k_p_quad_ = dtau_dtau_a_restore_C0M2_k_p_quad_; tmp_str = 'dtau_dtau_a_restore_C0M2'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dvol_a_k_Y_quad_yk_; tmp_k_p_quad_ = dvol_a_k_p_quad_; tmp_str = 'dvol_a'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = a_times_dtau_a_restore_C2M0_k_Y_yk_; tmp_k_p_quad_ = a_times_dtau_a_restore_C2M0_k_p_quad_; tmp_str = 'a_times_dtau_a_restore_C2M0'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dvol_a_times_a_restore_C2M0_k_Y_yk_; tmp_k_p_quad_ = dvol_a_times_a_restore_C2M0_k_p_quad_; tmp_str = 'dvol_a_times_a_restore_C2M0'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = a_times_a_k_Y_quad_yk_; tmp_k_p_quad_ = a_times_a_k_p_quad_; tmp_str = 'a_times_a'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = dvol_a_times_dvol_a_k_Y_quad_yk_; tmp_k_p_quad_ = dvol_a_times_dvol_a_k_p_quad_; tmp_str = 'dvol_a_times_dvol_a'; end; tab=tab+1;
if ntype==tab; tmp_k_Y_quad_yk_ = a_times_a_restore_C2M0_k_Y_yk_; tmp_k_p_quad_ = a_times_a_restore_C2M0_k_p_quad_; tmp_str = 'a_times_a_restore_C2M0'; end; tab=tab+1;
%%%%%%%%%%%%%%%%;
if ~isempty(tmp_k_Y_quad_yk_) & ~isempty(tmp_k_p_quad_);
tmp_t = tic;
[ ...
 tmp_k_Y_reco_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,tmp_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% %s_k_Y_reco_yk_ time %0.2fs',tmp_str,tmp_t)); end;
tmp_t = tic;
[ ...
 tmp_k_p_reco_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,tmp_k_Y_quad_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% %s_k_p_quad_ time %0.2fs',tmp_str,tmp_t)); end;
fnorm_disp(flag_verbose,sprintf('%s_k_p_quad_',tmp_str),tmp_k_p_quad_,sprintf('%s_k_p_reco_',tmp_str),tmp_k_p_reco_);
fnorm_disp(flag_verbose,sprintf('%s_k_Y_quad_yk_',tmp_str),tmp_k_Y_quad_yk_,sprintf('%s_k_Y_reco_yk_',tmp_str),tmp_k_Y_reco_yk_);
end;%if ~isempty(tmp_k_Y_quad_yk_) & ~isempty(tmp_k_p_quad_);
%%%%%%%%%%%%%%%%;
end;%for ntype=0:8-1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

