function ...
[ ...
 parameter ...
,Hvt_ykabc_ ...
,Hv_q3d_k_Y_quad_yk_ ...
,Hv_q3d_k_Y_quad_yk__ ...
,Hv_q3d_k_p_quad_ ...
,Ht_q2d_M3__ ...
,a_restore_C2M0_k_Y_yk_ ...
,a_restore_C2M0_k_p_quad_ ...
,Hvv_q3d_k_Y_quad_yk_ ...
,Hvt_q3d_k_Y_quad_yk_ ...
,Htv_q2d_M3__ ...
,Htt_q2d_M3__ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
,n_dvt ... 
,dvt_ ... 
,dvt ... 
,ssnll_tmp_q2d_dvt_ ... 
,dssnll_mid_q2d ... 
,dssnll_dif_q2d ... 
,dssnll_lsq_q2d ... 
,ddssnll_mid_q2d ... 
,ddssnll_dif_q2d ... 
,ddssnll_lsq_q2d ... 
] = ...
ddssnll_2( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_quad_yk_ ...
,a_k_Y_quad_yk__ ...
,dvol_a_k_Y_quad_yk_ ...
,dvol_a_k_Y_quad_yk__ ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,weight_3d_k_p_r_ ...
,a_k_p_quad_ ...
,dvol_a_k_p_quad_ ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,S_k_p_q2d_wkS__ ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,weight_imagecount_M_ ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
,CTF_k_p_wkC__ ...
,n_eta ...
,index_neta_from_nM_ ...
,eta_k_p_r_ke__ ...
,eta_k_p_wke__ ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
,KAPPA ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
,V_lmm___ ...
,L_lm__ ...
,d0W_betazeta_mlma____ ...
,d1W_betazeta_mlma____ ...
,d2W_betazeta_mlma____ ...
);

str_thisfunction = 'ddssnll_2';

%%%%%%%%;
if (nargin<1);
%%%%%%%%;
test_slice_vs_volume_integral_5;
%%%%%%%%;
disp(sprintf(' %% returning')); return;
%%%%%%%%;
end;%if (nargin<1);
%%%%%%%%;

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_k_p_r=[]; end; na=na+1;
if (nargin<1+na); k_p_r_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_max=[]; end; na=na+1;
if (nargin<1+na); l_max_=[]; end; na=na+1;
if (nargin<1+na); a_k_Y_quad_yk_=[]; end; na=na+1;
if (nargin<1+na); a_k_Y_quad_yk__=[]; end; na=na+1;
if (nargin<1+na); dvol_a_k_Y_quad_yk_=[]; end; na=na+1;
if (nargin<1+na); dvol_a_k_Y_quad_yk__=[]; end; na=na+1;
if (nargin<1+na); n_k_all=[]; end; na=na+1;
if (nargin<1+na); n_k_all_csum_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_all_=[]; end; na=na+1;
if (nargin<1+na); k_p_azimu_b_all_=[]; end; na=na+1;
if (nargin<1+na); k_p_polar_a_all_=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_all_=[]; end; na=na+1;
if (nargin<1+na); weight_shell_k_=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_r_=[]; end; na=na+1;
if (nargin<1+na); a_k_p_quad_=[]; end; na=na+1;
if (nargin<1+na); dvol_a_k_p_quad_=[]; end; na=na+1;
if (nargin<1+na); n_w_=[]; end; na=na+1;
if (nargin<1+na); weight_2d_k_p_r_=[]; end; na=na+1;
if (nargin<1+na); weight_2d_wk_=[]; end; na=na+1;
if (nargin<1+na); n_S=[]; end; na=na+1;
if (nargin<1+na); S_k_p_q2d_wkS__=[]; end; na=na+1;
if (nargin<1+na); viewing_polar_a_S_=[]; end; na=na+1;
if (nargin<1+na); viewing_azimu_b_S_=[]; end; na=na+1;
if (nargin<1+na); viewing_weight_S_=[]; end; na=na+1;
if (nargin<1+na); n_viewing_polar_a=[]; end; na=na+1;
if (nargin<1+na); viewing_polar_a_=[]; end; na=na+1;
if (nargin<1+na); n_viewing_azimu_b_=[]; end; na=na+1;
if (nargin<1+na); n_M=[]; end; na=na+1;
if (nargin<1+na); weight_imagecount_M_=[]; end; na=na+1;
if (nargin<1+na); M_k_p_wkM__=[]; end; na=na+1;
if (nargin<1+na); n_CTF=[]; end; na=na+1;
if (nargin<1+na); index_nCTF_from_nM_=[]; end; na=na+1;
if (nargin<1+na); CTF_k_p_r_kC__=[]; end; na=na+1;
if (nargin<1+na); CTF_k_p_wkC__=[]; end; na=na+1;
if (nargin<1+na); n_eta=[]; end; na=na+1;
if (nargin<1+na); index_neta_from_nM_=[]; end; na=na+1;
if (nargin<1+na); eta_k_p_r_ke__=[]; end; na=na+1;
if (nargin<1+na); eta_k_p_wke__=[]; end; na=na+1;
if (nargin<1+na); euler_polar_a_M_=[]; end; na=na+1;
if (nargin<1+na); euler_azimu_b_M_=[]; end; na=na+1;
if (nargin<1+na); euler_gamma_z_M_=[]; end; na=na+1;
if (nargin<1+na); dtau_euler_polar_a_M_=[]; end; na=na+1;
if (nargin<1+na); dtau_euler_azimu_b_M_=[]; end; na=na+1;
if (nargin<1+na); dtau_euler_gamma_z_M_=[]; end; na=na+1;
if (nargin<1+na); KAPPA=[]; end; na=na+1;
if (nargin<1+na); Ylm_uklma___=[]; end; na=na+1;
if (nargin<1+na); k_p_azimu_b_sub_uka__=[]; end; na=na+1;
if (nargin<1+na); k_p_polar_a_sub_uka__=[]; end; na=na+1;
if (nargin<1+na); l_max_uk_=[]; end; na=na+1;
if (nargin<1+na); index_nu_n_k_per_shell_from_nk_p_r_=[]; end; na=na+1;
if (nargin<1+na); index_k_per_shell_uka__=[]; end; na=na+1;
if (nargin<1+na); V_lmm___=[]; end; na=na+1;
if (nargin<1+na); L_lm__=[]; end; na=na+1;
if (nargin<1+na); d0W_betazeta_mlma____=[]; end; na=na+1;
if (nargin<1+na); d1W_betazeta_mlma____=[]; end; na=na+1;
if (nargin<1+na); d2W_betazeta_mlma____=[]; end; na=na+1;

if isempty(parameter);
parameter = struct('type','parameter');
end;%if isempty(parameter);
%%%%%%%%;
if (~isfield(parameter,'flag_verbose')); parameter.flag_verbose = 0; end; %<-- parameter_bookmark. ;
flag_verbose = parameter.flag_verbose;
if (~isfield(parameter,'flag_surrogate')); parameter.flag_surrogate = 0; end; %<-- parameter_bookmark. ;
flag_surrogate = parameter.flag_surrogate;
if (~isfield(parameter,'flag_check')); parameter.flag_check = 0; end; %<-- parameter_bookmark. ;
flag_check = parameter.flag_check;
if (~isfield(parameter,'dvt_check')); parameter.dvt_check = 1e-3; end; %<-- parameter_bookmark. ;
dvt_check = parameter.dvt_check;
if (~isfield(parameter,'flag_disp')); parameter.flag_disp = 0; end; %<-- parameter_bookmark. ;
flag_disp = parameter.flag_disp; nf=0;
if (~isfield(parameter,'tolerance_master')); parameter.tolerance_master = 1e-2; end; %<-- parameter_bookmark. ;
tolerance_master = parameter.tolerance_master;
if (~isfield(parameter,'viewing_k_eq_d')); parameter.viewing_k_eq_d = []; end; %<-- parameter_bookmark. ;
viewing_k_eq_d = parameter.viewing_k_eq_d;
if (~isfield(parameter,'template_k_eq_d')); parameter.template_k_eq_d = -1; end; %<-- parameter_bookmark. ;
template_k_eq_d = parameter.template_k_eq_d;
if (~isfield(parameter,'n_order')); parameter.n_order = 5; end; %<-- parameter_bookmark. ;
n_order = parameter.n_order;
if (~isfield(parameter,'flag_kernel_qpro_d0')); parameter.flag_kernel_qpro_d0 = 1; end; %<-- parameter_bookmark. ;
flag_kernel_qpro_d0 = parameter.flag_kernel_qpro_d0;
if (~isfield(parameter,'flag_kernel_qpro_d1')); parameter.flag_kernel_qpro_d1 = 1; end; %<-- parameter_bookmark. ;
flag_kernel_qpro_d1 = parameter.flag_kernel_qpro_d1;
if (~isfield(parameter,'kernel_qpro_polar_a_pole_north')); parameter.kernel_qpro_polar_a_pole_north = 4.5*pi/24; end; %<-- parameter_bookmark. ;
kernel_qpro_polar_a_pole_north = min(pi/2,parameter.kernel_qpro_polar_a_pole_north);
parameter.kernel_qpro_polar_a_pole_north = kernel_qpro_polar_a_pole_north;
if (~isfield(parameter,'kernel_qpro_polar_a_pole_south')); parameter.kernel_qpro_polar_a_pole_south = 3.5*pi/24; end; %<-- parameter_bookmark. ;
kernel_qpro_polar_a_pole_south = min(pi/2,parameter.kernel_qpro_polar_a_pole_south);
parameter.kernel_qpro_polar_a_pole_south = kernel_qpro_polar_a_pole_south;
if ~isfield(parameter,'kernel_qpro_qref_k_eq_d_double'); parameter.kernel_qpro_qref_k_eq_d_double=0.5; end;
kernel_qpro_qref_k_eq_d_double=parameter.kernel_qpro_qref_k_eq_d_double;
if (~isfield(parameter,'kernel_qpro_l_max_use')); parameter.kernel_qpro_l_max_use = l_max; end; %<-- parameter_bookmark. ;
kernel_qpro_l_max_use = parameter.kernel_qpro_l_max_use;
if (~isfield(parameter,'tolerance_pinv')); parameter.tolerance_pinv = 1e-6; end; %<-- parameter_bookmark. ;
tolerance_pinv = parameter.tolerance_pinv;
%%%%;
if ~isfield(parameter,'flag_kernel_full'); parameter.flag_kernel_full=0; end;
flag_kernel_full=parameter.flag_kernel_full;
if (kernel_qpro_polar_a_pole_north + kernel_qpro_polar_a_pole_south > pi-1e-12);
flag_kernel_full = 1;
parameter.flag_kernel_full = flag_kernel_full;
end;%if (kernel_qpro_polar_a_pole_north + kernel_qpro_polar_a_pole_south > pi-1e-12);
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% [entering %s]',str_thisfunction)); end;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

if isempty(weight_imagecount_M_); weight_imagecount_M_ = ones(n_M,1); end;

%%%%%%%%;
n_w_max = max(n_w_);
n_w_sum = sum(n_w_);
n_w_csum_ = cumsum([0;n_w_]);
n_lm_ = (l_max_+1).^2;
n_lm_max = max(n_lm_);
n_lm_sum = sum(n_lm_);
n_lm_csum_ = cumsum([0;n_lm_]);
l_max_max = max(l_max_);
m_max_ = -l_max_max : +l_max_max;
n_m_max = length(m_max_);
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
% This is used to test eig_ddssnll_lanczos_0. ;
%%%%%%%%;
if flag_surrogate==1;
if ~isfield(parameter,'surrogate_H__'); disp(sprintf(' %% Warning, surrogate_H__ not found')); end;
if fnorm(weight_imagecount_M_-ones(n_M,1))>1e-12; disp(sprintf(' %% Warning, expecting trivial weight_iamge_M_ in %s',str_thisfunction)); end;
Hvt_ykabc_=[];
Hv_q3d_k_Y_quad_yk_=[];
Hv_q3d_k_Y_quad_yk__=[];
Hv_q3d_k_p_quad_=[];
Ht_q2d_M3__=[];
a_restore_C2M0_k_Y_yk_=[];
a_restore_C2M0_k_p_quad_=[];
[tmp_ykabc_] = local_ykabc_from_yk_a_b_c_(n_k_p_r,l_max_,n_M,dvol_a_k_Y_quad_yk_,dtau_euler_polar_a_M_,dtau_euler_azimu_b_M_,dtau_euler_gamma_z_M_);
Hvt_ykabc_ = parameter.surrogate_H__*tmp_ykabc_;
end;%if flag_surrogate==1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_surrogate==0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%;
if isempty(a_k_Y_quad_yk__);
a_k_Y_quad_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,a_k_Y_quad_yk_);
end;%if isempty(a_k_Y_quad_yk__);
%%%%%%%%;
if isempty(dvol_a_k_Y_quad_yk__);
dvol_a_k_Y_quad_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,dvol_a_k_Y_quad_yk_);
end;%if isempty(dvol_a_k_Y_quad_yk__);
%%%%%%%%;
if isempty(a_k_p_quad_);
tmp_t = tic;
[ ...
 a_k_p_quad_ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_quad_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% a_k_p_quad_ time %0.2fs',tmp_t)); end;
end;%if isempty(a_k_p_quad_);
%%%%%%%%;
if isempty(dvol_a_k_p_quad_);
tmp_t = tic;
[ ...
 dvol_a_k_p_quad_ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,dvol_a_k_Y_quad_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% dvol_a_k_p_quad_ time %0.2fs',tmp_t)); end;
end;%if isempty(dvol_a_k_p_quad_);
%%%%%%%%;

%%%%%%%%;
% Calculate derivative using ssnll_from_a_k_Y_13. ;
%%%%%%%%;
dvol_S_k_p_q2d_wkS__=[];
dtau_S_k_p_q2d_wkS3___=[];
dtau_dvol_S_k_p_q2d_wkS3___=[];
dtau_dtau_S_k_p_q2d_wkS33____=[];
%%%%;
tmp_t = tic();
parameter_ssnll = struct('type','parameter');
parameter_ssnll.flag_verbose = 0*flag_verbose;
parameter_ssnll.viewing_k_eq_d = viewing_k_eq_d;
parameter_ssnll.template_k_eq_d = template_k_eq_d;
parameter_ssnll.n_order = n_order;
[ ...
 parameter_ssnll ...
,ssnll_q2d_M_ ...
,ssnll_q2d ...
,S_k_p_q2d_wkS__ ...
,dvol_ssnll_q2d_M_ ...
,dvol_ssnll_q2d ...
,dvol_S_k_p_q2d_wkS__ ...
,dvol_dvol_ssnll_q2d ...
,dtau_ssnll_q2d_M3__ ...
,dtau_ssnll_q2d ...
,dtau_S_k_p_q2d_wkS3___ ...
,dtau_dvol_ssnll_q2d_M3__ ...
,dtau_dvol_ssnll_q2d ...
,dtau_dvol_S_k_p_q2d_wkS3___ ...
,dtau_dtau_ssnll_q2d_M33___ ...
,dtau_dtau_ssnll_q2d ...
,dtau_dtau_S_k_p_q2d_wkS33____ ...
,V_lmm___ ...
,L_lm__ ...
,d0W_betazeta_mlma____ ...
,d1W_betazeta_mlma____ ...
,d2W_betazeta_mlma____ ...
] = ...
ssnll_from_a_k_Y_13( ...
 parameter_ssnll ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_quad_yk__ ...
,dvol_a_k_Y_quad_yk__ ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,S_k_p_q2d_wkS__ ...
,dvol_S_k_p_q2d_wkS__ ...
,dtau_S_k_p_q2d_wkS3___ ...
,dtau_dvol_S_k_p_q2d_wkS3___ ...
,dtau_dtau_S_k_p_q2d_wkS33____ ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,weight_imagecount_M_ ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
,V_lmm___ ...
,L_lm__ ...
,d0W_betazeta_mlma____ ...
,d1W_betazeta_mlma____ ...
,d2W_betazeta_mlma____ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% ssnll_from_a_k_Y_13: time %0.2fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
% Determine critical dtau. ;
%%%%%%%%;
n_3 = 3;
dtau_dtau_ssnll_q2d_33M___ = permute(dtau_dtau_ssnll_q2d_M33___,[2,3,1]);
dtau_dtau_inv_ssnll_q2d_33M___ = zeros(n_3,n_3,n_M);
for nM=0:n_M-1;
dtau_dtau_inv_ssnll_q2d_33M___(:,:,1+nM) = pinv(sqrt(weight_imagecount_M_(1+nM))*squeeze(dtau_dtau_ssnll_q2d_33M___(:,:,1+nM))*sqrt(weight_imagecount_M_(1+nM)),tolerance_pinv);
end;%for nM=0:n_M-1;
dtau_dvol_ssnll_q2d_3M__ = permute(dtau_dvol_ssnll_q2d_M3__,[2,1]);
dtau_firstorder_3M__ = zeros(n_3,n_M);
dtau_firstorder_3M__ = reshape(pagemtimes(-real(dtau_dtau_inv_ssnll_q2d_33M___),reshape(real(bsxfun(@times,dtau_dvol_ssnll_q2d_3M__,transpose(weight_imagecount_M_))),[n_3,1,n_M])),[n_3,n_M]);
dtau_firstorder_M3__ = permute(dtau_firstorder_3M__,[2,1]);
%%%%;
if flag_check;
tmp_H = @(dtau_3M__) dvol_dvol_ssnll_q2d + 2*real(sum(bsxfun(@times,dtau_3M__,transpose(weight_imagecount_M_)).*dtau_dvol_ssnll_q2d_3M__,'all')) + sum(bsxfun(@times,reshape(conj(bsxfun(@times,dtau_3M__,transpose(sqrt(weight_imagecount_M_)))),[n_3,1,n_M]),bsxfun(@times,reshape(bsxfun(@times,dtau_3M__,transpose(sqrt(weight_imagecount_M_))),[1,n_3,n_M]),real(dtau_dtau_ssnll_q2d_33M___))),'all');
if (flag_disp>1);
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,3,1)
dtau_randn_3M__ = randn(n_3,n_M);
hold on;
for ntmp=-20:+20;
plot(ntmp,tmp_H(dtau_firstorder_3M__ + dtau_randn_3M__*ntmp/20),'ko');
end;%for ntmp=-20:+20;
xlabel('abitrary step'); ylabel('value of tmp_H','Interpreter','none');
title('criticality of dtau_firstorder_3M__','Interpreter','none');
subplot(1,3,2);
hold on;
plot(1:n_M,dtau_firstorder_M3__(:,1+0),'ro');
plot(1:n_M,dtau_firstorder_M3__(:,1+1),'go');
plot(1:n_M,dtau_firstorder_M3__(:,1+2),'bo');
hold off;
xlim([0,n_M+1]); xlabel('nM','Interpreter','none');
ylabel('dtau_firstorder_M3__','Interpreter','none');
title('dtau_firstorder_M3__','Interpreter','none');
subplot(1,3,3);
hold on;
plot(euler_polar_a_M_,dtau_firstorder_M3__(:,1+0),'ro');
plot(euler_polar_a_M_,dtau_firstorder_M3__(:,1+1),'go');
plot(euler_polar_a_M_,dtau_firstorder_M3__(:,1+2),'bo');
hold off;
xlim([0,pi]); xlabel('euler_polar_a_M_','Interpreter','none');
ylabel('dtau_firstorder_M3__','Interpreter','none');
title('dtau_firstorder_M3__','Interpreter','none');
drawnow();
end;%if (flag_disp>1);
end;%if flag_check;
%%%%%%%%;

%%%%%%%%;
% Now if dtau is empty we fill dtau with dtau_firstorder. ;
%%%%%%%%;
if isempty(dtau_euler_polar_a_M_); dtau_euler_polar_a_M_ = real(dtau_firstorder_M3__(:,1+0)); end;
if isempty(dtau_euler_azimu_b_M_); dtau_euler_azimu_b_M_ = real(dtau_firstorder_M3__(:,1+1)); end;
if isempty(dtau_euler_gamma_z_M_); dtau_euler_gamma_z_M_ = real(dtau_firstorder_M3__(:,1+2)); end;

%%%%%%%%;
% We construct the riesz integration-weights on the sphere. ;
% These are associated with the riesz-potential 1/k^2.5, ;
% or a weighting-function (for the squared-L2-norm) of 1/k. ;
%%%%%%%%;
weight_3d_riesz_k_p_r_ = weight_3d_k_p_r_;
weight_3d_riesz_k_all_ = weight_3d_k_all_;
for nk_p_r=0:n_k_p_r-1;
k_p_r = k_p_r_(1+nk_p_r);
weight_3d_k_p_r = weight_3d_k_p_r_(1+nk_p_r);
weight_2d_k_p_r = weight_2d_k_p_r_(1+nk_p_r);
weight_3d_riesz_k_p_r_(1+nk_p_r) = weight_3d_k_p_r_(1+nk_p_r) * weight_2d_k_p_r / max(1e-16,weight_3d_k_p_r);
tmp_index_ = n_k_all_csum_(1+nk_p_r):n_k_all_csum_(1+nk_p_r+1)-1;
if (flag_verbose> 1); disp(sprintf(' %% k_p_r %0.6f: sum(weight_3d_k_all_(1+tmp_index_))/(weight_3d_k_p_r * 4*pi): %0.16f',k_p_r,sum(weight_3d_k_all_(1+tmp_index_))/(4*pi*weight_3d_k_p_r))); end;
weight_3d_riesz_k_all_(1+tmp_index_) = weight_3d_k_all_(1+tmp_index_) * weight_2d_k_p_r / max(1e-16,weight_3d_k_p_r);
if (flag_verbose> 1); disp(sprintf(' %% k_p_r %0.6f: sum(weight_3d_riesz_k_all_(1+tmp_index_))/(weight_2d_k_p_r * 4*pi): %0.16f',k_p_r,sum(weight_3d_riesz_k_all_(1+tmp_index_))/(4*pi*weight_2d_k_p_r))); end;
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;

%%%%%%%%;
% Calibrate scaling factor. ;
%%%%%%%%;
term_deltafunc = sqrt(2*pi);
term_2 = (pi*k_p_r_max^2)/(4*pi^2);
if (flag_verbose>0); disp(sprintf(' %% sum(weight_2d_wk_) vs (pi*k_p_r_max^2)/(4*pi^2): %0.16f',fnorm(sum(weight_2d_wk_) - term_2))); end;
term_3 = (4/3)*pi*k_p_r_max^3;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_3d_k_all_) vs (4/3)*pi*k_p_r_max^3: %0.16f',fnorm(sum(weight_3d_k_all_) - term_3))); end;
term_3r = (4*pi^2*k_p_r_max^2);
if (flag_verbose>0); disp(sprintf(' %% sum(weight_3d_riesz__all_) vs 4*pi^2*k_p_r_max^2: %0.16f',fnorm(sum(weight_3d_riesz_k_all_) - term_3r))); end;
scaling_volumetric = term_3r / term_2 / term_deltafunc ;
if (flag_verbose>0); disp(sprintf(' %% scaling_volumetric: %+0.6f',scaling_volumetric)); end;
if (flag_verbose>0); disp(sprintf(' %% (4*pi)^2 * sqrt(pi/2): %+0.6f',(4*pi)^2 * sqrt(pi/2))); end;
%%%%%%%%;

%%%%%%%%;
% Calculate volumetric terms. ;
%%%%%%%%;
tmp_t = tic();
parameter_KAPPA = struct('type','KAPPA');
parameter_KAPPA.flag_verbose = 0*flag_verbose;
parameter_KAPP.flag_kernel_full = flag_kernel_full;
parameter_KAPPA.flag_kernel_qpro_d0 = flag_kernel_qpro_d0;
parameter_KAPPA.flag_kernel_qpro_d1 = flag_kernel_qpro_d1;
parameter_KAPPA.kernel_qpro_polar_a_pole_north = kernel_qpro_polar_a_pole_north;
parameter_KAPPA.kernel_qpro_polar_a_pole_south = kernel_qpro_polar_a_pole_south;
parameter_KAPPA.kernel_qpro_qref_k_eq_d_double = kernel_qpro_qref_k_eq_d_double;
parameter_KAPPA.kernel_qpro_l_max_use = kernel_qpro_l_max_use;
[ ...
 parameter_KAPPA ...
,KAPPA ...
,a_restore_C2M0_k_Y_yk__ ...
,a_restore_C1M1_k_Y_yk__ ...
,a_restore_C0M2_k_Y_yk__ ...
,dtau_a_restore_C2M0_k_Y_yk__ ...
,dtau_a_restore_C1M1_k_Y_yk__ ...
,dtau_a_restore_C0M2_k_Y_yk__ ...
,dtau_dtau_a_restore_C2M0_k_Y_yk__ ...
,dtau_dtau_a_restore_C1M1_k_Y_yk__ ...
,dtau_dtau_a_restore_C0M2_k_Y_yk__ ...
] = ...
kappa_qpro_apply_3( ...
 parameter_KAPPA ...
,KAPPA ...
,n_w_max ...
,n_M ...
,weight_imagecount_M_ ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% kappa_qpro_apply_3 (yes derivatives) time %0.2fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
% Convert volumetric terms. ;
%%%%%%%%;
n_type_ = [0,3,4];
if flag_check;n_type_ = 0:3*3-1; end;
for n_type = n_type_;
ntype = 0;
if n_type==ntype; tmp_yk__ = a_restore_C2M0_k_Y_yk__; tmp_str = 'a_restore_C2M0_k_Y_yk__'; end; ntype = ntype + 1; %<-- Needed for Hvv_q3d. ;
if n_type==ntype; tmp_yk__ = a_restore_C1M1_k_Y_yk__; tmp_str = 'a_restore_C1M1_k_Y_yk__'; end; ntype = ntype + 1;
if n_type==ntype; tmp_yk__ = a_restore_C0M2_k_Y_yk__; tmp_str = 'a_restore_C0M2_k_Y_yk__'; end; ntype = ntype + 1;
if n_type==ntype; tmp_yk__ = dtau_a_restore_C2M0_k_Y_yk__; tmp_str = 'dtau_a_restore_C2M0_k_Y_yk__'; end; ntype = ntype + 1; %<-- Needed for Hvt_q3d. ;
if n_type==ntype; tmp_yk__ = dtau_a_restore_C1M1_k_Y_yk__; tmp_str = 'dtau_a_restore_C1M1_k_Y_yk__'; end; ntype = ntype + 1; %<-- Needed for Hvt_q3d. ;
if n_type==ntype; tmp_yk__ = dtau_a_restore_C0M2_k_Y_yk__; tmp_str = 'dtau_a_restore_C0M2_k_Y_yk__'; end; ntype = ntype + 1;
if n_type==ntype; tmp_yk__ = dtau_dtau_a_restore_C2M0_k_Y_yk__; tmp_str = 'dtau_dtau_a_restore_C2M0_k_Y_yk__'; end; ntype = ntype + 1;
if n_type==ntype; tmp_yk__ = dtau_dtau_a_restore_C1M1_k_Y_yk__; tmp_str = 'dtau_dtau_a_restore_C1M1_k_Y_yk__'; end; ntype = ntype + 1;
if n_type==ntype; tmp_yk__ = dtau_dtau_a_restore_C0M2_k_Y_yk__; tmp_str = 'dtau_dtau_a_restore_C0M2_k_Y_yk__'; end; ntype = ntype + 1;
%%%%;
tmp_t = tic();
tmp_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,tmp_yk__);
%%%%;
[ ...
 tmp_quad_ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,tmp_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% %s: convert_spharm_to_k_p_4: time %0.2fs',tmp_str,tmp_t)); end;
ntype = 0;
if n_type==ntype; a_restore_C2M0_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; a_restore_C1M1_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; a_restore_C0M2_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; dtau_a_restore_C2M0_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; dtau_a_restore_C1M1_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; dtau_a_restore_C0M2_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; dtau_dtau_a_restore_C2M0_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; dtau_dtau_a_restore_C1M1_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
if n_type==ntype; dtau_dtau_a_restore_C0M2_k_p_quad_ = tmp_quad_; end; ntype = ntype + 1;
end;%for n_type = n_type_;
%%%%%%%%;
a_restore_C2M0_k_Y_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,a_restore_C2M0_k_Y_yk__);

%%%%%%%%;
% determine expansion for a_times_dtau_a_restore_C2M0_k_Y_yk__. ;
%%%%%%%%;
tmp_str = 'a_times_dtau_a_restore_C2M0_k_Y_yk__';
tmp_t = tic();
[ ...
 a_times_dtau_a_restore_C2M0_k_Y_yk_ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_p_quad_.*dtau_a_restore_C2M0_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% %s: convert_k_p_to_spharm_4: time %0.2fs',tmp_str,tmp_t)); end;
%%%%;
a_times_dtau_a_restore_C2M0_k_Y_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,a_times_dtau_a_restore_C2M0_k_Y_yk_);
%%%%%%%%;

%%%%%%%%;
% determine expansion for dvol_a_times_a_restore_C2M0_k_Y_yk__. ;
%%%%%%%%;
tmp_str = 'dvol_a_times_a_restore_C2M0_k_Y_yk__';
tmp_t = tic();
[ ...
 dvol_a_times_a_restore_C2M0_k_Y_yk_ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,dvol_a_k_p_quad_.*a_restore_C2M0_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% %s: convert_k_p_to_spharm_4: time %0.2fs',tmp_str,tmp_t)); end;
%%%%;
dvol_a_times_a_restore_C2M0_k_Y_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,dvol_a_times_a_restore_C2M0_k_Y_yk_);
%%%%%%%%;

%%%%%%%%;
dtau_M3__ = [ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
] ;
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%;
Y_l_val_ = zeros(n_lm_sum,1);
Y_m_val_ = zeros(n_lm_sum,1);
Y_k_val_ = zeros(n_lm_sum,1);
for nk_p_r=0:n_k_p_r-1;
l_max = l_max_(1+nk_p_r);
tmp_l_val_ = zeros(n_lm_(1+nk_p_r),1);
tmp_m_val_ = zeros(n_lm_(1+nk_p_r),1);
na=0; 
for l_val=0:l_max;
for m_val=-l_val:+l_val;
tmp_l_val_(1+na) = l_val;
tmp_m_val_(1+na) = m_val;
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
Y_l_val_(1+tmp_index_) = tmp_l_val_;
Y_m_val_(1+tmp_index_) = tmp_m_val_;
Y_k_val_(1+tmp_index_) = k_p_r_(1+nk_p_r);
end;%for nk_p_r=0:n_k_p_r-1;
weight_Y_ = zeros(n_lm_sum,1);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
weight_Y_(1+tmp_index_) = weight_3d_k_p_r_(1+nk_p_r);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;

%%%%%%%%;
% determine expansion for abs(a).^2. ;
%%%%%%%%;
[ ...
 a_times_a_k_Y_quad_yk_ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,abs(a_k_p_quad_).^2 ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
%%%%;
a_times_a_k_Y_quad_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,a_times_a_k_Y_quad_yk_);
%%%%%%%%;

%%%%%%%%;
% determine expansion for abs(dvol_a).^2. ;
%%%%%%%%;
[ ...
 dvol_a_times_dvol_a_k_Y_quad_yk_ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,abs(dvol_a_k_p_quad_).^2 ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
%%%%;
dvol_a_times_dvol_a_k_Y_quad_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,dvol_a_times_dvol_a_k_Y_quad_yk_);
%%%%%%%%;

%%%%%%%%;
% determine expansion for a_times_a_restore_C2M0_k_Y_yk__. ;
%%%%%%%%;
[ ...
 a_times_a_restore_C2M0_k_Y_yk_ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_p_quad_.*a_restore_C2M0_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
%%%%;
a_times_a_restore_C2M0_k_Y_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,a_times_a_restore_C2M0_k_Y_yk_);
%%%%%%%%;

%%%%%%%%;
% Collect terms into ssnll. ;
%%%%%%%%;
ssnll_q3d = ...
 + 0.5 * sum( (conj(a_times_a_k_Y_quad_yk__) .* a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_quad_yk__).^1 .* a_restore_C1M1_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( a_restore_C0M2_k_Y_yk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
ssnll_q3d = ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_q2d vs ssnll_q3d: %0.16f',fnorm(ssnll_q2d-ssnll_q3d)/fnorm(ssnll_q2d))); end;
%%%%%%%%;
ssnll_q3d = ...
 + 0.5 * sum( abs(a_k_p_quad_).^2 .* a_restore_C2M0_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
 - 0.5 * 2*real(sum( conj(a_k_p_quad_).^1 .* a_restore_C1M1_k_p_quad_ .* weight_3d_riesz_k_all_ )) ...
 + 0.5 * sum( a_restore_C0M2_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
;
ssnll_q3d = ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_q2d vs ssnll_q3d: %0.16f',fnorm(ssnll_q2d-ssnll_q3d)/fnorm(ssnll_q2d))); end;
%%%%%%%%;
ssnll_q3d = ...
 + 0.5 * sum( conj(a_k_p_quad_) .* (a_k_p_quad_) .* a_restore_C2M0_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
 - 0.5 * sum( conj(a_k_p_quad_) .* a_restore_C1M1_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
 - 0.5 * sum( conj(a_restore_C1M1_k_p_quad_) .* (a_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
 + 0.5 * sum( a_restore_C0M2_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
;
ssnll_q3d = ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_q2d vs ssnll_q3d: %0.16f',fnorm(ssnll_q2d-ssnll_q3d)/fnorm(ssnll_q2d))); end;
%%%%%%%%;
ssnll_q3d = ...
 + 0.5 * sum( (conj(a_k_Y_quad_yk__) .* a_times_a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_quad_yk__).^1 .* a_restore_C1M1_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( a_restore_C0M2_k_Y_yk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
ssnll_q3d = ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_q2d vs ssnll_q3d: %0.16f',fnorm(ssnll_q2d-ssnll_q3d)/fnorm(ssnll_q2d))); end;
%%%%%%%%;

%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% comparing first-derivative (reasonably accurate): ')); end;
%%%%%%%%;
dtau_ssnll_q3d = ...
 + 0.5 * sum( (conj(a_times_a_k_Y_quad_yk__) .* dtau_a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_quad_yk__).^1 .* dtau_a_restore_C1M1_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( dtau_a_restore_C0M2_k_Y_yk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
dtau_ssnll_q3d = dtau_ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_q2d vs dtau_ssnll_q3d: %0.16f',fnorm(dtau_ssnll_q2d - dtau_ssnll_q3d)/max(1e-12,fnorm(dtau_ssnll_q2d)))); end;
%%%%%%%%;
dtau_ssnll_q3d = ...
 + 0.5 * sum( abs(a_k_p_quad_).^2 .* dtau_a_restore_C2M0_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
 - 0.5 * 2*real(sum( conj(a_k_p_quad_).^1 .* dtau_a_restore_C1M1_k_p_quad_ .* weight_3d_riesz_k_all_ )) ...
 + 0.5 * sum( dtau_a_restore_C0M2_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
  ;
dtau_ssnll_q3d = dtau_ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_q2d vs dtau_ssnll_q3d: %0.16f',fnorm(dtau_ssnll_q2d - dtau_ssnll_q3d)/max(1e-12,fnorm(dtau_ssnll_q2d)))); end;
%%%%%%%%;
dtau_ssnll_q3d = ...
 + 0.5 * sum( (conj(a_k_Y_quad_yk__).^1 .* a_times_dtau_a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_quad_yk__).^1 .* dtau_a_restore_C1M1_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( dtau_a_restore_C0M2_k_Y_yk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
dtau_ssnll_q3d = dtau_ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_q2d vs dtau_ssnll_q3d: %0.16f',fnorm(dtau_ssnll_q2d - dtau_ssnll_q3d)/max(1e-12,fnorm(dtau_ssnll_q2d)))); end;
%%%%%%%%;

%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% comparing second-derivative (not as accurate): ')); end;
%%%%%%%%;
dtau_dtau_ssnll_q3d = ...
 + 0.5 * sum( (conj(a_times_a_k_Y_quad_yk__) .* dtau_dtau_a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_quad_yk__).^1 .* dtau_dtau_a_restore_C1M1_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( dtau_dtau_a_restore_C0M2_k_Y_yk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
dtau_dtau_ssnll_q3d = dtau_dtau_ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% dtau_dtau_ssnll_q2d vs dtau_dtau_ssnll_q3d: %0.16f',fnorm(dtau_dtau_ssnll_q2d - dtau_dtau_ssnll_q3d)/max(1e-12,fnorm(dtau_dtau_ssnll_q2d)))); end;
%%%%%%%%;
dtau_dtau_ssnll_q3d = ...
 + 0.5 * sum( abs(a_k_p_quad_).^2 .* dtau_dtau_a_restore_C2M0_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
 - 0.5 * 2*real(sum( conj(a_k_p_quad_).^1 .* dtau_dtau_a_restore_C1M1_k_p_quad_ .* weight_3d_riesz_k_all_ )) ...
 + 0.5 * sum( dtau_dtau_a_restore_C0M2_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
  ;
dtau_dtau_ssnll_q3d = dtau_dtau_ssnll_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% dtau_dtau_ssnll_q2d vs dtau_dtau_ssnll_q3d: %0.16f',fnorm(dtau_dtau_ssnll_q2d - dtau_dtau_ssnll_q3d)/max(1e-12,fnorm(dtau_dtau_ssnll_q2d)))); end;
%%%%%%%%;

%%%%%%%%;
% Now construct hessian. ;
%%%%%%%%;
%{
  % As indicated via the above calculation: ;
  ssnll_q3d = ...
    + 0.5 * sum( conj(a_k_p_quad_) .* (a_k_p_quad_) .* a_restore_C2M0_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
    - 0.5 * sum( conj(a_k_p_quad_) .* a_restore_C1M1_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
    - 0.5 * sum( conj(a_restore_C1M1_k_p_quad_) .* (a_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
    + 0.5 * sum( a_restore_C0M2_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
    ;
  ssnll_q3d = ssnll_q3d / scaling_volumetric ;
  % rewriting this as: ;
  ssnll_q3d = ...
    + 0.5 * sum( conj(a_) .* (a_) .* C2M0_ .* w_ ) ...
    - 0.5 * sum( conj(a_) .* C1M1_ .* w_ ) ...
    - 0.5 * sum( conj(C1M1_) .* (a_) .* w_ ) ...
    + 0.5 * sum( C0M2_ .* w_ ) ...
    ;
  ssnll_q3d = ssnll_q3d / scaling_volumetric ;
  % we have: ;
  ssnll_q3d = ...
    + 0.5 * sum( conj(a_ + dvol_) .* (a_ + dvol_) .* (C2M0_ + dtau_C2M0_*dtau_ + 0.5*ctranspose(dtau_)*dtau_dtau_C2M0__*(dtau_)) .* w_ ) ...
    - 0.5 * sum( conj(a_ + dvol_) .* (C1M1_ + dtau_C1M1_*dtau_ + 0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* w_ ) ...
    - 0.5 * sum( conj(C1M1_ + dtau_C1M1_*dtau_ + 0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* (a_ + dvol_) .* w_ ) ...
    + 0.5 * sum( (C0M2_ + dtau_C0M2_*dtau_ + 0.5*ctranspose(dtau_)*dtau_dtau_C0M2__*(dtau_)) .* w_ ) ...
    ;
  ssnll_q3d = ssnll_q3d / scaling_volumetric ;
  % where we assume: ;
  % 1. dvol_ is a perturbation of the form dvol_k_p_quad_, ;
  % 2. dtau_ is a perturbation of the form dtau_M3__, not accounting for weight_imagecount_M_, ;
  % 3. dtau_CXMX_ is a jacobian (i.e., of the form dtau_CXMX_M3__), and ;
  % 4. dtau_dtau_CXMX__ is a hessian (i.e., of the form dtau_dtau_CXMX_M33__). ;
  % Using this notation, we can expand and retain terms of order 2 and lower: ;
  ssnll_q3d = ...
    ...
    + 0.5 * sum( conj(a_) .* (a_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(dvol_) .* (a_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (dvol_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (a_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    + 0.5 * sum( conj(dvol_) .* (dvol_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(dvol_) .* (a_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (dvol_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (a_ ) .* (0.5*ctranspose(dtau_)*dtau_dtau_C2M0__*(dtau_)) .* w_ ) ...
    ...
    - 0.5 * sum( conj(a_) .* (C1M1_) .* w_ ) ...
    - 0.5 * sum( conj(dvol_) .* (C1M1_) .* w_ ) ...
    - 0.5 * sum( conj(a_) .* (dtau_C1M1_*dtau_) .* w_ ) ...
    - 0.5 * sum( conj(dvol_) .* (dtau_C1M1_*dtau_) .* w_ ) ...
    - 0.5 * sum( conj(a_) .* (0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* w_ ) ...
    ...
    - 0.5 * sum( conj(C1M1_) .* (a_) .* w_ ) ...
    - 0.5 * sum( conj(C1M1_) .* (dvol_) .* w_ ) ...
    - 0.5 * sum( conj(dtau_C1M1_*dtau_) .* (a_) .* w_ ) ...
    - 0.5 * sum( conj(dtau_C1M1_*dtau_) .* (dvol_) .* w_ ) ...
    - 0.5 * sum( conj(0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* (a_) .* w_ ) ...
    ...
    + 0.5 * sum( (C0M2_) .* w_ ) ...
    + 0.5 * sum( (dtau_C0M2_*dtau_) .* w_ ) ...
    + 0.5 * sum( (0.5*ctranspose(dtau_)*dtau_dtau_C0M2__*(dtau_)) .* w_ ) ...
    ...
    ;
  ssnll_q3d = ssnll_q3d / scaling_volumetric ;
  % Combining terms of like order: ;
  ssnll_q3d = ...
    ...
    + 0.5 * sum( conj(a_) .* (a_) .* (C2M0_) .* w_ ) ...
    - 0.5 * sum( conj(a_) .* (C1M1_) .* w_ ) ...
    - 0.5 * sum( conj(C1M1_) .* (a_) .* w_ ) ...
    + 0.5 * sum( (C0M2_) .* w_ ) ...
    ...
    + 0.5 * sum( conj(dvol_) .* (a_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (dvol_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (a_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    - 0.5 * sum( conj(dvol_) .* (C1M1_) .* w_ ) ...
    - 0.5 * sum( conj(a_) .* (dtau_C1M1_*dtau_) .* w_ ) ...
    - 0.5 * sum( conj(C1M1_) .* (dvol_) .* w_ ) ...
    - 0.5 * sum( conj(dtau_C1M1_*dtau_) .* (a_) .* w_ ) ...
    + 0.5 * sum( (dtau_C0M2_*dtau_) .* w_ ) ...
    ...
    + 0.5 * sum( conj(dvol_) .* (dvol_) .* (C2M0_) .* w_ ) ...
    + 0.5 * sum( conj(dvol_) .* (a_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (dvol_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    + 0.5 * sum( conj(a_) .* (a_ ) .* (0.5*ctranspose(dtau_)*dtau_dtau_C2M0__*(dtau_)) .* w_ ) ...
    - 0.5 * sum( conj(dvol_) .* (dtau_C1M1_*dtau_) .* w_ ) ...
    - 0.5 * sum( conj(a_) .* (0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* w_ ) ...
    - 0.5 * sum( conj(dtau_C1M1_*dtau_) .* (dvol_) .* w_ ) ...
    - 0.5 * sum( conj(0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* (a_) .* w_ ) ...
    + 0.5 * sum( (0.5*ctranspose(dtau_)*dtau_dtau_C0M2__*(dtau_)) .* w_ ) ...
    ...
    ;
  ssnll_q3d = ssnll_q3d / scaling_volumetric ;
  % From this expansion we can extract the gradient as a linear-operator acting on [dvol_;dtau_]: ;
  Gradient of ssnll_q3d = ...
      + 1.0 * real(sum( [ conj(a_) .* (C2M0_) - conj(C1M1) ] .* (dvol_) .* w_ )) ...
      - 1.0 * real(sum( [ conj(a_).*dtau_C1M1_ - 0.5*conj(a_).*a_.*dtau_C2M0_ - 0.5*dtau_C0M2_ ] * (dtau_) .* w_ )) ...
    ;
  Gradient of ssnll_q3d = Gradient of ssnll_q3d / scaling_volumetric ;
  % Note that again we have not accounted for weight_imagecount_M_. ;
  % Similarly, we can extract the hessian as a quadratic-kernel acting on [dvol_;dtau_]: ;
  Hessian of ssnll_q3d = ...
    [ctranspose(dvol_) , ctranspose(dtau_)] * [ H ] * [dvol_;dtau_] ...
    ;
  % where the matrix H is a block-matrix with components: ;
  %      [ Hvv | Hvt ]  ;
  %  H = [-----+-----]  ;
  %      [ Htv | Htt ]  ;
  % such that: ;
  Hvv = quadratic-kernel acting on dvol_ = + 1.0 * sum( conj(dvol_) .* (C2M0_) .* (dvol_) .* w_ ) / scaling_volumetric ;
  Htt = quadratic-kernel acting on dtau_ = ...
    + 1.0 * sum( conj(a_) .* (a_ ) .* (0.5*ctranspose(dtau_)*dtau_dtau_C2M0__*(dtau_)) .* w_ ) ...
    - 1.0 * sum( conj(a_) .* (0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* w_ ) ...
    - 1.0 * sum( conj(0.5*ctranspose(dtau_)*dtau_dtau_C1M1__*(dtau_)) .* (a_) .* w_ ) ...
    + 1.0 * sum( (0.5*ctranspose(dtau_)*dtau_dtau_C0M2__*(dtau_)) .* w_ ) ...
    ;
  Htt = Htt / scaling_volumetric ;
  % Note that again we have not accounted for weight_imagecount_M_. ;
  % Note that, via ssnll_from_a_k_Y_12, Htt can be rewritten in the simpler form: ;
  Htt = sum( dtau_M3__(1+nM,1+ntau0) * dtau_dtau_ssnll_q2d_M33___(1+nM,1+ntau0,1+ntau1) * dtau_M3__(1+nM,1+ntau1) ). ;
  % The operator Hvt has a domain compatible with dtau_ and a range compatible with dvol_. ;
  Hvt = ...
    + 1.0 * sum( conj(dvol_) .* (a_) .* (dtau_C2M0_*dtau_) .* w_ ) ...
    - 1.0 * sum( conj(dvol_) .* (dtau_C1M1_*dtau_) .* w_ ) ...
    ;
  Hvt = Hvt / scaling_volumetric ;
  % Note that, given the output of kappa_qpro_apply_2, we can rewrite Hvt as:
  Hvt = ...
      + 1.0 * sum( conj(dvol_) .* (a_) .* (|dtau| * dtau_a_restore_C2M0_k_p_quad_) .* w_ ) ...
      - 1.0 * sum( conj(dvol_) .* (|dtau| * dtau_a_restore_C1M1_k_p_quad_) .* w_ ) ...
      ;
  Hvt = Hvt / scaling_volumetric ;
  % The operator Htv has a domain compatible with dvol_ and a range compatible with dtau_. ;
  Htv = ...
    + 1.0 * sum( conj(dtau_C2M0_*dtau_) .* conj(a_) .* (dvol_) .* w_ ) ...
    - 1.0 * sum( conj(dtau_C1M1_*dtau_) .* (dvol_) .* w_ ) ...
    ;
  Htv = Htv / scaling_volumetric ;
  % Note that, via ssnll_from_a_k_Y_12, Htv can be rewritten in the simpler form: ;
  Htv = sum( dtau_M3__(1+nM,1+ntau1) * dtau_dvol_ssnll_q2d_M3__(1+nM,1+ntau1) ). ;
 %}
%%%%%%%%;
Hvv_q3d = ...
 + 1.0 * sum( (conj(dvol_a_times_dvol_a_k_Y_quad_yk__) .* a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
Hvv_q3d = ...
 + 1.0 * sum( (conj(dvol_a_k_Y_quad_yk__) .* dvol_a_times_a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
Hvv_q3d = ...
 + 1.0 * sum( conj(dvol_a_k_Y_quad_yk__) .* bsxfun(@times,dvol_a_times_a_restore_C2M0_k_Y_yk__,reshape(weight_3d_riesz_k_p_r_,[1,n_k_p_r])) , 'all' ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
Hvv_q3d = ...
 + 1.0 * sum( conj(dvol_a_k_p_quad_) .* dvol_a_k_p_quad_ .* a_restore_C2M0_k_p_quad_ .* weight_3d_riesz_k_all_ ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
%%%%%%%%;
dtau_M33___ = bsxfun(@times,reshape(dtau_M3__,[n_M,3,1]),reshape(dtau_M3__,[n_M,1,3]));
Htt_q2d = sum( bsxfun(@times,dtau_dtau_ssnll_q2d_M33___.*dtau_M33___,weight_imagecount_M_) , 'all' ) ;
if (flag_verbose>0); disp(sprintf(' %% Htt_q2d: %0.16f',Htt_q2d)); end;
Htt_q2d = sum( bsxfun(@times,dtau_M3__,weight_imagecount_M_) .* sum(bsxfun(@times,dtau_dtau_ssnll_q2d_M33___,reshape(dtau_M3__,[n_M,1,3])),[3]) , 'all' ) ;
if (flag_verbose>0); disp(sprintf(' %% Htt_q2d: %0.16f',Htt_q2d)); end;
Htt_q3d = ...
  + 1.0 * sum( conj(a_k_p_quad_) .* (a_k_p_quad_ ) .* (0.5*dtau_dtau_a_restore_C2M0_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  - 1.0 * sum( conj(a_k_p_quad_) .* (0.5*dtau_dtau_a_restore_C1M1_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  - 1.0 * sum( conj(0.5*dtau_dtau_a_restore_C1M1_k_p_quad_) .* (a_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  + 1.0 * sum( (0.5*dtau_dtau_a_restore_C0M2_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  ;
Htt_q3d = Htt_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Htt_q3d: %0.16f',Htt_q3d)); end;
if (flag_verbose>0); disp(sprintf(' %% Htt_q2d vs Htt_q3d: %0.16f',fnorm(Htt_q2d - Htt_q3d)/max(1e-12,fnorm(Htt_q2d)))); end;
%%%%%%%%;
Htv_q3d = ...
  + 1.0 * sum( conj(dtau_a_restore_C2M0_k_p_quad_) .* conj(a_k_p_quad_) .* (dvol_a_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  - 1.0 * sum( conj(dtau_a_restore_C1M1_k_p_quad_) .* (dvol_a_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  ;
Htv_q3d = Htv_q3d / scaling_volumetric ;
Htv_q2d = sum( bsxfun(@times,dtau_M3__,weight_imagecount_M_) .* dtau_dvol_ssnll_q2d_M3__ , 'all' );
if (flag_verbose>0); disp(sprintf(' %% Htv_q2d vs Htv_q3d: %0.16f',fnorm(Htv_q2d - Htv_q3d)/max(1e-12,fnorm(Htv_q2d)))); end;
%%%%%%%%;
Hvt_q3d = ...
  + 1.0 * sum( conj(dvol_a_k_p_quad_) .* (a_k_p_quad_) .* (dtau_a_restore_C2M0_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  - 1.0 * sum( conj(dvol_a_k_p_quad_) .* (dtau_a_restore_C1M1_k_p_quad_) .* weight_3d_riesz_k_all_ ) ...
  ;
Hvt_q3d = Hvt_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvt_q3d: %0.16f',Hvt_q3d)); end;
Hvt_q3d = ...
  + 1.0 * sum( (conj(dvol_a_k_Y_quad_yk__) .* a_times_dtau_a_restore_C2M0_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
  - 1.0 * sum( (conj(dvol_a_k_Y_quad_yk__) .* dtau_a_restore_C1M1_k_Y_yk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
  ;
Hvt_q3d = Hvt_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvt_q3d: %0.16f',Hvt_q3d)); end;
Hvt_q3d = ...
  + 1.0 * sum( conj(dvol_a_k_Y_quad_yk__) .* bsxfun(@times,a_times_dtau_a_restore_C2M0_k_Y_yk__,reshape(weight_3d_riesz_k_p_r_,[1,n_k_p_r]) ) , 'all' ) ...
  - 1.0 * sum( conj(dvol_a_k_Y_quad_yk__) .* bsxfun(@times,dtau_a_restore_C1M1_k_Y_yk__,reshape(weight_3d_riesz_k_p_r_,[1,n_k_p_r]) ) , 'all' ) ...
  ;
Hvt_q3d = Hvt_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvt_q3d: %0.16f',Hvt_q3d)); end;
Hvt_q3d = ...
  + 1.0 * sum( conj(dvol_a_k_Y_quad_yk__) .* bsxfun(@times,a_times_dtau_a_restore_C2M0_k_Y_yk__-dtau_a_restore_C1M1_k_Y_yk__,reshape(weight_3d_riesz_k_p_r_,[1,n_k_p_r])) , 'all' ) ...
  ;
Hvt_q3d = Hvt_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvt_q3d: %0.16f',Hvt_q3d)); end;
Hvt_q2d = conj(Htv_q2d) ; %<-- due to symmetry. ;
if (flag_verbose>0); disp(sprintf(' %% Hvt_q2d vs Hvt_q3d: %0.16f',fnorm(Hvt_q2d - Hvt_q3d)/max(1e-12,fnorm(Hvt_q2d)))); end;
%%%%%%%%;

%%%%%%%%;
a_restore_C2M0_k_Y_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,a_restore_C2M0_k_Y_yk__);
%%%%%%%%;
dtau_a_restore_C2M0_k_Y_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,dtau_a_restore_C2M0_k_Y_yk__);
%%%%%%%%;
dtau_a_restore_C1M1_k_Y_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,dtau_a_restore_C1M1_k_Y_yk__);
%%%%%%%%;
if (flag_disp>1);
figure(1+nf);nf=nf+1;clf;figbig;
p_row=2; p_col=2*2; np=0;
%%%%;
for ntype=0:4-1;
if ntype==0; tmp_k_p_quad_ = a_k_p_quad_; tmp_k_Y_quad_yk__ = a_k_Y_quad_yk__; tmp_str = 'a_k_Y'; end;
if ntype==1; tmp_k_p_quad_ = a_restore_C2M0_k_p_quad_; tmp_k_Y_quad_yk__ = a_restore_C2M0_k_Y_yk__; tmp_str = 'a_restore_C2M0'; end;
if ntype==2; tmp_k_p_quad_ = dtau_a_restore_C2M0_k_p_quad_; tmp_k_Y_quad_yk__ = dtau_a_restore_C2M0_k_Y_yk__; tmp_str = 'dtau_a_restore_C2M0'; end;
if ntype==3; tmp_k_p_quad_ = dtau_a_restore_C1M1_k_p_quad_; tmp_k_Y_quad_yk__ = dtau_a_restore_C1M1_k_Y_yk__; tmp_str = 'dtau_a_restore_C1M1'; end;
tmp_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,tmp_k_Y_quad_yk__);
l2_a0 = sum ((conj(tmp_k_Y_quad_yk__).*tmp_k_Y_quad_yk__)*reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) , 'all' )/scaling_volumetric;
disp(sprintf(' %% %s: tmp_k_Y_quad_yk__: l2_a0: %0.16f',tmp_str,l2_a0));
l2_a0 = sum ((conj(tmp_k_p_quad_).*tmp_k_p_quad_).*weight_3d_riesz_k_all_ , 'all' )/scaling_volumetric;
disp(sprintf(' %% %s: tmp_k_p_quad_    : l2_a0: %0.16f',tmp_str,l2_a0));
subplot(p_row,p_col,1+np);np=np+1;
plot(Y_l_val_,abs(tmp_k_Y_quad_yk_),'k.');
xlabel('Y_l_val_','Interpreter','none');
title(sprintf('abs(%s)',tmp_str),'Interpreter','none');
%%%%;
tmp_abs_k_p_quad_ = abs(tmp_k_p_quad_).*sqrt(weight_3d_riesz_k_all_);
flag_2d_vs_3d = 0; c_use__ = colormap_81s;
nk_p_r = floor(n_k_p_r/2);
tmp_index_ = n_k_all_csum_(1+nk_p_r+0):n_k_all_csum_(1+nk_p_r+1)-1;
lim_ = prctile(tmp_abs_k_p_quad_(1+tmp_index_),[ 5,95]);
subplot(p_row,p_col,1+np);np=np+1;
imagesc_polar_a_azimu_b_0( ...
 k_p_polar_a_all_(1+tmp_index_) ...
,k_p_azimu_b_all_(1+tmp_index_) ...
,tmp_abs_k_p_quad_(1+tmp_index_) ... 
,lim_ ... 
,c_use__ ... 
,flag_2d_vs_3d ...
,k_p_r_max ...
);
axis equal; axis vis3d; axisnotick3d;
title(sprintf('abs(%s)',tmp_str),'Interpreter','none');
end;%for ntype=0:4-1;
end;%if (flag_disp>1);
%%%%%%%%;

%%%%%%%%;
Hvv_q3d_k_p_quad_ = dvol_a_k_p_quad_.*a_restore_C2M0_k_p_quad_;
Hvv_q3d_k_Y_quad_yk_ = dvol_a_times_a_restore_C2M0_k_Y_yk_;
Hvv_q3d_k_Y_quad_yk__ = dvol_a_times_a_restore_C2M0_k_Y_yk__;
Hvt_q3d_k_p_quad_ = a_k_p_quad_.*dtau_a_restore_C2M0_k_p_quad_ - dtau_a_restore_C1M1_k_p_quad_;
Hvt_q3d_k_Y_quad_yk_ = a_times_dtau_a_restore_C2M0_k_Y_yk_ - dtau_a_restore_C1M1_k_Y_yk_;
Hvt_q3d_k_Y_quad_yk__ = a_times_dtau_a_restore_C2M0_k_Y_yk__ - dtau_a_restore_C1M1_k_Y_yk__;
%%%%%%%%;
Hv_q3d_k_p_quad_ = Hvv_q3d_k_p_quad_ + Hvt_q3d_k_p_quad_;
Hv_q3d_k_Y_quad_yk__ = Hvv_q3d_k_Y_quad_yk__ + Hvt_q3d_k_Y_quad_yk__;
%%%%%%%%;
Hv_q3d_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,Hv_q3d_k_Y_quad_yk__);
%%%%%%%%;
[ ...
 Hv_q3d_k_p_reco_ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,Hv_q3d_k_Y_quad_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
if (flag_verbose>0); disp(sprintf(' %% Hv_q3d_k_p_quad_ vs Hv_q3d_k_p_reco_: %0.16f',fnorm(Hv_q3d_k_p_quad_ - Hv_q3d_k_p_reco_)/max(1e-12,fnorm(Hv_q3d_k_p_quad_)))); end;
%%%%%%%%;
if flag_check;
[ ...
 Hv_q3d_k_Y_reco_yk_ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,Hv_q3d_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
if (flag_verbose>0); disp(sprintf(' %% Hv_q3d_k_Y_quad_yk_ vs Hv_q3d_k_Y_reco_yk_: %0.16f',fnorm(Hv_q3d_k_Y_quad_yk_ - Hv_q3d_k_Y_reco_yk_)/max(1e-12,fnorm(Hv_q3d_k_Y_quad_yk_)))); end;
end;%if flag_check;
%%%%%%%%;
if (flag_disp>1);
figure(1+nf);nf=nf+1;clf;figmed;
p_row=1; p_col=2*1; np=0;
%%%%;
tmp_k_p_quad_ = Hv_q3d_k_p_quad_;
tmp_k_Y_quad_yk__ = Hv_q3d_k_Y_quad_yk__;
tmp_str = 'Hv_q3d';
tmp_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,tmp_k_Y_quad_yk__);
l2_a0 = sum ((conj(tmp_k_Y_quad_yk__).*tmp_k_Y_quad_yk__)*reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) , 'all' )/scaling_volumetric;
disp(sprintf(' %% %s: tmp_k_Y_quad_yk__: l2_a0: %0.16f',tmp_str,l2_a0));
l2_a0 = sum ((conj(tmp_k_p_quad_).*tmp_k_p_quad_).*weight_3d_riesz_k_all_ , 'all' )/scaling_volumetric;
disp(sprintf(' %% %s: tmp_k_p_quad_    : l2_a0: %0.16f',tmp_str,l2_a0));
subplot(p_row,p_col,1+np);np=np+1;
plot(Y_l_val_,abs(tmp_k_Y_quad_yk_),'k.');
xlabel('Y_l_val_','Interpreter','none');
title(sprintf('abs(%s)',tmp_str),'Interpreter','none');
%%%%;
tmp_abs_k_p_quad_ = abs(tmp_k_p_quad_).*sqrt(weight_3d_riesz_k_all_);
flag_2d_vs_3d = 0; c_use__ = colormap_81s;
nk_p_r = floor(n_k_p_r/2);
tmp_index_ = n_k_all_csum_(1+nk_p_r+0):n_k_all_csum_(1+nk_p_r+1)-1;
lim_ = prctile(tmp_abs_k_p_quad_(1+tmp_index_),[ 5,95]);
subplot(p_row,p_col,1+np);np=np+1;
imagesc_polar_a_azimu_b_0( ...
 k_p_polar_a_all_(1+tmp_index_) ...
,k_p_azimu_b_all_(1+tmp_index_) ...
,tmp_abs_k_p_quad_(1+tmp_index_) ... 
,lim_ ... 
,c_use__ ... 
,flag_2d_vs_3d ...
,k_p_r_max ...
);
axis equal; axis vis3d; axisnotick3d;
title(sprintf('abs(%s)',tmp_str),'Interpreter','none');
end;%if (flag_disp>1);
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%;
% Now we calculate the left-hand-side: ;
%%%%%%%%;
Hvv_q3d_k_p_quad_ = dvol_a_k_p_quad_.*a_restore_C2M0_k_p_quad_;
Hvv_q3d_k_Y_quad_yk__ = dvol_a_times_a_restore_C2M0_k_Y_yk__;
Htv_q2d_M3__ = dtau_dvol_ssnll_q2d_M3__;
Hvt_q3d_k_p_quad_ = (a_k_p_quad_.*dtau_a_restore_C2M0_k_p_quad_ - dtau_a_restore_C1M1_k_p_quad_);
Hvt_q3d_k_Y_quad_yk__ = (a_times_dtau_a_restore_C2M0_k_Y_yk__ - dtau_a_restore_C1M1_k_Y_yk__);
Htt_q2d_M3__ = sum(bsxfun(@times,dtau_dtau_ssnll_q2d_M33___,reshape(dtau_M3__,[n_M,1,3])),[3]);
%%%%%%%%;
Hv_q3d_k_p_quad_ = Hvv_q3d_k_p_quad_ + Hvt_q3d_k_p_quad_;
Hv_q3d_k_Y_quad_yk__ = Hvv_q3d_k_Y_quad_yk__ + Hvt_q3d_k_Y_quad_yk__;
Ht_q2d_M3__ = Htt_q2d_M3__ + Htv_q2d_M3__;
%%%%%%%%;
Hvv_q3d_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,Hvv_q3d_k_Y_quad_yk__);
Hvt_q3d_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,Hvt_q3d_k_Y_quad_yk__);
Hv_q3d_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,Hv_q3d_k_Y_quad_yk__);

Hvt_ykabc_ = cat(1,Hv_q3d_k_Y_quad_yk_,Ht_q2d_M3__(:,1+0),Ht_q2d_M3__(:,1+1),Ht_q2d_M3__(:,1+2));

dvt = [];
dvt_ = [];
n_dvt = [];
ssnll_tmp_q2d_dvt_ = [];
dssnll_mid_q2d = [];
dssnll_dif_q2d = [];
dssnll_lsq_q2d = [];
ddssnll_mid_q2d = [];
ddssnll_dif_q2d = [];
ddssnll_lsq_q2d = [];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
dvt = dvt_check;
%%%%%%%%;
% Calculate the gradient: ;
%%%%%%%%;
dvol_ssnll_q3d_k_p_quad_ = + 1.0 * ( conj(a_k_p_quad_) .* (a_restore_C2M0_k_p_quad_) - conj(a_restore_C1M1_k_p_quad_) );
dvol_ssnll_q3d_k_Y_quad_yk__ = + 1.0 * ( conj(a_times_a_restore_C2M0_k_Y_yk__) - conj(a_restore_C1M1_k_Y_yk__) );
dtau_ssnll_q2d_M3__ = dtau_ssnll_q2d_M3__ ;
%%%%%%%%;
dvol_ssnll_q3d_k_Y_quad_yk_ = local_yk_from_yk__(n_k_p_r,l_max_,dvol_ssnll_q3d_k_Y_quad_yk__);
%%%%%%%%;
G_ykabc_ = cat(1,dvol_ssnll_q3d_k_Y_quad_yk_,dtau_ssnll_q2d_M3__(:,1+0),dtau_ssnll_q2d_M3__(:,1+1),dtau_ssnll_q2d_M3__(:,1+2));
G_bar_ykabc_ = conj(G_ykabc_); %<-- note here we take a conjugate to allow for standard dot-product. ;
%%%%%%%%;
% Now calculate the difference-quotient and compare. ;
%%%%%%%%;
dvt_ykabc_ = local_ykabc_from_yk_a_b_c_(n_k_p_r,l_max_,n_M,dvol_a_k_Y_quad_yk_,dtau_euler_polar_a_M_,dtau_euler_azimu_b_M_,dtau_euler_gamma_z_M_);
dvt_ykabc_l2 = local_imagecount_f_bar_dot_g_(n_k_p_r,weight_3d_riesz_k_p_r_,l_max_,n_M,weight_imagecount_M_,dvt_ykabc_,dvt_ykabc_);
dssnll_mid_q2d = local_imagecount_f_bar_dot_g_(n_k_p_r,weight_3d_riesz_k_p_r_,l_max_,n_M,weight_imagecount_M_,G_bar_ykabc_,dvt_ykabc_);
%%%%;
dvt_ = transpose(-8:+8);
n_dvt = numel(dvt_);
ssnll_tmp_q2d_dvt_ = zeros(n_dvt,1);
%%%%;
for ndvt=0:n_dvt-1;
if (flag_verbose>0); disp(sprintf(' %% ndvt %d/%d',ndvt,n_dvt)); end;
tmp_euler_polar_a_M_ = euler_polar_a_M_ + 1.0*dvt*dvt_(1+ndvt)*dtau_euler_polar_a_M_;
tmp_euler_azimu_b_M_ = euler_azimu_b_M_ + 1.0*dvt*dvt_(1+ndvt)*dtau_euler_azimu_b_M_;
tmp_euler_gamma_z_M_ = euler_gamma_z_M_ + 1.0*dvt*dvt_(1+ndvt)*dtau_euler_gamma_z_M_;
[tmp_euler_polar_a_M_,tmp_euler_azimu_b_M_] = periodize_polar_a_azimu_b_0(tmp_euler_polar_a_M_,tmp_euler_azimu_b_M_);
tmp_euler_gamma_z_M_ = periodize(tmp_euler_gamma_z_M_,0,2*pi);
[ ...
 ~ ...
,~ ...
,ssnll_tmp_q2d_dvt_(1+ndvt) ...
] = ...
ssnll_from_a_k_Y_13( ...
 parameter_ssnll ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_quad_yk__ + 1.0*dvt*dvt_(1+ndvt)*dvol_a_k_Y_quad_yk__...
,[] ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,weight_imagecount_M_ ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,tmp_euler_polar_a_M_ ...
,tmp_euler_azimu_b_M_ ...
,tmp_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
);
end;%for ndvt=0:n_dvt-1;
%%%%;
ssnll_mid_q2d = ssnll_tmp_q2d_dvt_((1+n_dvt)/2);
ssnll_pos_q2d = ssnll_tmp_q2d_dvt_((1+n_dvt)/2+1);
ssnll_neg_q2d = ssnll_tmp_q2d_dvt_((1+n_dvt)/2-1);
dssnll_dif_q2d = (ssnll_pos_q2d - ssnll_neg_q2d)/max(1e-12,2*dvt);
if (flag_verbose>0); disp(sprintf(' %% dssnll_dif_q2d vs dssnll_mid_q2d: %0.16f',fnorm(dssnll_dif_q2d -dssnll_mid_q2d)/max(1e-12,fnorm(dssnll_dif_q2d)))); end;
%%%%;
tmp_x_ = dvt*dvt_;
tmp_y_ = real(ssnll_tmp_q2d_dvt_);
tmp_x4 = sum(tmp_x_.^4);
tmp_x3 = sum(tmp_x_.^3);
tmp_x2 = sum(tmp_x_.^2);
tmp_x1 = sum(tmp_x_.^1);
tmp_x0 = sum(tmp_x_.^0);
tmp_yx2 = sum(tmp_y_.*tmp_x_.^2);
tmp_yx1 = sum(tmp_y_.*tmp_x_.^1);
tmp_yx0 = sum(tmp_y_.*tmp_x_.^0);
tmp_lhs_ = [ ...
 tmp_x4 tmp_x3 tmp_x2 ...
;tmp_x3 tmp_x2 tmp_x1 ...
;tmp_x2 tmp_x1 tmp_x0 ...
];
tmp_rhs_ = [ tmp_yx2 ; tmp_yx1 ; tmp_yx0 ];
tmp_p_ = tmp_lhs_\tmp_rhs_;
tmp_p_x_ = polyval(tmp_p_,tmp_x_);
%%%%;
if (flag_disp>1);
figure(1+nf);nf=nf+1;clf;figsml;
markersize_use = 12;
linewidth_use = 2;
hold on;
plot(tmp_x_,tmp_p_x_,'k-','LineWidth',linewidth_use);
plot(tmp_x_,ssnll_tmp_q2d_dvt_,'ko','MarkerSize',markersize_use,'MarkerFaceColor','c');
xlabel('dvt_','Interpreter','none');
ylabel('ssnll_tmp_q2d_dvt_','Interpreter','none');
end;%if (flag_disp>1);
%%%%;
dssnll_lsq_q2d = 1.0*tmp_p_(1+1);
if (flag_verbose>0); disp(sprintf(' %% dssnll_lsq_q2d vs dssnll_mid_q2d: %0.16f',fnorm(dssnll_lsq_q2d -dssnll_mid_q2d)/max(1e-12,fnorm(dssnll_lsq_q2d)))); end;
%%%%%%%%;
% Estimate the second-derivative. ;
%%%%%%%%;
ddssnll_mid_q2d = local_imagecount_f_bar_dot_g_(n_k_p_r,weight_3d_riesz_k_p_r_,l_max_,n_M,weight_imagecount_M_,Hvt_ykabc_,dvt_ykabc_);
%%%%;
ssnll_mid_q2d = ssnll_tmp_q2d_dvt_((1+n_dvt)/2);
ssnll_pos_q2d = ssnll_tmp_q2d_dvt_((1+n_dvt)/2+1);
ssnll_neg_q2d = ssnll_tmp_q2d_dvt_((1+n_dvt)/2-1);
ddssnll_dif_q2d = (ssnll_pos_q2d - 2*ssnll_mid_q2d + ssnll_neg_q2d)/max(1e-12,dvt^2);
if (flag_verbose>0); disp(sprintf(' %% ddssnll_dif_q2d vs ddssnll_mid_q2d: %0.16f',fnorm(ddssnll_dif_q2d -ddssnll_mid_q2d)/max(1e-12,fnorm(ddssnll_dif_q2d)))); end;
%%%%;
ddssnll_lsq_q2d = 2.0*tmp_p_(1+0);
if (flag_verbose>0); disp(sprintf(' %% ddssnll_lsq_q2d vs ddssnll_mid_q2d: %0.16f',fnorm(ddssnll_lsq_q2d -ddssnll_mid_q2d)/max(1e-12,fnorm(ddssnll_lsq_q2d)))); end;
%%%%;
if (flag_verbose>0);
disp(sprintf(' %% dssnll_mid_q2d:  %+0.16f',dssnll_mid_q2d));
disp(sprintf(' %% dssnll_dif_q2d:  %+0.16f',dssnll_dif_q2d));
disp(sprintf(' %% dssnll_lsq_q2d:  %+0.16f',dssnll_lsq_q2d));
disp(sprintf(' %% ddssnll_mid_q2d: %+0.16f',ddssnll_mid_q2d));
disp(sprintf(' %% ddssnll_dif_q2d: %+0.16f',ddssnll_dif_q2d));
disp(sprintf(' %% ddssnll_lsq_q2d: %+0.16f',ddssnll_lsq_q2d));
end;%if (flag_verbose>0);
%%%%%%%%;
end;%if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%if flag_surrogate==0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% [finished %s]',str_thisfunction)); end;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
