%%%%%%%%;
% 2024/10/25: contemplating a hires calculation within ddssnll_3. ;
% Verdict: Just try to bandlimit the initial a_k_Y_quad_yk_ and see what happens. ;
%%%%%%%%;


l_hires_max_max = 2*l_max_max;

k_ori_int = 16;
k_ori_eq_d_double = 0.50;
k_ori_p_r_max = 2.5433847511800027; %k_ori_p_r_max = k_ori_int/(2*pi);
k_ori_eq_d = k_ori_eq_d_double/(2*pi);
str_T_vs_L = 'C';

k_lores_eq_d = k_ori_eq_d/max(1e-12,k_ori_p_r_max);
[ ...
 n_lores_all ...
,azimu_b_lores_all_ ...
,polar_a_lores_all_ ...
,weight_shell_lores_all_ ...
,k_lores_c_0_all_ ...
,k_lores_c_1_all_ ...
,k_lores_c_2_all_ ...
,n_polar_a_lores ...
,polar_a_lores_ ...
,n_azimu_b_lores_ ...
] = ...
sample_shell_6( ...
 1.0 ...
,k_lores_eq_d ...
,str_T_vs_L ...
,0 ...
) ;

nk_p_r = n_k_p_r-1;
tmp_index_ = [n_k_all_csum_(1+nk_p_r):n_k_all_csum_(1+nk_p_r+1)-1];
tmp_k_ori_p_r_all_ = k_p_r_all_(1+tmp_index_);
tmp_azimu_b_ori_all_ = k_p_azimu_b_all_(1+tmp_index_);
tmp_polar_a_ori_all_ = k_p_polar_a_all_(1+tmp_index_);
fnorm_disp(flag_verbose,'tmp_azimu_b_ori_all_',tmp_azimu_b_ori_all_,'azimu_b_lores_all_',azimu_b_lores_all_);
fnorm_disp(flag_verbose,'tmp_polar_a_ori_all_',tmp_polar_a_ori_all_,'polar_a_lores_all_',polar_a_lores_all_);

k_hires_eq_d = 0.5*k_ori_eq_d/max(1e-12,k_ori_p_r_max);
[ ...
 n_hires_all ...
,azimu_b_hires_all_ ...
,polar_a_hires_all_ ...
,weight_shell_hires_all_ ...
,k_hires_c_0_all_ ...
,k_hires_c_1_all_ ...
,k_hires_c_2_all_ ...
,n_polar_a_hires ...
,polar_a_hires_ ...
,n_azimu_b_hires_ ...
] = ...
sample_shell_6( ...
 1.0 ...
,k_hires_eq_d ...
,str_T_vs_L ...
,0 ...
) ;
n_k_hires_p_r = n_k_p_r;
k_hires_p_r_ = k_p_r_;
weight_3d_k_hires_p_r_ = weight_3d_k_p_r_;
n_k_hires_all = n_k_p_r*n_hires_all;
n_k_hires_all_csum_ = cumsum([0;n_hires_all*ones(n_k_p_r,1)]);
k_hires_p_r_all_ = reshape(ones(n_hires_all,1)*reshape(k_p_r_,[1,n_k_p_r]),[n_k_hires_all,1]);
k_hires_p_azimu_b_all_ = reshape(repmat(azimu_b_hires_all_,[1,n_k_p_r]),[n_k_hires_all,1]);
k_hires_p_polar_a_all_ = reshape(repmat(polar_a_hires_all_,[1,n_k_p_r]),[n_k_hires_all,1]);
weight_shell_k_hires_ = weight_shell_hires_all_/max(1e-12,sum(weight_shell_hires_all_))*sum(weight_shell_k_);
weight_3d_k_hires_all_ = zeros(n_k_hires_all,1);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = [n_k_all_csum_(1+nk_p_r):n_k_all_csum_(1+nk_p_r+1)-1];
tmp_index_hires_ = [n_k_hires_all_csum_(1+nk_p_r):n_k_hires_all_csum_(1+nk_p_r+1)-1];
weight_3d_k_hires_all_(1+tmp_index_hires_) = weight_shell_k_hires_/max(1e-12,sum(weight_shell_k_hires_))*sum(weight_3d_k_all_(1+tmp_index_));
end;%for nk_p_r=0:n_k_p_r-1;


if (flag_verbose>0); disp(sprintf(' %% n_lores_all: %d',n_lores_all)); end;
if (flag_verbose>0); disp(sprintf(' %% n_hires_all: %d',n_hires_all)); end;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_3d_k_all_): %0.16f',sum(weight_3d_k_all_))); end;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_3d_k_hires_all_): %0.16f',sum(weight_3d_k_hires_all_))); end;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_shell_k_): %0.16f',sum(weight_shell_k_))); end;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_shell_k_hires_): %0.16f',sum(weight_shell_k_hires_))); end;

if ~exist('a_hires_k_p_quad__','var'); a_hires_k_p_quad__ = []; end;

if ~exist('Ylm_xxres_uklma___','var'); Ylm_xxres_uklma___=[]; end;
if ~exist('k_xxres_p_azimu_b_sub_uka__','var'); k_xxres_p_azimu_b_sub_uka__=[]; end;
if ~exist('k_xxres_p_polar_a_sub_uka__','var'); k_xxres_p_polar_a_sub_uka__=[]; end;
if ~exist('l_max_xxres_uk_','var'); l_max_xxres_uk_=[]; end;
if ~exist('index_xxres_nu_n_k_per_shell_from_nk_p_r_','var'); index_xxres_nu_n_k_per_shell_from_nk_p_r_=[]; end;
if ~exist('index_xxres_k_per_shell_uka__','var'); index_xxres_k_per_shell_uka__=[]; end;

if isempty(a_hires_k_p_quad__) & ~isempty(a_k_Y_quad_yk_);
tmp_t = tic;
[ ...
 a_hires_k_p_quad__ ...
,Ylm_xxres_uklma___ ...
,k_xxres_p_azimu_b_sub_uka__ ...
,k_xxres_p_polar_a_sub_uka__ ...
,l_max_xxres_uk_ ...
,index_xxres_nu_n_k_per_shell_from_nk_p_r_ ...
,index_xxres_k_per_shell_uka__ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_k_hires_all ...
,n_k_hires_all_csum_ ...
,k_hires_p_r_all_ ...
,k_hires_p_azimu_b_all_ ...
,k_hires_p_polar_a_all_ ...
,weight_3d_k_hires_all_ ...
,weight_shell_k_hires_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_quad_yk_ ...
,Ylm_xxres_uklma___ ...
,k_xxres_p_azimu_b_sub_uka__ ...
,k_xxres_p_polar_a_sub_uka__ ...
,l_max_xxres_uk_ ...
,index_xxres_nu_n_k_per_shell_from_nk_p_r_ ...
,index_xxres_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% a_hires_k_p_quad__ time %0.2fs',tmp_t)); end;
end;%if isempty(a_hires_k_p_quad__) & ~isempty(a_k_Y_quad_yk_);





