%%%%%%%%;
% Collect terms into ssnll. ;
%%%%%%%%;
ssnll_q3d = ...
 + 0.5 * sum( abs(a_k_p_qk_).^2 .* a_restore_C2M0_k_p_qk_ .* weight_3d_riesz_qk_ ) ...
 - 0.5 * 2*real(sum( conj(a_k_p_qk_).^1 .* a_restore_C1M1_k_p_qk_ .* weight_3d_riesz_qk_ )) ...
 + 0.5 * sum( a_restore_C0M2_k_p_qk_ .* weight_3d_riesz_qk_ ) ...
;
ssnll_q3d = ssnll_q3d / scaling_volumetric ;
fnorm_disp(flag_verbose,'ssnll_q2d',ssnll_q2d,'ssnll_q3d',ssnll_q3d);
%%%%%%%%;
ssnll_q3d = ...
 + 0.5 * sum( conj(a_k_p_qk_) .* (a_k_p_qk_) .* a_restore_C2M0_k_p_qk_ .* weight_3d_riesz_qk_ ) ...
 - 0.5 * sum( conj(a_k_p_qk_) .* a_restore_C1M1_k_p_qk_ .* weight_3d_riesz_qk_ ) ...
 - 0.5 * sum( conj(a_restore_C1M1_k_p_qk_) .* (a_k_p_qk_) .* weight_3d_riesz_qk_ ) ...
 + 0.5 * sum( a_restore_C0M2_k_p_qk_ .* weight_3d_riesz_qk_ ) ...
;
ssnll_q3d = ssnll_q3d / scaling_volumetric ;
fnorm_disp(flag_verbose,'ssnll_q2d',ssnll_q2d,'ssnll_q3d',ssnll_q3d);
%%%%%%%%;
