%%%%%%%%;
Hvv_q3d = ...
 + 1.0 * sum( (conj(dvol_a_times_dvol_a_k_p_qk__) .* a_restore_C2M0_k_p_qk__) .* weight_3d_riesz_qk__ , 'all' ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
Hvv_q3d = ...
 + 1.0 * sum( (conj(dvol_a_k_p_qk__) .* dvol_a_times_a_restore_C2M0_k_p_qk__) .* weight_3d_riesz_qk__ , 'all' ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
Hvv_q3d = ...
 + 1.0 * sum( conj(dvol_a_k_p_qk__) .* dvol_a_times_a_restore_C2M0_k_p_qk__ .* weight_3d_riesz_qk__ , 'all' ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
Hvv_q3d = ...
 + 1.0 * sum( conj(dvol_a_k_p_qk_) .* dvol_a_k_p_qk_ .* a_restore_C2M0_k_p_qk_ .* weight_3d_riesz_qk_ , 'all' ) ...
;
Hvv_q3d = Hvv_q3d / scaling_volumetric ;
if (flag_verbose>0); disp(sprintf(' %% Hvv_q3d: %0.16f',Hvv_q3d)); end;
%%%%%%%%;
