%%%%%%%%;
n_q = qref_n_shell;
n_qk = n_q*n_k_p_r;
n_qk_csum_ = cumsum([0;n_q*ones(n_k_p_r,1)]);
n_polar_a_k_ = qref_n_polar_a*ones(n_k_p_r,1);
polar_a_ka__ = cell(n_k_p_r,1); for nk_p_r=0:n_k_p_r-1; polar_a_ka__{1+nk_p_r} = qref_polar_a_; end;
n_azimu_b_ka__ = cell(n_k_p_r,1); for nk_p_r=0:n_k_p_r-1; n_azimu_b_ka__{1+nk_p_r} = qref_n_azimu_b_; end;
%%%%%%%%;
k_p_r_qk__ = repmat(reshape(k_p_r_,[1,n_k_p_r]),[n_q,1]);
k_p_azimu_b_qk__ = repmat(reshape(qref_azimu_b_shell_,[n_q,1]),[1,n_k_p_r]);
k_p_polar_a_qk__ = repmat(reshape(qref_polar_a_shell_,[n_q,1]),[1,n_k_p_r]);
k_c_0_qk__ = k_p_r_qk__.*cos(k_p_azimu_b_qk__).*sin(k_p_polar_a_qk__);
k_c_1_qk__ = k_p_r_qk__.*sin(k_p_azimu_b_qk__).*sin(k_p_polar_a_qk__);
k_c_2_qk__ = k_p_r_qk__.*cos(k_p_polar_a_qk__);
k_p_r_qk_ = reshape(k_p_r_qk__,[n_qk,1]);
k_p_azimu_b_qk_ = reshape(k_p_azimu_b_qk__,[n_qk,1]);
k_p_polar_a_qk_ = reshape(k_p_polar_a_qk__,[n_qk,1]);
k_c_0_qk_ = reshape(k_c_0_qk__,[n_qk,1]);
k_c_1_qk_ = reshape(k_c_1_qk__,[n_qk,1]);
k_c_2_qk_ = reshape(k_c_2_qk__,[n_qk,1]);
%%%%%%%%;
