if flag_check;
tmp_H_q2d = @(dtau_3M__) ... 
 + 1.0*ssnll_q2d ...
 + 1.0*dvol_ssnll_q2d ...
 + 1.0*sum( ...
	    bsxfun(@times ...
		    ,dtau_ssnll_q2d_3M__ ...
		    ,bsxfun(@times ...
			     ,dtau_3M__ ...
			     ,transpose(weight_imagecount_M_) ...
			   ) ...
		  ) ...
	    ,'all' ...
	  ) ...
 + 0.5*dvol_dvol_ssnll_q2d ...
 + 1.0*sum(real(bsxfun(@times ...
			,dtau_dvol_ssnll_q2d_3M__ ...
			,bsxfun(@times ...
				,dtau_3M__ ...
				,transpose(weight_imagecount_M_) ...
			       ) ...
		      ) ...
	       ) ...
	   ,'all' ...
	  ) ...
 + 0.5*sum( ...
	    bsxfun(@times ...
		   ,reshape( ...
			     conj( ...
				   bsxfun(@times ...
					  ,dtau_3M__ ...
					  ,transpose(sqrt(weight_imagecount_M_)) ...
					 ) ...
				 ) ...
			     ,[n_3,1,n_M] ...
			   ) ...
		   ,bsxfun(@times ...
			   ,reshape( ...
				     bsxfun(@times ...
					    ,dtau_3M__ ...
					    ,transpose(sqrt(weight_imagecount_M_)) ...
					   ) ...
				     ,[1,n_3,n_M]...
				   ) ...
			   ,real(dtau_dtau_ssnll_q2d_33M___) ...
			  ) ...
		  ) ...
	    ,'all' ...
	  ) ...
;
%%%%%%%%;
if  exist('dtau_3M__','var'); tmp_dtau_3M__ = dtau_3M__; end;
if  exist('dtau_firstorder_3M__','var'); tmp_dtau_3M__ = dtau_firstorder_3M__; end;
if  exist('dtau_M3__','var'); tmp_dtau_M3__ = dtau_M3__; end;
if  exist('dtau_firstorder_M3__','var'); tmp_dtau_M3__ = dtau_firstorder_M3__; end;
if (flag_disp>1);
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,3,1)
dtau_randn_3M__ = randn(n_3,n_M);
dtau_randn_3M__ = dtau_randn_3M__ * fnorm(tmp_dtau_3M__)/max(1e-12,fnorm(dtau_randn_3M__));
hold on;
for ntmp=-20:+20;
plot(ntmp,tmp_H_q2d(tmp_dtau_3M__ + dtau_randn_3M__*ntmp/20),'ko');
end;%for ntmp=-20:+20;
xlabel('abitrary step'); ylabel('value of tmp_H_q2d','Interpreter','none');
title('criticality of tmp_dtau_3M__','Interpreter','none');
subplot(1,3,2);
hold on;
plot(1:n_M,tmp_dtau_M3__(:,1+0),'ro');
plot(1:n_M,tmp_dtau_M3__(:,1+1),'go');
plot(1:n_M,tmp_dtau_M3__(:,1+2),'bo');
hold off;
xlim([0,n_M+1]); xlabel('nM','Interpreter','none');
ylabel('tmp_dtau_M3__','Interpreter','none');
title('tmp_dtau_M3__','Interpreter','none');
subplot(1,3,3);
hold on;
plot(euler_polar_a_M_,tmp_dtau_M3__(:,1+0),'ro');
plot(euler_polar_a_M_,tmp_dtau_M3__(:,1+1),'go');
plot(euler_polar_a_M_,tmp_dtau_M3__(:,1+2),'bo');
hold off;
xlim([0,pi]); xlabel('euler_polar_a_M_','Interpreter','none');
ylabel('tmp_dtau_M3__','Interpreter','none');
title('tmp_dtau_M3__','Interpreter','none');
sgtitle(sprintf('flag_dtau %d flag_dvol %d (critical only if ~flag_dtau)',flag_dtau,flag_dvol),'Interpreter','none');
drawnow();
end;%if (flag_disp>1);
end;%if flag_check;
%%%%%%%%;
