function tmp_M_loading__ = get_loading_0(tmp_n_residual_loading,tmp_n_residual_iteration,syn_n_order,tmp_n_k_p_r,tmp_weight_k_p_r_,tmp_l_max_,tmp_n_w_,syn_n_M,tmp_M_k_p__,tmp_euler_polar_a_,tmp_euler_azimu_b_,tmp_euler_gamma_z_);
verbose=1;
%%%%%%%%;
tmp_n_lm_ = (tmp_l_max_+1).^2;
tmp_n_lm_max = max(tmp_n_lm_);
tmp_n_lm_sum = sum(tmp_n_lm_);
tmp_n_lm_csum_ = cumsum([0;tmp_n_lm_]);
tmp_l_max_max = max(tmp_l_max_); 
%%%%%%%%;
% Solve lsq with estimated viewing angles. ;
%%%%%%%%;
tmp_n_w_max = max(tmp_n_w_); tmp_n_w_sum = sum(tmp_n_w_); tmp_n_w_csum_ = cumsum([0;tmp_n_w_]);
tmp_n_lm_ = (1+tmp_l_max_).^2; tmp_n_lm_sum = sum(tmp_n_lm_);
tmp_t = tic();
syn_a_k_Y_0lsq_ = cg_lsq_3(syn_n_order,tmp_n_k_p_r,tmp_l_max_,tmp_n_w_,syn_n_M,tmp_M_k_p__,1,ones(tmp_n_w_sum,1),tmp_euler_polar_a_,tmp_euler_azimu_b_,tmp_euler_gamma_z_);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% syn_a_k_Y_0lsq_: %0.3fs',tmp_t)); end;
%%%%%%%%;
% calculate residual from lsq. ;
%%%%%%%%;
tmp_t = tic();
tmp_CTF_index_ = 1; tmp_CTF_k_p__ = ones(tmp_n_w_sum,1); %<-- no CTF necessary. ;
tmp_S_k_p__ = zeros(tmp_n_w_sum,syn_n_M);
for nk_p_r=0:tmp_n_k_p_r-1;
tmp_l_max = tmp_l_max_(1+nk_p_r);
tmp_Y_ij_ = tmp_n_lm_csum_(1+nk_p_r) + (0:tmp_n_lm_(1+nk_p_r)-1);
tmp_n_w = tmp_n_w_(1+nk_p_r);
tmp_M_ij_ = tmp_n_w_csum_(1+nk_p_r) + (0:tmp_n_w_(1+nk_p_r)-1);
if (isempty(tmp_CTF_index_) | numel(tmp_CTF_index_)==1);
tmp_CTF_k_p_ = reshape(repmat(tmp_CTF_k_p__(1+tmp_M_ij_),[1,syn_n_M]),[tmp_n_w*syn_n_M,1]);
 else;
tmp_CTF_k_p_ = reshape(tmp_CTF_k_p__(1+tmp_M_ij_,tmp_CTF_index_(1:syn_n_M)),[tmp_n_w*syn_n_M,1]);
end;%if (isempty(tmp_CTF_index_) | numel(tmp_CTF_index_)==1);
[tmp_k_p_polar_a__,tmp_k_p_azimu_b__] = cg_rhs_1(syn_n_M,tmp_n_w,tmp_euler_polar_a_,tmp_euler_azimu_b_,+tmp_euler_gamma_z_);
tmp_n_polar_a = ceil(tmp_n_w/2);
tmp_n_azimu_b = max(1+2*tmp_l_max,2*tmp_n_polar_a);
[tmp_legendre_evaluate_ljm___,tmp_legendre_evaluate_mlj___,tmp_expil__,tmp_expi__] = legendre_evaluate_ljm___0(tmp_l_max,cos(linspace(0,pi,tmp_n_polar_a)),tmp_n_azimu_b);
tmp_tensor_to_scatter__ = cg_interpolate_n_1(syn_n_order,tmp_n_polar_a,tmp_n_azimu_b,tmp_n_w*syn_n_M,tmp_k_p_polar_a__(:),tmp_k_p_azimu_b__(:));
tmp_scatter_to_tensor__ = ctranspose(tmp_tensor_to_scatter__); %<-- this conjugation is not necessary, since the matrix should be real. ;
An__ = @(a_k_Y_) tmp_CTF_k_p_.*(tmp_tensor_to_scatter__*reshape(cg_evaluate_n_1(tmp_l_max,convert_spharm_to_spharm__0(tmp_l_max,a_k_Y_),tmp_n_polar_a,tmp_n_azimu_b,tmp_legendre_evaluate_ljm___),[tmp_n_polar_a*tmp_n_azimu_b,1]));
At__ = @(a_k_X_) convert_spharm__to_spharm_0(tmp_l_max,cg_evaluate_t_1(tmp_n_polar_a,tmp_n_azimu_b,reshape(tmp_scatter_to_tensor__*(conj(tmp_CTF_k_p_).*a_k_X_),[tmp_n_polar_a,tmp_n_azimu_b]),tmp_l_max,tmp_legendre_evaluate_mlj___,tmp_expil__,tmp_expi__));
AtAn__ = @(a_k_Y_) At__(An__(a_k_Y_));
%[a_k_Y_(1+tmp_Y_ij_),~] = pcg(AtAn__,At__(reshape(tmp_M_k_p__(1+tmp_M_ij_,:),[tmp_n_w*syn_n_M,1])));
tmp_S_k_p__(1+tmp_M_ij_,:) = reshape(An__(syn_a_k_Y_0lsq_(1+tmp_Y_ij_)),[tmp_n_w_(1+nk_p_r),syn_n_M]);
end;%for nk_p_r=0:n_k_p_r-1;
tmp_R_k_p__ = tmp_M_k_p__ - tmp_S_k_p__;
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% tmp_R_k_p__: %0.3fs',tmp_t)); end;
%%%%%%%%;
% Initialize residual clustering. ;
%%%%%%%%;
tmp_t = tic();
tmp_H__ = zeros(tmp_n_lm_sum,syn_n_M);
for nk_p_r=0:tmp_n_k_p_r-1;
tmp_l_max = tmp_l_max_(1+nk_p_r);
tmp_Y_ij_ = tmp_n_lm_csum_(1+nk_p_r) + (0:tmp_n_lm_(1+nk_p_r)-1);
tmp_n_w = tmp_n_w_(1+nk_p_r);
tmp_M_ij_ = tmp_n_w_csum_(1+nk_p_r) + (0:tmp_n_w_(1+nk_p_r)-1);
tmp_n_polar_a = ceil(tmp_n_w/2);
tmp_n_azimu_b = max(1+2*tmp_l_max,2*tmp_n_polar_a);
[tmp_legendre_evaluate_ljm___,tmp_legendre_evaluate_mlj___,tmp_expil__,tmp_expi__] = legendre_evaluate_ljm___0(tmp_l_max,cos(linspace(0,pi,tmp_n_polar_a)),tmp_n_azimu_b);
for nM=0:syn_n_M-1;
if (isempty(tmp_CTF_index_) | numel(tmp_CTF_index_)==1);
tmp_CTF_k_p_ = reshape(repmat(tmp_CTF_k_p__(1+tmp_M_ij_),[1,1]),[tmp_n_w*1,1]);
 else;
tmp_CTF_k_p_ = reshape(tmp_CTF_k_p__(1+tmp_M_ij_,tmp_CTF_index_(1+nM)),[tmp_n_w*1,1]);
end;%if (isempty(tmp_CTF_index_) | numel(tmp_CTF_index_)==1);
[tmp_k_p_polar_a__,tmp_k_p_azimu_b__] = cg_rhs_1(1,tmp_n_w,tmp_euler_polar_a_(1+nM),tmp_euler_azimu_b_(1+nM),+tmp_euler_gamma_z_(1+nM));
tmp_tensor_to_scatter__ = cg_interpolate_n_1(syn_n_order,tmp_n_polar_a,tmp_n_azimu_b,tmp_n_w*1,tmp_k_p_polar_a__(:),tmp_k_p_azimu_b__(:));
tmp_scatter_to_tensor__ = ctranspose(tmp_tensor_to_scatter__); %<-- this conjugation is not necessary, since the matrix should be real. ;
At__ = @(a_k_X_) convert_spharm__to_spharm_0(tmp_l_max,cg_evaluate_t_1(tmp_n_polar_a,tmp_n_azimu_b,reshape(tmp_scatter_to_tensor__*(conj(tmp_CTF_k_p_).*a_k_X_),[tmp_n_polar_a,tmp_n_azimu_b]),tmp_l_max,tmp_legendre_evaluate_mlj___,tmp_expil__,tmp_expi__));
tmp_H__(1+tmp_Y_ij_,1+nM) = At__(tmp_R_k_p__(1+tmp_M_ij_,1+nM));
end;%for nM=0:syn_n_M-1;
end;%for nk_p_r=0:tmp_n_k_p_r-1;
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% tmp_H__: %0.3fs',tmp_t)); end;
%%%%%%%%;
tmp_t = tic();
tmp_HH_ = zeros(syn_n_M,1);
for nM=0:syn_n_M-1;
tmp_HH_(1+nM) = 0;
for nk_p_r=0:tmp_n_k_p_r-1;
tmp_l_max = tmp_l_max_(1+nk_p_r);
tmp_Y_ij_ = tmp_n_lm_csum_(1+nk_p_r) + (0:tmp_n_lm_(1+nk_p_r)-1);
tmp_HH_(1+nM) = tmp_HH_(1+nM) + sum(abs(tmp_H__(1+tmp_Y_ij_,1+nM)).^2)*tmp_weight_k_p_r_(1+nk_p_r);
end;%for nk_p_r=0:tmp_n_k_p_r-1;
end;%for nM=0:syn_n_M-1;
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% tmp_HH_: %0.3fs',tmp_t)); end;
%%%%%%%%;
% Iterate to cluster residuals. ;
%%%%%%%%;
tmp_t = tic();
tmp_M_loading__ = randn(tmp_n_residual_loading,syn_n_M);
tmp_G_ = randn(tmp_n_lm_sum,tmp_n_residual_loading); 
for nloading=0:tmp_n_residual_loading-1; 
tmp_G_(:,1+nloading) = tmp_G_(:,1+nloading)/fnorm(tmp_G_(:,1+nloading));
end;%for nloading=0:tmp_n_residual_loading-1; 
for niteration=0:tmp_n_residual_iteration-1;
%%%%;
if (niteration==0);
% do nothing;
end;%if (niteration==0);
if (niteration>0);
tmp_G_ = zeros(tmp_n_lm_sum,tmp_n_residual_loading);
for nM=0:syn_n_M-1;
for nloading=0:tmp_n_residual_loading-1;
tmp_G_(:,1+nloading) = tmp_G_(:,1+nloading) + tmp_M_loading__(1+nloading,1+nM)*tmp_H__(:,1+nM);
end;%for nloading=0:tmp_n_residual_loading-1;
end;%for nM=0:syn_n_M-1;
for nloading_0=0:tmp_n_residual_loading-1;
tmp_G_(:,1+nloading_0) = tmp_G_(:,1+nloading_0)/fnorm(tmp_G_(:,1+nloading_0));
for nloading_1=nloading_0+1:tmp_n_residual_loading-1;
tmp_G_(:,1+nloading_1) = tmp_G_(:,1+nloading_1) - (ctranspose(tmp_G_(:,1+nloading_0))*tmp_G_(:,1+nloading_1))*tmp_G_(:,1+nloading_0);
end;%for nloading_1=nloading_0+1:tmp_n_residual_loading-1;
end;%for nloading_0=0:tmp_n_residual_loading-1;
end;%if (niteration>0);
%%%%;
for nM=0:syn_n_M-1;
tmp_HH = tmp_HH_(1+nM);
for nloading=0:tmp_n_residual_loading-1;
tmp_HG = 0;
for nk_p_r=0:tmp_n_k_p_r-1;
tmp_l_max = tmp_l_max_(1+nk_p_r);
tmp_Y_ij_ = tmp_n_lm_csum_(1+nk_p_r) + (0:tmp_n_lm_(1+nk_p_r)-1);
tmp_HG = tmp_HG + sum(conj(tmp_H__(1+tmp_Y_ij_,1+nM)).*tmp_G_(1+tmp_Y_ij_,1+nloading))*tmp_weight_k_p_r_(1+nk_p_r);
end;%for nk_p_r=0:tmp_n_k_p_r-1;
tmp_M_loading__(1+nloading,1+nM) = real(tmp_HG)/max(1e-12,real(tmp_HH));
end;%for nloading=0:tmp_n_residual_loading-1;
end;%for nM=0:syn_n_M-1;
%%%%;
end;%for niteration=0:tmp_n_residual_iteration-1;
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% tmp_M_loading__: %0.3fs',tmp_t)); end;
