%{
if ~exist('wS_from_single_shell_sba__','var'); wS_from_single_shell_sba__=[]; end;
if ~exist('dwSda_from_single_shell_sba__','var'); dwSda_from_single_shell_sba__=[]; end;
if ~exist('dwSdb_from_single_shell_sba__','var'); dwSdb_from_single_shell_sba__=[]; end;
if ~exist('ddwSdaa_from_single_shell_sba__','var'); ddwSdaa_from_single_shell_sba__=[]; end;
if ~exist('ddwSdab_from_single_shell_sba__','var'); ddwSdab_from_single_shell_sba__=[]; end;
if ~exist('ddwSdbb_from_single_shell_sba__','var'); ddwSdbb_from_single_shell_sba__=[]; end;
%}
function ...
[ ...
 parameter ...
,template_wkS__ ...
,n_w ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_ ...
,wS_from_single_shell_sba__ ...
,dtemplateda_wkS__ ...
,dtemplatedb_wkS__ ...
,dtemplatedc_wkS__ ...
,dwSda_from_single_shell_sba__ ...
,dwSdb_from_single_shell_sba__ ...
,ddtemplatedaa_wkS__ ...
,ddtemplatedab_wkS__ ...
,ddtemplatedac_wkS__ ...
,ddtemplatedbb_wkS__ ...
,ddtemplatedbc_wkS__ ...
,ddtemplatedcc_wkS__ ...
,ddwSdaa_from_single_shell_sba__ ...
,ddwSdab_from_single_shell_sba__ ...
,ddwSdbb_from_single_shell_sba__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_ ...
,wS_from_single_shell_sba__ ...
,dwSda_from_single_shell_sba__ ...
,dwSdb_from_single_shell_sba__ ...
,ddwSdaa_from_single_shell_sba__ ...
,ddwSdab_from_single_shell_sba__ ...
,ddwSdbb_from_single_shell_sba__ ...
);
%%%%;
% Uses a_k_p_qk_ to evaluate templates on a collection of points on spherical shells. ;
% Each spherical-shell has the same resolution, determined by viewing_k_eq_d and template_k_eq_d and/or n_w_max. ;
% We assume that each spherical-shell is discretized with a (potentially adaptive) discretization with: ;
% a collection of equispaced longitudes (i.e., azimuthal-points) for each latitude (i.e., polar-point), with: ;
% polar-points equispaced from [0,pi]. ;
% Furthermore, we assume that the number of longitudes on each pole is 1, ;
% and that the number of longitudes at each other latitude is even. ;
%%%%;
% This code is largely similar to interpolate_template_4.m ;
% As an additional feature we calculate T_k_p_wkS__ as an alternative to S_k_p_wkS__. ;
% This can provide some accuracy near the poles. ;
%%%%;
% ;
% inputs: ;
% ;
% flag_verbose = integer verbosity_level. ;
% n_qk = integer total number of points in spherical discretization. ;
% n_qk_csum_ = integer array of size (n_k_p_r). n_qk_csum_(1+nk_p_r) is the number of points prior to shell nk_p_r. ;
% k_p_r_qk_ = double array of size (n_qk). k_p_r_qk_(1+na) = radius of point na. ;
% k_p_azimu_b_qk_ = double array of size (n_qk). k_p_azimu_b_qk_(1+na) = azimu_b of point na. ;
% k_p_polar_a_qk_ = double array of size (n_qk). k_p_polar_a_qk_(1+na) = azimu_b of point na. ;
% weight_3d_k_p_qk_ = double array of size (n_qk). weight_3d_k_p_qk_(1+na) = quadrature-weight (3d) for point na. ;
% weight_shell_qk_ = double array of size (n_qk). weight_shell_qk_(1+na) = quadrature-weight (shell) for point na. ;
% n_k_p_r = integer number of shells. ;
% k_p_r_ = double array of size (n_k_p_r). k_p_r_(1+nk_p_r) = radius of shell nk_p_r.
% weight_3d_k_p_r_ = double array of size (n_k_p_r). weight_3d_k_p_r_(1+nk_p_r) = quadrature-weight for shell nk_p_r. ;
% k_c_0_qk_ = double array of size (n_qk). k_c_0_qk_(1+na) = k_c_0 of point na. ;
% k_c_1_qk_ = double array of size (n_qk). k_c_1_qk_(1+na) = k_c_1 of point na. ;
% k_c_2_qk_ = double array of size (n_qk). k_c_2_qk_(1+na) = k_c_2 of point na. ;
% n_polar_a_k_ = integer array of size (n_k_p_r). n_polar_a_k_(1+nk_p_r) = number of latitudinal-lines for shell nk_p_r. ;
% polar_a_ka__ = cell-array of size (n_k_p_r). polar_a_ka__{1+nk_p_r} = double array of size n_polar_a_k_(1+nk_p_r) storing latitudes. ;
% n_azimu_b_ka__ = cell-array of size (n_k_p_r). n_azimu_b_ka__{1+nk_p_r} = integer array of size n_polar_a_k_(1+nk_p_r) storing n_azimu_b per latitude. ;
% a_k_p_qk_ = complex array of size (n_qk). a_k_p_qk_(1+na) = function-value a for point na. ;
% viewing_k_eq_d = real equatorial-distance used for sampling viewing angles and templates. ;
% template_k_eq_d = real equatorial-distance used for sampling inplane-shifts along each template. ;
% n_w_0in = integer. used if template_k_eq_d <=0; desired n_w for templates. ;
% n_viewing_S = integer. number of viewing angles (i.e., number of templates) .;
% viewing_azimu_b_S_ = real array of size (n_viewing_S,1). ;
%                        azimu_b values for each template. ;
% viewing_polar_a_S_ = real array of size (n_viewing_S,1). ;
%                        polar_a values for each template. ;
% viewing_weight_S_ = real array of size (n_viewing_S,1). ;
%                       integration weight (on shell of radius 1) for each template. ;
% n_viewing_polar_a = integer. number of distinct polar_a across the viewing angles. ;
% viewing_polar_a_ = real array of size (n_viewing_polar_a,1). ;
%                    polar_a values for each viewing_polar_a_. ;
% n_viewing_azimu_b_ = integer array of size (n_viewing_polar_a,1). ;
%                      number of azimu_b values for each polar_a. ;
%                      These azimu_b values are assumed to be equispaced on [0,2*pi). ;
% viewing_gamma_z_S_ = real gamma_z value for each template. (typically 0.0). ;
% ;
% outputs: ;
% ;
% template_wkS__ = complex array of templates. ;
%                  template_wkS__(1+nw+nk_p_r*n_w_max,1+nS) ;
%                  stores template value for angle-index nw, radial-index nk_p_r, ;
%                  and viewing_azimu_b = viewing_azimu_b_all_(1+nS). ;
%                  and viewing_polar_a = viewing_polar_a_all_(1+nS). ;
% dtemplatedx_wkS__ = complex array analogous to template_wkS__. ;
%                     stores first-derivative of template with respect to: ;
%                     x==a: polar_a ; %<-- note that the first-derivative with respect to polar_a has a different sign than wignerd_c produces. ;
%                     x==b: azimu_b ;
%                     x==c: gamma_z ;
% ddtemplatedxy_wkS__ = complex array analogous to template_wkS__. ;
%                       stores second-derivative of template with respect to x and y (see above). ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

str_thisfunction = 'interpolate_template_5';

if nargin<1;
rng(0);
flag_verbose = 2; nf=1;
if (flag_verbose); disp(sprintf(' %% testing %s',str_thisfunction)); end;
%%%%%%%%;
% First set up quadrature on the sphere. ;
%%%%%%%%;
k_p_r_max = 48.0/(2*pi); 
k_eq_d_double = 1.0/1.0;
k_eq_d = k_eq_d_double/(2*pi);
flag_uniform_over_n_k_p_r = 1;
flag_uniform_over_polar_a = 0;
str_T_vs_L = 'C2';
n_order = 13;
[ ...
 n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,~ ...
,~ ...
,~ ...
,~ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
] = ...
sample_sphere_7( ...
 0*flag_verbose ...
,k_p_r_max ...
,k_eq_d ...
,str_T_vs_L ...
,flag_uniform_over_n_k_p_r ...
,flag_uniform_over_polar_a ...
) ;
%%%%%%%%;
l_max = round(2*pi*k_p_r_max);
n_lm = (l_max+1)^2;
Y_l_val_ = zeros(n_lm,1);
Y_m_val_ = zeros(n_lm,1);
na=0;
for l_val=0:l_max;
for m_val=-l_val:+l_val;
Y_l_val_(1+na) = l_val;
Y_m_val_(1+na) = m_val;
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
%%%%;
l_max_ = l_max*ones(n_k_p_r,1);
l_max_max = max(l_max_);
m_max_ = -l_max_max:+l_max_max; n_m_max = numel(m_max_);
n_lm_ = n_lm*ones(n_k_p_r,1);
n_lm_max = max(n_lm_);
n_lm_sum = sum(n_lm_);
n_lm_csum_ = cumsum([0;n_lm_]);
Y_l_val__ = repmat(Y_l_val_,[1,n_k_p_r]);
Y_m_val__ = repmat(Y_m_val_,[1,n_k_p_r]);
sigma_l = 15;
sigma_m = 12;
a_k_Y_yk_ = (mod(transpose([0:n_lm_sum-1]),89)-44)/89 + i*(mod(transpose([0:n_lm_sum-1]),97)-48)/97;
a_k_Y_yk_ = a_k_Y_yk_.*exp(-Y_l_val__(:).^2/(2*sigma_l^2)).*exp(-Y_m_val__(:).^2/(2*sigma_m^2));
%%%%;
if (flag_verbose>1);
figure(1+nf);nf=nf+1; clf; figmed; 
subplot(1,2,1); plot(Y_l_val__(:),abs(a_k_Y_yk_(:)),'.'); xlabel('Y_l_val_','Interpreter','none'); ylabel('abs(a_k_Y_yk_)','Interpreter','none');
subplot(1,2,2); plot(Y_m_val__(:),abs(a_k_Y_yk_(:)),'.'); xlabel('Y_m_val_','Interpreter','none'); ylabel('abs(a_k_Y_yk_)','Interpreter','none');
end;%if (flag_verbose>1); 
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(real(a_k_Y_yk_),n_lm,n_k_p_r,' %% a_k_Y_yk_real___: '); end;
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(imag(a_k_Y_yk_),n_lm,n_k_p_r,' %% a_k_Y_yk_imag___: '); end;
%%%%%%%%;
viewing_k_eq_d = 1.0/max(1e-12,k_p_r_max);
template_k_eq_d = -1;
n_w_max = 2*(l_max_max+1); n_w_0in = n_w_max;
n_w = n_w_max; n_w_ = n_w_max*ones(n_k_p_r,1); n_w_sum = sum(n_w_); n_w_csum_ = cumsum([0;n_w_]);
%%%%%%%%;
a_k_Y_yk__ = local_yk__from_yk_(n_k_p_r,l_max_,a_k_Y_yk_);
%%%%;
flag_check=1;
if flag_check;
na=0;
for nk_p_r=0:n_k_p_r-1;
l_max=l_max_(1+nk_p_r);
for l_val=0:l_max;
for m_val=-l_val:+l_val;
assert(a_k_Y_yk_(1+n_lm_csum_(1+nk_p_r)+l_val*(l_val+1)+m_val)==a_k_Y_yk__(1+l_val*(l_val+1)+m_val,1+nk_p_r));
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
end;%for nk_p_r=0:n_k_p_r-1;
assert(na==n_lm_sum);
end;%if flag_check;
%%%%%%%%;
tmp_t = tic();
[ ...
 template_2_wkS___ ...
,n_w ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
] = ...
pm_template_2( ...
 0*flag_verbose ...
,l_max ...
,n_k_p_r ...
,a_k_Y_yk__ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
);
n_S = n_viewing_S;
template_2_wkS__ = reshape(template_2_wkS___,[n_w_max*n_k_p_r,n_S]);
tmp_t = toc(tmp_t); disp(sprintf(' %% pm_template_2: %0.2fs',tmp_t));
%%%%%%%%;
tmp_t = tic();
a_k_Y_lkm___ = [];
[ ...
 template_3_wkS__ ...
] = ...
sph_template_3( ...
 0*flag_verbose ...
,l_max ...
,n_k_p_r ...
,a_k_Y_yk__ ...
,a_k_Y_lkm___ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% sph_template_3: %0.2fs',tmp_t));
disp(sprintf(' %% n_S %d',n_S));
%%%%%%%%;
fnorm_disp(flag_verbose,'template_2_wkS__',template_2_wkS__,'template_3_wkS__',template_3_wkS__);
%%%%%%%%;
% Now form a_k_p_quad_. ;
%%%%%%%%;
if ~exist('Ylm_uklma___','var'); Ylm_uklma___=[]; end;
if ~exist('k_p_azimu_b_sub_uka__','var'); k_p_azimu_b_sub_uka__=[]; end;
if ~exist('k_p_polar_a_sub_uka__','var'); k_p_polar_a_sub_uka__=[]; end;
if ~exist('l_max_uk_','var'); l_max_uk_=[]; end;
if ~exist('index_nu_n_k_per_shell_from_nk_p_r_','var'); index_nu_n_k_per_shell_from_nk_p_r_=[]; end;
if ~exist('index_k_per_shell_uka__','var'); index_k_per_shell_uka__=[]; end;
tmp_t = tic();
[ ...
 a_k_p_qk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_spharm_to_k_p_4( ...
 0*flag_verbose ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% convert_spharm_to_k_p_4: %0.6fs',tmp_t)); end;
%%%%%%%%;
tmp_t = tic();
[ ...
 a_k_Y_reco_yk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_k_p_to_spharm_4( ...
 0*flag_verbose ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_p_qk_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% convert_k_p_to_spharm: %0.6fs',tmp_t)); end;
%%%%%%%%;
fnorm_disp(flag_verbose,'a_k_Y_yk_',a_k_Y_yk_,'a_k_Y_reco_yk_',a_k_Y_reco_yk_);
%%%%%%%%;
% Subselect some templates. ;
% Ensuring that some of the templates have polar_a and azimu_b at multiples of pi. ;
%%%%%%%%;
viewing_gamma_z_S_ = zeros(n_S,1);
n_S_sub = 4;
nS_sub_ = max(0,min(n_S-1,round(n_S*rand(n_S_sub,1))));
tmp_index_a_ = efind(abs(periodize(viewing_polar_a_S_,-pi/4,+pi/4))<1e-2);
tmp_index_b_ = efind(abs(periodize(viewing_azimu_b_S_,-pi/4,+pi/4))<1e-2);
tmp_index_ba_ = union(tmp_index_a_,tmp_index_b_);
nS_sub_ = union(tmp_index_ba_(:),nS_sub_);
n_S_sub = numel(nS_sub_);
n_viewing_S_sub = n_S_sub;
viewing_azimu_b_S_sub_ = viewing_azimu_b_S_(1+nS_sub_);
viewing_polar_a_S_sub_ = viewing_polar_a_S_(1+nS_sub_);
viewing_weight_S_sub_ = viewing_weight_S_(1+nS_sub_);
viewing_gamma_z_S_sub_ = viewing_gamma_z_S_(1+nS_sub_);
template_2_wkS_sub__ = template_2_wkS__(:,1+nS_sub_);
template_3_wkS_sub__ = template_3_wkS__(:,1+nS_sub_);
fnorm_disp(flag_verbose,'template_2_wkS_sub__',template_2_wkS_sub__,'template_3_wkS_sub__',template_3_wkS_sub__);
%%%%%%%%;
% Now form templates from a_k_p_quad_. ;
%%%%%%%%;
parameter = struct('type','parameter');
parameter.flag_verbose = flag_verbose;
parameter.tolerance_pinv = 1e-6;
tmp_t = tic();
[ ...
 parameter ...
,template_4_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% interpolate_template S_sub: %0.6fs',tmp_t)); end;
fnorm_disp(flag_verbose,'template_2_wkS_sub__',template_2_wkS_sub__,'template_4_wkS_sub__',template_4_wkS_sub__);
fnorm_disp(flag_verbose,'template_3_wkS_sub__',template_3_wkS_sub__,'template_4_wkS_sub__',template_4_wkS_sub__);
%%%%%%%%;
% Now compare derivatives to sph_template_3. ;
%%%%%%%%;
if (flag_verbose); disp(sprintf(' %% %% %% %% %% %% %% %% ')); end;
if (flag_verbose); disp(sprintf(' %% Now testing derivatives: ')); end;
if (flag_verbose); disp(sprintf(' %% %% %% %% %% %% %% %% ')); end;
%%%%%%%%;
if ~exist('wS_from_single_shell_sba__','var'); wS_from_single_shell_sba__=[]; end;
if ~exist('dwSda_from_single_shell_sba__','var'); dwSda_from_single_shell_sba__=[]; end;
if ~exist('dwSdb_from_single_shell_sba__','var'); dwSdb_from_single_shell_sba__=[]; end;
if ~exist('ddwSdaa_from_single_shell_sba__','var'); ddwSdaa_from_single_shell_sba__=[]; end;
if ~exist('ddwSdab_from_single_shell_sba__','var'); ddwSdab_from_single_shell_sba__=[]; end;
if ~exist('ddwSdbb_from_single_shell_sba__','var'); ddwSdbb_from_single_shell_sba__=[]; end;
[ ...
 parameter ...
,template_mid_x_wkS_sub__ ...
,n_w ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
,wS_sub_from_single_shell_sba__ ...
,dtemplateda_mid_wkS_sub__ ...
,dtemplatedb_mid_wkS_sub__ ...
,dtemplatedc_mid_wkS_sub__ ...
,dwS_subda_from_single_shell_sba__ ...
,dwS_subdb_from_single_shell_sba__ ...
,ddtemplatedaa_mid_wkS_sub__ ...
,ddtemplatedab_mid_wkS_sub__ ...
,ddtemplatedac_mid_wkS_sub__ ...
,ddtemplatedbb_mid_wkS_sub__ ...
,ddtemplatedbc_mid_wkS_sub__ ...
,ddtemplatedcc_mid_wkS_sub__ ...
,ddwS_subdaa_from_single_shell_sba__ ...
,ddwS_subdab_from_single_shell_sba__ ...
,ddwS_subdbb_from_single_shell_sba__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
,wS_from_single_shell_sba__ ...
,dwSda_from_single_shell_sba__ ...
,dwSdb_from_single_shell_sba__ ...
,ddwSdaa_from_single_shell_sba__ ...
,ddwSdab_from_single_shell_sba__ ...
,ddwSdbb_from_single_shell_sba__ ...
);
%%%%%%%%;
a_k_Y_lmk___ = zeros(1+l_max_max,n_m_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
tmp_a_k_Y_lm_ = a_k_Y_yk_(1+tmp_index_);
tmp_a_k_Y_lm__ = zeros(1+l_max_max,n_m_max);
l_max = l_max_(1+nk_p_r);
na=0;
for l_val=0:l_max;
for m_val=-l_val:+l_val;
assert(na==l_val*(l_val+1)+m_val);
tmp_a_k_Y_lm__(1+l_val,1+l_max_max+m_val) = tmp_a_k_Y_lm_(1+na);
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
a_k_Y_lmk___(:,:,1+nk_p_r) = tmp_a_k_Y_lm__;
end;%for nk_p_r=0:n_k_p_r-1;
a_k_Y_lkm___ = permute(a_k_Y_lmk___,[1,3,2]);
%%%%;
tmp_t = tic();
if ~exist('V_lmm___','var'); V_lmm___=[]; end;
if ~exist('L_lm__','var'); L_lm__=[]; end;
if ~exist('d0W_betazeta_mlma____','var'); d0W_betazeta_mlma____ = []; end;
if ~exist('d1W_betazeta_mlma____','var'); d1W_betazeta_mlma____ = []; end;
if ~exist('d2W_betazeta_mlma____','var'); d2W_betazeta_mlma____ = []; end;
viewing_gamma_z = 0.0;
[ ...
 template_3_mid_x_wkS__ ...
,n_w ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z ...
,V_lmm___ ...
,L_lm__ ...
,d0W_betazeta_mlma____ ...
,dtemplate_3da_mid_wkS__ ...
,dtemplate_3db_mid_wkS__ ...
,dtemplate_3dc_mid_wkS__ ...
,d1W_betazeta_mlma____ ...
,ddtemplate_3daa_mid_wkS__ ...
,ddtemplate_3dab_mid_wkS__ ...
,ddtemplate_3dac_mid_wkS__ ...
,ddtemplate_3dbb_mid_wkS__ ...
,ddtemplate_3dbc_mid_wkS__ ...
,ddtemplate_3dcc_mid_wkS__ ...
,d2W_betazeta_mlma____ ...
] = ...
sph_template_3( ...
 0*flag_verbose ...
,l_max ...
,n_k_p_r ...
,a_k_Y_yk__ ...
,a_k_Y_lkm___ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z ...
,V_lmm___ ...
,L_lm__ ...
,d0W_betazeta_mlma____ ...
,d1W_betazeta_mlma____ ...
,d2W_betazeta_mlma____ ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% sph_template_3: %0.2fs',tmp_t));
%%%%;
template_3_mid_x_wkS_sub__ = template_3_mid_x_wkS__(:,1+nS_sub_);
dtemplate_3da_mid_wkS_sub__ = dtemplate_3da_mid_wkS__(:,1+nS_sub_);
dtemplate_3db_mid_wkS_sub__ = dtemplate_3db_mid_wkS__(:,1+nS_sub_);
dtemplate_3dc_mid_wkS_sub__ = dtemplate_3dc_mid_wkS__(:,1+nS_sub_);
ddtemplate_3daa_mid_wkS_sub__ = ddtemplate_3daa_mid_wkS__(:,1+nS_sub_);
ddtemplate_3dab_mid_wkS_sub__ = ddtemplate_3dab_mid_wkS__(:,1+nS_sub_);
ddtemplate_3dac_mid_wkS_sub__ = ddtemplate_3dac_mid_wkS__(:,1+nS_sub_);
ddtemplate_3dbb_mid_wkS_sub__ = ddtemplate_3dbb_mid_wkS__(:,1+nS_sub_);
ddtemplate_3dbc_mid_wkS_sub__ = ddtemplate_3dbc_mid_wkS__(:,1+nS_sub_);
ddtemplate_3dcc_mid_wkS_sub__ = ddtemplate_3dcc_mid_wkS__(:,1+nS_sub_);
%%%%;
for nS_sub=0:n_S_sub-1;
nS = nS_sub_(1+nS_sub);
viewing_polar_a = viewing_polar_a_S_(1+nS); assert(viewing_polar_a==viewing_polar_a_S_sub_(1+nS_sub));
viewing_azimu_b = viewing_azimu_b_S_(1+nS); assert(viewing_azimu_b==viewing_azimu_b_S_sub_(1+nS_sub));
errrel_total = 0.0;
%%%%;
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'template_2_wkS_sub__(:,1+nS_sub)',template_2_wkS_sub__(:,1+nS_sub),'template_mid_x_wkS_sub__(:,1+nS_sub)',template_mid_x_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'template_2_wkS_sub__(:,1+nS_sub)',template_2_wkS_sub__(:,1+nS_sub),'template_3_mid_x_wkS_sub__(:,1+nS_sub)',template_3_mid_x_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'template_3_wkS_sub__(:,1+nS_sub)',template_3_wkS_sub__(:,1+nS_sub),'template_mid_x_wkS_sub__(:,1+nS_sub)',template_mid_x_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'template_3_wkS_sub__(:,1+nS_sub)',template_3_wkS_sub__(:,1+nS_sub),'template_3_mid_x_wkS_sub__(:,1+nS_sub)',template_3_mid_x_wkS_sub__(:,1+nS_sub));
%%%%;
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'+dtemplate_3da_mid_wkS_sub__(:,1+nS_sub)',+dtemplate_3da_mid_wkS_sub__(:,1+nS_sub),'dtemplateda_mid_wkS_sub__(:,1+nS_sub)',dtemplateda_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'+dtemplate_3db_mid_wkS_sub__(:,1+nS_sub)',+dtemplate_3db_mid_wkS_sub__(:,1+nS_sub),'dtemplatedb_mid_wkS_sub__(:,1+nS_sub)',dtemplatedb_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'-dtemplate_3dc_mid_wkS_sub__(:,1+nS_sub)',-dtemplate_3dc_mid_wkS_sub__(:,1+nS_sub),'dtemplatedc_mid_wkS_sub__(:,1+nS_sub)',dtemplatedc_mid_wkS_sub__(:,1+nS_sub));
%%%%;
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'+ddtemplate_3daa_mid_wkS_sub__(:,1+nS_sub)',+ddtemplate_3daa_mid_wkS_sub__(:,1+nS_sub),'ddtemplatedaa_mid_wkS_sub__(:,1+nS_sub)',ddtemplatedaa_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'+ddtemplate_3dab_mid_wkS_sub__(:,1+nS_sub)',+ddtemplate_3dab_mid_wkS_sub__(:,1+nS_sub),'ddtemplatedab_mid_wkS_sub__(:,1+nS_sub)',ddtemplatedab_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'-ddtemplate_3dac_mid_wkS_sub__(:,1+nS_sub)',-ddtemplate_3dac_mid_wkS_sub__(:,1+nS_sub),'ddtemplatedac_mid_wkS_sub__(:,1+nS_sub)',ddtemplatedac_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'+ddtemplate_3dbb_mid_wkS_sub__(:,1+nS_sub)',+ddtemplate_3dbb_mid_wkS_sub__(:,1+nS_sub),'ddtemplatedbb_mid_wkS_sub__(:,1+nS_sub)',ddtemplatedbb_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'-ddtemplate_3dbc_mid_wkS_sub__(:,1+nS_sub)',-ddtemplate_3dbc_mid_wkS_sub__(:,1+nS_sub),'ddtemplatedbc_mid_wkS_sub__(:,1+nS_sub)',ddtemplatedbc_mid_wkS_sub__(:,1+nS_sub));
errrel_total = errrel_total + fnorm_disp(0*flag_verbose,'+ddtemplate_3dcc_mid_wkS_sub__(:,1+nS_sub)',+ddtemplate_3dcc_mid_wkS_sub__(:,1+nS_sub),'ddtemplatedcc_mid_wkS_sub__(:,1+nS_sub)',ddtemplatedcc_mid_wkS_sub__(:,1+nS_sub));
%%%%;
disp(sprintf(' %% nS_sub %.4d nS %.4d viewing_polar_a/pi %+0.3f viewing_azimu_b/pi %+0.3f: errrel_total: %+0.16f',nS_sub,n_S,viewing_polar_a/pi,viewing_azimu_b/pi,errrel_total));
end;%for nS_sub=0:n_S_sub-1;
%%%%;
%%%%%%%%;
% Now compare derivatives to difference quotient. ;
%%%%%%%%;
parameter.flag_verbose = 0*flag_verbose;
da = 1.00*pi*1e-4; db = 1.25*pi*1e-3; dc = 0.75*pi*1e-3;
[ ...
 parameter ...
,template_pos_a_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ + da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ + da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_neg_a_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ - da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ - da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_pos_b_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ + db ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_neg_b_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ - db ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_pos_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ + dc...
);
[ ...
 parameter ...
,template_neg_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ - dc ...
);
dtemplateda_dif_wkS_sub__ = (template_pos_a_wkS_sub__ - template_neg_a_wkS_sub__)./max(1e-12,2*da);
dtemplatedb_dif_wkS_sub__ = (template_pos_b_wkS_sub__ - template_neg_b_wkS_sub__)./max(1e-12,2*db);
dtemplatedc_dif_wkS_sub__ = (template_pos_c_wkS_sub__ - template_neg_c_wkS_sub__)./max(1e-12,2*dc);
fnorm_disp(flag_verbose,'dtemplateda_dif_wkS_sub__',dtemplateda_dif_wkS_sub__,'dtemplateda_mid_wkS_sub__',dtemplateda_mid_wkS_sub__);
fnorm_disp(flag_verbose,'dtemplatedb_dif_wkS_sub__',dtemplatedb_dif_wkS_sub__,'dtemplatedb_mid_wkS_sub__',dtemplatedb_mid_wkS_sub__);
fnorm_disp(flag_verbose,'dtemplatedc_dif_wkS_sub__',dtemplatedc_dif_wkS_sub__,'dtemplatedc_mid_wkS_sub__',dtemplatedc_mid_wkS_sub__);
if (flag_verbose>1);
figure(1+nf);nf=nf+1; clf; figbig; p_row = 2; p_col = 3; np=0;
subplot(p_row,p_col,1+np+0*p_col); plot(real(dtemplateda_dif_wkS_sub__(:)),real(dtemplateda_mid_wkS_sub__(:)),'.');
xlabel('real(dtemplateda_dif_wkS_sub__)','Interpreter','none'); ylabel('real(dtemplateda_mid_wkS_sub__)','Interpreter','none'); axis equal; grid on;
subplot(p_row,p_col,1+np+1*p_col); plot(imag(dtemplateda_dif_wkS_sub__(:)),imag(dtemplateda_mid_wkS_sub__(:)),'.');
xlabel('imag(dtemplateda_dif_wkS_sub__)','Interpreter','none'); ylabel('imag(dtemplateda_mid_wkS_sub__)','Interpreter','none'); axis equal; grid on;
np=np+1;
subplot(p_row,p_col,1+np+0*p_col); plot(real(dtemplatedb_dif_wkS_sub__(:)),real(dtemplatedb_mid_wkS_sub__(:)),'.');
xlabel('real(dtemplatedb_dif_wkS_sub__)','Interpreter','none'); ylabel('real(dtemplatedb_mid_wkS_sub__)','Interpreter','none'); axis equal; grid on;
subplot(p_row,p_col,1+np+1*p_col); plot(imag(dtemplatedb_dif_wkS_sub__(:)),imag(dtemplatedb_mid_wkS_sub__(:)),'.');
xlabel('imag(dtemplatedb_dif_wkS_sub__)','Interpreter','none'); ylabel('imag(dtemplatedb_mid_wkS_sub__)','Interpreter','none'); axis equal; grid on;
np=np+1;
subplot(p_row,p_col,1+np+0*p_col); plot(real(dtemplatedc_dif_wkS_sub__(:)),real(dtemplatedc_mid_wkS_sub__(:)),'.');
xlabel('real(dtemplatedc_dif_wkS_sub__)','Interpreter','none'); ylabel('real(dtemplatedc_mid_wkS_sub__)','Interpreter','none'); axis equal; grid on;
subplot(p_row,p_col,1+np+1*p_col); plot(imag(dtemplatedc_dif_wkS_sub__(:)),imag(dtemplatedc_mid_wkS_sub__(:)),'.');
xlabel('imag(dtemplatedc_dif_wkS_sub__)','Interpreter','none'); ylabel('imag(dtemplatedc_mid_wkS_sub__)','Interpreter','none'); axis equal; grid on;
np=np+1;
end;%if (flag_verbose>1); 
%%%%%%%%;
% Now test second-derivative. ;
%%%%%%%%;
if (flag_verbose); disp(sprintf(' %% %% %% %% %% %% %% %% ')); end;
if (flag_verbose); disp(sprintf(' %% Now testing second-derivative: ')); end;
if (flag_verbose); disp(sprintf(' %% %% %% %% %% %% %% %% ')); end;
ddtemplatedaa_dif_wkS_sub__ = (template_pos_a_wkS_sub__ - 2*template_mid_x_wkS_sub__ + template_neg_a_wkS_sub__)./max(1e-12,da.^2);
ddtemplatedbb_dif_wkS_sub__ = (template_pos_b_wkS_sub__ - 2*template_mid_x_wkS_sub__ + template_neg_b_wkS_sub__)./max(1e-12,db.^2);
ddtemplatedcc_dif_wkS_sub__ = (template_pos_c_wkS_sub__ - 2*template_mid_x_wkS_sub__ + template_neg_c_wkS_sub__)./max(1e-12,dc.^2);
fnorm_disp(flag_verbose,'ddtemplatedaa_dif_wkS_sub__',ddtemplatedaa_dif_wkS_sub__,'ddtemplatedaa_mid_wkS_sub__',ddtemplatedaa_mid_wkS_sub__);
fnorm_disp(flag_verbose,'ddtemplatedbb_dif_wkS_sub__',ddtemplatedbb_dif_wkS_sub__,'ddtemplatedbb_mid_wkS_sub__',ddtemplatedbb_mid_wkS_sub__);
fnorm_disp(flag_verbose,'ddtemplatedcc_dif_wkS_sub__',ddtemplatedcc_dif_wkS_sub__,'ddtemplatedcc_mid_wkS_sub__',ddtemplatedcc_mid_wkS_sub__);
%%%%;
[ ...
 parameter ...
,template_pos_a_pos_b_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ + db ...
,viewing_polar_a_S_sub_ + da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ + da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_pos_a_neg_b_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ - db ...
,viewing_polar_a_S_sub_ + da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ + da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_neg_a_pos_b_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ + db ...
,viewing_polar_a_S_sub_ - da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ - da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
[ ...
 parameter ...
,template_neg_a_neg_b_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ - db ...
,viewing_polar_a_S_sub_ - da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ - da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ ...
);
ddtemplatedab_dif_wkS_sub__ = (template_pos_a_pos_b_wkS_sub__ + template_neg_a_neg_b_wkS_sub__ - template_pos_a_neg_b_wkS_sub__ - template_neg_a_pos_b_wkS_sub__)./max(1e-12,4*da*db);
fnorm_disp(flag_verbose,'ddtemplatedab_dif_wkS_sub__',ddtemplatedab_dif_wkS_sub__,'ddtemplatedab_mid_wkS_sub__',ddtemplatedab_mid_wkS_sub__);
%%%%;
[ ...
 parameter ...
,template_pos_a_pos_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ + da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ + da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ + dc ...
);
[ ...
 parameter ...
,template_pos_a_neg_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ + da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ + da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ - dc ...
);
[ ...
 parameter ...
,template_neg_a_pos_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ - da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ - da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ + dc ...
);
[ ...
 parameter ...
,template_neg_a_neg_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ ...
,viewing_polar_a_S_sub_ - da ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ - da ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ - dc ...
);
ddtemplatedac_dif_wkS_sub__ = (template_pos_a_pos_c_wkS_sub__ + template_neg_a_neg_c_wkS_sub__ - template_pos_a_neg_c_wkS_sub__ - template_neg_a_pos_c_wkS_sub__)./max(1e-12,4*da*dc);
fnorm_disp(flag_verbose,'ddtemplatedac_dif_wkS_sub__',ddtemplatedac_dif_wkS_sub__,'ddtemplatedac_mid_wkS_sub__',ddtemplatedac_mid_wkS_sub__);
%%%%;
[ ...
 parameter ...
,template_pos_b_pos_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ + db ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ + dc ...
);
[ ...
 parameter ...
,template_pos_b_neg_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ + db ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ - dc ...
);
[ ...
 parameter ...
,template_neg_b_pos_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ - db ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ + dc ...
);
[ ...
 parameter ...
,template_neg_b_neg_c_wkS_sub__ ...
] = ...
interpolate_template_5( ...
 parameter ...
,n_order ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
,a_k_p_qk_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in ...
,n_viewing_S_sub ...
,viewing_azimu_b_S_sub_ - db ...
,viewing_polar_a_S_sub_ ...
,viewing_weight_S_sub_ ...
,n_viewing_polar_a ...
,viewing_polar_a_...
,n_viewing_azimu_b_ ...
,viewing_gamma_z_S_sub_ - dc ...
);
ddtemplatedbc_dif_wkS_sub__ = (template_pos_b_pos_c_wkS_sub__ + template_neg_b_neg_c_wkS_sub__ - template_pos_b_neg_c_wkS_sub__ - template_neg_b_pos_c_wkS_sub__)./max(1e-12,4*db*dc);
fnorm_disp(flag_verbose,'ddtemplatedbc_dif_wkS_sub__',ddtemplatedbc_dif_wkS_sub__,'ddtemplatedbc_mid_wkS_sub__',ddtemplatedbc_mid_wkS_sub__);
%%%%;
%%%%%%%%;
disp(sprintf(' %% returning')); return;
end;% if nargin<7;
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_order=[]; end; na=na+1;
if (nargin<1+na); n_qk=[]; end; na=na+1;
if (nargin<1+na); n_qk_csum_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_qk_=[]; end; na=na+1;
if (nargin<1+na); k_p_azimu_b_qk_=[]; end; na=na+1;
if (nargin<1+na); k_p_polar_a_qk_=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_qk_=[]; end; na=na+1;
if (nargin<1+na); weight_shell_qk_=[]; end; na=na+1;
if (nargin<1+na); n_k_p_r=[]; end; na=na+1;
if (nargin<1+na); k_p_r_=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_r_=[]; end; na=na+1;
if (nargin<1+na); k_c_0_qk_=[]; end; na=na+1;
if (nargin<1+na); k_c_1_qk_=[]; end; na=na+1;
if (nargin<1+na); k_c_2_qk_=[]; end; na=na+1;
if (nargin<1+na); n_polar_a_k_=[]; end; na=na+1;
if (nargin<1+na); polar_a_ka__=[]; end; na=na+1;
if (nargin<1+na); n_azimu_b_ka__=[]; end; na=na+1;
if (nargin<1+na); a_k_p_qk_=[]; end; na=na+1;
if (nargin<1+na); viewing_k_eq_d=[]; end; na=na+1;
if (nargin<1+na); template_k_eq_d=[]; end; na=na+1;
if (nargin<1+na); n_w_0in=[]; end; na=na+1;
if (nargin<1+na); n_viewing_S=[]; end; na=na+1;
if (nargin<1+na); viewing_azimu_b_S_=[]; end; na=na+1;
if (nargin<1+na); viewing_polar_a_S_=[]; end; na=na+1;
if (nargin<1+na); viewing_weight_S_=[]; end; na=na+1;
if (nargin<1+na); n_viewing_polar_a=[]; end; na=na+1;
if (nargin<1+na); viewing_polar_a_=[]; end; na=na+1;
if (nargin<1+na); n_viewing_azimu_b_=[]; end; na=na+1;
if (nargin<1+na); viewing_gamma_z_S_=[]; end; na=na+1;
if (nargin<1+na); wS_from_single_shell_sba__=[]; end; na=na+1;
if (nargin<1+na); dwSda_from_single_shell_sba__=[]; end; na=na+1;
if (nargin<1+na); dwSdb_from_single_shell_sba__=[]; end; na=na+1;
if (nargin<1+na); ddwSdaa_from_single_shell_sba__=[]; end; na=na+1;
if (nargin<1+na); ddwSdab_from_single_shell_sba__=[]; end; na=na+1;
if (nargin<1+na); ddwSdbb_from_single_shell_sba__=[]; end; na=na+1;

if isempty(parameter); parameter=struct('type','parameter'); end;
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose=0; end;
flag_verbose=parameter.flag_verbose;
if ~isfield(parameter,'flag_attend'); parameter.flag_attend=1; end;
flag_attend=parameter.flag_attend;

if (flag_verbose>0); disp(sprintf(' %% [entering %s]',str_thisfunction)); end;

flag_1 = 1;
flag_d = (nargout>=12);
flag_dd = (nargout>=17);

if (flag_verbose>0); disp(sprintf(' %% flag_1 %d flag_d %d flag_dd %d',flag_1,flag_d,flag_dd)); end;

if isempty(n_order); n_order = 5; end;
if isempty(viewing_gamma_z_S_); viewing_gamma_z_S_ = zeros(n_viewing_S,1); end;

%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% First determine the viewing angles.')); end;
%%%%%%%%;
if isempty(n_viewing_S);
if (flag_verbose>0); disp(sprintf(' %% calling sample_shell_5.')); end;
tmp_t = tic();
k_p_r = 1.0;
[ ...
 n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,~ ...
,~ ...
,~ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
] = ...
sample_shell_5( ...
 k_p_r ...
,viewing_k_eq_d ...
,'L' ...
) ; %<-- obtain viewing angles. ;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% sample_shell_5: %0.6fs',tmp_t)); end;
end;%if isempty(n_viewing_S);
%%%%;
if isempty(viewing_weight_S_); viewing_weight_S_ = ones(n_viewing_S,1); end;
%%%%;
if isempty(n_viewing_polar_a);
if (flag_verbose>0); disp(sprintf(' %% defining n_viewing_polar_a.')); end;
tmp_t = tic();
viewing_polar_a_ = unique(viewing_polar_a_S_); n_viewing_polar_a = numel(viewing_polar_a_);
n_viewing_azimu_b_ = zeros(n_viewing_polar_a,1);
for nviewing_polar_a=0:n_viewing_polar_a-1;
viewing_polar_a = viewing_polar_a_(1+nviewing_polar_a);
n_viewing_azimu_b_(1+nviewing_polar_a) = numel(efind(abs(viewing_polar_a_S_-viewing_polar_a)<1e-12));
end;%for nviewing_polar_a=0:n_viewing_polar_a-1;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% n_viewing_azimu_b_: %0.6fs',tmp_t)); end;
end;%if isempty(n_viewing_polar_a);
%%%%;
n_viewing_azimu_b_sum = sum(n_viewing_azimu_b_);
n_viewing_azimu_b_csum_ = cumsum([0;n_viewing_azimu_b_]);
if (flag_verbose>0); disp(sprintf(' %% n_viewing_S %d n_viewing_polar_a %d n_viewing_azimu_b_sum %d',n_viewing_S,n_viewing_polar_a,n_viewing_azimu_b_sum)); end;
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(viewing_azimu_b_S_,1,n_viewing_S,' %% viewing_azimu_b_S_: '); end;
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(viewing_polar_a_S_,1,n_viewing_S,' %% viewing_polar_a_S_: '); end;
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(viewing_weight_S_,1,n_viewing_S,' %% viewing_weight_S_: '); end;
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(viewing_polar_a_,1,n_viewing_polar_a,' %% viewing_polar_a_: '); end;
if (flag_verbose>2); fprintf(1,' %% \t\n'); darray_printf_margin(n_viewing_azimu_b_,1,n_viewing_polar_a,' %% n_viewing_azimu_b_: '); end;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% Now determine the points along each equatorial plane (i.e., the points for each template).')); end;
%%%%%%%%;
n_w = 0;
if (template_k_eq_d>0);
k_p_r = 1;
n_equator = 3+round(2*pi*k_p_r/template_k_eq_d);
n_polar_a = 3+round(n_equator/2);
n_w = 2*n_polar_a;
end;%if (template_k_eq_d>0);
if (template_k_eq_d<=0);
%n_w = max(6,n_w_0in);
n_w = n_w_0in; %<-- no minimum. ;
end;%if (template_k_eq_d<=0);
if (flag_verbose>0); disp(sprintf(' %% n_w %d',n_w)); end;
n_w_max = n_w; n_w_sum = n_w_max*n_k_p_r; n_w_ = n_w_max*ones(n_k_p_r,1); n_w_csum_ = cumsum([0;n_w_]);
%%%%%%%%;
tolerance_w = 0.5*(2*pi)/max(1,n_w_max); %<-- tolerance used for correction. ;

%%%%%%%%;
% First check spherical-grid for consistency. ;
% For efficiency the spherical-grid should be generated using: ;
% flag_uniform_over_n_k_p_r = 1;
% flag_uniform_over_polar_a = 0;
% str_T_vs_L = 'C2';
% For accuracy one might consider increasing the angular-resolution (on each shell) ;
% without necessarily increasing the radial-resolution (i.e., the distance between shells). ;
%%%%%%%%;
tmp_t = tic();
if n_k_p_r> 1;
tmp_std = std(diff(n_qk_csum_));
if (flag_verbose>0); disp(sprintf(' %% std(diff(n_qk_csum_)) %0.6f',tmp_std)); end;
if tmp_std> 1e-12; disp(sprintf(' %% Warning, std(diff(n_qk_csum_)) %0.6f in %s',tmp_std,str_thisfunction)); end;
end;%if n_k_p_r> 1;
if n_k_p_r> 1;
tmp_std = std(diff(n_polar_a_k_));
if (flag_verbose>0); disp(sprintf(' %% std(diff(n_polar_a_k_)) %0.6f',tmp_std)); end;
if tmp_std> 1e-12; disp(sprintf(' %% Warning, std(diff(n_polar_a_k_)) %0.6f in %s',tmp_std,str_thisfunction)); end;
end;%if n_k_p_r> 1;
polar_a_single_shell_ = polar_a_ka__{1};
n_azimu_b_single_shell_ = n_azimu_b_ka__{1};
tmp_std = std(diff(polar_a_single_shell_));
if (flag_verbose>0); disp(sprintf(' %% std(diff(polar_a_single_shell_)) %0.6f',tmp_std)); end;
if tmp_std> 1e-12; disp(sprintf(' %% Warning, std(diff(polar_a_single_shell_)) %0.6f in %s',tmp_std,str_thisfunction)); end;
n_polar_a_single_shell = numel(polar_a_single_shell_);
polar_a_single_shell_lim_ = [polar_a_single_shell_(1),polar_a_single_shell_(end)];
tab_error=0; tab_check=0;
for npolar_a_single_shell=0:n_polar_a_single_shell-1;
n_azimu_b_single_shell = n_azimu_b_single_shell_(1+npolar_a_single_shell);
if npolar_a_single_shell==0; if n_azimu_b_single_shell~=1; disp(sprintf(' %% Warning, npolar_a_single_shell %d n_azimu_b_single_shell %d',npolar_a_single_shell,n_azimu_b_single_shell)); tab_error = tab_error+1; else; tab_check = tab_check+1; end; end;
if npolar_a_single_shell==n_polar_a_single_shell-1; if n_azimu_b_single_shell~=1; disp(sprintf(' %% Warning, npolar_a_single_shell %d n_azimu_b_single_shell %d',npolar_a_single_shell,n_azimu_b_single_shell)); tab_error = tab_error+1; else; tab_check = tab_check+1; end; end;
if npolar_a_single_shell> 0 & npolar_a_single_shell< n_polar_a_single_shell-1; if mod(n_azimu_b_single_shell,2)~=0; disp(sprintf(' %% Warning, npolar_a_single_shell %d n_azimu_b_single_shell %d',npolar_a_single_shell,n_azimu_b_single_shell)); tab_error = tab_error+1; else; tab_check = tab_check+1; end; end;
end;%for npolar_a_single_shell=0:n_polar_a_single_shell-1;
assert(tab_check==n_polar_a_single_shell);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% checking consistency: %0.6fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
n_q_single_shell = n_qk/max(1,n_k_p_r); n_3 = 3;
nk_p_r = n_k_p_r-1;
k_p_r = k_p_r_(1+nk_p_r);
weight_3d_k_p_r = weight_3d_k_p_r_(1+nk_p_r);
tmp_index_ = n_qk_csum_(1+nk_p_r)+[0:n_q_single_shell-1];
k_c_0_single_shell_ = k_c_0_qk_(1+tmp_index_)/max(1e-12,k_p_r);
k_c_1_single_shell_ = k_c_1_qk_(1+tmp_index_)/max(1e-12,k_p_r);
k_c_2_single_shell_ = k_c_2_qk_(1+tmp_index_)/max(1e-12,k_p_r);
k_p_azimu_b_single_shell_ = k_p_azimu_b_qk_(1+tmp_index_);
k_p_polar_a_single_shell_ = k_p_polar_a_qk_(1+tmp_index_);
weight_3d_k_single_shell_ = weight_3d_k_p_qk_(1+tmp_index_); %<-- sum(weight_3d_k_single_shell_) = 4*pi*weight_3d_k_p_r;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_3d_k_single_shell_) %0.16f 4*pi*weight_3d_k_p_r %0.16f',sum(weight_3d_k_single_shell_),4*pi*weight_3d_k_p_r)); end;
weight_shell_qk_single_shell_ = weight_shell_qk_(1+tmp_index_); %<-- sum(weight_shell_qk_single_shell_) = 4*pi*k_p_r^2. ;
if (flag_verbose>0); disp(sprintf(' %% sum(weight_shell_qk_single_shell_) %0.16f 4*pi*k_p_r^2 %0.16f',sum(weight_shell_qk_single_shell_),4*pi*k_p_r^2)); end;
weight_shell_qk_unit_shell_ = weight_shell_qk_single_shell_/max(1e-12,k_p_r)^2; %<-- sum(weight_shell_qk_unit_shell_) = 4*pi. ;
%%%%%%%%;

%%%%%%%%;
% Now generate great-circles for the templates. ;
%%%%%%%%;
tmp_t = tic();
if (flag_verbose>0); disp(sprintf(' %% calling cg_rhs_2.')); end;
n_S = n_viewing_S;
if  flag_1 & ~flag_d & ~flag_dd ;
[ ...
 k_p_polar_a_wS__ ...
,k_p_azimu_b_wS__ ...
,k_c_0_wS__ ...
,k_c_1_wS__ ...
,k_c_2_wS__ ...
,k_p_r01_wS__ ...
] = ...
cg_rhs_2( ...
 n_S ...
,n_w_max ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
end;%if  flag_1 & ~flag_d & ~flag_dd ;
if  flag_1 &  flag_d & ~flag_dd ;
[ ...
 k_p_polar_a_wS__ ...
,k_p_azimu_b_wS__ ...
,k_c_0_wS__ ...
,k_c_1_wS__ ...
,k_c_2_wS__ ...
,k_p_r01_wS__ ...
,dtau_k_p_polar_a_wS3___ ...
,dtau_k_p_azimu_b_wS3___ ...
,dtau_k_c_0_wS3___ ...
,dtau_k_c_1_wS3___ ...
,dtau_k_c_2_wS3___ ...
,dtau_k_p_r01_wS3___ ...
] = ...
cg_rhs_2( ...
 n_S ...
,n_w_max ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
end;%if  flag_1 &  flag_d & ~flag_dd ;
if  flag_1 &  flag_d &  flag_dd ;
[ ...
 k_p_polar_a_wS__ ...
,k_p_azimu_b_wS__ ...
,k_c_0_wS__ ...
,k_c_1_wS__ ...
,k_c_2_wS__ ...
,k_p_r01_wS__ ...
,dtau_k_p_polar_a_wS3___ ...
,dtau_k_p_azimu_b_wS3___ ...
,dtau_k_c_0_wS3___ ...
,dtau_k_c_1_wS3___ ...
,dtau_k_c_2_wS3___ ...
,dtau_k_p_r01_wS3___ ...
,dtau_dtau_k_p_polar_a_wS33____ ...
,dtau_dtau_k_p_azimu_b_wS33____ ...
,dtau_dtau_k_c_0_wS33____ ...
,dtau_dtau_k_c_1_wS33____ ...
,dtau_dtau_k_c_2_wS33____ ...
,dtau_dtau_k_p_r01_wS33____ ...
] = ...
cg_rhs_2( ...
 n_S ...
,n_w_max ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
end;%if  flag_1 &  flag_d &  flag_dd ;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% cg_rhs_2: %0.6fs',tmp_t)); end;
%%%%%%%%;
tmp_t = tic();
n_wS = n_w_max*n_S; n_3 = 3;
k_p_polar_a_wS_ = reshape(k_p_polar_a_wS__,[n_wS,1]);
k_p_azimu_b_wS_ = reshape(k_p_azimu_b_wS__,[n_wS,1]);
k_c_0_wS_ = reshape(k_c_0_wS__,[n_wS,1]);
k_c_1_wS_ = reshape(k_c_1_wS__,[n_wS,1]);
k_c_2_wS_ = reshape(k_c_2_wS__,[n_wS,1]);
k_p_r01_wS_ = reshape(k_p_r01_wS__,[n_wS,1]);
if flag_d;
dtau_k_p_polar_a_wS3__ = reshape(dtau_k_p_polar_a_wS3___,[n_wS,n_3]);
dtau_k_p_azimu_b_wS3__ = reshape(dtau_k_p_azimu_b_wS3___,[n_wS,n_3]);
dtau_k_c_0_wS3__ = reshape(dtau_k_c_0_wS3___,[n_wS,n_3]);
dtau_k_c_1_wS3__ = reshape(dtau_k_c_1_wS3___,[n_wS,n_3]);
dtau_k_c_2_wS3__ = reshape(dtau_k_c_2_wS3___,[n_wS,n_3]);
dtau_k_p_r01_wS3__ = reshape(dtau_k_p_r01_wS3___,[n_wS,n_3]);
end;%if flag_d;
if flag_dd;
dtau_dtau_k_p_polar_a_wS33___ = reshape(dtau_dtau_k_p_polar_a_wS33____,[n_wS,n_3,n_3]);
dtau_dtau_k_p_azimu_b_wS33___ = reshape(dtau_dtau_k_p_azimu_b_wS33____,[n_wS,n_3,n_3]);
dtau_dtau_k_c_0_wS33___ = reshape(dtau_dtau_k_c_0_wS33____,[n_wS,n_3,n_3]);
dtau_dtau_k_c_1_wS33___ = reshape(dtau_dtau_k_c_1_wS33____,[n_wS,n_3,n_3]);
dtau_dtau_k_c_2_wS33___ = reshape(dtau_dtau_k_c_2_wS33____,[n_wS,n_3,n_3]);
dtau_dtau_k_p_r01_wS33___ = reshape(dtau_dtau_k_p_r01_wS33____,[n_wS,n_3,n_3]);
end;%if flag_dd;
n_attend = 0;
if flag_attend==0;
% skipping any lsq-correction. ;
end;%if flag_attend==0;
if flag_attend==1;
index_attend_0_ = efind( (abs(periodize(k_p_azimu_b_wS_,-pi/2,pi/2))<=tolerance_w) & (abs(periodize(k_p_polar_a_wS_,-pi/2,pi/2))<=tolerance_w) );
viewing_polar_a_wS_ = reshape(repmat(reshape(viewing_polar_a_S_,[1,n_S]),[n_w_max,1]),[n_wS,1]);
viewing_azimu_b_wS_ = reshape(repmat(reshape(viewing_azimu_b_S_,[1,n_S]),[n_w_max,1]),[n_wS,1]);
viewing_gamma_z_wS_ = reshape(repmat(reshape(viewing_gamma_z_S_,[1,n_S]),[n_w_max,1]),[n_wS,1]);
index_attend_a_ = efind( (abs(periodize(viewing_polar_a_wS_,-pi/2,pi/2))<=tolerance_w) );
index_attend_b_ = efind( (abs(periodize(viewing_azimu_b_wS_,-pi/2,pi/2))<=tolerance_w) );
index_attend_c_ = efind( (abs(periodize(viewing_gamma_z_wS_,-pi/2,pi/2))<=tolerance_w) );
index_attend_ = unionall({index_attend_0_,index_attend_a_,index_attend_b_,index_attend_c_});
n_attend = numel(index_attend_);
if (flag_verbose>0); disp(sprintf(' %% n_attend %d',n_attend)); end;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% reshaping + n_attend: %0.6fs',tmp_t)); end;
end;%if flag_attend==1;

%%%%%%%%;
% Now generate the interpolation operator. ;
%%%%%%%%;
if  flag_1 & ~flag_d & ~flag_dd
if isempty(wS_from_single_shell_sba__);
if (flag_verbose>0); disp(sprintf(' %% calling shell_k_p_scatter_from_adaptive_interpolate_n_9.')); end;
tmp_t = tic();
[ ...
 wS_from_single_shell_sba__ ...
] = ...
shell_k_p_scatter_from_adaptive_interpolate_n_9( ...
 n_order ...
,n_polar_a_single_shell ...
,n_azimu_b_single_shell_ ...
,polar_a_single_shell_lim_ ...
,n_wS ...
,k_p_polar_a_wS_ ...
,k_p_azimu_b_wS_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% shell_k_p_scatter_from_adaptive_interpolate_n_9 (flag_1): %0.6fs',tmp_t)); end;
end;%if isempty(wS_from_single_shell_sba__);
end;%if  flag_1 & ~flag_d & ~flag_dd
if  flag_1 &  flag_d & ~flag_dd
if ...
0 ...
|isempty(wS_from_single_shell_sba__) ...
|isempty(dwSda_from_single_shell_sba__) ...
|isempty(dwSdb_from_single_shell_sba__) ...
;
if (flag_verbose>0); disp(sprintf(' %% calling shell_k_p_scatter_from_adaptive_interpolate_n_9.')); end;
tmp_t = tic();
[ ...
 wS_from_single_shell_sba__ ...
,dwSda_from_single_shell_sba__ ...
,dwSdb_from_single_shell_sba__ ...
] = ...
shell_k_p_scatter_from_adaptive_interpolate_n_9( ...
 n_order ...
,n_polar_a_single_shell ...
,n_azimu_b_single_shell_ ...
,polar_a_single_shell_lim_ ...
,n_wS ...
,k_p_polar_a_wS_ ...
,k_p_azimu_b_wS_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% shell_k_p_scatter_from_adaptive_interpolate_n_9 (flag_d): %0.6fs',tmp_t)); end;
end;%if;
end;%if  flag_1 &  flag_d & ~flag_dd
if  flag_1 &  flag_d &  flag_dd
if ...
0 ...
|isempty(wS_from_single_shell_sba__) ...
|isempty(dwSda_from_single_shell_sba__) ...
|isempty(dwSdb_from_single_shell_sba__) ...
|isempty(ddwSdaa_from_single_shell_sba__) ...
|isempty(ddwSdab_from_single_shell_sba__) ...
|isempty(ddwSdbb_from_single_shell_sba__) ...
;
if (flag_verbose>0); disp(sprintf(' %% calling shell_k_p_scatter_from_adaptive_interpolate_n_9.')); end;
tmp_t = tic();
[ ...
 wS_from_single_shell_sba__ ...
,dwSda_from_single_shell_sba__ ...
,dwSdb_from_single_shell_sba__ ...
,ddwSdaa_from_single_shell_sba__ ...
,ddwSdab_from_single_shell_sba__ ...
,ddwSdbb_from_single_shell_sba__ ...
] = ...
shell_k_p_scatter_from_adaptive_interpolate_n_9( ...
 n_order ...
,n_polar_a_single_shell ...
,n_azimu_b_single_shell_ ...
,polar_a_single_shell_lim_ ...
,n_wS ...
,k_p_polar_a_wS_ ...
,k_p_azimu_b_wS_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% shell_k_p_scatter_from_adaptive_interpolate_n_9 (flag_dd): %0.6fs',tmp_t)); end;
end;%if;
end;%if  flag_1 &  flag_d &  flag_dd
%%%%%%%%;

%%%%%%%%;
if sum(~isfinite(wS_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, wS_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(dwSda_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, dwSda_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(dwSdb_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, dwSdb_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddwSdaa_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, ddwSdaa_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddwSdab_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, ddwSdab_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddwSdbb_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, ddwSdbb_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
%%%%%%%%;

%%%%%%%%;
% Now apply the interpolation operator. ;
% Note that the derivatives with respect to gamma_z (i.e., tab_c) are opposite to sph_template_3. ;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% applying interpolation operator.')); end;
tmp_t_0 = tic();
S_k_p_wSk__ = zeros(n_wS,n_k_p_r);
if flag_d;
dSda_k_p_wSk__ = zeros(n_wS,n_k_p_r);
dSdb_k_p_wSk__ = zeros(n_wS,n_k_p_r);
dSdc_k_p_wSk__ = zeros(n_wS,n_k_p_r);
end;%if flag_d;
if flag_dd;
ddSdaa_k_p_wSk__ = zeros(n_wS,n_k_p_r);
ddSdab_k_p_wSk__ = zeros(n_wS,n_k_p_r);
ddSdac_k_p_wSk__ = zeros(n_wS,n_k_p_r);
ddSdbb_k_p_wSk__ = zeros(n_wS,n_k_p_r);
ddSdbc_k_p_wSk__ = zeros(n_wS,n_k_p_r);
ddSdcc_k_p_wSk__ = zeros(n_wS,n_k_p_r);
end;%if flag_dd;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
tab_a = 0; tab_b = 1; tab_c = 2;
for nk_p_r=0:n_k_p_r-1;
if (flag_verbose>0); disp(sprintf(' %% nk_p_r %d/%d',nk_p_r,n_k_p_r)); end;
tmp_t_1 = tic();
a_k_p_single_shell_ = a_k_p_qk_(1+nk_p_r*n_q_single_shell+[0:n_q_single_shell-1]);
S_k_p_wS_ = wS_from_single_shell_sba__*a_k_p_single_shell_;
if flag_d;
dSda_k_p_wS_ = dwSda_from_single_shell_sba__*a_k_p_single_shell_;
dSdb_k_p_wS_ = dwSdb_from_single_shell_sba__*a_k_p_single_shell_;
end;%if flag_d;
if flag_dd;
ddSdaa_k_p_wS_ = ddwSdaa_from_single_shell_sba__*a_k_p_single_shell_;
ddSdab_k_p_wS_ = ddwSdab_from_single_shell_sba__*a_k_p_single_shell_;
ddSdbb_k_p_wS_ = ddwSdbb_from_single_shell_sba__*a_k_p_single_shell_;
end;%if flag_dd;
tmp_t_1 = toc(tmp_t_1); if (flag_verbose>0); disp(sprintf(' %% extract ddSdxx_k_p_wS_: %0.6fs',tmp_t_1)); end;
%%%%%%%%;
S_k_p_wSk__(:,1+nk_p_r) = S_k_p_wS_;
if flag_d;
tmp_t_1 = tic();
dSda_k_p_wSk__(:,1+nk_p_r) = ...
+ bsxfun(@times,dSda_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a)) ...
+ bsxfun(@times,dSdb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a)) ...
;
dSdb_k_p_wSk__(:,1+nk_p_r) = ...
+ bsxfun(@times,dSda_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_b)) ...
+ bsxfun(@times,dSdb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_b)) ...
;
dSdc_k_p_wSk__(:,1+nk_p_r) = ...
+ bsxfun(@times,dSda_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ bsxfun(@times,dSdb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
;
tmp_t_1 = toc(tmp_t_1); if (flag_verbose>0); disp(sprintf(' %% calculate dSdx_k_p_wSk__: %0.6fs',tmp_t_1)); end;
end;%if flag_d;
if flag_dd;
tmp_t_1 = tic();
ddSdaa_k_p_wSk__(:,1+nk_p_r) = ...
+ 1.0*bsxfun(@times,dSda_k_p_wS_,dtau_dtau_k_p_polar_a_wS33___(:,1+tab_a,1+tab_a)) ...
+ 1.0*bsxfun(@times,dSdb_k_p_wS_,dtau_dtau_k_p_azimu_b_wS33___(:,1+tab_a,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSdaa_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a).*dtau_k_p_polar_a_wS3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a).*dtau_k_p_azimu_b_wS3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a).*dtau_k_p_polar_a_wS3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSdbb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a).*dtau_k_p_azimu_b_wS3__(:,1+tab_a)) ...
;
ddSdab_k_p_wSk__(:,1+nk_p_r) = ...
+ 1.0*bsxfun(@times,dSda_k_p_wS_,dtau_dtau_k_p_polar_a_wS33___(:,1+tab_a,1+tab_b)) ...
+ 1.0*bsxfun(@times,dSdb_k_p_wS_,dtau_dtau_k_p_azimu_b_wS33___(:,1+tab_a,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdaa_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a).*dtau_k_p_polar_a_wS3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a).*dtau_k_p_azimu_b_wS3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a).*dtau_k_p_polar_a_wS3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdbb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a).*dtau_k_p_azimu_b_wS3__(:,1+tab_b)) ...
;
ddSdac_k_p_wSk__(:,1+nk_p_r) = ...
+ 1.0*bsxfun(@times,dSda_k_p_wS_,dtau_dtau_k_p_polar_a_wS33___(:,1+tab_a,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSdb_k_p_wS_,dtau_dtau_k_p_azimu_b_wS33___(:,1+tab_a,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdaa_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a).*dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_a).*dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a).*dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdbb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_a).*dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
;
ddSdbb_k_p_wSk__(:,1+nk_p_r) = ...
+ 1.0*bsxfun(@times,dSda_k_p_wS_,dtau_dtau_k_p_polar_a_wS33___(:,1+tab_b,1+tab_b)) ...
+ 1.0*bsxfun(@times,dSdb_k_p_wS_,dtau_dtau_k_p_azimu_b_wS33___(:,1+tab_b,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdaa_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_b).*dtau_k_p_polar_a_wS3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_b).*dtau_k_p_azimu_b_wS3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_b).*dtau_k_p_polar_a_wS3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSdbb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_b).*dtau_k_p_azimu_b_wS3__(:,1+tab_b)) ...
;
ddSdbc_k_p_wSk__(:,1+nk_p_r) = ...
+ 1.0*bsxfun(@times,dSda_k_p_wS_,dtau_dtau_k_p_polar_a_wS33___(:,1+tab_b,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSdb_k_p_wS_,dtau_dtau_k_p_azimu_b_wS33___(:,1+tab_b,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdaa_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_b).*dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_b).*dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_b).*dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdbb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_b).*dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
;
ddSdcc_k_p_wSk__(:,1+nk_p_r) = ...
+ 1.0*bsxfun(@times,dSda_k_p_wS_,dtau_dtau_k_p_polar_a_wS33___(:,1+tab_c,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSdb_k_p_wS_,dtau_dtau_k_p_azimu_b_wS33___(:,1+tab_c,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdaa_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_c).*dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_polar_a_wS3__(:,1+tab_c).*dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdab_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_c).*dtau_k_p_polar_a_wS3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSdbb_k_p_wS_,dtau_k_p_azimu_b_wS3__(:,1+tab_c).*dtau_k_p_azimu_b_wS3__(:,1+tab_c)) ...
;
tmp_t_1 = toc(tmp_t_1); if (flag_verbose>0); disp(sprintf(' %% calculate ddSdxx_k_p_wSk__: %0.6fs',tmp_t_1)); end;
end;%if flag_dd;
%%%%%%%%%%%%%%%%;
if ~flag_attend | n_attend==0;
if (flag_verbose>0); disp(sprintf(' %% skipping any lsq-correction')); end;
end;%if ~flag_attend | n_attend==0;
if flag_attend & n_attend> 0;
tmp_t_1 = tic();
%%%%%%%%;
% Now apply the lsq-correction. ;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% beginning lsq-correction')); end;
tmp_t_2 = tic();
k_p_polar_a_wS_attend_ = k_p_polar_a_wS_(1+index_attend_);
k_p_azimu_b_wS_attend_ = k_p_azimu_b_wS_(1+index_attend_);
S_k_p_wS_attend_ = S_k_p_wS_(1+index_attend_);
%%%%%%%%;
if flag_d;
dSda_k_p_wS_attend_ = dSda_k_p_wS_(1+index_attend_);
dSdb_k_p_wS_attend_ = dSdb_k_p_wS_(1+index_attend_);
end;%if flag_d;
if flag_dd;
ddSdaa_k_p_wS_attend_ = ddSdaa_k_p_wS_(1+index_attend_);
ddSdab_k_p_wS_attend_ = ddSdab_k_p_wS_(1+index_attend_);
ddSdbb_k_p_wS_attend_ = ddSdbb_k_p_wS_(1+index_attend_);
end;%if flag_dd;
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% extract ddSdxx_k_p_wS_attend_: %0.6fs',tmp_t_2)); end;
%%%%%%%%;
if flag_d;
tmp_t_2 = tic();
dtau_k_p_polar_a_wS_attend_3__ = dtau_k_p_polar_a_wS3__(1+index_attend_,1:n_3);
dtau_k_p_azimu_b_wS_attend_3__ = dtau_k_p_azimu_b_wS3__(1+index_attend_,1:n_3);
dtau_k_c_0_wS_attend_3__ = dtau_k_c_0_wS3__(1+index_attend_,1:n_3);
dtau_k_c_1_wS_attend_3__ = dtau_k_c_1_wS3__(1+index_attend_,1:n_3);
dtau_k_c_2_wS_attend_3__ = dtau_k_c_2_wS3__(1+index_attend_,1:n_3);
dtau_k_p_r01_wS_attend_3__ = dtau_k_p_r01_wS3__(1+index_attend_,1:n_3);
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% extract dtau_k_c_x_wS_attend_3__: %0.6fs',tmp_t_2)); end;
end;%if flag_d;
if flag_dd;
tmp_t_2 = tic();
dtau_dtau_k_p_polar_a_wS_attend_33___ = dtau_dtau_k_p_polar_a_wS33___(1+index_attend_,1:n_3,1:n_3);
dtau_dtau_k_p_azimu_b_wS_attend_33___ = dtau_dtau_k_p_azimu_b_wS33___(1+index_attend_,1:n_3,1:n_3);
dtau_dtau_k_c_0_wS_attend_33___ = dtau_dtau_k_c_0_wS33___(1+index_attend_,1:n_3,1:n_3);
dtau_dtau_k_c_1_wS_attend_33___ = dtau_dtau_k_c_1_wS33___(1+index_attend_,1:n_3,1:n_3);
dtau_dtau_k_c_2_wS_attend_33___ = dtau_dtau_k_c_2_wS33___(1+index_attend_,1:n_3,1:n_3);
dtau_dtau_k_p_r01_wS_attend_33___ = dtau_dtau_k_p_r01_wS33___(1+index_attend_,1:n_3,1:n_3);
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% extract dtau_dtau_k_c_x_wS_attend_33___: %0.6fs',tmp_t_2)); end;
end;%if flag_dd;
%%%%%%%%;
% Note, the pseudo-inverse calculations in cartesian_from_shell_10 need only be calculated once per shell ;
% However, here we recalculate them for each nk_p_r. ;
% This is terribly inefficient. ;
%%%%%%%%;
if flag_d;
tmp_t_2 = tic();
parameter_cartesian_from_shell = parameter;
parameter_cartesian_from_shell.flag_verbose = 0;
[ ...
 parameter_cartesian_from_shell ...
,dSd0_k_p_wS_attend_ ...
,dSd1_k_p_wS_attend_ ...
,dSd2_k_p_wS_attend_ ...
] = ...
cartesian_from_shell_10( ...
 parameter_cartesian_from_shell ...
,n_attend ...
,1 ...
,k_p_polar_a_wS_attend_ ...
,k_p_azimu_b_wS_attend_ ...
,S_k_p_wS_attend_ ...
,dSda_k_p_wS_attend_ ...
,dSdb_k_p_wS_attend_ ...
);
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% calling cartesian_from_shell_10 (flag_d): %0.6fs',tmp_t_2)); end;
end;%if flag_d;
%%%%;
if flag_dd;
tmp_t_2 = tic();
parameter_cartesian_from_shell = parameter;
parameter_cartesian_from_shell.flag_verbose = 0;
[ ...
 parameter_cartesian_from_shell ...
,dSd0_k_p_wS_attend_ ...
,dSd1_k_p_wS_attend_ ...
,dSd2_k_p_wS_attend_ ...
,ddSd00_k_p_wS_attend_ ...
,ddSd01_k_p_wS_attend_ ...
,ddSd02_k_p_wS_attend_ ...
,ddSd11_k_p_wS_attend_ ...
,ddSd12_k_p_wS_attend_ ...
,ddSd22_k_p_wS_attend_ ...
] = ...
cartesian_from_shell_10( ...
 parameter_cartesian_from_shell ...
,n_attend ...
,1 ...
,k_p_polar_a_wS_attend_ ...
,k_p_azimu_b_wS_attend_ ...
,S_k_p_wS_attend_ ...
,dSda_k_p_wS_attend_ ...
,dSdb_k_p_wS_attend_ ...
,ddSdaa_k_p_wS_attend_ ...
,ddSdab_k_p_wS_attend_ ...
,ddSdbb_k_p_wS_attend_ ...
);
ddSd10_k_p_wS_attend_ = ddSd01_k_p_wS_attend_ ;
ddSd20_k_p_wS_attend_ = ddSd02_k_p_wS_attend_ ;
ddSd21_k_p_wS_attend_ = ddSd12_k_p_wS_attend_ ;
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% calling cartesian_from_shell_10 (flag_dd): %0.6fs',tmp_t_2)); end;
end;%if flag_dd;
%%%%%%%%;
T_k_p_wS_attend_ = S_k_p_wS_attend_;
if flag_d;
tmp_t_2 = tic();
dTda_k_p_wS_attend_ = ...
+ bsxfun(@times,dSd0_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a)) ...
+ bsxfun(@times,dSd1_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a)) ...
+ bsxfun(@times,dSd2_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a)) ...
;
dTdb_k_p_wS_attend_ = ...
+ bsxfun(@times,dSd0_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ bsxfun(@times,dSd1_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ bsxfun(@times,dSd2_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
;
dTdc_k_p_wS_attend_ = ...
+ bsxfun(@times,dSd0_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ bsxfun(@times,dSd1_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ bsxfun(@times,dSd2_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
;
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% calculate dTdx_k_p_wS_attend_ (flag_d): %0.6fs',tmp_t_2)); end;
end;%if flag_d;
if flag_dd;
tmp_t_2 = tic();
ddTdaa_k_p_wS_attend_ = ...
+ 1.0*bsxfun(@times,dSd0_k_p_wS_attend_,dtau_dtau_k_c_0_wS_attend_33___(:,1+tab_a,1+tab_a)) ...
+ 1.0*bsxfun(@times,dSd1_k_p_wS_attend_,dtau_dtau_k_c_1_wS_attend_33___(:,1+tab_a,1+tab_a)) ...
+ 1.0*bsxfun(@times,dSd2_k_p_wS_attend_,dtau_dtau_k_c_2_wS_attend_33___(:,1+tab_a,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd00_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd01_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd02_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd10_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd11_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd12_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd20_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd21_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_a)) ...
+ 1.0*bsxfun(@times,ddSd22_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_a)) ...
;
ddTdab_k_p_wS_attend_ = ...
+ 1.0*bsxfun(@times,dSd0_k_p_wS_attend_,dtau_dtau_k_c_0_wS_attend_33___(:,1+tab_a,1+tab_b)) ...
+ 1.0*bsxfun(@times,dSd1_k_p_wS_attend_,dtau_dtau_k_c_1_wS_attend_33___(:,1+tab_a,1+tab_b)) ...
+ 1.0*bsxfun(@times,dSd2_k_p_wS_attend_,dtau_dtau_k_c_2_wS_attend_33___(:,1+tab_a,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd00_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd01_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd02_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd10_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd11_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd12_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd20_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd21_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd22_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
;
ddTdac_k_p_wS_attend_ = ...
+ 1.0*bsxfun(@times,dSd0_k_p_wS_attend_,dtau_dtau_k_c_0_wS_attend_33___(:,1+tab_a,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSd1_k_p_wS_attend_,dtau_dtau_k_c_1_wS_attend_33___(:,1+tab_a,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSd2_k_p_wS_attend_,dtau_dtau_k_c_2_wS_attend_33___(:,1+tab_a,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd00_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd01_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd02_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd10_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd11_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd12_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd20_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd21_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd22_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_a).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
;
ddTdbb_k_p_wS_attend_ = ...
+ 1.0*bsxfun(@times,dSd0_k_p_wS_attend_,dtau_dtau_k_c_0_wS_attend_33___(:,1+tab_b,1+tab_b)) ...
+ 1.0*bsxfun(@times,dSd1_k_p_wS_attend_,dtau_dtau_k_c_1_wS_attend_33___(:,1+tab_b,1+tab_b)) ...
+ 1.0*bsxfun(@times,dSd2_k_p_wS_attend_,dtau_dtau_k_c_2_wS_attend_33___(:,1+tab_b,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd00_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b).*dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd01_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b).*dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd02_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b).*dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd10_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b).*dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd11_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b).*dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd12_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b).*dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd20_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b).*dtau_k_c_0_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd21_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b).*dtau_k_c_1_wS_attend_3__(:,1+tab_b)) ...
+ 1.0*bsxfun(@times,ddSd22_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b).*dtau_k_c_2_wS_attend_3__(:,1+tab_b)) ...
;
ddTdbc_k_p_wS_attend_ = ...
+ 1.0*bsxfun(@times,dSd0_k_p_wS_attend_,dtau_dtau_k_c_0_wS_attend_33___(:,1+tab_b,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSd1_k_p_wS_attend_,dtau_dtau_k_c_1_wS_attend_33___(:,1+tab_b,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSd2_k_p_wS_attend_,dtau_dtau_k_c_2_wS_attend_33___(:,1+tab_b,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd00_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd01_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd02_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_b).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd10_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd11_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd12_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_b).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd20_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd21_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd22_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_b).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
;
ddTdcc_k_p_wS_attend_ = ...
+ 1.0*bsxfun(@times,dSd0_k_p_wS_attend_,dtau_dtau_k_c_0_wS_attend_33___(:,1+tab_c,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSd1_k_p_wS_attend_,dtau_dtau_k_c_1_wS_attend_33___(:,1+tab_c,1+tab_c)) ...
+ 1.0*bsxfun(@times,dSd2_k_p_wS_attend_,dtau_dtau_k_c_2_wS_attend_33___(:,1+tab_c,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd00_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_c).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd01_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_c).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd02_k_p_wS_attend_,dtau_k_c_0_wS_attend_3__(:,1+tab_c).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd10_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_c).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd11_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_c).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd12_k_p_wS_attend_,dtau_k_c_1_wS_attend_3__(:,1+tab_c).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd20_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_c).*dtau_k_c_0_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd21_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_c).*dtau_k_c_1_wS_attend_3__(:,1+tab_c)) ...
+ 1.0*bsxfun(@times,ddSd22_k_p_wS_attend_,dtau_k_c_2_wS_attend_3__(:,1+tab_c).*dtau_k_c_2_wS_attend_3__(:,1+tab_c)) ...
;
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% calculate ddTdxx_k_p_wS_attend_ (flag_dd): %0.6fs',tmp_t_2)); end;
end;%if flag_dd;
%%%%%%%%;
tmp_t_2 = tic();
S_k_p_wSk__(1+index_attend_,1+nk_p_r) = T_k_p_wS_attend_ ;
if flag_d;
dSda_k_p_wSk__(1+index_attend_,1+nk_p_r) = dTda_k_p_wS_attend_ ;
dSdb_k_p_wSk__(1+index_attend_,1+nk_p_r) = dTdb_k_p_wS_attend_ ;
dSdc_k_p_wSk__(1+index_attend_,1+nk_p_r) = dTdc_k_p_wS_attend_ ;
end;%if flag_d;
if flag_dd;
ddSdaa_k_p_wSk__(1+index_attend_,1+nk_p_r) = ddTdaa_k_p_wS_attend_ ;
ddSdab_k_p_wSk__(1+index_attend_,1+nk_p_r) = ddTdab_k_p_wS_attend_ ;
ddSdac_k_p_wSk__(1+index_attend_,1+nk_p_r) = ddTdac_k_p_wS_attend_ ;
ddSdbb_k_p_wSk__(1+index_attend_,1+nk_p_r) = ddTdbb_k_p_wS_attend_ ;
ddSdbc_k_p_wSk__(1+index_attend_,1+nk_p_r) = ddTdbc_k_p_wS_attend_ ;
ddSdcc_k_p_wSk__(1+index_attend_,1+nk_p_r) = ddTdcc_k_p_wS_attend_ ;
end;%if flag_dd;
tmp_t_2 = toc(tmp_t_2); if (flag_verbose>0); disp(sprintf(' %% copying ddSdxx_k_p_wSk__: %0.6fs',tmp_t_2)); end;
%%%%%%%%;
tmp_t_1 = toc(tmp_t_1); if (flag_verbose>0); disp(sprintf(' %% finish lsq-correction: %0.6fs',tmp_t_1)); end;
end;%if flag_attend & n_attend> 0;
%%%%%%%%%%%%%%%%;
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
tmp_t_0 = toc(tmp_t_0); if (flag_verbose>0); disp(sprintf(' %% applying interpolation operator: %0.6fs',tmp_t_0)); end;

%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% permuting template values.')); end;
tmp_t = tic();
S_k_p_wkS__ = reshape(permute(reshape(S_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
if flag_d;
if (flag_verbose>0); disp(sprintf(' %% permuting dtemplate values.')); end;
dSda_k_p_wkS__ = reshape(permute(reshape(dSda_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
dSdb_k_p_wkS__ = reshape(permute(reshape(dSdb_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
dSdc_k_p_wkS__ = reshape(permute(reshape(dSdc_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
end;%if flag_d;
if flag_dd;
if (flag_verbose>0); disp(sprintf(' %% permuting ddtemplate values.')); end;
ddSdaa_k_p_wkS__ = reshape(permute(reshape(ddSdaa_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
ddSdab_k_p_wkS__ = reshape(permute(reshape(ddSdab_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
ddSdac_k_p_wkS__ = reshape(permute(reshape(ddSdac_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
ddSdbb_k_p_wkS__ = reshape(permute(reshape(ddSdbb_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
ddSdbc_k_p_wkS__ = reshape(permute(reshape(ddSdbc_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
ddSdcc_k_p_wkS__ = reshape(permute(reshape(ddSdcc_k_p_wSk__,[n_w_max,n_S,n_k_p_r]),[1,3,2]),[n_w_sum,n_S]);
end;%if flag_dd;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% permuting template values: %0.6fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
% Copying to output. ;
%%%%%%%%;
tmp_t = tic();
if flag_1; template_wkS__ = S_k_p_wkS__; end;
if flag_d;
dtemplateda_wkS__ = dSda_k_p_wkS__;
dtemplatedb_wkS__ = dSdb_k_p_wkS__;
dtemplatedc_wkS__ = dSdc_k_p_wkS__;
end;%if flag_d;
if flag_dd;
ddtemplatedaa_wkS__ = ddSdaa_k_p_wkS__;
ddtemplatedab_wkS__ = ddSdab_k_p_wkS__;
ddtemplatedac_wkS__ = ddSdac_k_p_wkS__;
ddtemplatedbb_wkS__ = ddSdbb_k_p_wkS__;
ddtemplatedbc_wkS__ = ddSdbc_k_p_wkS__;
ddtemplatedcc_wkS__ = ddSdcc_k_p_wkS__;
end;%if flag_dd;
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% copying to output: %0.6fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
if flag_1;
if sum(~isfinite(template_wkS__),'all')> 0; disp(sprintf(' %% Warning, template_wkS__ not finite in %s',str_thisfunction)); end;
end;%if flag_1;
if sum(~isfinite(n_w),'all')> 0; disp(sprintf(' %% Warning, n_w not finite in %s',str_thisfunction)); end;
if sum(~isfinite(n_viewing_S),'all')> 0; disp(sprintf(' %% Warning, n_viewing_S not finite in %s',str_thisfunction)); end;
if sum(~isfinite(viewing_azimu_b_S_),'all')> 0; disp(sprintf(' %% Warning, viewing_azimu_b_S_ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(viewing_polar_a_S_),'all')> 0; disp(sprintf(' %% Warning, viewing_polar_a_S_ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(viewing_weight_S_),'all')> 0; disp(sprintf(' %% Warning, viewing_weight_S_ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(n_viewing_polar_a),'all')> 0; disp(sprintf(' %% Warning, n_viewing_polar_a not finite in %s',str_thisfunction)); end;
if sum(~isfinite(viewing_polar_a_),'all')> 0; disp(sprintf(' %% Warning, viewing_polar_a_ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(n_viewing_azimu_b_),'all')> 0; disp(sprintf(' %% Warning, n_viewing_azimu_b_ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(viewing_gamma_z_S_),'all')> 0; disp(sprintf(' %% Warning, viewing_gamma_z_S_ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(wS_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, wS_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if flag_d;
if sum(~isfinite(dtemplateda_wkS__),'all')> 0; disp(sprintf(' %% Warning, dtemplateda_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(dtemplatedb_wkS__),'all')> 0; disp(sprintf(' %% Warning, dtemplatedb_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(dtemplatedc_wkS__),'all')> 0; disp(sprintf(' %% Warning, dtemplatedc_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(dwSda_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, dwSda_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(dwSdb_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, dwSdb_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
end;%if flag_d;
if flag_dd;
if sum(~isfinite(ddtemplatedaa_wkS__),'all')> 0; disp(sprintf(' %% Warning, ddtemplatedaa_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddtemplatedab_wkS__),'all')> 0; disp(sprintf(' %% Warning, ddtemplatedab_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddtemplatedac_wkS__),'all')> 0; disp(sprintf(' %% Warning, ddtemplatedac_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddtemplatedbb_wkS__),'all')> 0; disp(sprintf(' %% Warning, ddtemplatedbb_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddtemplatedbc_wkS__),'all')> 0; disp(sprintf(' %% Warning, ddtemplatedbc_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddtemplatedcc_wkS__),'all')> 0; disp(sprintf(' %% Warning, ddtemplatedcc_wkS__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddwSdaa_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, ddwSdaa_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddwSdab_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, ddwSdab_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
if sum(~isfinite(ddwSdbb_from_single_shell_sba__),'all')> 0; disp(sprintf(' %% Warning, ddwSdbb_from_single_shell_sba__ not finite in %s',str_thisfunction)); end;
end;%if flag_dd;
%%%%%%%%;

if (flag_verbose>0); disp(sprintf(' %% [finished %s]',str_thisfunction)); end;



