function ...
[ ...
 parameter ...
,l_max ...
,kappa_norm_ ...
,chebfun_kernel_norm_ ...
,deconvolve_q ...
,relative_error_full_ ...
,chebleg_d_ ...
,k_p_r_max ...
,k_eq_d ...
,n_k_p_r ...
,k_p_r_1 ...
,k_p_r_ ...
,n_shell ...
,azimu_b_shell_ ...
,polar_a_shell_ ...
,weight_shell_ ...
,k_c_0_shell_ ...
,k_c_1_shell_ ...
,k_c_2_shell_ ...
,k_p_r_shell_ ...
,n_lm ...
,m_max_ ...
,n_m_max ...
,Y_l_val_ ...
,Y_m_val_ ...
,weight_3d_k_p_r_ ...
] = ...
kappa_basic_recon_4( ...
 parameter ...
,l_max ...
,kappa_norm_ ...
,chebfun_kernel_norm_ ...
,deconvolve_q ...
,relative_error_full_ ...
,chebleg_d_ ...
,k_p_r_max ...
,k_eq_d ...
,n_k_p_r ...
,k_p_r_1 ...
,k_p_r_ ...
,n_shell ...
,azimu_b_shell_ ...
,polar_a_shell_ ...
,weight_shell_ ...
,k_c_0_shell_ ...
,k_c_1_shell_ ...
,k_c_2_shell_ ...
,k_p_r_shell_ ...
,n_lm ...
,m_max_ ...
,n_m_max ...
,Y_l_val_ ...
,Y_m_val_ ...
,weight_3d_k_p_r_ ...
);

str_thisfunction = 'kappa_basic_recon_4';

%%%%%%%%;
if nargin<1;
disp(sprintf(' %% testing %s',str_thisfunction));
parameter = struct('type','parameter'); parameter.flag_verbose = 1; parameter.flag_disp = 1; parameter.flag_check = 0;
parameter.flag_recalc_qref_from_data=0;
parameter.flag_recalc_dtau_qref_from_data=0;
parameter.flag_recalc_dtau_dtau_qref_from_data=0;
parameter.kernel_basic_l_max_use = 24;
parameter.kernel_basic_l_max_band = floor(24/2)-1;%parameter.kernel_basic_l_max_band = +Inf;
parameter.kernel_basic_l_max_ext = ceil(1.25*parameter.kernel_basic_l_max_use);
parameter.flag_kernel_full = 1; %<-- if set to 1 then use full brute-force kernel. ;
parameter.kernel_basic_qref_k_eq_d_double = [];
kappa_basic_recon_4( ...
 parameter ...
);
disp('returning'); return;
end;%if nargin<1;
%%%%%%%%;

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); l_max=[]; end; na=na+1;
if (nargin<1+na); kappa_norm_=[]; end; na=na+1;
if (nargin<1+na); chebfun_kernel_norm_=[]; end; na=na+1;
if (nargin<1+na); deconvolve_q=[]; end; na=na+1;
if (nargin<1+na); relative_error_full_=[]; end; na=na+1;
if (nargin<1+na); chebleg_d_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_max=[]; end; na=na+1;
if (nargin<1+na); k_eq_d=[]; end; na=na+1;
if (nargin<1+na); n_k_p_r=[]; end; na=na+1;
if (nargin<1+na); k_p_r_1=[]; end; na=na+1;
if (nargin<1+na); k_p_r_=[]; end; na=na+1;
if (nargin<1+na); n_shell=[]; end; na=na+1;
if (nargin<1+na); azimu_b_shell_=[]; end; na=na+1;
if (nargin<1+na); polar_a_shell_=[]; end; na=na+1;
if (nargin<1+na); weight_shell_=[]; end; na=na+1;
if (nargin<1+na); k_c_0_shell_=[]; end; na=na+1;
if (nargin<1+na); k_c_1_shell_=[]; end; na=na+1;
if (nargin<1+na); k_c_2_shell_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_shell_=[]; end; na=na+1;
if (nargin<1+na); n_lm=[]; end; na=na+1;
if (nargin<1+na); m_max_=[]; end; na=na+1;
if (nargin<1+na); n_m_max=[]; end; na=na+1;
if (nargin<1+na); Y_l_val_=[]; end; na=na+1;
if (nargin<1+na); Y_m_val_=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_r_=[]; end; na=na+1;

%{
str_thisfunction = 'kappa_basic_recon_4';
parameter=[];
parameter = struct('type','parameter'); parameter.flag_verbose = 1; parameter.flag_disp = 0; parameter.flag_check = 0;
parameter.flag_recalc_qref_from_data=0;
parameter.flag_recalc_dtau_qref_from_data=0;
parameter.flag_recalc_dtau_dtau_qref_from_data=0;
parameter.kernel_basic_l_max_use = 24;
parameter.kernel_basic_l_max_band = floor(24/2)-1;
parameter.kernel_basic_l_max_ext = ceil(1.25*parameter.kernel_basic_l_max_use);
parameter.flag_kernel_full = 1; %<-- if set to 1 then use full brute-force kernel. ;
l_max=[];
kappa_norm_=[];
chebfun_kernel_norm_=[];
deconvolve_q=[];
relative_error_full_=[];
chebleg_d_=[];
k_p_r_max=[];
k_eq_d=[];
n_k_p_r=[];
k_p_r_1=[];
k_p_r_=[];
n_shell=[];
azimu_b_shell_=[];
polar_a_shell_=[];
weight_shell_=[];
k_c_0_shell_=[];
k_c_1_shell_=[];
k_c_2_shell_=[];
k_p_r_shell_=[];
n_lm=[];
m_max_=[];
n_m_max=[];
Y_l_val_=[];
Y_m_val_=[];
weight_3d_k_p_r_=[];
 %}

if isempty(parameter); parameter=struct('type','parameter'); end;
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose=0; end;
flag_verbose=parameter.flag_verbose;
if ~isfield(parameter,'flag_disp'); parameter.flag_disp=0; end;
flag_disp=parameter.flag_disp; nf=0;
if ~isfield(parameter,'flag_check'); parameter.flag_check=0; end;
flag_check=parameter.flag_check;
if ~isfield(parameter,'tolerance_master'); parameter.tolerance_master=1e-2; end;
tolerance_master=parameter.tolerance_master;
if ~isfield(parameter,'kernel_basic_l_max_use'); parameter.kernel_basic_l_max_use=49; end;
kernel_basic_l_max_use=parameter.kernel_basic_l_max_use;
if ~isfield(parameter,'kernel_basic_l_max_ext'); parameter.kernel_basic_l_max_ext=ceil(1.25*kernel_basic_l_max_use); end;
kernel_basic_l_max_ext=parameter.kernel_basic_l_max_ext;
if ~isfield(parameter,'kernel_basic_l_max_band'); parameter.kernel_basic_l_max_band=+Inf; end;
kernel_basic_l_max_band=parameter.kernel_basic_l_max_band;
if ~isfield(parameter,'kernel_basic_qref_k_eq_d_double'); parameter.kernel_basic_qref_k_eq_d_double=[]; end;
kernel_basic_qref_k_eq_d_double=parameter.kernel_basic_qref_k_eq_d_double;
%%%%;
if ~isfield(parameter,'flag_recalc_qref_from_data'); parameter.flag_recalc_qref_from_data=1; end;
flag_recalc_qref_from_data=parameter.flag_recalc_qref_from_data;
if ~isfield(parameter,'flag_recalc_dtau_qref_from_data'); parameter.flag_recalc_dtau_qref_from_data=1; end;
flag_recalc_dtau_qref_from_data=parameter.flag_recalc_dtau_qref_from_data;
if ~isfield(parameter,'flag_recalc_dtau_dtau_qref_from_data'); parameter.flag_recalc_dtau_dtau_qref_from_data=1; end;
flag_recalc_dtau_dtau_qref_from_data=parameter.flag_recalc_dtau_dtau_qref_from_data;
%%%%;

if (flag_verbose> 0); disp(sprintf(' %% [entering %s]',str_thisfunction)); end;

%%%%%%%%;
if isempty(l_max); l_max = kernel_basic_l_max_use; end;
l_val_ = transpose([0:l_max]);
%%%%%%%%;
% generating KAPPA. ;
%%%%%%%%;
parameter = struct('type','parameter');
parameter.flag_verbose = 0; parameter.flag_disp = 0;
parameter.kernel_basic_l_max_use = kernel_basic_l_max_use;
parameter.kernel_basic_l_max_ext = ceil(1.25*parameter.kernel_basic_l_max_use);
parameter.kernel_basic_l_max_band = floor(parameter.kernel_basic_l_max_use/2)-1;
parameter.flag_kernel_full = 1; %<-- if set to 1 then use basic. ;
[ ...
 ~ ...
,KAPPA ...
,qref_k_eq_d ...
,qref_n_shell ...
,qref_azimu_b_shell_ ...
,qref_polar_a_shell_ ...
,qref_weight_shell_ ...
,qref_k_c_0_shell_ ...
,qref_k_c_1_shell_ ...
,qref_k_c_2_shell_ ...
,qref_n_polar_a ...
,qref_polar_a_ ...
,qref_n_azimu_b_ ...
] = ...
kappa_basic_1( ...
 parameter ...
);
%%%%%%%%;
flag_verbose = 1; flag_disp = 1; nf=0;
l_max = KAPPA.l_max_use;
l_max_band = KAPPA.l_max_band;
Rz = KAPPA.Rz;
dRz = KAPPA.dRz;
Ry = KAPPA.Ry;
dRy = KAPPA.dRy;
kappa_norm_ = KAPPA.kappa_norm_;
flag_kernel_full = KAPPA.flag_kernel_full;
n_nearest_total = KAPPA.n_nearest_total;
qref_k_eq_d = KAPPA.qref_k_eq_d;
qref_n_shell = KAPPA.qref_n_shell;
qref_azimu_b_shell_ = KAPPA.qref_azimu_b_shell_;
qref_polar_a_shell_ = KAPPA.qref_polar_a_shell_;
qref_weight_shell_ = KAPPA.qref_weight_shell_;
qref_k_c_0_shell_ = KAPPA.qref_k_c_0_shell_;
qref_k_c_1_shell_ = KAPPA.qref_k_c_1_shell_;
qref_k_c_2_shell_ = KAPPA.qref_k_c_2_shell_;
qref_n_polar_a = KAPPA.qref_n_polar_a;
qref_polar_a_ = KAPPA.qref_polar_a_;
qref_n_azimu_b_ = KAPPA.qref_n_azimu_b_;
qref_k_c_qc__ = KAPPA.qref_k_c_qc__;
a_full_node_ = KAPPA.a_full_node_;
n_a_use = numel(a_full_node_);
chebfun_kernel_norm_ = KAPPA.chebfun_kernel_norm_;
if (flag_verbose>0);
  disp(sprintf(' %% KAPPA.qref_k_eq_d %+0.6f',KAPPA.qref_k_eq_d));
  disp(sprintf(' %% KAPPA.n_nearest_total %+0.6f',KAPPA.n_nearest_total));
  disp(sprintf(' %% KAPPA.qref_n_shell %+0.6f',KAPPA.qref_n_shell));
  disp(sprintf(' %% KAPPA.qref_n_polar_a %+0.6f',KAPPA.qref_n_polar_a));
end;%if (flag_verbose>0);
%%%%;
% build grid on shell. ;
%%%%;
k_p_r_max = 48.0/(2*pi);
n_k_p_r = 1; k_p_r_1 = 1.0; k_p_r_ = k_p_r_1;
k_eq_d = KAPPA.qref_k_eq_d;
n_shell = KAPPA.qref_n_shell;
azimu_b_shell_ = KAPPA.qref_azimu_b_shell_;
polar_a_shell_ = KAPPA.qref_polar_a_shell_;
weight_shell_ = KAPPA.qref_weight_shell_;
k_c_0_shell_ = KAPPA.qref_k_c_0_shell_;
k_c_1_shell_ = KAPPA.qref_k_c_1_shell_;
k_c_2_shell_ = KAPPA.qref_k_c_2_shell_;
k_p_r_shell_ = k_p_r_(1+0)*ones(n_shell,1);

%%%%%%%%;
% set up Y_lm indices. ;
%%%%%%%%;
n_lm = (l_max+1).^2;
m_max_ = -l_max : +l_max;
n_m_max = length(m_max_);
Y_l_val_ = zeros(n_lm,1);
Y_m_val_ = zeros(n_lm,1);
tmp_l_val_ = zeros(n_lm,1);
tmp_m_val_ = zeros(n_lm,1);
na=0; 
for l_val=0:l_max;
for m_val=-l_val:+l_val;
tmp_l_val_(1+na) = l_val;
tmp_m_val_(1+na) = m_val;
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
tmp_index_ = 0:n_lm-1;
Y_l_val_(1+tmp_index_) = tmp_l_val_;
Y_m_val_(1+tmp_index_) = tmp_m_val_;
weight_Y_ = ones(n_lm,1);
weight_3d_k_p_r_ = 4*pi;
%%%%%%%%;
% build Ylm_weight_yq__. ;
%%%%%%%%;
tmp_t = tic();
Ylm__ = get_Ylm__(1+l_max,0:l_max,qref_n_shell,qref_azimu_b_shell_,qref_polar_a_shell_);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% get_Ylm__: %0.2fs',tmp_t)); end;
tmp_t = tic();
Ylm_yq__ = zeros(n_lm,qref_n_shell);
nml=0;
for l_val=0:l_max;
for m_val=-l_val:+l_val;
Y_l_val_(1+nml) = l_val;
Y_m_val_(1+nml) = m_val;
Ylm_yq__(1+nml,:) = Ylm__{1+l_val}(1+l_val+m_val,:);
nml=nml+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
Ylm_weight_yq__ = Ylm_yq__ * sparse(1:qref_n_shell,1:qref_n_shell,qref_weight_shell_,qref_n_shell,qref_n_shell);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% Ylm_weight_yq__: %0.2fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
a_deltafunct_I_I_k_Y_lm_ = sqrt(2*pi)*sqrt(4*pi)*sqrt(1+2*Y_l_val_).*(Y_m_val_==0);
if ~exist('Ylm_uklma___','var'); Ylm_uklma___=[]; end;
if ~exist('k_p_azimu_b_sub_uka__','var'); k_p_azimu_b_sub_uka__ = []; end;
if ~exist('k_p_polar_a_sub_uka__','var'); k_p_polar_a_sub_uka__ = []; end;
if ~exist('l_max_uk_','var'); l_max_uk_ = []; end;
if ~exist('index_nu_n_k_per_shell_from_nk_p_r_','var'); index_nu_n_k_per_shell_from_nk_p_r_ = []; end;
if ~exist('index_k_per_shell_uka__','var'); index_k_per_shell_uka__ = []; end;
[ ...
 a_deltafunct_I_I_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_spharm_to_k_p_4( ...
 flag_verbose ...
,n_shell ...
,[0,n_shell] ...
,k_p_r_shell_ ...
,azimu_b_shell_ ...
,polar_a_shell_ ...
,weight_3d_k_p_r_ ...
,weight_shell_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max ...
,a_deltafunct_I_I_k_Y_lm_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
%%%%%%%%;

%%%%%%%%;
a_deltafunct_band_I_I_k_Y_lm_ = sqrt(2*pi)*sqrt(4*pi)*sqrt(1+2*Y_l_val_).*(Y_m_val_==0).*(Y_l_val_<=kernel_basic_l_max_band);
if ~exist('Ylm_uklma___','var'); Ylm_uklma___=[]; end;
if ~exist('k_p_azimu_b_sub_uka__','var'); k_p_azimu_b_sub_uka__ = []; end;
if ~exist('k_p_polar_a_sub_uka__','var'); k_p_polar_a_sub_uka__ = []; end;
if ~exist('l_max_uk_','var'); l_max_uk_ = []; end;
if ~exist('index_nu_n_k_per_shell_from_nk_p_r_','var'); index_nu_n_k_per_shell_from_nk_p_r_ = []; end;
if ~exist('index_k_per_shell_uka__','var'); index_k_per_shell_uka__ = []; end;
[ ...
 a_deltafunct_band_I_I_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
] = ...
convert_spharm_to_k_p_4( ...
 flag_verbose ...
,n_shell ...
,[0,n_shell] ...
,k_p_r_shell_ ...
,azimu_b_shell_ ...
,polar_a_shell_ ...
,weight_3d_k_p_r_ ...
,weight_shell_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max ...
,a_deltafunct_band_I_I_k_Y_lm_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
%%%%%%%%;

%%%%%%%%;
kernel_basic_k_Y_form_ = zeros(n_lm,1);
kernel_basic_k_Y_form_(1+l_val_.^2 + l_val_) = kappa_norm_(1+l_val_);
%%%%;
deconvolve_lm_ = (sqrt(4*pi)*sqrt(1+2*Y_l_val_).*(Y_l_val_<=kernel_basic_l_max_band))./max(1e-12,kappa_norm_(1+Y_l_val_));
if flag_disp;
figure(1+nf);nf=nf+1;clf;figsml;
linewidth_use = 3;
plot(Y_l_val_,log(deconvolve_lm_),'k.','LineWidth',linewidth_use);
xlabel('Y_l_val_','Interpreter','none');
ylabel('log(deconvolve_lm_)','Interpreter','none');
grid on;
end;%if flag_disp;
%%%%;
[ ...
 kernel_basic_k_p_quad_ ...
] = ...
convert_spharm_to_k_p_4( ...
 flag_verbose ...
,n_shell ...
,[0,n_shell] ...
,k_p_r_shell_ ...
,azimu_b_shell_ ...
,polar_a_shell_ ...
,weight_3d_k_p_r_ ...
,weight_shell_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max ...
,kernel_basic_k_Y_form_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
if (flag_verbose>0); disp(sprintf(' %% sum(kernel_basic_k_p_quad_.*weight_shell_): %0.6f',sum(kernel_basic_k_p_quad_.*weight_shell_))); end;
fnorm_disp(flag_verbose,'chebfun_kernel_norm_(cos(polar_a_shell_))',chebfun_kernel_norm_(cos(polar_a_shell_)),'kernel_basic_k_p_quad_*sqrt(2*pi)',kernel_basic_k_p_quad_*sqrt(2*pi));
[ ...
 kernel_basic_k_Y_quad_ ...
] = ...
convert_k_p_to_spharm_4( ...
 flag_verbose ...
,n_shell ...
,[0,n_shell] ...
,k_p_r_shell_ ...
,azimu_b_shell_ ...
,polar_a_shell_ ...
,weight_3d_k_p_r_ ...
,weight_shell_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max ...
,kernel_basic_k_p_quad_ ...
,Ylm_uklma___ ...
,k_p_azimu_b_sub_uka__ ...
,k_p_polar_a_sub_uka__ ...
,l_max_uk_ ...
,index_nu_n_k_per_shell_from_nk_p_r_ ...
,index_k_per_shell_uka__ ...
);
fnorm_disp(flag_verbose,'kernel_basic_k_Y_form_',kernel_basic_k_Y_form_,'kernel_basic_k_Y_quad_',kernel_basic_k_Y_quad_);
if flag_disp;
figure(1+nf);nf=nf+1;clf;figsml;
klim_ = [0,prctile(chebfun_kernel_norm_(cos(a_full_node_)),99.5)];
flag_2d_vs_3d = 0;
imagesc_polar_a_azimu_b_0( ...
 polar_a_shell_ ... 
,azimu_b_shell_ ... 
,real(kernel_basic_k_p_quad_) ... 
,klim_ ... 
,colormap_81s ... 
,flag_2d_vs_3d ...
,k_p_r_1 ...
);
title('real(kernel_basic_k_p_quad_)','Interpreter','none');
end;%if flag_disp;

%%%%;
% Now we place a point-source (i.e., delta-function) somewhere on the sphere, ;
% mollify it via the kernel_basic_, ;
% then apply quadrature to calculate the associated spherical-harmonics, ;
% then compare the result with the rotated kernel. ;
%%%%;
% For this calculation we use the default quadrature-reference grid (qref). ;
%%%%;
tmp_I__ = eye(3,3);
tmp_I_pole_ = tmp_I__*[0;0;1];
tmp_I_d2_ = (qref_k_c_0_shell_ - tmp_I_pole_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_I_pole_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_I_pole_(1+2)).^2 ;
tmp_I_arc_ = acos(1-tmp_I_d2_/2);
tmp_I_ker_ = chebfun_kernel_norm_(cos(tmp_I_arc_));
tmp_euler_a = -3*pi/8;
tmp_euler_b = pi/12;
tmp_euler_c = pi/4;
tmp_R__ = Rz(tmp_euler_b)*Ry(tmp_euler_a)*Rz(tmp_euler_c);
tmp_R_pole_ = tmp_R__*[0;0;1];
tmp_R_d2_ = (qref_k_c_0_shell_ - tmp_R_pole_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_R_pole_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_R_pole_(1+2)).^2 ;
tmp_R_arc_ = acos(1-tmp_R_d2_/2);
tmp_R_ker_ = chebfun_kernel_norm_(cos(tmp_R_arc_));
fnorm_disp(flag_verbose,'tmp_R_ker_',tmp_R_ker_,'chebfun_kernel_norm_(1-tmp_R_d2_/2)',chebfun_kernel_norm_(1-tmp_R_d2_/2));
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;
p_row = 1; p_col = 3; np=0;
subplot(p_row,p_col,1+np);np=np+1;
alim_ = [0,prctile(tmp_R_arc_,99.5)];
imagesc_polar_a_azimu_b_0( ...
 qref_polar_a_shell_ ... 
,qref_azimu_b_shell_ ... 
,real(tmp_R_arc_) ... 
,alim_ ... 
,colormap_81s ... 
,flag_2d_vs_3d ...
,k_p_r_1 ...
);
hold on;
plot3(tmp_R_pole_(1+0),tmp_R_pole_(1+1),tmp_R_pole_(1+2),'wo','MarkerFaceColor','g');
hold off;
title('real(tmp_R_arc_)','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;
klim_ = prctile(chebfun_kernel_norm_(cos(a_full_node_)),75)*[-1,+1];
imagesc_polar_a_azimu_b_0( ...
 qref_polar_a_shell_ ... 
,qref_azimu_b_shell_ ... 
,real(tmp_I_ker_) ... 
,klim_ ... 
,colormap_80s ... 
,flag_2d_vs_3d ...
,k_p_r_1 ...
);
hold on;
plot3(tmp_I_pole_(1+0),tmp_I_pole_(1+1),tmp_I_pole_(1+2),'wo','MarkerFaceColor','g');
hold off;
title('real(tmp_I_ker_)','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;
klim_ = prctile(chebfun_kernel_norm_(cos(a_full_node_)),75)*[-1,+1];
imagesc_polar_a_azimu_b_0( ...
 qref_polar_a_shell_ ... 
,qref_azimu_b_shell_ ... 
,real(tmp_R_ker_) ...
,klim_ ... 
,colormap_80s ... 
,flag_2d_vs_3d ...
,k_p_r_1 ...
);
hold on;
plot3(tmp_R_pole_(1+0),tmp_R_pole_(1+1),tmp_R_pole_(1+2),'wo','MarkerFaceColor','g');
hold off;
title('real(tmp_R_ker_)','Interpreter','none');
end;%if flag_disp;
%%%%;
a_I_I_k_Y_lm_ = conj(Ylm_weight_yq__)*tmp_I_ker_;
a_I_R_k_Y_lm_ = conj(Ylm_weight_yq__)*tmp_R_ker_;
tmp_euler_ = [tmp_euler_b,tmp_euler_a,tmp_euler_c];
tmp_euler_pos_ = [tmp_euler_c,tmp_euler_a,tmp_euler_b]; tmp_euler_neg_ = -flip(tmp_euler_pos_);
a_R_I_k_Y_lm_ = rotate_spharm_to_spharm_3(1,1,l_max,a_I_I_k_Y_lm_,tmp_euler_pos_);
a_R_R_k_Y_lm_ = rotate_spharm_to_spharm_3(1,1,l_max,a_I_R_k_Y_lm_,tmp_euler_neg_);
fnorm_disp(flag_verbose,'a_R_I_k_Y_lm_',a_R_I_k_Y_lm_,'a_I_R_k_Y_lm_',a_I_R_k_Y_lm_);
fnorm_disp(flag_verbose,'a_I_I_k_Y_lm_',a_I_I_k_Y_lm_,'a_R_R_k_Y_lm_',a_R_R_k_Y_lm_);
%%%%;

%%%%;
% Now we continue the above experiment: ;
% place a point-source (i.e., delta-function) somewhere on the sphere, ;
% mollify it via the kernel_basic_, ;
% then apply quadrature to calculate the associated spherical-harmonics, ;
% then deconvolve by the scaling associated with kernel_basic_, ;
% then compare the result with the rotated kernel. ;
%%%%;
tmp_euler_ = [tmp_euler_b,tmp_euler_a,tmp_euler_c];
tmp_euler_pos_ = [tmp_euler_c,tmp_euler_a,tmp_euler_b]; tmp_euler_neg_ = -flip(tmp_euler_pos_);
a_deltafunct_band_R_I_k_Y_lm_ = rotate_spharm_to_spharm_3(1,1,l_max,a_deltafunct_band_I_I_k_Y_lm_,tmp_euler_pos_);
a_deltafunct_band_I_R_k_Y_lm_ = a_deltafunct_band_R_I_k_Y_lm_; %<-- use formula. ;
a_deltafunct_band_R_R_k_Y_lm_ = rotate_spharm_to_spharm_3(1,1,l_max,a_deltafunct_band_I_R_k_Y_lm_,tmp_euler_neg_);
fnorm_disp(flag_verbose,'a_deltafunct_band_I_I_k_Y_lm_',a_deltafunct_band_I_I_k_Y_lm_,'a_deltafunct_band_R_R_k_Y_lm_',a_deltafunct_band_R_R_k_Y_lm_);
a_deconvolve_I_I_k_Y_lm_ = a_I_I_k_Y_lm_.*deconvolve_lm_;
a_deconvolve_I_R_k_Y_lm_ = a_I_R_k_Y_lm_.*deconvolve_lm_;
a_deconvolve_R_I_k_Y_lm_ = a_R_I_k_Y_lm_.*deconvolve_lm_;
a_deconvolve_R_R_k_Y_lm_ = a_R_R_k_Y_lm_.*deconvolve_lm_;
fnorm_disp(flag_verbose,'a_deltafunct_band_I_I_k_Y_lm_',a_deltafunct_band_I_I_k_Y_lm_,'a_deconvolve_I_I_k_Y_lm_',a_deconvolve_I_I_k_Y_lm_);
fnorm_disp(flag_verbose,'a_deltafunct_band_I_R_k_Y_lm_',a_deltafunct_band_I_R_k_Y_lm_,'a_deconvolve_I_R_k_Y_lm_',a_deconvolve_I_R_k_Y_lm_);
fnorm_disp(flag_verbose,'a_deltafunct_band_R_I_k_Y_lm_',a_deltafunct_band_R_I_k_Y_lm_,'a_deconvolve_R_I_k_Y_lm_',a_deconvolve_R_I_k_Y_lm_);
fnorm_disp(flag_verbose,'a_deltafunct_band_R_R_k_Y_lm_',a_deltafunct_band_R_R_k_Y_lm_,'a_deconvolve_R_R_k_Y_lm_',a_deconvolve_R_R_k_Y_lm_);
%%%%%%%%;
if (flag_disp);
figure(1+nf);nf=nf+1;clf;figsml;
p_row = 1; p_col = 1; np=0;
deltafunct_band_lim_ = [0,prctile(a_deltafunct_band_I_I_k_p_quad_,99.5)];
subplot(p_row,p_col,1+np);np=np+1;
flag_2d_vs_3d = 0;
k_p_r_max = 1;
imagesc_polar_a_azimu_b_0( ...
 polar_a_shell_ ... 
,azimu_b_shell_ ... 
,a_deltafunct_band_I_I_k_p_quad_ ... 
,deltafunct_band_lim_ ... 
,colormap_81s ... 
,flag_2d_vs_3d ...
,k_p_r_max ...
);
axisnotick3d; axis vis3d;
title('deltafunct_band_I_I_k_p_form_','Interpreter','none');
end;%if (flag_disp);
%%%%%%%%;

%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% testing first-derivative')); end;
%%%%%%%%;
tmp_I__ = eye(3,3);
tmp_I_pole_ = tmp_I__*[0;0;1];
tmp_I_d2_ = (qref_k_c_0_shell_ - tmp_I_pole_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_I_pole_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_I_pole_(1+2)).^2 ;
tmp_I_arc_ = acos(1-tmp_I_d2_/2);
tmp_I_ker_ = chebfun_kernel_norm_(cos(tmp_I_arc_));
%%%%;
tmp_euler_a = -3*pi/8;
tmp_euler_b = pi/12;
tmp_euler_c = pi/4;
tmp_R__ = Rz(tmp_euler_b)*Ry(tmp_euler_a)*Rz(tmp_euler_c);
tmp_R_pole_ = tmp_R__*[0;0;1];
tmp_R_d2_ = (qref_k_c_0_shell_ - tmp_R_pole_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_R_pole_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_R_pole_(1+2)).^2 ;
tmp_R_arc_ = acos(1-tmp_R_d2_/2);
tmp_R_ker_ = chebfun_kernel_norm_(cos(tmp_R_arc_));
%%%%;
da = +0.65*1e-4;
db = -1.00*1e-4;
dc = +0.25*1e-4;
tmp_dRda__ = Rz(tmp_euler_b)*dRy(tmp_euler_a)*Rz(tmp_euler_c);
tmp_dRdb__ = dRz(tmp_euler_b)*Ry(tmp_euler_a)*Rz(tmp_euler_c);
tmp_dRdc__ = Rz(tmp_euler_b)*Ry(tmp_euler_a)*dRz(tmp_euler_c);
tmp_dR_mid__ = (tmp_dRda__*da + tmp_dRdb__*db + tmp_dRdc__*dc)/max(1e-12,fnorm([da;db;dc]));
tmp_R_pos__ = Rz(tmp_euler_b+db)*Ry(tmp_euler_a+da)*Rz(tmp_euler_c+dc);
tmp_R_neg__ = Rz(tmp_euler_b-db)*Ry(tmp_euler_a-da)*Rz(tmp_euler_c-dc);
tmp_dR_dif__ = (tmp_R_pos__ - tmp_R_neg__)/max(1e-12,2*fnorm([da;db;dc]));;
fnorm_disp(flag_verbose,'tmp_dR_dif__',tmp_dR_dif__,'tmp_dR_mid__',tmp_dR_mid__);
tmp_R_pos_pole_ = tmp_R_pos__*[0;0;1];
tmp_R_neg_pole_ = tmp_R_neg__*[0;0;1];
tmp_dRda_pole_ = tmp_dRda__*[0;0;1];
tmp_dRdb_pole_ = tmp_dRdb__*[0;0;1];
tmp_dRdc_pole_ = tmp_dRdc__*[0;0;1];
tmp_dR_mid_d2_ = ...
 - 2*(qref_k_c_0_shell_ - tmp_R_pole_(1+0)).*(tmp_dRda_pole_(1+0)*da + tmp_dRdb_pole_(1+0)*db + tmp_dRdc_pole_(1+0)*dc) ...
 - 2*(qref_k_c_1_shell_ - tmp_R_pole_(1+1)).*(tmp_dRda_pole_(1+1)*da + tmp_dRdb_pole_(1+1)*db + tmp_dRdc_pole_(1+1)*dc) ...
 - 2*(qref_k_c_2_shell_ - tmp_R_pole_(1+2)).*(tmp_dRda_pole_(1+2)*da + tmp_dRdb_pole_(1+2)*db + tmp_dRdc_pole_(1+2)*dc) ...
;
tmp_R_pos_d2_ = (qref_k_c_0_shell_ - tmp_R_pos_pole_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_R_pos_pole_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_R_pos_pole_(1+2)).^2 ;
tmp_R_neg_d2_ = (qref_k_c_0_shell_ - tmp_R_neg_pole_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_R_neg_pole_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_R_neg_pole_(1+2)).^2 ;
tmp_dR_dif_d2_ = (tmp_R_pos_d2_ - tmp_R_neg_d2_)/2;
fnorm_disp(flag_verbose,'tmp_dR_dif_d2_',tmp_dR_dif_d2_,'tmp_dR_mid_d2_',tmp_dR_mid_d2_);
dchebfun_kernel_norm_ = diff(chebfun_kernel_norm_);
tmp_dR_mid_ker_ = -dchebfun_kernel_norm_(1-tmp_R_d2_/2).*tmp_dR_mid_d2_/2;
tmp_R_pos_ker_ = chebfun_kernel_norm_(1-tmp_R_pos_d2_/2);
tmp_R_neg_ker_ = chebfun_kernel_norm_(1-tmp_R_neg_d2_/2);
tmp_dR_dif_ker_ = (tmp_R_pos_ker_ - tmp_R_neg_ker_)/2;
fnorm_disp(flag_verbose,'tmp_dR_dif_ker_',tmp_dR_dif_ker_,'tmp_dR_mid_ker_',tmp_dR_mid_ker_);
%%%%;
a_I_dR_mid_k_Y_lm_ = conj(Ylm_weight_yq__)*tmp_dR_mid_ker_;
a_I_R_pos_k_Y_lm_ = conj(Ylm_weight_yq__)*tmp_R_pos_ker_;
a_I_R_neg_k_Y_lm_ = conj(Ylm_weight_yq__)*tmp_R_neg_ker_;
a_I_dR_dif_k_Y_lm_ = (a_I_R_pos_k_Y_lm_ - a_I_R_neg_k_Y_lm_)/2;
fnorm_disp(flag_verbose,'a_I_dR_dif_k_Y_lm_',a_I_dR_dif_k_Y_lm_,'a_I_dR_mid_k_Y_lm_',a_I_dR_mid_k_Y_lm_);
%%%%;
a_deconvolve_I_dR_mid_k_Y_lm_ = a_I_dR_mid_k_Y_lm_.*deconvolve_lm_;
a_deconvolve_I_R_pos_k_Y_lm_ = a_I_R_pos_k_Y_lm_.*deconvolve_lm_;
a_deconvolve_I_R_neg_k_Y_lm_ = a_I_R_neg_k_Y_lm_.*deconvolve_lm_;
a_deconvolve_I_dR_dif_k_Y_lm_ = (a_deconvolve_I_R_pos_k_Y_lm_ - a_deconvolve_I_R_neg_k_Y_lm_)/2;
fnorm_disp(flag_verbose,'a_deconvolve_I_dR_dif_k_Y_lm_',a_deconvolve_I_dR_dif_k_Y_lm_,'a_deconvolve_I_dR_mid_k_Y_lm_',a_deconvolve_I_dR_mid_k_Y_lm_);
%%%%%%%%;

n_q = qref_n_shell; n_3 = 3; deconvolve_q = sqrt(4*pi);
%%%%%%%%;
% Now testing with image-data. ;
%%%%%%%%;
n_M = 4;
n_w = 98;
rng(0);
viewing_polar_a_M_ = 2*pi*rand(n_M,1);
viewing_azimu_b_M_ = 2*pi*rand(n_M,1);
viewing_gamma_z_M_ = 2*pi*rand(n_M,1);
[ ...
 k_p_polar_a_wM__ ...
,k_p_azimu_b_wM__ ...
,k_c_0_wM__ ...
,k_c_1_wM__ ...
,k_c_2_wM__ ...
,k_p_r01_wM__ ...
,dtau_k_p_polar_a_wM3___ ...
,dtau_k_p_azimu_b_wM3___ ...
,dtau_k_c_0_wM3___ ...
,dtau_k_c_1_wM3___ ...
,dtau_k_c_2_wM3___ ...
,dtau_k_p_r01_wM3___ ...
,dtau_dtau_k_p_polar_a_wM33____ ...
,dtau_dtau_k_p_azimu_b_wM33____ ...
,dtau_dtau_k_c_0_wM33____ ...
,dtau_dtau_k_c_1_wM33____ ...
,dtau_dtau_k_c_2_wM33____ ...
,dtau_dtau_k_p_r01_wM33____ ...
] = ...
cg_rhs_2( ...
 n_M ...
,n_w ...
,viewing_polar_a_M_ ...
,viewing_azimu_b_M_ ...
,viewing_gamma_z_M_ ...
);
data_k_c_wMc__ = [ k_c_0_wM__(:) , k_c_1_wM__(:) , k_c_2_wM__(:) ];
%%%%;
tmp_error = 0;
for nM=0:n_M-1; for nw=0:n_w-1;
tmp_euler_a = +viewing_polar_a_M_(1+nM); tmp_euler_b = +viewing_azimu_b_M_(1+nM); tmp_euler_c = -viewing_gamma_z_M_(1+nM) + (2*pi*nw)/n_w ;
tmp_R__ = Rz(tmp_euler_b)*Ry(tmp_euler_a)*Rz(tmp_euler_c);
tmp_R_point_k_c_ = tmp_R__*[1;0;0];
tmp_diff_ = data_k_c_wMc__(1+nw+nM*n_w,:) - reshape(tmp_R_point_k_c_,[1,n_3]);
tmp_error = tmp_error + fnorm(tmp_diff_);
end;end;%for nw=0:n_w-1; for nM=0:n_M-1;
if (flag_verbose>0); disp(sprintf(' %% data_k_c_wMc__ error: %0.16f',tmp_error)); end;
%%%%%%%%;
d2_full_wMq__ = sum(bsxfun(@minus,reshape(qref_k_c_qc__,[1,n_q,n_3]),reshape(+data_k_c_wMc__,[n_w*n_M,1,n_3])).^2,3);
d1_full_wMq__ = sqrt(d2_full_wMq__);
mollify_qref_from_data_wMq__ = chebfun_kernel_norm_(1-d2_full_wMq__/2);
index_qref_wMq__ = repmat([0:n_q-1],[n_w*n_M,1]);
index_data_wMq__ = repmat(transpose(0:n_w*n_M-1),[1,n_q]);
qref_from_data_qwM__ = sparse(1+index_qref_wMq__(:),1+index_data_wMq__(:),mollify_qref_from_data_wMq__,n_q,n_w*n_M);
%%%%%%%%;
rng(0);
T_k_p_wM__ = randn(n_w,n_M); T_k_p_wM_ = reshape(T_k_p_wM__,[n_w*n_M,1]);
T_k_p_q_ = qref_from_data_qwM__*T_k_p_wM_;
T_restore_k_p_q_ = T_k_p_q_.*deconvolve_q;
T_k_Y_lm_ = conj(Ylm_weight_yq__)*T_k_p_q_;
T_restore_k_Y_lm_ = T_k_Y_lm_.*deconvolve_lm_;
%%%%;
R_k_p_q_ = zeros(qref_n_shell,1);
for nM=0:n_M-1; for nw=0:n_w-1;
tmp_euler_a = +viewing_polar_a_M_(1+nM); tmp_euler_b = +viewing_azimu_b_M_(1+nM); tmp_euler_c = -viewing_gamma_z_M_(1+nM) + (2*pi*nw)/n_w ;
tmp_R__ = Rz(tmp_euler_b)*Ry(tmp_euler_a)*Rz(tmp_euler_c); tmp_R_point_k_c_ = tmp_R__*[1;0;0];
tmp_R_d2_ = (qref_k_c_0_shell_ - tmp_R_point_k_c_(1+0)).^2 + (qref_k_c_1_shell_ - tmp_R_point_k_c_(1+1)).^2 + (qref_k_c_2_shell_ - tmp_R_point_k_c_(1+2)).^2 ;
R_k_p_q_ = R_k_p_q_ + T_k_p_wM_(1+nw+nM*n_w)*chebfun_kernel_norm_(1-tmp_R_d2_/2);
end;end;%for nw=0:n_w-1; for nM=0:n_M-1;
R_restore_k_p_q_ = R_k_p_q_.*deconvolve_q;
R_k_Y_lm_ = conj(Ylm_weight_yq__)*R_k_p_q_;
R_restore_k_Y_lm_ = R_k_Y_lm_.*deconvolve_lm_;
fnorm_disp(flag_verbose,'T_k_p_q_',T_k_p_q_,'R_k_p_q_',R_k_p_q_);
fnorm_disp(flag_verbose,'T_k_Y_lm_',T_k_Y_lm_,'R_k_Y_lm_',R_k_Y_lm_);
fnorm_disp(flag_verbose,'T_restore_k_Y_lm_',T_restore_k_Y_lm_,'R_restore_k_Y_lm_',R_restore_k_Y_lm_);
%%%%;

%%%%%%%%;
% reconstructing with kappa_basic_apply_4. ;
%%%%%%%%;
KAPPA = [];
n_w_max = n_w;
weight_imagecount_M_ = [];
M_k_p_wkM__ = T_k_p_wM__;
n_CTF = [];
index_nCTF_from_nM_ = [];
CTF_k_p_wkC__ = [];
rng(1);
dtau_viewing_polar_a_M_ = 2*pi*rand(n_M,1);
dtau_viewing_azimu_b_M_ = 2*pi*rand(n_M,1);
dtau_viewing_gamma_z_M_ = 2*pi*rand(n_M,1);
[ ...
 parameter ...
,KAPPA ...
,a_restore_mid_C2M0_k_p_q_ ...
,a_restore_mid_C1M1_k_p_q_ ...
,a_restore_mid_C0M2_k_p_q_ ...
,dtau_a_restore_mid_C2M0_k_p_q_ ...
,dtau_a_restore_mid_C1M1_k_p_q_ ...
,dtau_a_restore_mid_C0M2_k_p_q_ ...
,dtau_dtau_a_restore_mid_C2M0_k_p_q_ ...
,dtau_dtau_a_restore_mid_C1M1_k_p_q_ ...
,dtau_dtau_a_restore_mid_C0M2_k_p_q_ ...
] = ...
kappa_basic_apply_4( ...
 parameter ...
,KAPPA ...
,n_w_max ...
,n_M ...
,weight_imagecount_M_ ...
,viewing_polar_a_M_ ...
,viewing_azimu_b_M_ ...
,viewing_gamma_z_M_ ...
,dtau_viewing_polar_a_M_ ...
,dtau_viewing_azimu_b_M_ ...
,dtau_viewing_gamma_z_M_ ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,qref_k_eq_d ...
,qref_n_shell ...
,qref_azimu_b_shell_ ...
,qref_polar_a_shell_ ...
,qref_weight_shell_ ...
,qref_k_c_0_shell_ ...
,qref_k_c_1_shell_ ...
,qref_k_c_2_shell_ ...
,qref_n_polar_a ...
,qref_polar_a_ ...
,qref_n_azimu_b_ ...
);
fnorm_disp(flag_verbose,'T_restore_k_p_q_',T_restore_k_p_q_,'a_restore_mid_C1M1_k_p_q_*n_w_max/(2*pi)',a_restore_mid_C1M1_k_p_q_*n_w_max/(2*pi));
%%%%%%%%;

%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% testing first-derivative (directional derivative only)')); end;
%%%%%%%%;
dtau = 1e-4;
parameter.flag_recalc_qref_from_data = 1;
parameter.flag_recalc_dtau_qref_from_data = 0;
parameter.flag_recalc_dtau_dtau_qref_from_data = 0;
[ ...
 ~ ...
,~ ...
,a_restore_pos_C2M0_k_p_q_ ...
,a_restore_pos_C1M1_k_p_q_ ...
,a_restore_pos_C0M2_k_p_q_ ...
] = ...
kappa_basic_apply_4( ...
 parameter ...
,KAPPA ...
,n_w_max ...
,n_M ...
,weight_imagecount_M_ ...
,viewing_polar_a_M_ + dtau*dtau_viewing_polar_a_M_ ...
,viewing_azimu_b_M_ + dtau*dtau_viewing_azimu_b_M_ ...
,viewing_gamma_z_M_ + dtau*dtau_viewing_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
);
parameter.flag_recalc_qref_from_data = 1;
parameter.flag_recalc_dtau_qref_from_data = 0;
parameter.flag_recalc_dtau_dtau_qref_from_data = 0;
[ ...
 ~ ...
,~ ...
,a_restore_neg_C2M0_k_p_q_ ...
,a_restore_neg_C1M1_k_p_q_ ...
,a_restore_neg_C0M2_k_p_q_ ...
] = ...
kappa_basic_apply_4( ...
 parameter ...
,KAPPA ...
,n_w_max ...
,n_M ...
,weight_imagecount_M_ ...
,viewing_polar_a_M_ - dtau*dtau_viewing_polar_a_M_ ...
,viewing_azimu_b_M_ - dtau*dtau_viewing_azimu_b_M_ ...
,viewing_gamma_z_M_ - dtau*dtau_viewing_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
);
%%%%%%%%;

dtau_a_restore_dif_C2M0_k_p_q_ = (a_restore_pos_C2M0_k_p_q_ - a_restore_neg_C2M0_k_p_q_)/max(1e-12,2*dtau);
dtau_a_restore_dif_C1M1_k_p_q_ = (a_restore_pos_C1M1_k_p_q_ - a_restore_neg_C1M1_k_p_q_)/max(1e-12,2*dtau);
dtau_a_restore_dif_C0M2_k_p_q_ = (a_restore_pos_C0M2_k_p_q_ - a_restore_neg_C0M2_k_p_q_)/max(1e-12,2*dtau);
fnorm_disp(flag_verbose,'dtau_a_restore_dif_C2M0_k_p_q_',dtau_a_restore_dif_C2M0_k_p_q_,'dtau_a_restore_mid_C2M0_k_p_q_',dtau_a_restore_mid_C2M0_k_p_q_);
fnorm_disp(flag_verbose,'dtau_a_restore_dif_C1M1_k_p_q_',dtau_a_restore_dif_C1M1_k_p_q_,'dtau_a_restore_mid_C1M1_k_p_q_',dtau_a_restore_mid_C1M1_k_p_q_);
fnorm_disp(flag_verbose,'dtau_a_restore_dif_C0M2_k_p_q_',dtau_a_restore_dif_C0M2_k_p_q_,'dtau_a_restore_mid_C0M2_k_p_q_',dtau_a_restore_mid_C0M2_k_p_q_);
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figbig;
p_row=2; p_col=3; np=0;
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
plot(qref_polar_a_shell_,log10(abs(dtau_a_restore_dif_C2M0_k_p_q_-dtau_a_restore_mid_C2M0_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(error))','Interpreter','none');
title('log10(abs(dtau C2M0 error))','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;cla;
plot(qref_polar_a_shell_,log10(abs(dtau_a_restore_dif_C2M0_k_p_q_-dtau_a_restore_mid_C2M0_k_p_q_)./abs(dtau_a_restore_dif_C2M0_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(relative C2M0 error))','Interpreter','none');
title('log10(abs(dtau C2M0 relative error))','Interpreter','none');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
plot(qref_polar_a_shell_,log10(abs(dtau_a_restore_dif_C1M1_k_p_q_-dtau_a_restore_mid_C1M1_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(error))','Interpreter','none');
title('log10(abs(dtau C1M1 error))','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;cla;
plot(qref_polar_a_shell_,log10(abs(dtau_a_restore_dif_C1M1_k_p_q_-dtau_a_restore_mid_C1M1_k_p_q_)./abs(dtau_a_restore_dif_C1M1_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(relative C1M1 error))','Interpreter','none');
title('log10(abs(dtau C1M1 relative error))','Interpreter','none');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
plot(qref_polar_a_shell_,log10(abs(dtau_a_restore_dif_C0M2_k_p_q_-dtau_a_restore_mid_C0M2_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(error))','Interpreter','none');
title('log10(abs(dtau C0M2 error))','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;cla;
plot(qref_polar_a_shell_,log10(abs(dtau_a_restore_dif_C0M2_k_p_q_-dtau_a_restore_mid_C0M2_k_p_q_)./abs(dtau_a_restore_dif_C0M2_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(relative C0M2 error))','Interpreter','none');
title('log10(abs(dtau C0M2 relative error))','Interpreter','none');
%%%%;
end;%if flag_disp;
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;
p_row = 1; p_col = 3; np=0;
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
hold on;
rlim_dif_ = prctile(real(dtau_a_restore_dif_C2M0_k_p_q_),[  0,100]); rlim_dif_ = mean(rlim_dif_) + 0.5*1.25*diff(rlim_dif_)*[-1,+1]; if diff(rlim_dif_)==0; rlim_dif_=[-1,+1]; end;
rlim_mid_ = prctile(real(dtau_a_restore_mid_C2M0_k_p_q_),[  0,100]); rlim_mid_ = mean(rlim_mid_) + 0.5*1.25*diff(rlim_mid_)*[-1,+1]; if diff(rlim_mid_)==0; rlim_mid_=[-1,+1]; end;
rlim_ = [min([rlim_dif_,rlim_mid_]),max([rlim_dif_,rlim_mid_])];
ilim_dif_ = prctile(imag(dtau_a_restore_dif_C2M0_k_p_q_),[  0,100]); ilim_dif_ = mean(ilim_dif_) + 0.5*1.25*diff(ilim_dif_)*[-1,+1]; if diff(ilim_dif_)==0; ilim_dif_=[-1,+1]; end;
ilim_mid_ = prctile(imag(dtau_a_restore_mid_C2M0_k_p_q_),[  0,100]); ilim_mid_ = mean(ilim_mid_) + 0.5*1.25*diff(ilim_mid_)*[-1,+1]; if diff(ilim_mid_)==0; ilim_mid_=[-1,+1]; end;
ilim_ = [min([ilim_dif_,ilim_mid_]),max([ilim_dif_,ilim_mid_])];
dlim_ = [min([rlim_,ilim_]),max([rlim_,ilim_])];
plot(dlim_,dlim_,'-','Color',0.85*[1,1,1]);
plot(real(dtau_a_restore_dif_C2M0_k_p_q_),real(dtau_a_restore_mid_C2M0_k_p_q_),'ro');
plot(imag(dtau_a_restore_dif_C2M0_k_p_q_),imag(dtau_a_restore_mid_C2M0_k_p_q_),'bx');
hold off;
xlim(dlim_); ylim(dlim_);
axisnotick;
xlabel('dif'); ylabel('mid');
title('C2M0');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
hold on;
rlim_dif_ = prctile(real(dtau_a_restore_dif_C1M1_k_p_q_),[  0,100]); rlim_dif_ = mean(rlim_dif_) + 0.5*1.25*diff(rlim_dif_)*[-1,+1]; if diff(rlim_dif_)==0; rlim_dif_=[-1,+1]; end;
rlim_mid_ = prctile(real(dtau_a_restore_mid_C1M1_k_p_q_),[  0,100]); rlim_mid_ = mean(rlim_mid_) + 0.5*1.25*diff(rlim_mid_)*[-1,+1]; if diff(rlim_mid_)==0; rlim_mid_=[-1,+1]; end;
rlim_ = [min([rlim_dif_,rlim_mid_]),max([rlim_dif_,rlim_mid_])];
ilim_dif_ = prctile(imag(dtau_a_restore_dif_C1M1_k_p_q_),[  0,100]); ilim_dif_ = mean(ilim_dif_) + 0.5*1.25*diff(ilim_dif_)*[-1,+1]; if diff(ilim_dif_)==0; ilim_dif_=[-1,+1]; end;
ilim_mid_ = prctile(imag(dtau_a_restore_mid_C1M1_k_p_q_),[  0,100]); ilim_mid_ = mean(ilim_mid_) + 0.5*1.25*diff(ilim_mid_)*[-1,+1]; if diff(ilim_mid_)==0; ilim_mid_=[-1,+1]; end;
ilim_ = [min([ilim_dif_,ilim_mid_]),max([ilim_dif_,ilim_mid_])];
dlim_ = [min([rlim_,ilim_]),max([rlim_,ilim_])];
plot(dlim_,dlim_,'-','Color',0.85*[1,1,1]);
plot(real(dtau_a_restore_dif_C1M1_k_p_q_),real(dtau_a_restore_mid_C1M1_k_p_q_),'ro');
plot(imag(dtau_a_restore_dif_C1M1_k_p_q_),imag(dtau_a_restore_mid_C1M1_k_p_q_),'bx');
hold off;
xlim(dlim_); ylim(dlim_);
axisnotick;
xlabel('dif'); ylabel('mid');
title('C1M1');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
hold on;
rlim_dif_ = prctile(real(dtau_a_restore_dif_C0M2_k_p_q_),[  0,100]); rlim_dif_ = mean(rlim_dif_) + 0.5*1.25*diff(rlim_dif_)*[-1,+1]; if diff(rlim_dif_)==0; rlim_dif_=[-1,+1]; end;
rlim_mid_ = prctile(real(dtau_a_restore_mid_C0M2_k_p_q_),[  0,100]); rlim_mid_ = mean(rlim_mid_) + 0.5*1.25*diff(rlim_mid_)*[-1,+1]; if diff(rlim_mid_)==0; rlim_mid_=[-1,+1]; end;
rlim_ = [min([rlim_dif_,rlim_mid_]),max([rlim_dif_,rlim_mid_])];
ilim_dif_ = prctile(imag(dtau_a_restore_dif_C0M2_k_p_q_),[  0,100]); ilim_dif_ = mean(ilim_dif_) + 0.5*1.25*diff(ilim_dif_)*[-1,+1]; if diff(ilim_dif_)==0; ilim_dif_=[-1,+1]; end;
ilim_mid_ = prctile(imag(dtau_a_restore_mid_C0M2_k_p_q_),[  0,100]); ilim_mid_ = mean(ilim_mid_) + 0.5*1.25*diff(ilim_mid_)*[-1,+1]; if diff(ilim_mid_)==0; ilim_mid_=[-1,+1]; end;
ilim_ = [min([ilim_dif_,ilim_mid_]),max([ilim_dif_,ilim_mid_])];
dlim_ = [min([rlim_,ilim_]),max([rlim_,ilim_])];
plot(dlim_,dlim_,'-','Color',0.85*[1,1,1]);
plot(real(dtau_a_restore_dif_C0M2_k_p_q_),real(dtau_a_restore_mid_C0M2_k_p_q_),'ro');
plot(imag(dtau_a_restore_dif_C0M2_k_p_q_),imag(dtau_a_restore_mid_C0M2_k_p_q_),'bx');
hold off;
xlim(dlim_); ylim(dlim_);
axisnotick;
xlabel('dif'); ylabel('mid');
title('C0M2');
%%%%;
sgtitle(sprintf('dtau_scatterplot'),'Interpreter','none');
end;%if flag_disp;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% testing second-derivative (directional derivative only)')); end;
%%%%%%%%;
dtau_dtau_a_restore_dif_C2M0_k_p_q_ = (a_restore_pos_C2M0_k_p_q_ - 2*a_restore_mid_C2M0_k_p_q_ + a_restore_neg_C2M0_k_p_q_)/max(1e-12,dtau*dtau);
fnorm_disp(flag_verbose,'dtau_dtau_a_restore_dif_C2M0_k_p_q_',dtau_dtau_a_restore_dif_C2M0_k_p_q_,'dtau_dtau_a_restore_mid_C2M0_k_p_q_',dtau_dtau_a_restore_mid_C2M0_k_p_q_);
dtau_dtau_a_restore_dif_C1M1_k_p_q_ = (a_restore_pos_C1M1_k_p_q_ - 2*a_restore_mid_C1M1_k_p_q_ + a_restore_neg_C1M1_k_p_q_)/max(1e-12,dtau*dtau);
fnorm_disp(flag_verbose,'dtau_dtau_a_restore_dif_C1M1_k_p_q_',dtau_dtau_a_restore_dif_C1M1_k_p_q_,'dtau_dtau_a_restore_mid_C1M1_k_p_q_',dtau_dtau_a_restore_mid_C1M1_k_p_q_);
dtau_dtau_a_restore_dif_C0M2_k_p_q_ = (a_restore_pos_C0M2_k_p_q_ - 2*a_restore_mid_C0M2_k_p_q_ + a_restore_neg_C0M2_k_p_q_)/max(1e-12,dtau*dtau);
fnorm_disp(flag_verbose,'dtau_dtau_a_restore_dif_C0M2_k_p_q_',dtau_dtau_a_restore_dif_C0M2_k_p_q_,'dtau_dtau_a_restore_mid_C0M2_k_p_q_',dtau_dtau_a_restore_mid_C0M2_k_p_q_);
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figbig;
p_row=2; p_col=3; np=0;
%%%%;
subplot(p_row,p_col,1+np);np=np+1;
plot(qref_polar_a_shell_,log10(abs(dtau_dtau_a_restore_dif_C2M0_k_p_q_-dtau_dtau_a_restore_mid_C2M0_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(error))','Interpreter','none');
title('log10(abs(dtau_dtau C2M0 error))','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;
plot(qref_polar_a_shell_,log10(abs(dtau_dtau_a_restore_dif_C2M0_k_p_q_-dtau_dtau_a_restore_mid_C2M0_k_p_q_)./abs(dtau_dtau_a_restore_dif_C2M0_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(relative error))','Interpreter','none');
title('log10(abs(dtau_dtau C2M0 relative error))','Interpreter','none');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;
plot(qref_polar_a_shell_,log10(abs(dtau_dtau_a_restore_dif_C1M1_k_p_q_-dtau_dtau_a_restore_mid_C1M1_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(error))','Interpreter','none');
title('log10(abs(dtau_dtau C1M1 error))','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;
plot(qref_polar_a_shell_,log10(abs(dtau_dtau_a_restore_dif_C1M1_k_p_q_-dtau_dtau_a_restore_mid_C1M1_k_p_q_)./abs(dtau_dtau_a_restore_dif_C1M1_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(relative error))','Interpreter','none');
title('log10(abs(dtau_dtau C1M1 relative error))','Interpreter','none');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;
plot(qref_polar_a_shell_,log10(abs(dtau_dtau_a_restore_dif_C0M2_k_p_q_-dtau_dtau_a_restore_mid_C0M2_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(error))','Interpreter','none');
title('log10(abs(dtau_dtau C0M2 error))','Interpreter','none');
subplot(p_row,p_col,1+np);np=np+1;
plot(qref_polar_a_shell_,log10(abs(dtau_dtau_a_restore_dif_C0M2_k_p_q_-dtau_dtau_a_restore_mid_C0M2_k_p_q_)./abs(dtau_dtau_a_restore_dif_C0M2_k_p_q_)),'.');
xlim([0,pi]); xlabel('qref_polar_a_shell_','Interpreter','none');
ylabel('log10(abs(relative error))','Interpreter','none');
title('log10(abs(dtau_dtau C0M2 relative error))','Interpreter','none');
%%%%;
end;%if flag_disp;
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;
p_row = 1; p_col = 3; np=0;
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
hold on;
rlim_dif_ = prctile(real(dtau_dtau_a_restore_dif_C2M0_k_p_q_),[  0,100]); rlim_dif_ = mean(rlim_dif_) + 0.5*1.25*diff(rlim_dif_)*[-1,+1]; if diff(rlim_dif_)==0; rlim_dif_=[-1,+1]; end;
rlim_mid_ = prctile(real(dtau_dtau_a_restore_mid_C2M0_k_p_q_),[  0,100]); rlim_mid_ = mean(rlim_mid_) + 0.5*1.25*diff(rlim_mid_)*[-1,+1]; if diff(rlim_mid_)==0; rlim_mid_=[-1,+1]; end;
rlim_ = [min([rlim_dif_,rlim_mid_]),max([rlim_dif_,rlim_mid_])];
ilim_dif_ = prctile(imag(dtau_dtau_a_restore_dif_C2M0_k_p_q_),[  0,100]); ilim_dif_ = mean(ilim_dif_) + 0.5*1.25*diff(ilim_dif_)*[-1,+1]; if diff(ilim_dif_)==0; ilim_dif_=[-1,+1]; end;
ilim_mid_ = prctile(imag(dtau_dtau_a_restore_mid_C2M0_k_p_q_),[  0,100]); ilim_mid_ = mean(ilim_mid_) + 0.5*1.25*diff(ilim_mid_)*[-1,+1]; if diff(ilim_mid_)==0; ilim_mid_=[-1,+1]; end;
ilim_ = [min([ilim_dif_,ilim_mid_]),max([ilim_dif_,ilim_mid_])];
dlim_ = [min([rlim_,ilim_]),max([rlim_,ilim_])];
plot(dlim_,dlim_,'-','Color',0.85*[1,1,1]);
plot(real(dtau_dtau_a_restore_dif_C2M0_k_p_q_),real(dtau_dtau_a_restore_mid_C2M0_k_p_q_),'ro');
plot(imag(dtau_dtau_a_restore_dif_C2M0_k_p_q_),imag(dtau_dtau_a_restore_mid_C2M0_k_p_q_),'bx');
hold off;
xlim(dlim_); ylim(dlim_);
axisnotick;
xlabel('dif'); ylabel('mid');
title('C2M0');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
hold on;
rlim_dif_ = prctile(real(dtau_dtau_a_restore_dif_C1M1_k_p_q_),[  0,100]); rlim_dif_ = mean(rlim_dif_) + 0.5*1.25*diff(rlim_dif_)*[-1,+1]; if diff(rlim_dif_)==0; rlim_dif_=[-1,+1]; end;
rlim_mid_ = prctile(real(dtau_dtau_a_restore_mid_C1M1_k_p_q_),[  0,100]); rlim_mid_ = mean(rlim_mid_) + 0.5*1.25*diff(rlim_mid_)*[-1,+1]; if diff(rlim_mid_)==0; rlim_mid_=[-1,+1]; end;
rlim_ = [min([rlim_dif_,rlim_mid_]),max([rlim_dif_,rlim_mid_])];
ilim_dif_ = prctile(imag(dtau_dtau_a_restore_dif_C1M1_k_p_q_),[  0,100]); ilim_dif_ = mean(ilim_dif_) + 0.5*1.25*diff(ilim_dif_)*[-1,+1]; if diff(ilim_dif_)==0; ilim_dif_=[-1,+1]; end;
ilim_mid_ = prctile(imag(dtau_dtau_a_restore_mid_C1M1_k_p_q_),[  0,100]); ilim_mid_ = mean(ilim_mid_) + 0.5*1.25*diff(ilim_mid_)*[-1,+1]; if diff(ilim_mid_)==0; ilim_mid_=[-1,+1]; end;
ilim_ = [min([ilim_dif_,ilim_mid_]),max([ilim_dif_,ilim_mid_])];
dlim_ = [min([rlim_,ilim_]),max([rlim_,ilim_])];
plot(dlim_,dlim_,'-','Color',0.85*[1,1,1]);
plot(real(dtau_dtau_a_restore_dif_C1M1_k_p_q_),real(dtau_dtau_a_restore_mid_C1M1_k_p_q_),'ro');
plot(imag(dtau_dtau_a_restore_dif_C1M1_k_p_q_),imag(dtau_dtau_a_restore_mid_C1M1_k_p_q_),'bx');
hold off;
xlim(dlim_); ylim(dlim_);
axisnotick;
xlabel('dif'); ylabel('mid');
title('C1M1');
%%%%;
subplot(p_row,p_col,1+np);np=np+1;cla;
hold on;
rlim_dif_ = prctile(real(dtau_dtau_a_restore_dif_C0M2_k_p_q_),[  0,100]); rlim_dif_ = mean(rlim_dif_) + 0.5*1.25*diff(rlim_dif_)*[-1,+1]; if diff(rlim_dif_)==0; rlim_dif_=[-1,+1]; end;
rlim_mid_ = prctile(real(dtau_dtau_a_restore_mid_C0M2_k_p_q_),[  0,100]); rlim_mid_ = mean(rlim_mid_) + 0.5*1.25*diff(rlim_mid_)*[-1,+1]; if diff(rlim_mid_)==0; rlim_mid_=[-1,+1]; end;
rlim_ = [min([rlim_dif_,rlim_mid_]),max([rlim_dif_,rlim_mid_])];
ilim_dif_ = prctile(imag(dtau_dtau_a_restore_dif_C0M2_k_p_q_),[  0,100]); ilim_dif_ = mean(ilim_dif_) + 0.5*1.25*diff(ilim_dif_)*[-1,+1]; if diff(ilim_dif_)==0; ilim_dif_=[-1,+1]; end;
ilim_mid_ = prctile(imag(dtau_dtau_a_restore_mid_C0M2_k_p_q_),[  0,100]); ilim_mid_ = mean(ilim_mid_) + 0.5*1.25*diff(ilim_mid_)*[-1,+1]; if diff(ilim_mid_)==0; ilim_mid_=[-1,+1]; end;
ilim_ = [min([ilim_dif_,ilim_mid_]),max([ilim_dif_,ilim_mid_])];
dlim_ = [min([rlim_,ilim_]),max([rlim_,ilim_])];
plot(dlim_,dlim_,'-','Color',0.85*[1,1,1]);
plot(real(dtau_dtau_a_restore_dif_C0M2_k_p_q_),real(dtau_dtau_a_restore_mid_C0M2_k_p_q_),'ro');
plot(imag(dtau_dtau_a_restore_dif_C0M2_k_p_q_),imag(dtau_dtau_a_restore_mid_C0M2_k_p_q_),'bx');
hold off;
xlim(dlim_); ylim(dlim_);
axisnotick;
xlabel('dif'); ylabel('mid');
title('C0M2');
%%%%;
sgtitle(sprintf('dtau_dtau_scatterplot'),'Interpreter','none');
end;%if flag_disp;
%%%%%%%%;

if (flag_verbose> 0); disp(sprintf(' %% [finished %s]',str_thisfunction)); end;

