function [X_,X_ori_,X_tau_,weight_so3,n_m_max,polar_a_,azimu_b_,gamma_z_] = principled_marching_cost_matrix_1(n_k_p_r,weight_k_p_r_,l_max,a_k_Y__);
% very inefficient: need to precompute wigner-d and reorganized a_k_Y__(:,nk_p_r), as well as use fft instead of nufft ;
% scales by inverse-standard-deviations. ;
verbose=1;
%%%%%%%%;
n_lm_max = (1+l_max)^2;
n_m_max = 1+2*l_max;
n_polar_a = n_m_max; polar_a_ = linspace(-pi,pi,n_polar_a+1); polar_a_ = polar_a_(1:end-1);
n_azimu_b = n_m_max; azimu_b_ = linspace(0,2*pi,n_azimu_b+1); azimu_b_ = azimu_b_(1:end-1);
n_gamma_z = n_m_max; gamma_z_ = linspace(0,2*pi,n_gamma_z+1); gamma_z_ = gamma_z_(1:end-1);
weight_so3 = (2*pi)*(2*pi)*4; %<-- total volume of so3. ;
weight_sub = ((2*pi)/n_m_max)^3; %<-- abs(sin(polar_a))*weight_sub is used for each summand on so3. ;
%%%%%%%%;
X_ori_ = zeros(n_k_p_r,n_k_p_r);
for nk_p_r_0=1:n_k_p_r;
X_weight_r_0 = sqrt(weight_k_p_r_(1+nk_p_r_0)); %<-- volume element = inverse-variance associated with nk_p_r_0. ;
for nk_p_r_1=nk_p_r_0:n_k_p_r;
X_weight_r_1 = sqrt(weight_k_p_r_(1+nk_p_r_1)); %<-- volume element = inverse-variance associated with nk_p_r_1. ;
X_weight_r_01 = X_weight_r_0*X_weight_r_1; %<-- product of inverse-standard-deviations associated with nk_p_r_0 and nk_p_r_1. ;
polar_a = 0;
X_ori_(nk_p_r_0,nk_p_r_1) = register_spharm_to_spharm_2(verbose,1,1,1,l_max,a_k_Y__(:,nk_p_r_0),a_k_Y__(:,nk_p_r_1)) * X_weight_r_01;
X_ori_(nk_p_r_1,nk_p_r_0) = conj(X_ori_(nk_p_r_0,nk_p_r_1));
tmp_sum = 0;
for npolar_a=1:n_polar_a;
polar_a = polar_a_(npolar_a);
%[tmp_X_tau__] = register_spharm_to_spharm_single_beta_2(verbose,1,1,1,l_max,a_k_Y__(:,nk_p_r_0),a_k_Y__(:,nk_p_r_1),polar_a,n_m_max,azimu_b_,n_m_max,gamma_z_,[],[],[],[]);
[tmp_X_tau__] = register_spharm_to_spharm_single_beta_2(verbose,1,1,1,l_max,a_k_Y__(:,nk_p_r_0),a_k_Y__(:,nk_p_r_1),polar_a,0,[],0,[],[],[],[],[]);
tmp_sum = tmp_sum + sum(tmp_X_tau__,'all')*abs(sin(polar_a))*weight_sub; %<-- need quadrature weight to ensure uniform measure over SO3. ;
end;%for npolar_a=1:n_polar_a;
if (verbose>1); disp(sprintf(' %% nk_p_r_0 %d nk_p_r_1 %d --> sum %0.16f',nk_p_r_0,nk_p_r_1,real(tmp_sum))); end;
X_tau_(nk_p_r_0,nk_p_r_1) = tmp_sum * X_weight_r_01;
X_tau_(nk_p_r_1,nk_p_r_0) = conj(X_tau_(nk_p_r_0,nk_p_r_1));
end;%for nk_p_r_1=nk_p_r_0:n_k_p_r;
if (verbose>0); disp(sprintf(' %% nk_p_r_0 %d nk_p_r_1 %d --> sum %0.16f',nk_p_r_0,nk_p_r_1,real(tmp_sum))); end;
end;%for nk_p_r_0=1:n_k_p_r;
%%%%%%%%;
X_ = real(X_ori_)*weight_so3 - real(X_tau_);
%%%%%%%%;
