function ...
[ ...
 X_best ...
,flag_flip ...
,polar_a_best ...
,azimu_b_best ...
,gamma_z_best ...
,delta_best_ ...
,a_k_Y_best_ ...
,b_k_Y_best_ ...
] = ...
register_spharm_to_spharm_wigner_wrap_1( ...
 n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,N_wavelength ...
,l_max_ ...
,a_k_Y_ ...
,b_k_Y_ ...
);
%%%%%%%%;
[ ...
 X_orig ...
,polar_a_orig ...
,azimu_b_orig ...
,gamma_z_orig ...
,delta_orig_ ...
,a_k_Y_orig_ ...
,b_k_Y_orig_ ...
] = ...
register_spharm_to_spharm_wigner_1( ...
 n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,N_wavelength ...
,l_max_ ...
,a_k_Y_ ...
,b_k_Y_ ...
);
%%%%%%%%;
[ ...
 X_flip ...
,polar_a_flip ...
,azimu_b_flip ...
,gamma_z_flip ...
,delta_flip_ ...
,a_k_Y_flip_ ...
,b_k_Y_flip_ ...
] = ...
register_spharm_to_spharm_wigner_1( ...
 n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,N_wavelength ...
,l_max_ ...
,a_k_Y_ ...
,flipY(n_k_p_r,l_max_,b_k_Y_) ...
);
%%%%%%%%;
if (X_orig>=X_flip);
flag_flip = 0;
X_best = X_orig;
polar_a_best = polar_a_orig;
azimu_b_best = azimu_b_orig;
gamma_z_best = gamma_z_orig;
delta_best_ = delta_orig_;
a_k_Y_best_ = a_k_Y_orig_;
b_k_Y_best_ = b_k_Y_orig_;
end;%if (X_orig>=X_flip);
%%%%%%%%;
if (X_orig< X_flip);
flag_flip = 1;
X_best = X_flip;
polar_a_best = polar_a_flip;
azimu_b_best = azimu_b_flip;
gamma_z_best = gamma_z_flip;
delta_best_ = delta_flip_;
a_k_Y_best_ = a_k_Y_flip_;
b_k_Y_best_ = b_k_Y_flip_;
end;%if (X_orig>=X_flip);
%%%%%%%%;
