function ...
[ ...
 parameter ...
,d_mmlb____ ...
,d_mmzb____ ...
,X_best_a_ ...
,flag_flip_a_ ...
,niteration ...
,tmp_corr ...
,a_k_Y_best_ ...
,b_k_Y_best_ya__ ...
,viewing_euler_polar_a_pos_Ma__ ...
,viewing_euler_azimu_b_pos_Ma__ ...
,viewing_euler_gamma_z_pos_Ma__ ...
] = ...
register_spharm_to_spharm_3_stripped_wrap_wrap_0( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,N_wavelength ...
,l_max_ ...
,n_UZ_rank ...
,U_lz__ ...
,d_mmlb____ ...
,d_mmzb____ ...
,b_k_Y_ya__ ...
,viewing_euler_polar_a_pre_Ma__ ...
,viewing_euler_azimu_b_pre_Ma__ ...
,viewing_euler_gamma_z_pre_Ma__ ...
);

str_thisfunction = 'register_spharm_to_spharm_3_stripped_wrap_wrap_0';

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_k_p_r=[]; end; na=na+1;
if (nargin<1+na); k_p_r_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_max=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_r_=[]; end; na=na+1;
if (nargin<1+na); N_wavelength=[]; end; na=na+1;
if (nargin<1+na); l_max_=[]; end; na=na+1;
if (nargin<1+na); n_UZ_rank=[]; end; na=na+1;
if (nargin<1+na); U_lz__=[]; end; na=na+1;
if (nargin<1+na); d_mmlb____=[]; end; na=na+1;
if (nargin<1+na); d_mmzb____=[]; end; na=na+1;
if (nargin<1+na); b_k_Y_=[]; end; na=na+1;
if (nargin<1+na); viewing_euler_polar_a_pre_Ma__=[]; end; na=na+1;
if (nargin<1+na); viewing_euler_azimu_b_pre_Ma__=[]; end; na=na+1;
if (nargin<1+na); viewing_euler_gamma_z_pre_Ma__=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;
if ~isfield(parameter,'tolerance_master'); parameter.tolerance_master = 1e-2; end;
if ~isfield(parameter,'n_iteration'); parameter.n_iteration = 32; end;
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose = 0; end;
tolerance_master = parameter.tolerance_master;
n_iteration = parameter.n_iteration;
flag_verbose = parameter.flag_verbose;

if isempty(N_wavelength); N_wavelength = 0; end;
if N_wavelength~=0; disp(sprintf(' %% Warning, N_wavelength~=0 in %s, returning',str_thisfunction)); return; end;

if (flag_verbose); disp(sprintf(' %% [entering %s]',str_thisfunction)); end;

l_max_max = max(l_max_);
n_l_max = 1+l_max_max;
n_m_max = 1+2*l_max_max;
n_polar_a = n_m_max; polar_a_ = transpose(linspace(-1*pi,+1*pi,n_polar_a+1)); polar_a_ = polar_a_(1:end-1);
n_azimu_b = n_m_max; azimu_b_ = transpose(linspace( 0*pi,+2*pi,n_azimu_b+1)); azimu_b_ = azimu_b_(1:end-1);
n_gamma_z = n_m_max; gamma_z_ = transpose(linspace( 0*pi,+2*pi,n_gamma_z+1)); gamma_z_ = gamma_z_(1:end-1);
if isempty(n_UZ_rank); n_UZ_rank = 0; end;
if isempty(U_lz__); U_lz__ = zeros(n_l_max,n_UZ_rank); end;
if isempty(d_mmlb____);
t_0in = tic;
d_mmlb____ = zeros(n_m_max,n_m_max,n_l_max,n_polar_a);
d_mmzb____ = zeros(n_m_max,n_m_max,n_UZ_rank,n_polar_a);
for npolar_a=0:n_polar_a-1;
if (flag_verbose); if (mod(npolar_a,16)==0); disp(sprintf(' %% npolar_a %d/%d',npolar_a,n_polar_a)); end; end;
polar_a = polar_a_(1+npolar_a);
W_ = wignerd_b(l_max_max,-polar_a);
n_W_ = zeros(1,1+l_max_max); for (l_val=0:l_max_max); n_W_(1+l_val) = numel(W_{1+l_val}); end;
d_mml___ = zeros(n_m_max,n_m_max,1+l_max_max);
for l_val=0:l_max_max;
d_mml___(1+l_max_max + [-l_val:+l_val],1+l_max_max + [-l_val:+l_val],1+l_val) = W_{1+l_val};
end;%for l_val=0:l_max_max;
d_mmz___ = reshape(reshape(d_mml___,[n_m_max*n_m_max,n_l_max])*U_lz__,[n_m_max,n_m_max,n_UZ_rank]);
d_mmlb____(:,:,:,1+npolar_a) = d_mml___;
d_mmzb____(:,:,:,1+npolar_a) = d_mmz___;
end;%for npolar_a=0:n_polar_a-1;
t_out = toc(t_0in); if (flag_verbose); disp(sprintf(' %% calculate d_: t %0.6f',t_out)); end;
end;%if isempty(d_mmlb____);

n_a = size(b_k_Y_ya__,2);
b_k_Y_best_ya__ = b_k_Y_ya__;
viewing_euler_polar_a_pos_Ma__ = viewing_euler_polar_a_pre_Ma__;
viewing_euler_azimu_b_pos_Ma__ = viewing_euler_azimu_b_pre_Ma__;
viewing_euler_gamma_z_pos_Ma__ = viewing_euler_gamma_z_pre_Ma__;
a_k_Y_best_ = b_k_Y_best_ya__(:,1);

flag_continue=1; niteration=0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
while flag_continue;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
t_0in = tic;
parameter.flag_verbose = max(0,flag_verbose-1);
for na=0:n_a-1;
[ ...
 parameter ...
,d_mmlb____ ...
,d_mmzb____ ...
,X_best_a_(1+na) ...
,flag_flip_a_(1+na) ...
,~ ...
,~ ...
,~ ...
,delta_best_ ...
,b_k_Y_best_ya__(:,1+na) ...
,viewing_euler_polar_a_pos_Ma__(:,1+na) ...
,viewing_euler_azimu_b_pos_Ma__(:,1+na) ...
,viewing_euler_gamma_z_pos_Ma__(:,1+na) ...
] = ...
register_spharm_to_spharm_3_stripped_wrap_0( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,N_wavelength ...
,l_max_ ...
,n_UZ_rank ...
,U_lz__ ...
,d_mmlb____ ...
,d_mmzb____ ...
,a_k_Y_best_ ...
,b_k_Y_best_ya__(:,1+na) ...
,viewing_euler_polar_a_pos_Ma__(:,1+na) ...
,viewing_euler_azimu_b_pos_Ma__(:,1+na) ...
,viewing_euler_gamma_z_pos_Ma__(:,1+na) ...
);
end;%for na=0:n_a-1;
parameter.flag_verbose = flag_verbose;
t_out = toc(t_0in); if (flag_verbose); disp(sprintf(' %% registration: t %0.6f',t_out)); end;
%%%%%%%%;
a_k_Y_next_ = mean(b_k_Y_best_ya__,2);
[ ...
 ~ ...
,tmp_corr ...
] = ...
register_spharm_to_spharm_3( ...
 max(0,flag_verbose-1) ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_next_ ...
,a_k_Y_best_ ...
);
a_k_Y_best_ = a_k_Y_next_;
niteration = niteration+1;
flag_continue = (niteration<n_iteration) & (abs(1-tmp_corr)>=tolerance_master) ;
if (flag_verbose); disp(sprintf(' %% niteration %d/%d tmp_corr: %0.16f',niteration,n_iteration,tmp_corr)); end;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%while flag_continue;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

if (flag_verbose); disp(sprintf(' %% [finished %s]',str_thisfunction)); end;
