runction RMat = relion_euler_rot_mat(phi,theta,psi);
%     RELION rotation angles ;
%     rotation around z axis in lab frame by angle phi ;
%     0 < phi < 2.0d0*pi ;
%     the rotation results in new axis x2,y2,z2   ;
%     rotation around the new y2 axis by angle theta ;
%     0 < theta < pi ;
%     the rotation results in new axis x3,y3,z3 ;
%     rotation around the new z3 axis by angle psi ;
%     0 < psi < 2.0d0*pi ;
%     output is the rotation matrix RMat ; ;
;
RotMat = zeros(3,3);
RotMat(1,1) = cos(psi)*cos(theta)*cos(phi)-sin(psi)*sin(phi) ;
RotMat(2,1) = -sin(psi)*cos(theta)*cos(phi)-cos(psi)*sin(phi) ;
RotMat(3,1) = sin(theta)*cos(phi) ;
RotMat(1,2) = cos(psi)*cos(theta)*sin(phi)+sin(psi)*cos(phi) ;
RotMat(2,2) = -sin(psi)*cos(theta)*sin(phi)+cos(psi)*cos(phi) ;
RotMat(3,2) = sin(theta)*sin(phi) ;
RotMat(1,3) = -cos(psi)*sin(theta) ;
RotMat(2,3) = sin(psi)*sin(theta) ;
RotMat(3,3) = cos(theta) ;
TRotMat = transpose(RotMat);
RMat = TRotMat;

function angles = rot_mat_to_euler(RotMat) ;
angles = zeros(3,1);
angles(1) = RotMat(3,3) ;
angles(2) = atan2(RotMat(2,3),RotMat(1,3)) ;
if(angles(2) < 0);
angles(2) = angles(2)+2.0d0*pi ;
end;%if ;
angles(3) = atan2(RotMat(3,2),-RotMat(3,1)) ;
if(angles(3) < 0);
angles(3) = angles(3)+2.0d0*pi ;
end%if ;

function RotMat = euler_to_rot_mat(angles);
RotMat = zeros(3,3);
calphai=angles(1) ;
salphai=sqrt(1-calphai^2) ;
cbetaj=cos(angles(2)) ;
sbetaj=sin(angles(2)) ;
cgamma=cos(angles(3)) ;
sgamma=sin(angles(3)) ;
;
R3(1,1) = cgamma;
R3(1,2) = -sgamma;
R3(1,3) = 0.0d0;
R3(2,1) = sgamma;
R3(2,2) = cgamma;
R3(2,3) = 0.0d0;
R3(3,1) = 0.0d0;
R3(3,2) = 0.0d0;
R3(3,3) = 1;
;
R1(1,1) = calphai ;
R1(1,2) = 0.0d0 ;
R1(1,3) = salphai ;
R1(2,1) = 0.0d0;
R1(2,2) = 1;
R1(2,3) = 0.0d0;
R1(3,1) = -salphai ;
R1(3,2) = 0.0d0 ;
R1(3,3) = calphai          ;
;
R2(1,1) = cbetaj;
R2(1,2) = -sbetaj;
R2(1,3) = 0.0d0;
R2(2,1) = sbetaj;
R2(2,2) = cbetaj;
R2(2,3) = 0.0d0;
R2(3,1) = 0.0d0;
R2(3,2) = 0.0d0;
R2(3,3) = 1;
;
RotMat1(1,1) = calphai*cbetaj ;
RotMat1(1,2) = -sbetaj ;
RotMat1(1,3) = salphai*cbetaj ;
RotMat1(2,1) = calphai*sbetaj ;
RotMat1(2,2) = cbetaj ;
RotMat1(2,3) = salphai*sbetaj ;
RotMat1(3,1) = -salphai ;
RotMat1(3,2) = 0.0d0 ;
RotMat1(3,3) = calphai ;
;
RotMat(1,1) = calphai*cbetaj*cgamma-sbetaj*sgamma ;
RotMat(1,2) = -calphai*cbetaj*sgamma-sbetaj*cgamma ;
RotMat(1,3) = salphai*cbetaj ;
RotMat(2,1) = calphai*sbetaj*cgamma+cbetaj*sgamma ;
RotMat(2,2) = -calphai*sbetaj*sgamma+cbetaj*cgamma ;
RotMat(2,3) = salphai*sbetaj ;
RotMat(3,1) = -salphai*cgamma ;
RotMat(3,2) = salphai*sgamma ;
RotMat(3,3) = calphai ;

