function [p,lim_] = stairfall_0(X__,x_ord_,lim_,c_);
% plots each column of X__ as an opaque staircase. ;
% we assume that lower column-indices correspond to shorter staircases. ;
if nargin<2; x_ord_ = []; end;
if nargin<3; lim_ = []; end;
if nargin<4; c_ = []; end;
if (isempty(x_ord_)); x_ord_ = 0:1+size(X__,1); end;
if (isempty(c_)); c_ = colormap_beach(); end;
n_c = size(c_,1);
[n_row,n_col] = size(X__);
if (isempty(lim_)); lim_ = [min(X__,[],'all'),max(X__,[],'all')]; end;
X__ = max(lim_(1),X__);
X__ = min(lim_(2),X__);
x__ = zeros(3+4*n_row,n_col);
y__ = zeros(3+4*n_row,n_col);
c___ = zeros(n_col,1,3);
for ncol=0:n_col-1;
nc = max(0,min(n_c,floor(n_c*ncol/n_col)));
c___(1+ncol,1,:) = c_(1+nc,:);
x_ = zeros(1+2*n_row,1);
y_ = zeros(1+2*n_row,1);
na=0;
for nrow=0:n_row-1;
x_(1+na) = x_ord_(1+nrow+0);
y_(1+na) = X__(1+nrow,1+ncol);
na=na+1;
x_(1+na) = x_ord_(1+nrow+1);
y_(1+na) = X__(1+nrow,1+ncol);
na=na+1;
end;%for nrow=0:n_row-1;
if (ncol>0);
for nrow=n_row-1:-1:0;
x_(1+na) = x_ord_(1+nrow+1);
y_(1+na) = X__(1+nrow,1+ncol-1);
na=na+1;
x_(1+na) = x_ord_(1+nrow+0);
y_(1+na) = X__(1+nrow,1+ncol-1);
na=na+1;
end;%for nrow=n_row-1:-1:0;
end;%if (ncol>0);
if (ncol==0);
for nrow=n_row-1:-1:0;
x_(1+na) = x_ord_(1+nrow+1);
y_(1+na) = min(lim_);
na=na+1;
x_(1+na) = x_ord_(1+nrow+0);
y_(1+na) = min(lim_);
na=na+1;
end;%for nrow=n_row-1:-1:0;
end;%if (ncol==0);
x_(1+na) = x_(1+0);
y_(1+na) = y_(1+0);
na=na+1;
n_a = na;
x__(1:n_a,1+ncol) = x_;
y__(1:n_a,1+ncol) = y_;
end;%for ncol=0:n_col-1;
p = patch(x__,y__,c___,'EdgeColor','k');
