 sample_d = 0.125; [n_all,theta_all_,phi_all_,weight_all_] = sample_shell_2(1.0,sample_d,'L') ;
 x_all_ = cos(theta_all_).*sin(phi_all_);
 y_all_ = sin(theta_all_).*sin(phi_all_);
 z_all_ = cos(phi_all_);
 nd_degree = 18;
 d_tmp = svd_d_(nd_degree);
 Ylm_d__ = get_Ylm__(n_l,0:l_max,1,0,0);
 Ylm_r__ = get_Ylm__(n_l,0:l_max,n_all,theta_all_,phi_all_);
 j_ = zeros(n_l,n_r_degree);
 for nl=1:n_l;
 l_val = nl-1;
 tmp_ = besselj(l_val+0.5,svd_r_.*d_tmp).*sqrt(pi)./sqrt(2*svd_r_.*d_tmp);
 j_(nl,:) = tmp_;
 end;%for nl=1:n_l;
 IT_ = zeros(n_r_degree,1);
 QT_ = zeros(n_r_degree,1);
 QA_ = zeros(n_r_degree,1);
 EA__ = zeros(n_r_degree,n_l);
 for nr_degree=1:n_r_degree;
 r_tmp = svd_r_(nr_degree); k_tmp = r_tmp/(2*pi); 
 %xr_all_ = x_all_*k_tmp; yr_all_ = y_all_*k_tmp; zr_all_ = z_all_*k_tmp;
 zr_all_ = z_all_*k_tmp;
 T_ = exp(+i*2*pi*zr_all_.*d_tmp);
 A_ = zeros(n_all,n_l);
 for nl=1:n_l;
 l_val = nl-1;
 for m_val=-l_val:+l_val;
 tmp_ = 4*pi * (i)^(l_val) * j_(nl,nr_degree) .* reshape(Ylm_r__{nl}(1+l_val+m_val,:),n_all,1) .* conj(Ylm_d__{nl}(1+l_val+m_val,1)) ;
 for nl2=1:nl; A_(:,nl2) = A_(:,nl2) + tmp_; end;
 end;%for m_val=-l_val:+l_val;
 end;%for nl=1:n_l;
 IT_(nr_degree) = 4*pi*(1/d_tmp)*sin(d_tmp*r_tmp).*r_tmp./r_tmp.^2;
 %IT_(nr_degree) = 4*pi*(1/d_tmp)*sin(d_tmp*r_tmp).*r_tmp;
 QT_(nr_degree) = sum(T_.*weight_all_);
 QA_(nr_degree) = sum(A_.*weight_all_);
 for nl=1:n_l; tmp_ = abs(T_ - A_(:,nl)).^2; EA__(nr_degree,nl) = sum(tmp_.*weight_all_); end;
 end;%for nr_degree=1:n_r_degree;
 %plot(1:n_r_degree,real(QT_),'ko-',1:n_r_degree,IT_,'rx-',1:n_r_degree,QA_,'ms-');
 IT = 4*pi*(1/d_tmp^3)*( sin(R_max*d_tmp) - (R_max*d_tmp)*cos(R_max*d_tmp) );
 QT = 4*pi*K_max^2 * sum(svd_r_w_.*QT_)*(2*pi)^2*8;
 QA = 4*pi*K_max^2 * sum(svd_r_w_.*QA_)*(2*pi)^2*8;
 EA_ = zeros(n_l,1); for nl=1:n_l; EA_(nl) = 4*pi*K_max^2 * sum(svd_r_w_.*EA__(:,nl))*(2*pi)^2*8; end;
 ET = norm(QT - IT,'fro');
 disp(sprintf(' %% IT %0.16f',IT));
 disp(sprintf(' %% QT %0.16f',QT));
 disp(sprintf(' %% QA %0.16f',QA));
 disp(sprintf(' %% EA %0.16f',EA));
 disp(sprintf(' %% ET %0.16f',ET));

%{
%%%%%%%%%%%%%%%%;
% count number of terms for various eps_target;
%%%%%%%%%%%%%%%%;
eps_target_ = 0.1.^[0:0.5:8]; n_eps_target = length(eps_target_);
n_term_A_ = zeros(n_eps_target,1); n_term_B_ = zeros(n_eps_target,1); n_term_C_ = zeros(n_eps_target,1);
for nn=0:(l_max + l_add + 1)^2*n_beta-1;
nnx = nn;
tmp_lm2 = mod(nnx,(l_max + l_add + 1)^2); nnx = nnx - tmp_lm2; nnx = nnx/(l_max+l_add+1)^2;
nbeta = mod(nnx,n_beta); nnx = nnx - nbeta;
assert(nnx==0);
tmp_l2 = floor(sqrt(tmp_lm2)); tmp_m2 = tmp_lm2 - tmp_l2*(tmp_l2+1);
tmp_ij_ = find((par_symbol_l2_==tmp_l2) & (par_symbol_m2_==tmp_m2)); %n_total = n_total + length(tmp_ij_);
for ni=1:length(tmp_ij_);
assert(par_symbol_l2_(tmp_ij_(ni))==tmp_l2); assert(par_symbol_m2_(tmp_ij_(ni))==tmp_m2); 
tmp_l1 = par_symbol_l1_(tmp_ij_(ni)); tmp_l3 = par_symbol_l3_(tmp_ij_(ni));
tmp_m1 = par_symbol_m1_(tmp_ij_(ni)); tmp_m3 = par_symbol_m3_(tmp_ij_(ni));
tmp_sy = par_symbol_sy_(tmp_ij_(ni)); tmp_l4 = tmp_l1;
nk_min = min(find(n_l_>=max([tmp_l3,tmp_l1])))-1;
for nt=1:n_svd_l_(1+tmp_l2);
assert(sum(svd_l_(n_svd_l_csum_(1+tmp_l2) + (1:n_svd_l_(1+tmp_l2)))==tmp_l2)==n_svd_l_(1+tmp_l2));
tmp_nt = n_svd_l_csum_(1+tmp_l2) + nt;
n_term_C_ = n_term_C_ + 1;
tmp_ij_ = find(eps_target_<abs(tmp_sy*4*pi*svd_s_(tmp_nt)));
n_term_A_(tmp_ij_) = n_term_A_(tmp_ij_) + 1;
tmp_ij_ = find(eps_target_<abs(svd_s_(tmp_nt)));
n_term_B_(tmp_ij_) = n_term_B_(tmp_ij_) + 1;
end;%for nt=1:n_svd_l_(1+tmp_l2);
end;%for ni=1:length(tmp_ij_);
end;%for nn=0:(l_max + l_add + 1)^2*n_beta-1;
 %}
