function ...
[ ...
 parameter ...
] = ...
test_template_single_ring_0( ...
 parameter ...
);

str_thisfunction = 'test_template_single_ring_0';

if (nargin<1);
disp(sprintf(' %% testing %s',str_thisfunction));
parameter = struct('type','parameter');
parameter.flag_verbose = 1;
parameter.str_shape = 'rand';
test_template_single_ring_0(parameter);
disp(sprintf(' %% returning')); return;
end;%if (nargin<1);

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;

%clear; parameter = [];

if isempty(parameter); parameter = struct('type','parameter'); end;
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose = 1; end;
flag_verbose = parameter.flag_verbose;
if ~isfield(parameter,'flag_disp'); parameter.flag_disp = 0; end;
flag_disp = parameter.flag_disp; nf=0;
if ~isfield(parameter,'flag_replot'); parameter.flag_replot = 0; end;
flag_replot = parameter.flag_replot;
if ~isfield(parameter,'str_shape'); parameter.str_shape = 'rand'; end;
str_shape = parameter.str_shape;
if ~isfield(parameter,'n_mode'); parameter.n_mode = 2; end;
n_mode = parameter.n_mode;
if ~isfield(parameter,'d_source'); parameter.d_source = 0.25*pi; end;
d_source = parameter.d_source;
if ~isfield(parameter,'sigma_x_c'); parameter.sigma_x_c = 0.025; end;
sigma_x_c = parameter.sigma_x_c;
if ~isfield(parameter,'str_shape'); parameter.str_shape = 'rand'; end;
str_shape = parameter.str_shape;
if ~isfield(parameter,'rseed'); parameter.rseed = 0; end;
rseed = parameter.rseed;
if ~isfield(parameter,'n_x_c'); parameter.n_x_c = 256; end;
n_x_c = parameter.n_x_c;
if ~isfield(parameter,'k_p_r_max'); parameter.k_p_r_max = 1.0*48.0/(2*pi); end;
k_p_r_max = parameter.k_p_r_max;
if ~isfield(parameter,'k_eq_d'); parameter.k_eq_d = sqrt(1.0)/(2*pi); end;
k_eq_d = parameter.k_eq_d;

if flag_verbose; disp(sprintf(' %% [entering %s]',str_thisfunction)); end;

%%%%%%%%;
platform = 'rusty';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
if (strcmp(platform,'eval1')); setup_eval1; string_root = 'home'; end;
if (strcmp(platform,'rusty')); setup_rusty; string_root = 'mnt/home'; end;
%%%%%%%%;
dir_manuscript = sprintf('/%s/rangan/dir_cryoem/dir_spurious_heterogeneity_manuscript',string_root);
if ~exist(dir_manuscript,'dir'); disp(sprintf(' %% mkdir %s',dir_manuscript)); mkdir(dir_manuscript); end;
dir_manuscript_jpg = sprintf('%s/dir_M3d_shape_longitudinal_perturbation_jpg',dir_manuscript);
if ~exist(dir_manuscript_jpg,'dir'); disp(sprintf(' %% mkdir %s',dir_manuscript_jpg)); mkdir(dir_manuscript_jpg); end;

if strcmp(str_shape,'rand'); rng(rseed); end;

%%%%%%%%;
flag_unif_vs_adap = 1;
flag_tensor_vs_adap = 1;
half_diameter_x_c = 1.0d0;
diameter_x_c = 2.0d0*half_diameter_x_c;
x_p_r_max = 1.0;
x_c_0_ = -half_diameter_x_c + transpose([0:n_x_c-1]/n_x_c)*diameter_x_c;
x_c_1_ = -half_diameter_x_c + transpose([0:n_x_c-1]/n_x_c)*diameter_x_c;
x_c_2_ = -half_diameter_x_c + transpose([0:n_x_c-1]/n_x_c)*diameter_x_c;
dx = diameter_x_c/n_x_c;
[x_c_0_012___,x_c_1_012___,x_c_2_012___] = ndgrid(x_c_0_,x_c_1_,x_c_2_); n_xxx_c = n_x_c^3; xxx_c_weight = (2*x_p_r_max/n_x_c)^3;
k_c_0_ = periodize(0:n_x_c-1,-n_x_c/2,+n_x_c/2)/2; %<-- box has diameter 2. ;
k_c_1_ = periodize(0:n_x_c-1,-n_x_c/2,+n_x_c/2)/2; %<-- box has diameter 2. ;
k_c_2_ = periodize(0:n_x_c-1,-n_x_c/2,+n_x_c/2)/2; %<-- box has diameter 2. ;
dk = 1.0/diameter_x_c;
[k_c_0_012___,k_c_1_012___,k_c_2_012___] = ndgrid(k_c_0_,k_c_1_,k_c_2_); n_kkk_c = n_x_c^3;
%%%%%%%%;
tmp_t = tic;
[ ...
 n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_all_ ...
,k_c_1_all_ ...
,k_c_2_all_ ...
,J_node_ ...
,J_weight_ ...
,J_chebfun_ ...
,J_polyval_ ...
,n_polar_a_k_ ...
,polar_a_ka__ ...
,n_azimu_b_ka__ ...
] = ...
sample_sphere_7( ...
 flag_verbose ...
,k_p_r_max ...
,k_eq_d ...
,'L' ...
,flag_unif_vs_adap ...
,flag_tensor_vs_adap ...
) ; %<-- sum(weight_3d_k_p_r_)*(4*pi) = (4/3)*pi*k_p_r_max^3 --> sum(weight_3d_k_p_r_) = (1/3)*k_p_r_max^3 ;
tmp_t = toc(tmp_t); disp(sprintf(' %% sample_sphere_7: time %0.2fs',tmp_t));
%%%%%%%%;
n_w_max = 2*(n_k_p_r);
template_k_eq_d = -1;%template_k_eq_d = 1.0/(2*pi);
n_w_0in_ = n_w_max*ones(n_k_p_r,1);
[ ...
 n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_all_ ...
,k_p_r_wk_ ...
,k_p_w_wk_ ...
,k_c_0_wk_ ...
,k_c_1_wk_ ...
] = ...
get_weight_2d_2( ...
 flag_verbose ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,template_k_eq_d ...
,n_w_0in_ ...
);
n_w_max = max(n_w_); n_w_sum = sum(n_w_); n_w_csum_ = cumsum([0;n_w_]);
%%%%%%%%;

sigma_k_p = 1/sigma_x_c;
%%%%%%%%;
% check formula for fourier-transform of gaussian. ;
%%%%%%%%;
flag_check=0;
if flag_check;
b_x_c_0_ = 1/(sqrt(2*pi)*sigma_x_c) * exp(-(x_c_0_).^2/(2*sigma_x_c^2));
b_k_c_0_ = exp(-(2*pi*k_c_0_).^2/(2*sigma_k_p^2));
b_x_c_l2 = sum(abs(b_x_c_0_).^2,'all')*dx;
disp(sprintf(' %% b_x_c_l2 = %0.16f',b_x_c_l2));
b_k_c_l2 = sum(abs(b_k_c_0_).^2,'all')*dk;
disp(sprintf(' %% b_k_c_l2 = %0.16f',b_k_c_l2));
b_x_c_form_ = 1/(sqrt(2*pi)*sigma_x_c)^3 * exp( -( ...
						    + (x_c_0_012___).^2 ...
						    + (x_c_1_012___).^2 ...
						    + (x_c_2_012___).^2 ...
						    ) / (2*sigma_x_c^2) );
b_k_p_form_ = exp( -(2*pi*k_p_r_all_).^2 / (2*sigma_k_p^2) ) ;
b_x_c_l2 = sum(abs(b_x_c_form_).^2,'all')*dx^3;
disp(sprintf(' %% b_x_c_l2 = %0.16f',b_x_c_l2));
b_k_p_l2 = sum(abs(b_k_p_form_).^2.*weight_3d_k_all_,'all');
disp(sprintf(' %% b_k_p_l2 = %0.16f',b_k_p_l2));
end;%if flag_check;

%%%%%%%%;
% Sum of gaussians. ;
%%%%%%%%;
[ ...
 n_source ...
,azimu_b_source_ ...
,polar_a_source_ ...
,weight_source_ ...
,x_c_0_source_ ...
,x_c_1_source_ ...
,x_c_2_source_ ...
] = ...
sample_shell_5( ...
 0.75*half_diameter_x_c ...
,0.75*half_diameter_x_c*d_source ...
) ;
%%%%%%%%;
a_x_c_form_ = zeros(n_x_c,n_x_c,n_x_c);
a_k_p_form_ = zeros(n_k_all,1);
for nsource=0:n_source-1;
b_x_c_form_ = 1/(sqrt(2*pi)*sigma_x_c)^3 * exp( -( ...
						    + (x_c_0_012___ - x_c_0_source_(1+nsource)).^2 ...
						    + (x_c_1_012___ - x_c_1_source_(1+nsource)).^2 ...
						    + (x_c_2_012___ - x_c_2_source_(1+nsource)).^2 ...
						    ) / (2*sigma_x_c^2) );
a_x_c_form_ = a_x_c_form_ + b_x_c_form_;
b_k_p_form_ = exp( -(2*pi*k_p_r_all_).^2 / (2*sigma_k_p^2) ) .* ...
  exp(-i*2*pi*( ...
		+k_c_0_all_*x_c_0_source_(1+nsource) ...
		+k_c_1_all_*x_c_1_source_(1+nsource) ...
		+k_c_2_all_*x_c_2_source_(1+nsource) ...
		));
a_k_p_form_ = a_k_p_form_ + b_k_p_form_;
clear b_x_c_form_ b_k_p_form_;
end;%for nsource=0:n_source-1;
%%%%%%%%;
a_x_c_l2 = sum(abs(a_x_c_form_).^2,'all')*dx^3;
disp(sprintf(' %% a_x_c_l2 = %0.16f',a_x_c_l2));
a_k_p_l2 = sum(abs(a_k_p_form_).^2.*weight_3d_k_all_,'all');
disp(sprintf(' %% a_k_p_l2 = %0.16f',a_k_p_l2));
%%%%%%%%;
flag_disp=0;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figsml;
isosurface_f_x_c_0(a_x_c_form_,98.5);
end;%if flag_disp;
%%%%%%%%;

%%%%%%%%;
% Now convert to a_k_p_ ;
%%%%%%%%;
%%%%%%%%;
eta = pi/x_p_r_max; tmp_t = tic;
a_k_p_quad_ = xxnufft3d3(n_xxx_c,x_c_0_012___(:)*eta,x_c_1_012___(:)*eta,x_c_2_012___(:)*eta,a_x_c_form_(:).*xxx_c_weight,-1,1e-12,n_k_all,2*pi*k_c_0_all_/eta,2*pi*k_c_1_all_/eta,2*pi*k_c_2_all_/eta)/sqrt(2*pi)/sqrt(2*pi)/sqrt(2*pi) *  sqrt(2*pi)^3;
tmp_t = toc(tmp_t); disp(sprintf(' %% xxnufft3d3: a_k_p_quad_ time %0.2fs',tmp_t));
disp(sprintf(' %% xxnufft3d3: a_k_p_l2 ratio: (sum(abs(a_k_p_form_).^2.*weight_3d_k_all_)/sum(abs(a_k_p_quad_).^2.*weight_3d_k_all_)): %0.16f',(sum(abs(a_k_p_form_).^2.*weight_3d_k_all_)/sum(abs(a_k_p_quad_).^2.*weight_3d_k_all_))));
disp(sprintf(' %% xxnufft3d3: a_k_p_quad error: %0.16f',fnorm(a_k_p_form_-a_k_p_quad_)/fnorm(a_k_p_form_)));
%%%%%%%%;
eta = pi/k_p_r_max; tmp_t = tic;
a_x_c_reco_ = xxnufft3d3(n_k_all,2*pi*k_c_0_all_*eta,2*pi*k_c_1_all_*eta,2*pi*k_c_2_all_*eta,a_k_p_quad_.*(2*pi)^3.*weight_3d_k_all_,+1,1e-12,n_xxx_c,x_c_0_012___(:)/eta,x_c_1_012___(:)/eta,x_c_2_012___(:)/eta)/sqrt(2*pi)/sqrt(2*pi)/sqrt(2*pi) /  sqrt(2*pi)^3;
tmp_t = toc(tmp_t); disp(sprintf(' %% xxnufft3d3: a_x_c_reco_ time %0.2fs',tmp_t));
disp(sprintf(' %% xxnufft3d3: a_x_c_reco error: %0.16f',fnorm(a_x_c_form_(:)-a_x_c_reco_)/fnorm(a_x_c_form_(:))));
%%%%%%%%;
flag_disp=1;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,2,1); isosurface_f_x_u_0(a_x_c_form_,98.5); title('a_x_c_form_','Interpreter','none');
subplot(1,2,2); isosurface_f_x_u_0(a_x_c_reco_,98.5); title('a_x_c_reco_','Interpreter','none');
end;%if flag_disp;
%%%%%%%%;

%%%%%%%%;
% Set up interpolation matrix. ;
% This strongly assumes that each shell and ring is discretized identically. ;
% (i.e., flag_unif_vs_adap==1 & flag_tensor_vs_adap==1). ;
%%%%%%%%;
nk_p_r = 0; %<-- any individual shell will do. ;
t_max = 1.0; n_t = 16;
dt = t_max/max(1,n_t);
g_dilation = @(polar_a) dt*sin(2*polar_a); %<-- first mode. ;
n_order = 5;
%%%%;
n_k_all_csum_pre = n_k_all_csum_(1+nk_p_r+0);
n_k_all_csum_pos = n_k_all_csum_(1+nk_p_r+1);
shell_n_k_all = n_k_all_csum_pos-n_k_all_csum_pre;
shell_n_polar_a = n_polar_a_k_(1+nk_p_r);
tmp_n_azimu_b_a_ = n_azimu_b_ka__{1+nk_p_r};
if (mean(diff(tmp_n_azimu_b_a_))> 0); disp(sprintf(' %% Warning, nonuniform tmp_n_azimu_b_a_')); end;
shell_n_azimu_b = tmp_n_azimu_b_a_(1+0);
assert(shell_n_k_all==shell_n_polar_a*shell_n_azimu_b);
shell_k_p_azimu_b_ = k_p_azimu_b_all_(1+n_k_all_csum_pre+[0:shell_n_k_all-1]);
shell_k_p_polar_a_ = k_p_polar_a_all_(1+n_k_all_csum_pre+[0:shell_n_k_all-1]);
shell_longitudinal_r_ = 0.5*g_dilation(shell_k_p_polar_a_);
%%%%;
tmp_t = tic();
shell_n_scatter = shell_n_k_all; %<-- single point for each. ;
shell_azimu_b_scatter__ = shell_k_p_azimu_b_;
shell_polar_a_scatter_ = shell_k_p_polar_a_ + shell_longitudinal_r_;
[ ...
 shell_scatter_from_tensor_sba__ ...
,shell_scatter_from_tensor_db1da0_sba__ ...
,shell_scatter_from_tensor_db0da1_sba__ ...
,shell_scatter_from_tensor_db1da1_sba__ ...
,shell_scatter_from_tensor_db2da0_sba__ ...
,shell_scatter_from_tensor_db0da2_sba__ ...
] = ...
cg_interpolate_n_3( ...
 n_order ...
,shell_n_azimu_b ...
,shell_n_polar_a ...
,shell_n_scatter ...
,shell_azimu_b_scatter__ ...
,shell_polar_a_scatter_ ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% cg_interpolate_n_3: time %0.2fs',tmp_t));
%%%%%%%%;

%%%%%%%%;
% Construct a_k_Y_quad_. ;
%%%%%%%%;
l_max_upb = round(2*pi*k_p_r_max); %<-- typically sufficient for 2-3 digits of precision. ;
l_max_ = zeros(n_k_p_r,1);
for nk_p_r=0:n_k_p_r-1;
l_max_(1+nk_p_r) = max(0,min(l_max_upb,1+ceil(2*pi*k_p_r_(1+nk_p_r))));
end;%for nk_p_r=0:n_k_p_r-1;
n_lm_ = (l_max_+1).^2;
n_lm_max = max(n_lm_);
n_lm_sum = sum(n_lm_);
n_lm_csum_ = cumsum([0;n_lm_]);
l_max_max = max(l_max_); dWtdkd__l_max_max = 2*l_max_max;
m_max_ = -l_max_max : +l_max_max;
n_m_max = length(m_max_);
Y_l_val_ = zeros(n_lm_sum,1);
Y_m_val_ = zeros(n_lm_sum,1);
Y_k_val_ = zeros(n_lm_sum,1);
for nk_p_r=0:n_k_p_r-1;
l_max = l_max_(1+nk_p_r);
tmp_l_val_ = zeros(n_lm_(1+nk_p_r),1);
tmp_m_val_ = zeros(n_lm_(1+nk_p_r),1);
na=0; 
for l_val=0:l_max;
for m_val=-l_val:+l_val;
tmp_l_val_(1+na) = l_val;
tmp_m_val_(1+na) = m_val;
na=na+1;
end;%for m_val=-l_val:+l_val;
end;%for l_val=0:l_max;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
Y_l_val_(1+tmp_index_) = tmp_l_val_;
Y_m_val_(1+tmp_index_) = tmp_m_val_;
Y_k_val_(1+tmp_index_) = k_p_r_(1+nk_p_r);
end;%for nk_p_r=0:n_k_p_r-1;
weight_Y_ = zeros(n_lm_sum,1);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
weight_Y_(1+tmp_index_) = weight_3d_k_p_r_(1+nk_p_r);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
tmp_t = tic;
[a_k_Y_quad_] = convert_k_p_to_spharm_1(flag_verbose,n_k_all,n_k_all_csum_,k_p_r_all_,k_p_azimu_b_all_,k_p_polar_a_all_,weight_3d_k_all_,weight_shell_k_,n_k_p_r,k_p_r_,weight_3d_k_p_r_,l_max_,a_k_p_quad_);
tmp_t = toc(tmp_t); disp(sprintf(' %% a_k_Y_quad_ time %0.2fs',tmp_t));
disp(sprintf(' %% Here we should ensure that a_k_Y_ on the outer shells has decayed to the desired precision.'));
disp(sprintf(' %% Moreover, we should ensure that a_k_Y_(l,m) has decayed for large l,m at each shell.'));
tmp_t = tic;
[a_k_p_reco_] = convert_spharm_to_k_p_1(flag_verbose,n_k_all,n_k_all_csum_,k_p_r_all_,k_p_azimu_b_all_,k_p_polar_a_all_,weight_3d_k_all_,weight_shell_k_,n_k_p_r,k_p_r_,weight_3d_k_p_r_,l_max_,a_k_Y_quad_);
tmp_t = toc(tmp_t); disp(sprintf(' %% a_k_Y_quad_ --> a_k_p_reco_ time %0.2fs',tmp_t));
disp(sprintf(' %% xxnufft3d3: a_k_p_reco error: %0.16f',fnorm(a_k_p_quad_-a_k_p_reco_)/fnorm(a_k_p_quad_))); %<-- this should be 2-3 digits. ;
%%%%%%%%;
a_k_Y_quad__ = zeros(n_lm_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
a_k_Y_quad__(1:n_lm_(1+nk_p_r),1+nk_p_r) = a_k_Y_quad_(1+tmp_index_);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;

%%%%%%%%;
% Construct S_k_p_wkS__. ;
%%%%%%%%;
template_k_eq_d = -1;
viewing_k_eq_d = 1.0; %<-- subsample just a few templates for visualization. ;
tmp_t = tic();
[ ...
 S_k_p_wkS__ ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_all_ ...
,n_viewing_all ...
,viewing_azimu_b_all_ ...
,viewing_polar_a_all_ ...
,viewing_weight_all_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,template_k_c_0__ ...
,template_k_c_1__ ...
,template_k_c_2__ ...
] = ...
get_template_1( ...
 0*flag_verbose ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_quad_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_max*ones(n_k_p_r,1) ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% get_template_1: %0.2fs',tmp_t)); end;
if (flag_verbose); disp(sprintf(' %% n_viewing_all %d n_viewing_polar_a %d n_w_max %d',n_viewing_all,n_viewing_polar_a,max(n_w_))); end;
n_S = n_viewing_all; n_w_max = max(n_w_); n_w_sum = sum(n_w_); n_w_csum_ = cumsum([0;n_w_]);

n_viewing_sub = 12; index_viewing_sub_ = floor(linspace(0,n_S-1,n_viewing_sub));
template_viewing_sub_azimu_b_ = viewing_azimu_b_all_(1+index_viewing_sub_);
template_viewing_sub_polar_a_ = viewing_polar_a_all_(1+index_viewing_sub_);
S_k_p_wkn__ = zeros(n_w_sum,n_viewing_sub);
%%%%%%%%;
for nviewing_sub=0:n_viewing_sub-1;
template_viewing_sub_azimu_b = template_viewing_sub_azimu_b_(1+nviewing_sub);
template_viewing_sub_polar_a = template_viewing_sub_polar_a_(1+nviewing_sub);
[ ...
 template_ring_k_c_0__ ...
,template_ring_k_c_1__ ...
,template_ring_k_c_2__ ...
,template_ring_azimu_b__ ...
,template_ring_polar_a__ ...
] = ...
get_template_single_ring_k_c_0( ...
 flag_verbose ...
,1 ...
,template_viewing_sub_azimu_b ...
,template_viewing_sub_polar_a ...
,n_w_max ...
);
%%%%%%%%;
n_order = 5;
ring_azimu_b_scatter_ = template_ring_azimu_b__(:,1+0);
ring_polar_a_scatter_ = template_ring_polar_a__(:,1+0);
[ ...
 ring_scatter_from_tensor_sba__ ...
] = ...
cg_interpolate_n_3( ...
 n_order ...
,shell_n_azimu_b ...
,shell_n_polar_a ...
,n_w_max ...
,ring_azimu_b_scatter_ ...
,ring_polar_a_scatter_ ...
);
%%%%%%%%;
S_k_p_wk_ = zeros(n_w_sum,1);
for nk_p_r=0:n_k_p_r-1;
n_k_all_csum_pre = n_k_all_csum_(1+nk_p_r+0);
n_k_all_csum_pos = n_k_all_csum_(1+nk_p_r+1);
assert(shell_n_k_all==n_k_all_csum_pos-n_k_all_csum_pre);
a_k_p_sub_ = a_k_p_quad_(1+n_k_all_csum_pre+[0:shell_n_k_all-1]);
S_k_p_sub_ = ring_scatter_from_tensor_sba__*a_k_p_sub_;
S_k_p_wk_(1+n_w_csum_(1+nk_p_r)+[0:n_w_max-1]) = S_k_p_sub_;
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
S_k_p_wkn__(:,1+nviewing_sub) = S_k_p_wk_;
clear template_ring* ring_azimu_b_scatter_ ring_polar_a_scatter_ ring_scatter_from_tensor_sba__ S_k_p_wk_;
end;%for nviewing_sub=0:n_viewing_sub-1;
%%%%%%%%;
if (flag_verbose> 0); 
disp(sprintf(' %% S_k_p_wkS__(:,1+index_viewing_sub_) vs S_k_p_wkn__: %0.16f',fnorm(S_k_p_wkS__(:,1+index_viewing_sub_)-S_k_p_wkn__)/fnorm(S_k_p_wkS__(:,1+index_viewing_sub_)))); 
disp(sprintf(' %% S_k_p_wkS__(:,1+randperm(n_S,n_viewing_sub)-1) vs S_k_p_wkn__: %0.16f',fnorm(S_k_p_wkS__(:,1+randperm(n_S,n_viewing_sub)-1)-S_k_p_wkn__)/fnorm(S_k_p_wkS__(:,1+randperm(n_S,n_viewing_sub)-1)))); 
end;%if (flag_verbose> 0); 

flag_disp=1;
if flag_disp;
%%%%%%%%;
% illustrate some of the templates. ;
%%%%%%%%;
np=0;
for nviewing_sub=0:n_viewing_sub-1;
subplot(4,6,1+np);np=np+1; imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,real(S_k_p_wkS__(:,1+index_viewing_sub_(1+nviewing_sub)))); title(sprintf('%.2d <- Y',nviewing_sub));
subplot(4,6,1+np);np=np+1; imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,real(S_k_p_wkn__(:,1+nviewing_sub))); title(sprintf('%.2d <- p',nviewing_sub));
end;%for nviewing_sub=0:n_viewing_sub-1;
end;%if flag_disp;

if flag_verbose; disp(sprintf(' %% [finished %s]',str_thisfunction)); end;

