% tests to see what kind of weights to give a uniform measure on euler-angles so as to cover SO3 uniformly. ;
% It seems reasonable to ensure that polar_a and azimu_b sample the sphere roughly uniformly, and then let gamma_z be uniform. ;
N = 15;
n_polar_a = N; polar_a_ = linspace(0,+pi,n_polar_a+1); polar_a_ = polar_a_(1:end-1);
n_azimu_b_ = zeros(n_polar_a,1);
for npolar_a=1:n_polar_a;
polar_a = polar_a_(npolar_a);
n_azimu_b_(npolar_a) = ceil(2*n_polar_a*abs(sin(polar_a)));
end;%for npolar_a=1:n_polar_a;
n_azimu_b_sum = sum(n_azimu_b_);
n_gamma_z = 2*n_polar_a; gamma_z_ = linspace(-pi,+pi,n_gamma_z+1); gamma_z_ = gamma_z_(1:end-1);
x0__ = zeros(3,n_azimu_b_sum*n_gamma_z);
x1__ = zeros(3,n_azimu_b_sum*n_gamma_z);
x2__ = zeros(3,n_azimu_b_sum*n_gamma_z);
na=0;
for npolar_a=1:n_polar_a; polar_a = polar_a_(npolar_a);
for nazimu_b=1:n_azimu_b_(npolar_a); azimu_b = 2*pi*(nazimu_b-1)/n_azimu_b_(npolar_a);
for ngamma_z=1:n_gamma_z; gamma_z = gamma_z_(ngamma_z);
R_ = euler_to_R([gamma_z,polar_a,azimu_b]); %<-- note reversal of angles. ;
x0__(:,1+na) = R_(:,1+0); x1__(:,1+na) = R_(:,1+1); x2__(:,1+na) = R_(:,1+2); %<-- columns of R*I ;
na = na+1;
end;%for ngamma_z=1:n_gamma_z;
end;%for nazimu_b=1:n_azimu_b_(npolar_a);
end;%for npolar_a=1:n_polar_a;

Msize = 15;
figure;clf;hold on;
%plot3(x0__(1+0,:),x0__(1+1,:),x0__(1+2,:),'ro','MarkerSize',Msize,'MarkerFaceColor','r');
%plot3(x1__(1+0,:),x1__(1+1,:),x1__(1+2,:),'go','MarkerSize',Msize,'MarkerFaceColor','g');
plot3(x2__(1+0,:),x2__(1+1,:),x2__(1+2,:),'bo','MarkerSize',Msize,'MarkerFaceColor','b');
hold off;
view([-65,+20]);
axis vis3d;
set(gca,'XTick',[],'YTick',[],'ZTick',[]);
figbig;
