%%%%%%%%;
% define empirical viewing weights. ;
%%%%%%%%;
tmp_sigma = 1.125*mean(S_p123_l2_S_);
tmp_p123_ = exp(-S_p123_l2_S_(:).^2/(2*tmp_sigma^2));
tmp_p123_ = tmp_p123_ * sum(viewing_weight_all_)./max(1e-12,sum(tmp_p123_.*viewing_weight_all_));
viewing_weight_p123_ = tmp_p123_;
tmp_p231_ = exp(-S_p231_l2_S_(:).^2/(2*tmp_sigma^2));
tmp_p231_ = tmp_p231_ * sum(viewing_weight_all_)./max(1e-12,sum(tmp_p231_.*viewing_weight_all_));
viewing_weight_p231_ = tmp_p231_;
tmp_p312_ = exp(-S_p312_l2_S_(:).^2/(2*tmp_sigma^2));
tmp_p312_ = tmp_p312_ * sum(viewing_weight_all_)./max(1e-12,sum(tmp_p312_.*viewing_weight_all_));
viewing_weight_p312_ = tmp_p312_;
%%%%;
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,3,1); plot(S_p123_l2_S_,viewing_weight_p123_,'.');
xlabel('S_p123_l2_S_','Interpreter','none');
ylabel('viewing_weight_p123_','Interpreter','none');
subplot(1,3,2); plot(S_p231_l2_S_,viewing_weight_p231_,'.');
xlabel('S_p231_l2_S_','Interpreter','none');
ylabel('viewing_weight_p231_','Interpreter','none');
subplot(1,3,3); plot(S_p312_l2_S_,viewing_weight_p312_,'.');
xlabel('S_p312_l2_S_','Interpreter','none');
ylabel('viewing_weight_p312_','Interpreter','none');
fname_fig_pre = sprintf('%s_jpg/test_heterogeneity_spurious_clathrin1_viewing_weight_pxxx_FIGD',dir_pm);
fname_fig_jpg = sprintf('%s.jpg',fname_fig_pre);
fname_fig_stripped_jpg = sprintf('%s_stripped.jpg',fname_fig_pre);
if (flag_replot | ~exist(fname_fig_jpg,'file'));
disp(sprintf(' %% %s not found, creating',fname_fig_jpg));
print('-djpeg',fname_fig_stripped_jpg);
sgtitle(fname_fig_pre,'Interpreter','none');
print('-djpeg',fname_fig_jpg);
end;%if (flag_replot | ~exist(fname_fig_jpg,'file'));
%%%%;
close(gcf);
%%%%%%%%;
