clear;
%%%%%%%%;
platform = 'rusty';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
if (strcmp(platform,'eval1')); setup_eval1; string_root = 'home'; end;
if (strcmp(platform,'rusty')); setup_rusty; string_root = 'mnt/home'; end;
%%%%%%%%;
fname_prefix = 'SR0A_2';
fname_prefix_xfix = sprintf('%s',fname_prefix);
dir_pm = sprintf('/%s/rangan/dir_cryoem/dir_%s/dir_pm',string_root,fname_prefix_xfix);

verbose=1;
snr_per_A_ = 10.^[0:-0.5:-4]; n_snr_per_A = numel(snr_per_A_);
n_M_factor_ = 1:5; n_n_M_factor = numel(n_M_factor_);
n_pick_ = 1:16; n_n_pick = numel(n_pick_);
f_rand_ = [0.00,0.05]; n_f_rand = numel(f_rand_);
local_rseed_ = 0:0; n_local_rseed = numel(local_rseed_);
global_n_iteration = 32;
pm_n_UX_rank_max = 20;
X_insmpfr_______ =  zeros(global_n_iteration,pm_n_UX_rank_max,n_snr_per_A,n_n_M_factor,n_n_pick,n_f_rand,n_local_rseed);
kdl_insmpfr_______ =  zeros(global_n_iteration,pm_n_UX_rank_max,n_snr_per_A,n_n_M_factor,n_n_pick,n_f_rand,n_local_rseed);
na=0;
for nlocal_rseed=0:n_local_rseed-1;
local_rseed = local_rseed_(1+nlocal_rseed);
for nf_rand=0:n_f_rand-1;
f_rand = f_rand_(1+nf_rand);
for nn_pick=0:n_n_pick-1;
n_pick = n_pick_(1+nn_pick);
for nn_M_factor=0:n_n_M_factor-1;
n_M_factor = n_M_factor_(1+nn_M_factor);
for nsnr_per_A=0:n_snr_per_A-1;
snr_per_A = snr_per_A_(1+nsnr_per_A);
%%%%;
str_snr = sprintf('s%.2d',round(10*-log10(snr_per_A)));
str_nMf = sprintf('M%.2d',n_M_factor);
str_npi = sprintf('p%.2d',n_pick);
str_fra = sprintf('f%.2d',round(100*f_rand));
str_rng = sprintf('r%.2d',local_rseed);
string_infix = sprintf('%s%s%s%s%s' ...
,str_snr ...
,str_nMf ...
,str_npi ...
,str_fra ...
,str_rng ...
);
fname_SR0A_pre = sprintf('%s_mat/SR0A_%s',dir_pm,string_infix);
fname_SR0A_mat = sprintf('%s.mat',fname_SR0A_pre);
if (verbose); if (mod(na,128)==0); disp(sprintf(' %% %s',fname_SR0A_mat)); end; end;
if ( exist(fname_SR0A_mat,'file'));
tmp_ = load(fname_SR0A_mat,'X_in__','kld_in__');
X_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed) = tmp_.X_in__;
kld_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed) = tmp_.kld_in__;
end;%if ( exist(fname_SR0A_mat,'file'));
na=na+1;
%%%%;
end;%for nsnr_per_A=0:n_snr_per_A-1;
end;%for nn_M_factor=0:n_n_M_factor-1;
end;%for nn_pick=0:n_n_pick-1;
end;%for nf_rand=0:n_f_rand-1;
end;%for nlocal_rseed=0:n_local_rseed-1;

%%%%%%%%;
% look at some of the X_ and kld_ trajectories. ;
%%%%%%%%;
nf_rand = 0; f_rand = f_rand_(1+nf_rand);
nlocal_rseed = 0; local_rseed = local_rseed_(1+nlocal_rseed);
nn_pick = 15; n_pick = n_pick_(1+nn_pick);
%%%%;
figure(1);clf;figbig;
c_80s__ = colormap_80s; n_c_80s = size(c_80s__,1);
p_row = n_n_M_factor; p_col = n_snr_per_A; np=0;
linewidth_use = 2;
for nn_M_factor=0:n_n_M_factor-1;
n_M_factor = n_M_factor_(1+nn_M_factor);
for nsnr_per_A=0:n_snr_per_A-1;
snr_per_A = snr_per_A_(1+nsnr_per_A);
subplot(p_row,p_col,1+np);np=np+1;
X_in__ = X_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
kld_in__ = kld_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
hold on;
for pm_n_UX_rank=1:pm_n_UX_rank_max;
nc_80s = max(0,min(n_c_80s-1,floor(n_c_80s*pm_n_UX_rank/pm_n_UX_rank_max)));
X_i_ = X_insmpfr_______(:,pm_n_UX_rank,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
kld_i_ = kld_insmpfr_______(:,pm_n_UX_rank,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
plot(1:global_n_iteration,X_i_,'Color',c_80s__(1+nc_80s,:),'LineWidth',linewidth_use);
end;%for pm_n_UX_rank=1:pm_n_UX_rank_max;
hold off;
xlim([1,global_n_iteration]); ylim([-0.25,+1.25]); grid on;
xlabel('iteration'); ylabel('X');
title(sprintf('snr %d %0.6f nMf %d',nsnr_per_A,snr_per_A,n_M_factor),'Interpreter','none');
end;%for nsnr_per_A=0:n_snr_per_A-1;
end;%for nn_M_factor=0:n_n_M_factor-1;
sgtitle(sprintf('X: f_rand %0.2f local_rseed %d n_pick %d',f_rand,local_rseed,n_pick),'Interpreter','none');
%%%%;
figure(2);clf;figbig;
c_80s__ = colormap_80s; n_c_80s = size(c_80s__,1);
p_row = n_n_M_factor; p_col = n_snr_per_A; np=0;
linewidth_use = 2;
for nn_M_factor=0:n_n_M_factor-1;
n_M_factor = n_M_factor_(1+nn_M_factor);
for nsnr_per_A=0:n_snr_per_A-1;
snr_per_A = snr_per_A_(1+nsnr_per_A);
subplot(p_row,p_col,1+np);np=np+1;
X_in__ = X_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
kld_in__ = kld_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
hold on;
for pm_n_UX_rank=1:pm_n_UX_rank_max;
nc_80s = max(0,min(n_c_80s-1,floor(n_c_80s*pm_n_UX_rank/pm_n_UX_rank_max)));
X_i_ = X_insmpfr_______(:,pm_n_UX_rank,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
kld_i_ = kld_insmpfr_______(:,pm_n_UX_rank,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
plot(1:global_n_iteration,kld_i_,'Color',c_80s__(1+nc_80s,:),'LineWidth',linewidth_use);
end;%for pm_n_UX_rank=1:pm_n_UX_rank_max;
hold off;
xlim([1,global_n_iteration]); ylim([-0.25,+1.25]); grid on;
xlabel('iteration'); ylabel('kld');
title(sprintf('snr %d %0.6f nMf %d',nsnr_per_A,snr_per_A,n_M_factor),'Interpreter','none');
end;%for nsnr_per_A=0:n_snr_per_A-1;
end;%for nn_M_factor=0:n_n_M_factor-1;
sgtitle(sprintf('kld: f_rand %0.2f local_rseed %d n_pick %d',f_rand,local_rseed,n_pick),'Interpreter','none');
%%%%;

%%%%%%%%;
% try to visualize side by side. ;
%%%%%%%%;
nf_rand = 1; f_rand = f_rand_(1+nf_rand);
nlocal_rseed = 0; local_rseed = local_rseed_(1+nlocal_rseed);
nn_pick = 15; n_pick = n_pick_(1+nn_pick);
%%%%;
figure(3);clf;figbig; fig80s;
p_row = n_n_M_factor; p_col = n_snr_per_A; np=0;
for nn_M_factor=0:n_n_M_factor-1;
n_M_factor = n_M_factor_(1+nn_M_factor);
for nsnr_per_A=0:n_snr_per_A-1;
snr_per_A = snr_per_A_(1+nsnr_per_A);
subplot(p_row,p_col,1+np);np=np+1;
X_in__ = X_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
kld_in__ = kld_insmpfr_______(:,:,1+nsnr_per_A,1+nn_M_factor,1+nn_pick,1+nf_rand,1+nlocal_rseed);
llim_ = [0.0,1.0]; lmid = mean(llim_);
tmp__ = [ X_in__ , lmid*ones(global_n_iteration,1) , kld_in__ ];
imagesc(tmp__,llim_); axisnotick;
title(sprintf('snr %d %0.6f nMf %d',nsnr_per_A,snr_per_A,n_M_factor),'Interpreter','none');
end;%for nsnr_per_A=0:n_snr_per_A-1;
end;%for nn_M_factor=0:n_n_M_factor-1;
sgtitle(sprintf('X|kld: f_rand %0.2f local_rseed %d n_pick %d',f_rand,local_rseed,n_pick),'Interpreter','none');


