str_thisfunction = 'tfpmh_Z_cluster_wrap_SM__13';

%%%%%%%%;
% First define integral of <f,f>. ;
%%%%%%%%;
h2d_ = @(kd) 4*pi^2*(besselj(0,kd) + besselj(2,kd)); % calculates <f_j,f_k>, normalized so that <f,f> = (4*pi^2);
dh2d_ = @(kd) 4*pi^3*(besselj(-1,kd) - besselj(+3,kd));
h3d_ = @(kd) 4*pi*( sin(kd) - (kd).*cos(kd) ) ./ kd.^3 ; % calculates <f_j,f_k>, normalized so that <f,f> = 4*pi/3;
dh3d_ = @(kd) 12*pi*( (kd.^2/3 - 1) .* sin(kd) + (kd).*cos(kd) ) ./ kd.^4 ;
%%%%%%%%;
flag_verbose=1;
k_p_r_max = 48/(2*pi); k_eq_d = 1.0/(2*pi); str_L = 'L'; flag_uniform_over_n_k_p_r = 1; flag_uniform_over_polar_a = 0;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
if (flag_verbose>0); disp(sprintf(' %% [testing %s]',str_thisfunction)); end;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
if (flag_verbose>0); disp(sprintf(' %% Test grid and template generation: ;')); end;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
%%%%%%%%;
tmp_t=tic();
[ ...
 n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,k_c_0_qk_ ...
,k_c_1_qk_ ...
,k_c_2_qk_ ...
] = ...
sample_sphere_7( ...
 0*flag_verbose ...
,k_p_r_max ...
,k_eq_d ...
,str_L ...
,flag_uniform_over_n_k_p_r ...
,flag_uniform_over_polar_a ...
) ;
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% sample_sphere_7: %0.2fs',tmp_t)); end;
if (flag_verbose>0); disp(sprintf(' %% k_p_r_max %0.2f k_eq_d %0.2f n_qk %d n_k_p_r %d',k_p_r_max,k_eq_d,n_qk,n_k_p_r)); end;
%%%%%%%%;
l_max_upb = round(2*pi*k_p_r_max); %<-- typically sufficient for 2-3 digits of precision. ;
l_max_ = zeros(n_k_p_r,1);
for nk_p_r=0:n_k_p_r-1;
l_max_(1+nk_p_r) = max(0,min(l_max_upb,1+ceil(2*pi*k_p_r_(1+nk_p_r))));
end;%for nk_p_r=0:n_k_p_r-1;
n_y_ = (l_max_+1).^2;
n_y_max = max(n_y_);
n_y_sum = sum(n_y_);
n_y_csum_ = cumsum([0;n_y_]);
l_max_max = max(l_max_);
m_max_ = -l_max_max : +l_max_max;
n_m_max = length(m_max_);
%%%%%%%%;
n_w_max = 2*(l_max_max+1);
template_k_eq_d = -1;
n_w_0in_ = n_w_max*ones(n_k_p_r,1);
[ ...
 n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_p_wk_ ...
,k_p_r_wk_ ...
,k_p_w_wk_ ...
,k_c_0_wk_ ...
,k_c_1_wk_ ...
] = ...
get_weight_2d_2( ...
 0*flag_verbose ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,template_k_eq_d ...
,n_w_0in_ ...
,weight_3d_k_p_r_ ...
);
n_w_sum = sum(n_w_); n_w_max = max(n_w_); n_w_csum_ = cumsum([0;n_w_]);
if (flag_verbose>0); disp(sprintf(' %% n_w_max %d n_w_sum %d',n_w_max,n_w_sum)); end;
%%%%%%%%;
delta_orig_ = [+0.12;-0.3;+0.23];
a_k_p_orig_ = exp(+2*pi*i*(k_c_0_qk_*delta_orig_(1+0) + k_c_1_qk_*delta_orig_(1+1) + k_c_2_qk_*delta_orig_(1+2)));
tmp_t=tic();
[ ...
 a_k_Y_quad_ ...
] = ...
convert_k_p_to_spharm_uniform_over_n_k_p_r_5( ...
 0*flag_verbose ...
,n_qk ...
,n_qk_csum_ ...
,k_p_r_qk_ ...
,k_p_azimu_b_qk_ ...
,k_p_polar_a_qk_ ...
,weight_3d_k_p_qk_ ...
,weight_shell_qk_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_p_orig_ ...
);
tmp_t=toc(tmp_t); disp(sprintf(' %% convert_k_p_to_spharm_5 time %0.2fs',tmp_t));
%%%%%%%%;
a_k_Y_form_ = plane_wave_expansion_1(n_k_p_r,k_p_r_,delta_orig_,l_max_);
fnorm_disp(flag_verbose,'a_k_Y_form_',a_k_Y_form_,'a_k_Y_quad_',a_k_Y_quad_);
%%%%%%%%;
viewing_k_eq_d = 1.0*128; %<-- subsample just a few templates for visualization. ;
tmp_t=tic();
[ ...
 S_k_p_wkS__ ...
,~ ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
] = ...
pm_template_2( ...
 0*flag_verbose ...
,l_max_max ...
,n_k_p_r ...
,reshape(local_yk__from_yk_(n_k_p_r,l_max_,a_k_Y_quad_),[n_y_max,n_k_p_r]) ...
,viewing_k_eq_d/max(1e-12,k_p_r_max) ...
,template_k_eq_d ...
,n_w_max ...
);
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% pm_template_2: %0.2fs',tmp_t)); end;
n_S = n_viewing_S;
S_k_p_wkS__ = reshape(S_k_p_wkS__,[n_w_max*n_k_p_r,n_viewing_S]);
%%%%%%%%;
[ ...
 template_k_p_polar_a_wS__ ...
,template_k_p_azimu_b_wS__ ...
,template_k_c_0_wS__ ...
,template_k_c_1_wS__ ...
,template_k_c_2_wS__ ...
,template_k_p_r01_wS__ ...
] = ...
cg_rhs_2( ...
 n_S ...
,n_w_max ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,zeros(n_S,1) ...
);
template_k_p_polar_a_wkS___ = repmat(reshape(template_k_p_polar_a_wS__,[n_w_max,1,n_S]),[1,n_k_p_r,1]);
template_k_p_azimu_b_wkS___ = repmat(reshape(template_k_p_azimu_b_wS__,[n_w_max,1,n_S]),[1,n_k_p_r,1]);
template_k_p_r_wkS___ = repmat(reshape(k_p_r_,[1,n_k_p_r,1]),[n_w_max,1,n_S]);
template_k_c_0_wkS__ = reshape(template_k_p_r_wkS___.*sin(template_k_p_polar_a_wkS___).*cos(template_k_p_azimu_b_wkS___),[n_w_sum,n_S]);
template_k_c_1_wkS__ = reshape(template_k_p_r_wkS___.*sin(template_k_p_polar_a_wkS___).*sin(template_k_p_azimu_b_wkS___),[n_w_sum,n_S]);
template_k_c_2_wkS__ = reshape(template_k_p_r_wkS___.*cos(template_k_p_polar_a_wkS___),[n_w_sum,n_S]);
%%%%%%%%;
pole_k_c_0_ = zeros(n_w_sum,1);
pole_k_c_1_ = zeros(n_w_sum,1);
pole_k_c_2_ = zeros(n_w_sum,1);
na=0;
for nk_p_r=0:n_k_p_r-1;
k_p_r = k_p_r_(1+nk_p_r);
n_w = n_w_(1+nk_p_r);
for nw=0:n_w-1;
gamma_z = 2*pi*nw/n_w;
cc = cos(gamma_z); sc = sin(gamma_z);
pole_k_c_0_(1+na) = k_p_r*cc;
pole_k_c_1_(1+na) = k_p_r*sc;
pole_k_c_2_(1+na) = 0;
na=na+1;
end;%for nw=0:n_w-1;
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
% after calling get_template_1: ;
% A template with viewing angle viewing_polar_a and viewing_azimu_b corresponds to the evaluations: ;
% let sa and ca be sin(polar_a) and cos(polar_a), respectively. ;
% let sb and cb be sin(azimu_b) and cos(azimu_b), respectively. ;
% let sc and cc be sin(gamma_z) and cos(gamma_z), respectively. ;
% [ template_k_c_0 ; template_k_c_1 ; template_k_c_2 ] = [ +cb*ca*cc - sb*sc ; +sb*ca*cc + cb*sc ; -sa*cc ] ;
% for gamma_z = 2*pi*[0:n_gamma_z-1]/n_gamma_z. ;
% Given that the original function is a plane-wave defined as: ;
% a_k_p_ = exp(+2*pi*i*( delta_orig_(1+0)*template_k_c_0 + delta_orig_(1+1)*template_k_c_1 + delta_orig_(1+2)*template_k_c_2 )) ;
% we have that the template evaluates to: ;
% S_k_p_ = exp(+2*pi*i*( delta_orig_ * Rz(azimu_b) * Ry(polar_a) * Rz(gamma_z) * [1;0;0]*k_p_r )) ;
% S_k_p_ = exp(+2*pi*i*( (Ry(-polar_a) * Rz(-azimu_b) * delta_orig_) * Rz(gamma_z) * [1;0;0]*k_p_r )) ;
%%%%%%%%;
n_test = 8;
for ntest=0:n_test-1;
nS=max(0,min(n_S-1,floor(n_S*rand())));
disp(sprintf(' %% ntest %d/%d --> nS %d',ntest,n_test,nS));
S_k_p_quad_ = S_k_p_wkS__(:,1+nS);
S_k_p_orig_ = exp(+2*pi*i*(template_k_c_0_wkS__(:,1+nS)*delta_orig_(1+0) + template_k_c_1_wkS__(:,1+nS)*delta_orig_(1+1) + template_k_c_2_wkS__(:,1+nS)*delta_orig_(1+2)));
viewing_azimu_b = viewing_azimu_b_S_(1+nS);
cb = cos(+viewing_azimu_b); sb = sin(+viewing_azimu_b);
Rz = [ +cb , -sb , 0 ; +sb , +cb , 0 ; 0 , 0 , 1 ]; %<-- rotation about the positive z-axis. ;
viewing_polar_a = viewing_polar_a_S_(1+nS);
ca = cos(+viewing_polar_a); sa = sin(+viewing_polar_a);
Ry = [ +ca , 0 , +sa ; 0 , 1 , 0 ; -sa , 0 , +ca ]; %<-- rotation about the positive y-axis. ;
delta_temp_ = transpose(Ry)*transpose(Rz)*delta_orig_;
S_k_p_form_ = exp(+2*pi*i*(pole_k_c_0_*delta_temp_(1+0) + pole_k_c_1_*delta_temp_(1+1) + pole_k_c_2_*delta_temp_(1+2)));
flag_plot=0;
if flag_plot;
figure(1);clf;
subplot(2,3,1+0); imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,real(S_k_p_orig_),[-1,+1],colormap_beach()); title('real orig'); axisnotick; axis image;
subplot(2,3,1+3); imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,imag(S_k_p_orig_),[-1,+1],colormap_beach()); title('imag orig'); axisnotick; axis image;
subplot(2,3,2+0); imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,real(S_k_p_quad_),[-1,+1],colormap_beach()); title('real quad'); axisnotick; axis image;
subplot(2,3,2+3); imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,imag(S_k_p_quad_),[-1,+1],colormap_beach()); title('imag quad'); axisnotick; axis image;
subplot(2,3,3+0); imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,real(S_k_p_form_),[-1,+1],colormap_beach()); title('real form'); axisnotick; axis image;
subplot(2,3,3+3); imagesc_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,imag(S_k_p_form_),[-1,+1],colormap_beach()); title('imag form'); axisnotick; axis image;
figbig;
end;%if flag_plot;
fnorm_disp(flag_verbose,'S_k_p_orig_',S_k_p_orig_,'S_k_p_quad_',S_k_p_quad_);
fnorm_disp(flag_verbose,'S_k_p_orig_',S_k_p_orig_,'S_k_p_form_',S_k_p_form_);
end;%for ntest=0:n_test-1;
%%%%%%%%;
S_k_q_wkS__ = interp_p_to_q(n_k_p_r,n_w_,n_w_sum,S_k_p_wkS__);
tmp_t=tic();
S_k_p_form__ = zeros(n_w_sum,n_S);
S_k_q_form__ = zeros(n_w_sum,n_S);
for nS=0:n_S-1;
viewing_azimu_b = viewing_azimu_b_S_(1+nS);
cb = cos(+viewing_azimu_b); sb = sin(+viewing_azimu_b);
Rz = [ +cb , -sb , 0 ; +sb , +cb , 0 ; 0 , 0 , 1 ]; %<-- rotation about the positive z-axis. ;
viewing_polar_a = viewing_polar_a_S_(1+nS);
ca = cos(+viewing_polar_a); sa = sin(+viewing_polar_a);
Ry = [ +ca , 0 , +sa ; 0 , 1 , 0 ; -sa , 0 , +ca ]; %<-- rotation about the positive y-axis. ;
delta_temp_ = transpose(Ry)*transpose(Rz)*delta_orig_;
S_k_p_form_ = exp(+2*pi*i*(pole_k_c_0_*delta_temp_(1+0) + pole_k_c_1_*delta_temp_(1+1) + pole_k_c_2_*delta_temp_(1+2)));
S_k_p_form__(:,1+nS) = S_k_p_form_;
S_k_q_form_ = interp_p_to_q(n_k_p_r,n_w_,n_w_sum,S_k_p_form_);
S_k_q_form__(:,1+nS) = S_k_q_form_;
end;%for nS=0:n_S-1;
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% S_k_q_form__: %0.3fs',tmp_t)); end;
fnorm_disp(flag_verbose,'S_k_p_form__',S_k_p_form__,'S_k_p_wkS__',S_k_p_wkS__);
fnorm_disp(flag_verbose,'S_k_q_form__',S_k_q_form__,'S_k_q_wkS__',S_k_q_wkS__);
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
if (flag_verbose>0); disp(sprintf(' %% A simple test assuming isotropic CTF: ;')); end;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
%%%%%%%%;
delta_r_max = 0.05; n_delta_v_requested = 64;
delta_r_p = 0.05;
delta_r_s = delta_r_max/sqrt(2*log(1/delta_r_p));
delta_r_N = delta_r_max * (2*pi*k_p_r_max) / (pi*sqrt(2));
svd_eps = 1e-12;
tmp_t=tic();
FTK = tfh_FTK_2(n_k_p_r,k_p_r_,k_p_r_max,delta_r_max,svd_eps,n_delta_v_requested);
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% FTK: %0.3fs',tmp_t)); end;
disp(sprintf(' %% p-val %0.4f delta_r_max %0.6f sigma %0.4f N_pixel %0.4f --> FTK.n_svd_l %d, n_delta_v_requested %d',delta_r_p,delta_r_max,delta_r_s,delta_r_N,FTK.n_svd_l,n_delta_v_requested));
%%%%%%%%;
% design index_nCTF_from_nM_. ;
%%%%%%%%;
n_M = n_S - 1; %<-- just to check dimensions. ;
n_CTF = 2;
index_nCTF_from_nM_ = mod(0:n_M-1,n_CTF);
CTF_k_p_r_kC__ = zeros(n_k_p_r,n_CTF);
%CTF_k_p_r_kC__ = 1 + rand(n_k_p_r,n_CTF); %<-- invertible. ;
for nCTF=0:n_CTF-1;
CTF_k_p_r_kC__(:,1+nCTF) = 1.5 + sin(2*pi*(1+nCTF/n_CTF)*k_p_r_/k_p_r_max); %<-- invertible. ;
end;%for nCTF=0:n_CTF-1;
%%%%%%%%;
%  Construct CTF of same size as images. ;
%%%%%%%%;
CTF_k_p_wkC__ = zeros(n_w_sum,n_CTF);
for nCTF=0:n_CTF-1;
for nk_p_r=0:n_k_p_r-1;
n_w = n_w_(1+nk_p_r);
tmp_index_ = n_w_csum_(1+nk_p_r) + [0:n_w-1];
CTF_k_p_wkC__(1+tmp_index_,1+nCTF) = CTF_k_p_r_kC__(1+nk_p_r,1+nCTF);
end;%for nk_p_r=0:n_k_p_r-1;
end;%for nCTF=0:n_CTF-1;
CTF_inv_k_p_wkC__ = 1./max(1e-12,CTF_k_p_wkC__);
%%%%%%%%;
% Generate images to use. ;
%%%%%%%%;
M_k_p_wkM__ = S_k_p_form__(:,1:n_M);
M_k_q_wkM__ = S_k_q_form__(:,1:n_M);
for nM=0:n_M-1;
nCTF = index_nCTF_from_nM_(1+nM);
M_k_p_wkM__(:,1+nM) = M_k_p_wkM__(:,1+nM).*CTF_inv_k_p_wkC__(:,1+nCTF);
M_k_q_wkM__(:,1+nM) = M_k_q_wkM__(:,1+nM).*CTF_inv_k_p_wkC__(:,1+nCTF);
end;%for nM=0:n_M-1;
%%%%%%%%;
n_cluster = n_CTF;
index_ncluster_from_nCTF_ = mod(transpose(0:n_CTF-1),n_cluster); %<-- give each nCTF its own cluster. ;
index_ncluster_from_nM_ = index_ncluster_from_nCTF_(1+index_nCTF_from_nM_);
index_nM_from_ncluster__ = cell(n_cluster,1);
n_index_nM_from_ncluster_ = zeros(n_cluster,1);
for ncluster=0:n_cluster-1;
index_nM_from_ncluster__{1+ncluster} = efind(index_ncluster_from_nM_==ncluster);
n_index_nM_from_ncluster_(1+ncluster) = numel(index_nM_from_ncluster__{1+ncluster});
end;%for ncluster=0:n_cluster-1;
%%%%%%%%;
% design principal-modes. ;
%%%%%%%%;
tmp_t=tic();
pm_n_UX_rank_max = n_k_p_r-1; %<-- just to check dimensions.; 
pm_n_UX_rank_c_ = max(1,min(n_k_p_r-1,pm_n_UX_rank_max - transpose([0:n_cluster-1])));
pm_UX_knc___ = zeros(n_k_p_r,pm_n_UX_rank_max,n_cluster);
pm_X_weight_rc__ = zeros(n_k_p_r,n_cluster);
for ncluster=0:n_cluster-1;
pm_n_UX_rank = pm_n_UX_rank_c_(1+ncluster);
index_nM_from_ncluster_ = index_nM_from_ncluster__{1+ncluster};
tmp_n_M = numel(index_nM_from_ncluster_);
assert(tmp_n_M==n_index_nM_from_ncluster_(1+ncluster));
tmp_M_k_p_wkM__ = M_k_p_wkM__(:,1+index_nM_from_ncluster_);
[ ...
 X_kk__ ...
,X_weight_r_ ...
] = ...
principled_marching_empirical_cost_matrix_0( ...
 n_k_p_r ...
,k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,tmp_n_M ...
,tmp_M_k_p_wkM__ ...
);
[tmp_UX_kn__,tmp_SX_k__,tmp_VX_kn__] = svds(X_kk__,pm_n_UX_rank);
pm_UX_knc___(:,1:pm_n_UX_rank,1+ncluster) = tmp_UX_kn__(:,1:pm_n_UX_rank);
pm_X_weight_rc__(:,1+ncluster) = X_weight_r_;
end;%for ncluster=0:n_cluster-1;
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% pm_UX_knc___: %0.3fs',tmp_t)); end;
%%%%%%%%;
% Now calculate the inner-products. ;
%%%%%%%%;
tmp_t=tic();
parameter = struct('type','parameter');
[ ...
 parameter ...
,Z_SM_tfpm__ ...
,UX_CTF_R_S_l2_SM_tfpm__ ...
,UX_T_M_l2_SM_tfpm__ ...
,X_SM_tfpm__ ...
,delta_x_SM_tfpm__ ...
,delta_y_SM_tfpm__ ...
,gamma_z_SM_tfpm__ ...
,index_sub_SM_tfpm__ ...
,index_nM_from_ncluster__ ...
,n_index_nM_from_ncluster_ ...
] = ...
tfpmh_Z_cluster_wrap_SM__13( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_p_wk_ ...
,n_S ...
,S_k_p_wkS__ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,n_cluster ...
,index_ncluster_from_nCTF_ ...
,pm_n_UX_rank_c_ ...
,pm_UX_knc___ ...
,pm_X_weight_rc__ ...
,FTK ...
);
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% X_SM_tfpm__: %0.3fs',tmp_t)); end;
%%%%%%%%;
% Calculate true landscape of innerproducts for the same set of translations. ;
%%%%%%%%;
X_SM_form__ = zeros(n_S,n_M);
X_SM_quad__ = zeros(n_S,n_M);
for nS=0:n_S-1;
viewing_azimu_b = viewing_azimu_b_S_(1+nS);
cb = cos(+viewing_azimu_b); sb = sin(+viewing_azimu_b);
Rz = [ +cb , -sb , 0 ; +sb , +cb , 0 ; 0 , 0 , 1 ]; %<-- rotation about the positive z-axis. ;
viewing_polar_a = viewing_polar_a_S_(1+nS);
ca = cos(+viewing_polar_a); sa = sin(+viewing_polar_a);
Ry = [ +ca , 0 , +sa ; 0 , 1 , 0 ; -sa , 0 , +ca ]; %<-- rotation about the positive y-axis. ;
delta_temp_0_ = transpose(Ry)*transpose(Rz)*delta_orig_;
for nM=0:n_M-1;
nCTF = index_nCTF_from_nM_(1+nM);
CTF_k_p_wk_ = CTF_k_p_wkC__(:,1+nCTF);
CTF_inv_k_p_wk_ = CTF_inv_k_p_wkC__(:,1+nCTF);
image_viewing_azimu_b = viewing_azimu_b_S_(1+nM);
cb = cos(+image_viewing_azimu_b); sb = sin(+image_viewing_azimu_b);
Rz = [ +cb , -sb , 0 ; +sb , +cb , 0 ; 0 , 0 , 1 ]; %<-- rotation about the positive z-axis. ;
image_viewing_polar_a = viewing_polar_a_S_(1+nM);
ca = cos(+image_viewing_polar_a); sa = sin(+image_viewing_polar_a);
Ry = [ +ca , 0 , +sa ; 0 , 1 , 0 ; -sa , 0 , +ca ]; %<-- rotation about the positive y-axis. ;
delta_temp_1_ = transpose(Ry)*transpose(Rz)*delta_orig_;
%%%%;
gamma_z = gamma_z_SM_tfpm__(1+nS,1+nM);%gamma_z = 2*pi*nw/n_w_max;
cc = cos(+gamma_z); sc = sin(+gamma_z);
Rz = [+cc , -sc ; +sc , +cc];
delta_x = delta_x_SM_tfpm__(1+nS,1+nM);
delta_y = delta_y_SM_tfpm__(1+nS,1+nM);
delta_temp_0b_ = Rz*delta_temp_0_(1+[0:1]); %<-- rotate delta_temp_0_ by +gamma_z = rotate k by -gamma_z = rotate S_0 by +gamma_z. ;
delta_temp_1b_ = delta_temp_1_(1+[0:1]) - [delta_x;delta_y]; %<-- translate delta_temp_1_ by -delta_ = multiply S_1 by exp(-2*pi*i*dot(k_,delta_)). ;
%%%%;
S_k_p_form_ = exp(+2*pi*i*(pole_k_c_0_*delta_temp_0b_(1+0) + pole_k_c_1_*delta_temp_0b_(1+1)));
S_k_p_temp_ = S_k_p_form_.*CTF_k_p_wk_;
M_k_p_form_ = exp(+2*pi*i*(pole_k_c_0_*delta_temp_1b_(1+0) + pole_k_c_1_*delta_temp_1b_(1+1)));
M_k_p_temp_ = M_k_p_form_.*CTF_inv_k_p_wk_;
%%%%;
S_l2_quad = sqrt(sum(reshape(conj(S_k_p_temp_).*S_k_p_temp_,[n_w_max,n_k_p_r])*weight_2d_k_p_r_)/n_w_max);
M_l2_quad = sqrt(sum(reshape(conj(M_k_p_temp_).*M_k_p_temp_,[n_w_max,n_k_p_r])*weight_2d_k_p_r_)/n_w_max);
%%%%;
X_form = h2d_(2*pi*k_p_r_max*fnorm(delta_temp_0b_ - delta_temp_1b_))/(2*pi)^2 * (pi*k_p_r_max^2); %<-- note sign of translation. ;
X_SM_form__(1+nS,1+nM) = real(X_form) / (S_l2_quad*M_l2_quad) ;
%%%%;
X_quad = sum(reshape(conj(S_k_p_temp_).*M_k_p_temp_,[n_w_max,n_k_p_r])*weight_2d_k_p_r_)/n_w_max;
X_SM_quad__(1+nS,1+nM) = real(X_quad) / (S_l2_quad*M_l2_quad) ;
%%%%;
end;%for nM=0:n_M-1;
end;%for nS=0:n_S-1;
%%%%%%%%;
fnorm_disp(flag_verbose,'X_SM_form__',X_SM_form__,'X_SM_tfpm__',X_SM_tfpm__);
fnorm_disp(flag_verbose,'X_SM_quad__',X_SM_quad__,'X_SM_tfpm__',X_SM_tfpm__);
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
if (flag_verbose>0); disp(sprintf(' %% A more complicated test assuming anisotropic CTF: ;')); end;
if (flag_verbose>0); disp(sprintf(' %% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;')); end;
%%%%%%%%;
n_2 = 2;
%%%%;
n_source_S = 7; delta_source_2sS___ = 0.10*(2*rand(n_2,n_source_S,n_S)-1);
for nS=0:n_S-1;
S_k_p_wkS__(:,1+nS) = zeros(n_w_sum,1);
for nsource_S=0:n_source_S-1;
tmp_wk_ = exp(+2*pi*i*(k_c_0_wk_*delta_source_2sS___(1+0,1+nsource_S,1+nS) + k_c_1_wk_*delta_source_2sS___(1+1,1+nsource_S,1+nS)));
S_k_p_wkS__(:,1+nS) = S_k_p_wkS__(:,1+nS) + tmp_wk_;
end;%for nsource_S=0:n_source_S-1;
end;%for nS=0:n_S-1;
%%%%;
n_source_M = 8; delta_source_2sM___ = 0.10*(2*rand(n_2,n_source_M,n_M)-1);
for nM=0:n_M-1;
M_k_p_wkM__(:,1+nM) = zeros(n_w_sum,1);
for nsource_M=0:n_source_M-1;
tmp_wk_ = exp(+2*pi*i*(k_c_0_wk_*delta_source_2sM___(1+0,1+nsource_M,1+nM) + k_c_1_wk_*delta_source_2sM___(1+1,1+nsource_M,1+nM)));
M_k_p_wkM__(:,1+nM) = M_k_p_wkM__(:,1+nM) + tmp_wk_;
end;%for nsource_M=0:n_source_M-1;
end;%for nM=0:n_M-1;
%%%%;
n_source_C = 9; delta_source_2sC___ = 0.10*(2*rand(n_2,n_source_C,n_CTF)-1);
for nCTF=0:n_CTF-1;
CTF_k_p_wkC__(:,1+nCTF) = zeros(n_w_sum,1);
for nsource_C=0:n_source_C-1;
tmp_wk_ = real(exp(+2*pi*i*(k_c_0_wk_*delta_source_2sC___(1+0,1+nsource_C,1+nCTF) + k_c_1_wk_*delta_source_2sC___(1+1,1+nsource_C,1+nCTF)))); %<-- assumed to be real. ;
CTF_k_p_wkC__(:,1+nCTF) = CTF_k_p_wkC__(:,1+nCTF) + tmp_wk_;
end;%for nsource_C=0:n_source_C-1;
end;%for nCTF=0:n_CTF-1;
%%%%%%%%;
% recalculate principal-modes. ;
%%%%%%%%;
tmp_t=tic();
pm_n_UX_rank_max = min(n_k_p_r-1,5); %pm_n_UX_rank = n_k_p_r-1; %<-- just to check dimensions.; 
pm_n_UX_rank_c_ = max(1,min(n_k_p_r-1,pm_n_UX_rank_max - transpose([0:n_cluster-1])));
pm_UX_knc___ = zeros(n_k_p_r,pm_n_UX_rank_max,n_cluster);
pm_X_weight_rc__ = zeros(n_k_p_r,n_cluster);
for ncluster=0:n_cluster-1;
pm_n_UX_rank = pm_n_UX_rank_c_(1+ncluster);
index_nM_from_ncluster_ = index_nM_from_ncluster__{1+ncluster};
tmp_n_M = numel(index_nM_from_ncluster_);
assert(tmp_n_M==n_index_nM_from_ncluster_(1+ncluster));
tmp_M_k_p_wkM__ = M_k_p_wkM__(:,1+index_nM_from_ncluster_);
[ ...
 X_kk__ ...
,X_weight_r_ ...
] = ...
principled_marching_empirical_cost_matrix_0( ...
 n_k_p_r ...
,k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,tmp_n_M ...
,tmp_M_k_p_wkM__ ...
);
[tmp_UX_kn__,tmp_SX_k__,tmp_VX_kn__] = svds(X_kk__,pm_n_UX_rank);
pm_UX_knc___(:,1:pm_n_UX_rank,1+ncluster) = tmp_UX_kn__(:,1:pm_n_UX_rank);
pm_X_weight_rc__(:,1+ncluster) = X_weight_r_;
end;%for ncluster=0:n_cluster-1;
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% pm_UX_knc___: %0.3fs',tmp_t)); end;
%%%%%%%%;
% Now calculate the inner-products. ;
%%%%%%%%;
tmp_t=tic();
parameter = struct('type','parameter');
parameter.flag_CTF_anisotropic = 1;
[ ...
 parameter ...
,Z_SM_tfpm__ ...
,UX_CTF_R_S_l2_SM_tfpm__ ...
,UX_T_M_l2_SM_tfpm__ ...
,X_SM_tfpm__ ...
,delta_x_SM_tfpm__ ...
,delta_y_SM_tfpm__ ...
,gamma_z_SM_tfpm__ ...
,index_sub_SM_tfpm__ ...
,index_nM_from_ncluster__ ...
,n_index_nM_from_ncluster_ ...
] = ...
tfpmh_Z_cluster_wrap_SM__13( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_p_wk_ ...
,n_S ...
,S_k_p_wkS__ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,n_cluster ...
,index_ncluster_from_nCTF_ ...
,pm_n_UX_rank_c_ ...
,pm_UX_knc___ ...
,pm_X_weight_rc__ ...
,FTK ...
);
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% X_SM_tfpm__: %0.3fs',tmp_t)); end;
%%%%%%%%;
% Calculate true landscape of innerproducts for the same set of translations. ;
%%%%%%%%;
X_SM_quad__ = zeros(n_S,n_M);
Z_SM_quad__ = zeros(n_S,n_M);
for nS=0:n_S-1;
S_k_p_wk_ = S_k_p_wkS__(:,1+nS);
for nM=0:n_M-1;
M_k_p_wk_ = M_k_p_wkM__(:,1+nM);
ncluster = index_ncluster_from_nM_(1+nM);
pm_n_UX_rank = pm_n_UX_rank_c_(1+ncluster); pm_n_w_max = n_w_max; pm_n_w_sum = pm_n_w_max*pm_n_UX_rank;
pm_UX_kn__ = pm_UX_knc___(:,1:pm_n_UX_rank,1+ncluster);
pm_X_weight_r_ = pm_X_weight_rc__(:,1+ncluster);
pm_wUX_kn__ = bsxfun(@times,reshape(pm_X_weight_r_,[n_k_p_r,1]),pm_UX_kn__);
nCTF = index_nCTF_from_nM_(1+nM);
CTF_k_p_wk_ = CTF_k_p_wkC__(:,1+nCTF);
gamma_z = gamma_z_SM_tfpm__(1+nS,1+nM);
delta_x = delta_x_SM_tfpm__(1+nS,1+nM);
delta_y = delta_y_SM_tfpm__(1+nS,1+nM);
RS_k_p_wk_ = rotate_p_to_p_fftw(n_k_p_r,n_w_,n_w_sum,S_k_p_wk_,+gamma_z);
QS_k_p_wk_ = rotate_p_to_p_fftw(n_k_p_r,n_w_,n_w_sum,S_k_p_wk_,+0);
CTF_RS_k_p_wk_ = RS_k_p_wk_.*CTF_k_p_wk_;
CTF_QS_k_p_wk_ = QS_k_p_wk_.*CTF_k_p_wk_;
UX_CTF_RS_k_p_wn_ = reshape(reshape(CTF_RS_k_p_wk_,[n_w_max,n_k_p_r])*pm_wUX_kn__,[pm_n_w_sum,1]);
UX_CTF_QS_k_p_wn_ = reshape(reshape(CTF_QS_k_p_wk_,[n_w_max,n_k_p_r])*pm_wUX_kn__,[pm_n_w_sum,1]);
UX_CTF_RS_l2 = sum(conj(UX_CTF_RS_k_p_wn_).*UX_CTF_RS_k_p_wn_) / max(1,pm_n_w_max) ;
UX_CTF_QS_l2 = sum(conj(UX_CTF_QS_k_p_wn_).*UX_CTF_QS_k_p_wn_) / max(1,pm_n_w_max) ;
TM_k_p_wk_ = transf_p_to_p(n_k_p_r,k_p_r_,n_w_,n_w_sum,M_k_p_wk_,+delta_x,+delta_y);
UX_TM_k_p_wn_ = reshape(reshape(TM_k_p_wk_,[n_w_max,n_k_p_r])*pm_wUX_kn__,[pm_n_w_sum,1]);
UX_TM_l2 = sum(conj(UX_TM_k_p_wn_).*UX_TM_k_p_wn_) / max(1,pm_n_w_max) ;
UX_CTF_RS_k_p_UX_TM_k_p = sum(conj(UX_CTF_RS_k_p_wn_).*UX_TM_k_p_wn_) / max(1,pm_n_w_max) ;
Z_quad = UX_CTF_RS_k_p_UX_TM_k_p;
if parameter.flag_CTF_anisotropic==0; X_quad = Z_quad / max(1e-12,sqrt(UX_CTF_QS_l2)) / max(1e-12,sqrt(UX_TM_l2)); end;
if parameter.flag_CTF_anisotropic==1; X_quad = Z_quad / max(1e-12,sqrt(UX_CTF_RS_l2)) / max(1e-12,sqrt(UX_TM_l2)); end;
Z_SM_quad__(1+nS,1+nM) = real(Z_quad);
X_SM_quad__(1+nS,1+nM) = real(X_quad);
%%%%;
end;%for nM=0:n_M-1;
end;%for nS=0:n_S-1;
%%%%%%%%;
fnorm_disp(flag_verbose,'Z_SM_quad__',Z_SM_quad__,'Z_SM_tfpm__',Z_SM_tfpm__);
fnorm_disp(flag_verbose,'X_SM_quad__',X_SM_quad__,'X_SM_tfpm__',X_SM_tfpm__);
%%%%%%%%;

%%%%%%%%;
% Now repeat with precalculation. ;
%%%%%%%%;
tmp_t=tic();
if ~exist('index_nM_to_update_','var'); index_nM_to_update_=[]; end;
if ~exist('M_k_q_wkM__','var'); M_k_q_wkM__=[]; end;
if ~exist('UX_T_M_l2_dM__','var'); UX_T_M_l2_dM__=[]; end;
if ~exist('UX_M_l2_M_','var'); UX_M_l2_M_=[]; end;
if ~exist('CTF_M_k_q_wkM__','var'); CTF_M_k_q_wkM__=[]; end;
if ~exist('CTF_k_q_wkM__','var'); CTF_k_q_wkM__=[]; end;
if ~exist('UX_CC_k_q_wnM__','var'); UX_CC_k_q_wnM__=[]; end;
if ~exist('svd_V_UX_CTF_M_lwnM____','var'); svd_V_UX_CTF_M_lwnM____=[]; end;
if ~exist('svd_V_UX_M_lwnM____','var'); svd_V_UX_M_lwnM____=[]; end;
if ~exist('index_nS_to_update_','var'); index_nS_to_update_=[]; end;
if ~exist('UX_S_k_q_wnS__','var'); UX_S_k_q_wnS__=[]; end;
if ~exist('UX_SS_k_q_wnS__','var'); UX_SS_k_q_wnS__=[]; end;
parameter = struct('type','parameter');
parameter.flag_CTF_anisotropic = 1;
index_nM_to_update_ = transpose(0:n_M-1);
index_nS_to_update_ = [];
parameter.flag_precompute_M_k_q_wkM__ = 1*1;
parameter.flag_precompute_UX_T_M_l2_dM__ = 1*1;
parameter.flag_precompute_UX_M_l2_M_ = 1*1;
parameter.flag_precompute_CTF_M_k_q_wkM__ = 1*1;
parameter.flag_precompute_CTF_k_q_wkM__ = 1*1;
parameter.flag_precompute_UX_CC_k_q_wnM__ = 1*1;
parameter.flag_precompute_svd_V_UX_CTF_M_lwnM____ = 1*1;
parameter.flag_precompute_svd_V_UX_M_lwnM____ = 1*1;
parameter.flag_precompute_UX_S_k_q_wnS__ = 0;
parameter.flag_precompute_UX_SS_k_q_wnS__ = 0;
[ ...
 parameter ...
,tmp_Z_SM_tfpm__ ...
,tmp_UX_CTF_R_S_l2_SM_tfpm__ ...
,tmp_UX_T_M_l2_SM_tfpm__ ...
,tmp_X_SM_tfpm__ ...
,tmp_delta_x_SM_tfpm__ ...
,tmp_delta_y_SM_tfpm__ ...
,tmp_gamma_z_SM_tfpm__ ...
,tmp_index_sub_SM_tfpm__ ...
,tmp_index_nM_from_ncluster__ ...
,tmp_n_index_nM_from_ncluster_ ...
,tmp_M_k_q_wkM__ ...
,tmp_UX_T_M_l2_dM__ ...
,tmp_UX_M_l2_M_ ...
,tmp_CTF_M_k_q_wkM__ ...
,tmp_CTF_k_q_wkM__ ...
,tmp_UX_CC_k_q_wnM__ ...
,tmp_svd_V_UX_CTF_M_lwnM____ ...
,tmp_svd_V_UX_M_lwnM____ ...
,tmp_UX_S_k_q_wnS__ ...
,tmp_UX_SS_k_q_wnS__ ...
] = ...
tfpmh_Z_cluster_wrap_SM__13( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_p_wk_ ...
,n_S ...
,S_k_p_wkS__ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,n_cluster ...
,index_ncluster_from_nCTF_ ...
,pm_n_UX_rank_c_ ...
,pm_UX_knc___ ...
,pm_X_weight_rc__ ...
,FTK ...
,index_nM_to_update_ ...
,M_k_q_wkM__ ...
,UX_T_M_l2_dM__ ...
,UX_M_l2_M_ ...
,CTF_M_k_q_wkM__ ...
,CTF_k_q_wkM__ ...
,UX_CC_k_q_wnM__ ...
,svd_V_UX_CTF_M_lwnM____ ...
,svd_V_UX_M_lwnM____ ...
,index_nS_to_update_ ...
,UX_S_k_q_wnS__ ...
,UX_SS_k_q_wnS__ ...
);
tmp_t=toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% X_SM_tfpm__: %0.3fs',tmp_t)); end;
%%%%%%%%;
fnorm_disp(flag_verbose,'Z_SM_tfpm__',Z_SM_tfpm__,'tmp_Z_SM_tfpm__',tmp_Z_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'UX_CTF_R_S_l2_SM_tfpm__',UX_CTF_R_S_l2_SM_tfpm__,'tmp_UX_CTF_R_S_l2_SM_tfpm__',tmp_UX_CTF_R_S_l2_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'UX_T_M_l2_SM_tfpm__',UX_T_M_l2_SM_tfpm__,'tmp_UX_T_M_l2_SM_tfpm__',tmp_UX_T_M_l2_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'X_SM_tfpm__',X_SM_tfpm__,'tmp_X_SM_tfpm__',tmp_X_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'delta_x_SM_tfpm__',delta_x_SM_tfpm__,'tmp_delta_x_SM_tfpm__',tmp_delta_x_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'delta_y_SM_tfpm__',delta_y_SM_tfpm__,'tmp_delta_y_SM_tfpm__',tmp_delta_y_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'gamma_z_SM_tfpm__',gamma_z_SM_tfpm__,'tmp_gamma_z_SM_tfpm__',tmp_gamma_z_SM_tfpm__,' %%<-- should be zero');
fnorm_disp(flag_verbose,'index_sub_SM_tfpm__',index_sub_SM_tfpm__,'tmp_index_sub_SM_tfpm__',tmp_index_sub_SM_tfpm__,' %%<-- should be zero');
