%%%%%%%%;
% Recalculate templates using unit norm volume. ;
%%%%%%%%;
[ ...
 X0_quad ...
,C0_quad ...
] = ...
register_spharm_to_spharm_3( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p123_k_Y_quad_ ...
,a_p123_k_Y_quad_ ...
);
%%%%%%%%;
a_p123_k_Y_norm_yk_ = a_p123_k_Y_quad_/max(1e-12,sqrt(X0_quad));
a_p123_k_Y_norm_yk__ = zeros(n_lm_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
a_p123_k_Y_norm_yk__(1:n_lm_(1+nk_p_r),1+nk_p_r) = a_p123_k_Y_norm_yk_(1+tmp_index_);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
[ ...
 X0_norm ...
,C0_norm ...
] = ...
register_spharm_to_spharm_3( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p123_k_Y_norm_yk_ ...
,a_p123_k_Y_norm_yk_ ...
);
%%%%%%%%;
if (verbose>0); disp(sprintf(' %% p123: X0_norm %0.6f',X0_norm)); end;

tmp_t = tic();
[ ...
 S_p123_k_p__ ...
,~ ...
,tmp_n_S ...
,~ ...
,~ ...
] = ...
pm_template_2( ...
 verbose ...
,l_max_max...
,n_k_p_r ...
,reshape(a_p123_k_Y_norm_yk__,[n_lm_max,n_k_p_r]) ...
,viewing_k_eq_d/k_p_r_max ...
,template_k_eq_d ...
,n_w_max ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% pm_template_2: %0.2fs',tmp_t));
S_p123_k_p__ = reshape(S_p123_k_p__,[n_w_max*n_k_p_r,tmp_n_S]);
S_p123_l2_S_ = sum(abs(S_p123_k_p__).^2 .* weight_2d_k_all_,1);

%%%%%%%%;
% Recalculate templates using unit norm volume. ;
%%%%%%%%;
[ ...
 X0_quad ...
,C0_quad ...
] = ...
register_spharm_to_spharm_3( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p231_k_Y_quad_ ...
,a_p231_k_Y_quad_ ...
);
%%%%%%%%;
a_p231_k_Y_norm_yk_ = a_p231_k_Y_quad_/max(1e-12,sqrt(X0_quad));
a_p231_k_Y_norm_yk__ = zeros(n_lm_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
a_p231_k_Y_norm_yk__(1:n_lm_(1+nk_p_r),1+nk_p_r) = a_p231_k_Y_norm_yk_(1+tmp_index_);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
[ ...
 X0_norm ...
,C0_norm ...
] = ...
register_spharm_to_spharm_3( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p231_k_Y_norm_yk_ ...
,a_p231_k_Y_norm_yk_ ...
);
%%%%%%%%;
if (verbose>0); disp(sprintf(' %% p231: X0_norm %0.6f',X0_norm)); end;

tmp_t = tic();
[ ...
 S_p231_k_p__ ...
,~ ...
,tmp_n_S ...
,~ ...
,~ ...
] = ...
pm_template_2( ...
 verbose ...
,l_max_max...
,n_k_p_r ...
,reshape(a_p231_k_Y_norm_yk__,[n_lm_max,n_k_p_r]) ...
,viewing_k_eq_d/k_p_r_max ...
,template_k_eq_d ...
,n_w_max ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% pm_template_2: %0.2fs',tmp_t));
S_p231_k_p__ = reshape(S_p231_k_p__,[n_w_max*n_k_p_r,tmp_n_S]);
S_p231_l2_S_ = sum(abs(S_p231_k_p__).^2 .* weight_2d_k_all_,1);

%%%%%%%%;
% Recalculate templates using unit norm volume. ;
%%%%%%%%;
[ ...
 X0_quad ...
,C0_quad ...
] = ...
register_spharm_to_spharm_3( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p312_k_Y_quad_ ...
,a_p312_k_Y_quad_ ...
);
%%%%%%%%;
a_p312_k_Y_norm_yk_ = a_p312_k_Y_quad_/max(1e-12,sqrt(X0_quad));
a_p312_k_Y_norm_yk__ = zeros(n_lm_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
a_p312_k_Y_norm_yk__(1:n_lm_(1+nk_p_r),1+nk_p_r) = a_p312_k_Y_norm_yk_(1+tmp_index_);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
[ ...
 X0_norm ...
,C0_norm ...
] = ...
register_spharm_to_spharm_3( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p312_k_Y_norm_yk_ ...
,a_p312_k_Y_norm_yk_ ...
);
%%%%%%%%;
if (verbose>0); disp(sprintf(' %% p312: X0_norm %0.6f',X0_norm)); end;

tmp_t = tic();
[ ...
 S_p312_k_p__ ...
,~ ...
,tmp_n_S ...
,~ ...
,~ ...
] = ...
pm_template_2( ...
 verbose ...
,l_max_max...
,n_k_p_r ...
,reshape(a_p312_k_Y_norm_yk__,[n_lm_max,n_k_p_r]) ...
,viewing_k_eq_d/k_p_r_max ...
,template_k_eq_d ...
,n_w_max ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% pm_template_2: %0.2fs',tmp_t));
S_p312_k_p__ = reshape(S_p312_k_p__,[n_w_max*n_k_p_r,tmp_n_S]);
S_p312_l2_S_ = sum(abs(S_p312_k_p__).^2 .* weight_2d_k_all_,1);

