%%%%%%%%%%%%%%%%;
p123_pole_from_R_S_reco_k_p_wkS__ = zeros(n_w_sum,n_S);
p123_pole_from_R_S_reco_k_q_wkS__ = zeros(n_w_sum,n_S);
%%%%%%%%%%%%%%%%;
if n_R> 0;
%%%%%%%%%%%%%%%%;
%%%%%%%%;
% Now align these R_k_p_ to a_p123_pole_k_Y_yk_. ;
%%%%%%%%;
R_k_p_wkM__ = R_mon_k_p_wkM__;
R_k_q_wkM__ = R_mon_k_q_wkM__;
parameter = struct('type','parameter');
parameter.fname_align_a_k_Y_pre = sprintf('%s_mat/test_heterogeneity_spurious_clathrin1l_p123_pole_from_R_R%.4d',dir_pm,n_R);
tmp_fname_mat = sprintf('%s.mat',parameter.fname_align_a_k_Y_pre);
if flag_realign &  exist(tmp_fname_mat,'file'); delete(tmp_fname_mat); end;
parameter.n_iteration = 4;
tmp_n_cluster = 1; %<-- just use the first cluster. ;
tmp_index_ncluster_from_nCTF_ = 0;
tmp_n_CTF = 1;
tmp_index_nCTF_from_nM_ = zeros(n_R,1);
tmp_CTF_k_p_r_kC__ = CTF_k_p_r_kC__(:,1+0); %<-- just use the first cluster. ;
tmp_t = tic();
[ ...
 parameter ...
,p123_pole_from_R_a_k_Y_reco_yki__ ...
,p123_pole_from_R_corr_a_k_Y_i_ ...
,p123_pole_from_R_euler_polar_a_Mi__ ...
,p123_pole_from_R_euler_azimu_b_Mi__ ...
,p123_pole_from_R_euler_gamma_z_Mi__ ...
,p123_pole_from_R_image_delta_x_acc_Mi__ ...
,p123_pole_from_R_image_delta_y_acc_Mi__ ...
,p123_pole_from_R_image_delta_x_upd_Mi__ ...
,p123_pole_from_R_image_delta_y_upd_Mi__ ...
,p123_pole_from_R_flag_image_delta_upd_Mi__ ...
,p123_pole_from_R_image_I_value_Mi__ ...
,p123_pole_from_R_image_X_value_Mi__ ...
,p123_pole_from_R_image_S_index_Mi__ ...
,p123_pole_from_R_n_S ...
,p123_pole_from_R_template_viewing_azimu_b_all_ ...
,p123_pole_from_R_template_viewing_polar_a_all_ ...
,p123_pole_from_R_X_SMi___ ...
,p123_pole_from_R_delta_x_SMi___ ...
,p123_pole_from_R_delta_y_SMi___ ...
,p123_pole_from_R_gamma_z_SMi___ ...
,p123_pole_from_R_I_value_SMi___ ...
] = ...
pm_align_M_k_p_to_a_k_Y_3( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,n_R ...
,R_k_p_wkM__(:,1:n_R) ...
,tmp_n_cluster ...
,tmp_index_ncluster_from_nCTF_ ...
,tmp_n_CTF ...
,tmp_index_nCTF_from_nM_(1:n_R) ...
,tmp_CTF_k_p_r_kC__ ...
,l_max_ ...
,a_p123_pole_k_Y_yk_ ...
);
tmp_t = toc(tmp_t); if (verbose>1); disp(sprintf(' %% pm_align_M_k_p_to_a_k_Y_3: %0.3fs',tmp_t)); end;
%%%%%%%%;
flag_disp=1;
if flag_disp;
fname_fig_pre = sprintf('%s_jpg/test_heterogeneity_spurious_clathrin1l_p123_pole_from_R_R%.4d_FIGA',dir_pm,n_R);
fname_fig_jpg = sprintf('%s.jpg',fname_fig_pre);
fname_fig_eps = sprintf('%s.eps',fname_fig_pre);
fname_fig_stripped_jpg = sprintf('%s_stripped.jpg',fname_fig_pre);
fname_fig_stripped_eps = sprintf('%s_stripped.eps',fname_fig_pre);
if (flag_replot | ~exist(fname_fig_jpg,'file'));
if (verbose); disp(sprintf(' %% %s not found, creating',fname_fig_jpg)); end;
figure(1+nf);nf=nf+1;clf;figbig;
p_row = 2; p_col = ceil(parameter.n_iteration/p_row); np=0;
%%%%;
p123_pole_from_R_a_x_u_reco_ixxx__ = cell(parameter.n_iteration,1);
for niteration=0:parameter.n_iteration-1;
tmp_t = tic();
[ ... 
  p123_pole_from_R_a_x_u_reco_ixxx__{1+niteration} ...
] = ...
convert_spharm_to_x_c_4( ...
 k_eq_d ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,p123_pole_from_R_a_k_Y_reco_yki__(:,1+niteration) ...
,half_diameter_x_c ...
,n_x_u_pack ...
);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% convert_spharm_to_x_c_4 time %0.2fs',tmp_t)); end;
subplot(p_row,p_col,1+niteration); isosurface_f_x_u_1([],p123_pole_from_R_a_x_u_reco_ixxx__{1+niteration});
title(sprintf('niteration %d',niteration),'Interpreter','none');
end;%for niteration=0:parameter.n_iteration-1;
%%%%;
print('-djpeg',fname_fig_stripped_jpg);
%print('-depsc',fname_fig_stripped_eps);
sgtitle(fname_fig_pre,'Interpreter','none');
print('-djpeg',fname_fig_jpg);
%print('-depsc',fname_fig_eps);
end;%if (flag_replot | ~exist(fname_fig_jpg,'file'));
%%%%;
close(gcf);
end;%if flag_disp;
%%%%%%%%;
% Now generate templates associated with p123_pole_from_R_a_k_Y_reco_yk__. ;
%%%%%%%%;
[~,ij_use] = max(real(p123_pole_from_R_corr_a_k_Y_i_)); niteration_use = ij_use-1;
p123_pole_from_R_a_k_Y_reco_yk__ = zeros(n_lm_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
p123_pole_from_R_a_k_Y_reco_yk__(1:n_lm_(1+nk_p_r),1+nk_p_r) = p123_pole_from_R_a_k_Y_reco_yki__(1+tmp_index_,1+niteration_use);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
template_k_eq_d = -1;
viewing_k_eq_d = 1.0; %<-- subsample just a few templates for visualization. ;
tmp_t = tic();
[ ...
 p123_pole_from_R_S_reco_k_p_wkS__ ...
] = ...
pm_template_2( ...
 verbose ...
,l_max_max ...
,n_k_p_r ...
,reshape(p123_pole_from_R_a_k_Y_reco_yk__,[n_lm_max,n_k_p_r]) ...
,viewing_k_eq_d/k_p_r_max ...
,template_k_eq_d ...
,n_w_max ...
);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% pm_template_2: %0.6fs',tmp_t)); end;
p123_pole_from_R_S_reco_k_p_wkS__ = reshape(p123_pole_from_R_S_reco_k_p_wkS__,[n_w_max*n_k_p_r,n_S]);
%%%%;
clear p123_pole_from_R_a_k_Y_reco_yki__ ;
clear p123_pole_from_R_corr_a_k_Y_i_ ;
clear p123_pole_from_R_euler_polar_a_Mi__ ;
clear p123_pole_from_R_euler_azimu_b_Mi__ ;
clear p123_pole_from_R_euler_gamma_z_Mi__ ;
clear p123_pole_from_R_image_delta_x_acc_Mi__ ;
clear p123_pole_from_R_image_delta_y_acc_Mi__ ;
clear p123_pole_from_R_image_delta_x_upd_Mi__ ;
clear p123_pole_from_R_image_delta_y_upd_Mi__ ;
clear p123_pole_from_R_flag_image_delta_upd_Mi__ ;
clear p123_pole_from_R_image_I_value_Mi__ ;
clear p123_pole_from_R_image_X_value_Mi__ ;
clear p123_pole_from_R_image_S_index_Mi__ ;
clear p123_pole_from_R_n_S ;
clear p123_pole_from_R_template_viewing_azimu_b_all_ ;
clear p123_pole_from_R_template_viewing_polar_a_all_ ;
clear p123_pole_from_R_X_SMi___ ;
clear p123_pole_from_R_delta_x_SMi___ ;
clear p123_pole_from_R_delta_y_SMi___ ;
clear p123_pole_from_R_gamma_z_SMi___ ;
clear p123_pole_from_R_I_value_SMi___ ;
%clear p123_pole_from_R_a_x_u_reco_ixxx__ ; %<-- use later for garbage-can. ;
%clear p123_pole_from_R_a_k_Y_reco_yk__ ; %<-- use later for garbage-can. ;
p123_pole_from_R_S_reco_k_q_wkS__ = zeros(n_w_sum,n_S);
for nS=0:n_S-1;
p123_pole_from_R_S_reco_k_q_wkS__(:,1+nS) = interp_p_to_q(n_k_p_r,n_w_,n_w_sum,p123_pole_from_R_S_reco_k_p_wkS__(:,1+nS));
end;%for nS=0:n_S-1;
%%%%%%%%%%%%%%%%;
end;% if n_R> 0;
%%%%%%%%%%%%%%%%;
%%%%%%%%;
% Now build p123_pol3. ;
%%%%%%%%;
ca3_theta = cap_theta; %<-- restrictive polar-cap used for p123_pole. ;
tmp_template_polar_a_wkS__ = min(1,min(template_polar_a_wkS__,pi-template_polar_a_wkS__)/max(1e-12,ca3_theta));
g_ca3_wkS__ = 1-sin((pi/2)*tmp_template_polar_a_wkS__).^4;
S_amp3_k_p_wkS__ = S_p123_k_p_wkS__;
ind_0in_wkS__ = (abs(template_polar_a_wkS__-pi/2)<=pi/2-ca3_theta); %<-- near equator. ;
ind_out_wkS__ = (abs(template_polar_a_wkS__-pi/2)> pi/2-ca3_theta); %<-- near polar cap. ;
S_ca3_avg = real(mean(S_p123_k_p_wkS__(find(ind_out_wkS__)))); %<-- average of (unused) polar cap values. ;
%S_amp3_k_p_wkS__ = S_amp3_k_p_wkS__.*ind_0in_wkS__ ....
  + ( p123_pole_from_R_S_reco_k_p_wkS__.*g_ca3_wkS__ + S_amp3_k_p_wkS__.*(1-g_ca3_wkS__) ).*ind_out_wkS__ ...
  ; %<-- modify the poles smoothly. ;
tmp_f = fnorm(S_amp3_k_p_wkS__)/max(1e-12,fnorm(p123_pole_from_R_S_reco_k_p_wkS__));
S_amp3_k_p_wkS__ = ...
  S_amp3_k_p_wkS__.*ind_0in_wkS__ + ...
  tmp_f*p123_pole_from_R_S_reco_k_p_wkS__.*ind_out_wkS__ ...
  ; %<-- modify the poles abruptly. ;
%%%%%%%%;
% Now we can actually use all the templates in S_amp3_k_p_wkS__, since we have set the polar data to be consistent. ;
%%%%%%%%;
flag_disp=0; if flag_disp; plot(viewing_polar_a_all_(tmp_nllr_sort_ij_rem_),'.'); end;
%%%%%%%%;
tmp_t = tic();
tmp_n_order = 5;
a_p123_pol3_k_Y_yk_ = ...
cg_lsq_6( ...
 tmp_n_order ...
,n_k_p_r ...
,k_p_r_ ...
,l_max_ ...
,n_w_ ...
,n_S ...
,S_amp3_k_p_wkS__ ...
,[] ...
,[] ...
,viewing_polar_a_all_ ...
,viewing_azimu_b_all_ ...
,zeros(n_S,1) ...
,[] ...
,[] ...
);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% a_p123_pol3_k_Y_yk_ time %0.2fs',tmp_t)); end;
%%%%%%%%;
tmp_t = tic();
[ ... 
  a_p123_pol3_x_u_xxx_ ...
] = ...
convert_spharm_to_x_c_4( ...
 k_eq_d ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p123_pol3_k_Y_yk_ ...
,half_diameter_x_c ...
,n_x_u_pack ...
);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% a_p123_pol3_x_u_xxx_ time %0.2fs',tmp_t)); end;
%%%%%%%%;
if ~exist('a_p123_x_u_reco_','var');
tmp_t = tic();
[ ... 
  a_p123_x_u_reco_ ...
] = ...
convert_spharm_to_x_c_4( ...
 k_eq_d ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_p123_k_Y_reco_yk_ ...
,half_diameter_x_c ...
,n_x_u_pack ...
);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% a_p123_x_u_reco_ time %0.2fs',tmp_t)); end;
end;%if ~exist('a_p123_x_u_reco_','var');
%%%%%%%%;
flag_disp=1;
if flag_disp;
fname_fig_pre = sprintf('%s_jpg/test_heterogeneity_spurious_clathrin1l_p123_reco_pole_pol3_R%.4d_FIGB',dir_pm,n_R);
fname_fig_jpg = sprintf('%s.jpg',fname_fig_pre);
fname_fig_stripped_jpg = sprintf('%s_stripped.jpg',fname_fig_pre);
if (flag_replot | ~exist(fname_fig_jpg,'file'));
if (verbose); disp(sprintf(' %% %s not found, creating',fname_fig_jpg)); end;
%%%%;
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,3,1);isosurface_f_x_u_1([],a_p123_x_u_reco_);
subplot(1,3,2);isosurface_f_x_u_1([],a_p123_pole_x_u_xxx_);
subplot(1,3,3);isosurface_f_x_u_1([],a_p123_pol3_x_u_xxx_);
%%%%;
print('-djpeg',fname_fig_stripped_jpg);
sgtitle(fname_fig_pre,'Interpreter','none');
print('-djpeg',fname_fig_jpg);
end;%if (flag_replot | ~exist(fname_fig_jpg,'file'));
%%%%;
close(gcf);
end;%if flag_disp;
%%%%;
if flag_disp;
fname_fig_pre = sprintf('%s_jpg/test_heterogeneity_spurious_clathrin1l_p123_pol3_R%.4d_FIGB',dir_pm,n_R);
fname_fig_jpg = sprintf('%s.jpg',fname_fig_pre);
fname_fig_stripped_jpg = sprintf('%s_stripped.jpg',fname_fig_pre);
if (flag_replot | ~exist(fname_fig_jpg,'file'));
if (verbose); disp(sprintf(' %% %s not found, creating',fname_fig_jpg)); end;
%%%%;
figure(1+nf);nf=nf+1;clf;figsml;
subplot(1,1,1);isosurface_f_x_u_1([],a_p123_pol3_x_u_xxx_);
%%%%;
print('-djpeg',fname_fig_stripped_jpg);
sgtitle(fname_fig_pre,'Interpreter','none');
print('-djpeg',fname_fig_jpg);
end;%if (flag_replot | ~exist(fname_fig_jpg,'file'));
%%%%;
close(gcf);
end;%if flag_disp;
%%%%%%%%;
% Now generate all templates from p123_pol3. ;
%%%%%%%%;
a_p123_pol3_k_Y_yk__ = zeros(n_lm_max,n_k_p_r);
for nk_p_r=0:n_k_p_r-1;
tmp_index_ = n_lm_csum_(1+nk_p_r) + (0:n_lm_(1+nk_p_r)-1);
a_p123_pol3_k_Y_yk__(1:n_lm_(1+nk_p_r),1+nk_p_r) = a_p123_pol3_k_Y_yk_(1+tmp_index_);
end;%for nk_p_r=0:n_k_p_r-1;
%%%%%%%%;
template_k_eq_d = -1;
viewing_k_eq_d = 1.0; %<-- subsample just a few templates for visualization. ;
tmp_t = tic();
[ ...
 S_p123_pol3_k_p_wkS__ ...
,~ ...
,n_S ...
,template_viewing_azimu_b_all_ ...
,template_viewing_polar_a_all_ ...
] = ...
pm_template_2( ...
 verbose ...
,l_max_max ...
,n_k_p_r ...
,reshape(a_p123_pol3_k_Y_yk__,[n_lm_max,n_k_p_r]) ...
,viewing_k_eq_d/k_p_r_max ...
,template_k_eq_d ...
,n_w_max ...
);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% pm_template_2: %0.6fs',tmp_t)); end;
S_p123_pol3_k_p_wkS__ = reshape(S_p123_pol3_k_p_wkS__,[n_w_max*n_k_p_r,n_S]);
S_p123_pol3_k_q_wkS__ = zeros(n_w_sum,n_S);
for nS=0:n_S-1;
S_p123_pol3_k_q_wkS__(:,1+nS) = interp_p_to_q(n_k_p_r,n_w_,n_w_sum,S_p123_pol3_k_p_wkS__(:,1+nS));
end;%for nS=0:n_S-1;
%%%%%%%%;
