%%%%%%%%;
% setting up simple multi-slice-alignment. ;
% assume a 2d-volume x, comprising a single ring. ;
% Assume that x is restricted to just 2 bessel-coefficients, implying a circle in C. ;
%%%%%%%%;

clear;
%%%%%%%%;
platform = 'rusty';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
if (strcmp(platform,'eval1')); setup_eval1; string_root = 'home'; end;
if (strcmp(platform,'rusty')); setup_rusty; string_root = 'mnt/home'; end;
%%%%%%%%;
  
dir_jpg = sprintf('/%s/rangan/dir_cryoem/dir_rangan_playroom/dir_jpg',string_root);

fname_fig = sprintf('%s/MSA_summary_FIGA',dir_jpg);
if (~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig));
%%%%%%%%%%%%%%%%;
figure(1);clf;figbig;
subplot_ = [];
fig80s();
markersize_use = 8;
n_contour = 64;
p_row = 3; np=0;
n_point = 16;
rseed=0;rng(rseed);
M_nois_p2__ = randn(n_point,2);
n_x = 512;
snr_ = [ +inf, 10.^[2:-0.5:0] ]; n_snr = numel(snr_);
for nsnr=0:n_snr-1;
snr = snr_(1+nsnr);
%%%%;
gamma_z_ = linspace(0,2*pi,n_point+1); gamma_z_ = transpose(gamma_z_(1:end-1));
M_p2__ = [cos(gamma_z_) , sin(gamma_z_)];
M_l2 = fnorm(M_p2__);
sigma=0; if (snr> 0); sigma = M_l2/max(1e-12,snr); end;
M_p2__ = M_p2__ + sigma*M_nois_p2__;
xlim_ = mean(M_p2__(:)) + 5.5*std(M_p2__(:),1)*[-1,+1];
x_0_ = linspace(min(xlim_),max(xlim_),n_x);
x_1_ = linspace(min(xlim_),max(xlim_),n_x);
[x_0__,x_1__] = meshgrid(x_0_,x_1_); n_xx = n_x^2;
N_0_p01___ = reshape(bsxfun(@minus,M_p2__(:,1+0),reshape(x_0__(:),[1,n_xx])),[n_point,n_x,n_x]);
N_1_p01___ = reshape(bsxfun(@minus,M_p2__(:,1+1),reshape(x_1__(:),[1,n_xx])),[n_point,n_x,n_x]);
r_p01___ = zeros(n_point,n_xx);
r_p01___ = sqrt( N_0_p01___.^2 + N_1_p01___.^2 );
r_p01___ = reshape(r_p01___,[n_point,n_x,n_x]);
r_x01___ = mean(r_p01___,1);
dr_p01___ = bsxfun(@minus,r_p01___,r_x01___);
Nhat_0_p01___ = bsxfun(@rdivide,N_0_p01___,r_p01___);
Nhat_1_p01___ = bsxfun(@rdivide,N_1_p01___,r_p01___);
dNhat_0_p01___ = bsxfun(@minus,Nhat_0_p01___,mean(Nhat_0_p01___,1));
dNhat_1_p01___ = bsxfun(@minus,Nhat_1_p01___,mean(Nhat_1_p01___,1));
L_x01___ = mean(dr_p01___.^2,1);
DL0_x01___ = mean(dNhat_0_p01___.*dr_p01___,1);
DL1_x01___ = mean(dNhat_1_p01___.*dr_p01___,1);
DL_x01___ = sqrt( DL0_x01___.^2 + DL1_x01___.^2);
%%%%;
subplot_(1+np) = subplot(p_row,ceil(2*n_snr/p_row),1+np);np=np+1;
hold on;
imagesc(squeeze(L_x01___),[min(L_x01___,[],'all'),max(L_x01___,[],'all')]);
plot(1 + (n_x-1)*(M_p2__(:,1+0) - min(xlim_))/diff(xlim_),1 + (n_x-1)*(M_p2__(:,1+1) - min(xlim_))/diff(xlim_),'o','MarkerSize',6,'MarkerEdgeColor','k','MarkerFaceColor','w');
hold off;
axis image; axisnotick;
title(sprintf('snr %0.3f $L$',snr),'Interpreter','latex');
set(gca,'FontSize',18);
subplot_(1+np) = subplot(p_row,ceil(2*n_snr/p_row),1+np);np=np+1;
hold on;
imagesc(squeeze(DL_x01___),[0,max(DL_x01___,[],'all')]);
hold off;
axis image; axisnotick;
title(sprintf('snr %0.3f $|\\nabla L|$',snr),'Interpreter','latex');
set(gca,'FontSize',18);
end;%for nsnr=0:n_snr-1;
np=0;
for nsnr=0:n_snr-1;
colormap(subplot_(1+np),colormap_beach()); np=np+1;
colormap(subplot_(1+np),colormap_80s()); np=np+1;
end;%for nsnr=0:n_snr-1;
%%%%%%%%;
disp(sprintf(' %% writing %s',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
%%%%%%%%%%%%%%%%;
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));

n_point = 16;
rseed=0;rng(rseed);
M_nois_p2__ = randn(n_point,2);
n_x = 512;
snr_ = [ +inf, 10.^[2:-0.25:0] ]; n_snr = numel(snr_);
for nsnr=0:n_snr-1;
snr = snr_(1+nsnr);
%%%%;
gamma_z_ = linspace(0,2*pi,n_point+1); gamma_z_ = transpose(gamma_z_(1:end-1));
M_p2__ = [cos(gamma_z_) , sin(gamma_z_)];
M_l2 = fnorm(M_p2__);
sigma=0; if (snr> 0); sigma = M_l2/max(1e-12,snr); end;
M_p2__ = M_p2__ + sigma*M_nois_p2__;
xlim_ = mean(M_p2__(:)) + 5.5*std(M_p2__(:),1)*[-1,+1];
x_0_ = linspace(min(xlim_),max(xlim_),n_x);
x_1_ = linspace(min(xlim_),max(xlim_),n_x);
[x_0__,x_1__] = meshgrid(x_0_,x_1_); n_xx = n_x^2;
N_0_p01___ = reshape(bsxfun(@minus,M_p2__(:,1+0),reshape(x_0__(:),[1,n_xx])),[n_point,n_x,n_x]);
N_1_p01___ = reshape(bsxfun(@minus,M_p2__(:,1+1),reshape(x_1__(:),[1,n_xx])),[n_point,n_x,n_x]);
r_p01___ = zeros(n_point,n_xx);
r_p01___ = sqrt( N_0_p01___.^2 + N_1_p01___.^2 );
r_p01___ = reshape(r_p01___,[n_point,n_x,n_x]);
r_x01___ = mean(r_p01___,1);
dr_p01___ = bsxfun(@minus,r_p01___,r_x01___);
Nhat_0_p01___ = bsxfun(@rdivide,N_0_p01___,r_p01___);
Nhat_1_p01___ = bsxfun(@rdivide,N_1_p01___,r_p01___);
dNhat_0_p01___ = bsxfun(@minus,Nhat_0_p01___,mean(Nhat_0_p01___,1));
dNhat_1_p01___ = bsxfun(@minus,Nhat_1_p01___,mean(Nhat_1_p01___,1));
L_x01___ = mean(dr_p01___.^2,1);
DL0_x01___ = mean(dNhat_0_p01___.*dr_p01___,1);
DL1_x01___ = mean(dNhat_1_p01___.*dr_p01___,1);
DL_x01___ = sqrt( DL0_x01___.^2 + DL1_x01___.^2);
%%%%%%%%%%%%%%%%;
fname_fig = sprintf('%s/MSA_s%.4d_FIGB',dir_jpg,floor(min(1000,snr)));
if (~exist(sprintf('%s.jpg',fname_fig),'file'));
disp(sprintf(' %% %s not found, creating',fname_fig));
%%%%%%%%%%%%%%%%;
figure(1);clf;figbig; np=0;
linewidth_use = 2;
figbeach;
c_beach__ = colormap_beach; n_c_beach = size(c_beach__,1);
c_80s__ = colormap_80s; n_c_80s = size(c_80s__,1);
%%%%%%%%;
subplot_(1+np) = subplot(1,2,1+np); np=np+1;
hold on;
%%%%;
index_half0_ = 0:n_x/1-1;
index_half1_ = n_x/2:n_x-1;
%s00=surf(x_0_(1+index_half0_),x_1_(1+index_half0_),squeeze((L_x01___(1,1+index_half0_,1+index_half0_)))); set(s00,'LineStyle','none');
s01=surf(x_0_(1+index_half0_),x_1_(1+index_half1_),squeeze((L_x01___(1,1+index_half1_,1+index_half0_)))); set(s01,'LineStyle','none');
s10=surf(x_0_(1+index_half1_),x_1_(1+index_half0_),squeeze((L_x01___(1,1+index_half0_,1+index_half1_)))); set(s10,'LineStyle','none');
s11=surf(x_0_(1+index_half1_),x_1_(1+index_half1_),squeeze((L_x01___(1,1+index_half1_,1+index_half1_)))); set(s11,'LineStyle','none');
zlim_L_ = [ min(L_x01___,[],'all') , max(L_x01___,[],'all') ] ;
zmin_plot_L  = min(zlim_L_) - 0.50*diff(zlim_L_);
%%%%;
[n_contour_L,contour_L_cell___,contour_L_level_] = contour_cell_from_matrix_0(contourc(x_0_,x_1_,squeeze((L_x01___(1,:,:))),prctile(L_x01___,[0:2.5:100],'all')));
contour_L_lim_ = [min(contour_L_level_) , max(contour_L_level_)];
for ncontour_L=0:n_contour_L-1;
nc_beach = max(0,min(n_c_beach-1,floor(n_c_beach* ( contour_L_level_(1+ncontour_L) - min(contour_L_lim_) )/diff(contour_L_lim_))));
contour_L_x_ = contour_L_cell___{1+ncontour_L}(:,1+0);
contour_L_y_ = contour_L_cell___{1+ncontour_L}(:,1+1);
contour_L_z_ = zmin_plot_L*ones(size(contour_L_x_)) + 1e-6;
plot3(contour_L_x_,contour_L_y_,contour_L_z_,'-','LineWidth',linewidth_use,'Color',c_beach__(1+nc_beach,:));
end;%for ncontour_L=0:n_contour_L-1;
%%%%;
%line(x_0_(1+0*n_x/1)*[1,1]+1e-12,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_L,L_x01___(1,0+1*n_x/2,1+0*n_x/1)],'LineStyle',':','Color','k','LineWidth',2);
%line(x_0_(0+1*n_x/1)*[1,1]-1e-12,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_L,L_x01___(1,0+1*n_x/2,0+1*n_x/1)],'LineStyle',':','Color','k','LineWidth',2);
%line([x_0_(1+0*n_x/1),x_0_(0+1*n_x/1)],x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_L,zmin_plot_L],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(0+1*n_x/2)*[1,1]+1e-12,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_L,L_x01___(1,0+1*n_x/2,0+1*n_x/2)],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(1+0*n_x/1)*[1,1]+1e-12,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_L,L_x01___(1,0+1*n_x/2,1+0*n_x/1)],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(0+1*n_x/2)*[1,1]-1e-12,x_1_(1+0*n_x/1)*[1,1]+0e-12,[zmin_plot_L,L_x01___(1,1+0*n_x/1,0+1*n_x/2)],'LineStyle',':','Color','k','LineWidth',2);
line([x_0_(1+0*n_x/1),x_0_(0+1*n_x/2)],x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_L,zmin_plot_L],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(0+1*n_x/2)*[1,1]+0e-12,[x_1_(1+0*n_x/1),x_1_(0+1*n_x/2)],[zmin_plot_L,zmin_plot_L],'LineStyle',':','Color','k','LineWidth',2);
hold off;
xlim(xlim_); %xlabel('x');
ylim(xlim_); %ylabel('y');
zlim([zmin_plot_L-1e-12,max(zlim_L_)]); %zlabel('z');
set(gca,'XTick',[]); set(gca,'YTick',[]); set(gca,'ZTick',[]);
view(-40,+30);
title('$L$','Interpreter','latex');
set(gca,'FontSize',24);
axis vis3d;
%%%%%%%%;
subplot_(1+np) = subplot(1,2,1+np);np=np+1;
hold on;
%%%%;
index_half0_ = 0:n_x/1-1;
index_half1_ = n_x/2:n_x-1;
%s00=surf(x_0_(1+index_half0_),x_1_(1+index_half0_),squeeze((DL_x01___(1,1+index_half0_,1+index_half0_)))); set(s00,'LineStyle','none');
s01=surf(x_0_(1+index_half0_),x_1_(1+index_half1_),squeeze((DL_x01___(1,1+index_half1_,1+index_half0_)))); set(s01,'LineStyle','none');
s10=surf(x_0_(1+index_half1_),x_1_(1+index_half0_),squeeze((DL_x01___(1,1+index_half0_,1+index_half1_)))); set(s10,'LineStyle','none');
s11=surf(x_0_(1+index_half1_),x_1_(1+index_half1_),squeeze((DL_x01___(1,1+index_half1_,1+index_half1_)))); set(s11,'LineStyle','none');
zlim_DL_ = [ min(DL_x01___,[],'all') , max(DL_x01___,[],'all') ] ;
zmin_plot_DL  = min(zlim_DL_) - 0.50*diff(zlim_DL_);
%%%%;
[n_contour_DL,contour_DL_cell___,contour_DL_level_] = contour_cell_from_matrix_0(contourc(x_0_,x_1_,squeeze((DL_x01___(1,:,:))),prctile(DL_x01___,[0,[0:2.5:100]],'all')));
contour_DL_lim_ = [min(contour_DL_level_) , max(contour_DL_level_)];
for ncontour_DL=0:n_contour_DL-1;
nc_80s = max(0,min(n_c_80s-1,floor(n_c_80s* ( contour_DL_level_(1+ncontour_DL) - min(contour_DL_lim_) )/diff(contour_DL_lim_))));
contour_DL_x_ = contour_DL_cell___{1+ncontour_DL}(:,1+0);
contour_DL_y_ = contour_DL_cell___{1+ncontour_DL}(:,1+1);
contour_DL_z_ = zmin_plot_DL*ones(size(contour_DL_x_)) + 1e-6;
plot3(contour_DL_x_,contour_DL_y_,contour_DL_z_,'-','LineWidth',linewidth_use,'Color',c_80s__(1+nc_80s,:));
end;%for ncontour_DL=0:n_contour_DL-1;
%%%%;
%line(x_0_(1+0*n_x/1)*[1,1]+1e-2,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_DL,DL_x01___(1,0+1*n_x/2,1+0*n_x/1)],'LineStyle',':','Color','k','LineWidth',2);
%line(x_0_(0+1*n_x/1)*[1,1]-1e-2,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_DL,DL_x01___(1,0+1*n_x/2,0+1*n_x/1)],'LineStyle',':','Color','k','LineWidth',2);
%line([x_0_(1+0*n_x/1),x_0_(0+1*n_x/1)],x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_DL,zmin_plot_DL],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(0+1*n_x/2)*[1,1]+1e-12,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_DL,DL_x01___(1,0+1*n_x/2,0+1*n_x/2)],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(1+0*n_x/1)*[1,1]+1e-12,x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_DL,DL_x01___(1,0+1*n_x/2,1+0*n_x/1)],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(0+1*n_x/2)*[1,1]-1e-12,x_1_(1+0*n_x/1)*[1,1]+0e-12,[zmin_plot_DL,DL_x01___(1,1+0*n_x/1,0+1*n_x/2)],'LineStyle',':','Color','k','LineWidth',2);
line([x_0_(1+0*n_x/1),x_0_(0+1*n_x/2)],x_1_(0+1*n_x/2)*[1,1]+0e-12,[zmin_plot_DL,zmin_plot_DL],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(0+1*n_x/2)*[1,1]+0e-12,[x_1_(1+0*n_x/1),x_1_(0+1*n_x/2)],[zmin_plot_DL,zmin_plot_DL],'LineStyle',':','Color','k','LineWidth',2);
line(x_0_(1+0*n_x/1)*[1,1]-1e-12,[x_1_(0+1*n_x/2),x_1_(0+1*n_x/1)],0*[1,1],'LineStyle','-','Color','c','LineWidth',3);
line([x_0_(0+1*n_x/2),x_0_(0+1*n_x/1)],x_1_(1+0*n_x/1)*[1,1]-1e-12,0*[1,1],'LineStyle','-','Color','c','LineWidth',3);
line(x_0_(0+1*n_x/1)*[1,1]-1e-12,[x_1_(1+0*n_x/1),x_1_(0+1*n_x/1)],0*[1,1],'LineStyle','-','Color','c','LineWidth',3);
line([x_0_(1+0*n_x/1),x_0_(0+1*n_x/1)],x_1_(0+1*n_x/1)*[1,1]-1e-12,0*[1,1],'LineStyle','-','Color','c','LineWidth',3);
hold off;
xlim(xlim_); %xlabel('x');
ylim(xlim_); %ylabel('y');
zlim([zmin_plot_DL-1e-12,max(zlim_DL_)]); %zlabel('z');
set(gca,'XTick',[]); set(gca,'YTick',[]); set(gca,'ZTick',[]);
view(-40,+30);
title('$|\nabla L|$','Interpreter','latex');
set(gca,'FontSize',24);
axis vis3d;
%%%%%%%%;
np=0;
colormap(subplot_(1+np),colormap_beach); np=np+1;
colormap(subplot_(1+np),colormap_80s); np=np+1;
sgtitle(sprintf('snr %0.2f',snr));
%%%%%%%%;
disp(sprintf(' %% writing %s',fname_fig));
print('-djpeg',sprintf('%s.jpg',fname_fig));
close(gcf);
%%%%%%%%%%%%%%%%;
end;%if (~exist(sprintf('%s.jpg',fname_fig),'file'));
%%%%%%%%%%%%%%%%;
end;%for nsnr=0:n_snr-1;

