function test_spharm_1(n_l,a_,res_);
% l_ = array of l-values ;
% m_ = array of m-values ;
% a_ = array of coefficients ;
% note that l_(ns) should be higher than m_(ns) ;
% res_ = [ resolution_theta , resolution_phi ] ;
% test with: ;
%{
  test_spharm_1();
  % or something like: ;
  n_l =  2; a_ = [+0,+0,+0,+0,+0,+0,+1,+0,+0]; res_ = [96,96]; test_spharm_1(n_l,a_,res_);
  n_l =  1; a_ = [+0,+0,+0,+1]; res_ = [96,96]; test_spharm_1(n_l,a_,res_);
  %}

if nargin<3; res_ = [64,64]; end;
if nargin<2; a_ = linspace(-1,1,9); end;
if nargin<1; n_l = 2; end;
if nargin<1;
isph_start_ = MDA_read_i4('./dir_mda6/isph_start_.mda');
nterms_sph_ = MDA_read_i4('./dir_mda6/nterms_sph_.mda');
modsph_A_ori_ = MDA_read_c16('./dir_mda6/modsph_A_ori_.mda');
ngridr = length(isph_start_);
ncur = 3;
n_l = nterms_sph_(ncur);
n_lm = (n_l+1).^2;
a_ = modsph_A_ori_(isph_start_(ncur) + (1:n_lm));
end;%if nargin<1;

n_lm = (n_l+1).^2;
l_ = []; m_ = [];
for nl=0:n_l;
l_ = [l_ , nl*ones(1,2*nl+1) ];
m_ = [m_ , [-nl:+nl] ];
end;%for nl=0:n_l;

assert(length(a_)>=(n_l+1).^2);

theta_ = linspace( 0 , 2*pi , res_(1) );  % Azimuthal/Longitude/Circumferential
dtheta = mean(diff(theta_));
phi_   = linspace( 0 ,   pi , res_(2) );  % Altitude /Latitude /Elevation
dphi = mean(diff(phi_));
[THETA_,PHI_]=meshgrid(theta_,phi_);

Y_1n1 = +0.5*sqrt(3/2/pi)*sin(PHI_).*exp(-i*THETA_);
Y_1_0 = +0.5*sqrt(3/pi)*cos(PHI_);
Y_1p1 = -0.5*sqrt(3/2/pi)*sin(PHI_).*exp(+i*THETA_);

Lmn_ = cell(n_lm,1);
Ymn_ = cell(n_lm,1);

for nl=0:n_l;
l_val = nl;
Lmn_tmp=legendre(l_val,cos(PHI_),'unnorm');
for m_val = -l_val:+l_val;
ix = 1+l_val*(l_val+1)+m_val;
m_abs = abs(m_val);
Lmn_{ix} = squeeze(Lmn_tmp(1+m_abs,:,:));
a1=((2*l_val+1)/(4*pi));
a2=exp(lfactorial(l_val-m_abs) - lfactorial(l_val+m_abs));
c=sqrt(a1*a2);
s=(-1)^((m_val<0)*m_val); % needed to preserve condon-shortley phase. ;
%disp(sprintf(' %% l_val %d m_val %d ix %d s %d',l_val,m_val,ix,s));
Ymn_{ix}=s*c*Lmn_{ix}.*exp(i*m_val*THETA_);
end;%for m_val = -l_val:+l_val;
end;%for nl=0:n_l;

norm_flag=0;
if norm_flag;
YY_ = zeros(n_lm,n_lm);
for ix1=1:n_lm;for ix2=1:n_lm;
Ymn_tmp = conj(Ymn_{ix1}).*(Ymn_{ix2}).*sin(PHI_); 
Ymn_sum = sum(Ymn_tmp(:))*dtheta*dphi;
YY_(ix1,ix2) = Ymn_sum ;
end;end;%for ix1=1:n_lm;for ix2=1:n_lm;
disp(abs(YY_));imagesc(abs(YY_)); colorbar;
disp('returning');return;
end;%if norm_flag;

beta = pi/6;
W_ = wignerd(n_l,beta);
b_ = zeros(size(a_));
for nl=0:n_l;
a_tmp = a_(1+nl*(nl+1) + (-nl:+nl));
a_tmp = reshape(a_tmp,2*nl+1,1);
b_tmp = W_{1+nl}*a_tmp;
b_(1+nl*(nl+1) + (-nl:+nl)) = b_tmp;
%disp(sprintf(' %% nl %d',nl));
%disp(a_tmp);
%disp(W_{1+nl});
%disp(b_tmp);
end;%for nl=0:n_l;
%disp(a_);
%disp(b_);

Ymn_orig = zeros(size(Ymn_{1}));
Ymn_rota = zeros(size(Ymn_{1}));
for nl=0:n_l;
for m_val = -nl:+nl;
ix = 1+nl*(nl+1)+m_val;
%disp(sprintf(' %% l_val %d m_val %d ix %d',l_val,m_val,ix));
Ymn_orig = Ymn_orig + a_(ix) * Ymn_{ix};
Ymn_rota = Ymn_rota + b_(ix) * Ymn_{ix};
end;%for m_val = -nl:+nl;
end;%for nl=0:n_l;

norm_flag=0;
YY_orig = zeros(1,n_lm);
YY_rota = zeros(1,n_lm);
if norm_flag;
for ix1=1:n_lm;
Ymn_tmp = conj(Ymn_{ix1}).*(Ymn_orig).*sin(PHI_); 
Ymn_sum = sum(Ymn_tmp(:))*dtheta*dphi;
YY_orig(ix1) = Ymn_sum ;
Ymn_tmp = conj(Ymn_{ix1}).*(Ymn_rota).*sin(PHI_); 
Ymn_sum = sum(Ymn_tmp(:))*dtheta*dphi;
YY_rota(ix1) = Ymn_sum ;
end;%for ix1=1:n_lm;
disp(abs(YY_orig));
disp(abs(YY_rota));
disp('returning');return;
end;%if norm_flag;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ; 
% original function ; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ; 
[Xm,Ym,Zm]=sph2cart(THETA_,PHI_-pi/2,abs(Ymn_orig).^2);
[Xr,Yr,Zr]=sph2cart(THETA_,PHI_-pi/2,real(Ymn_orig).^2);
[Xi,Yi,Zi]=sph2cart(THETA_,PHI_-pi/2,imag(Ymn_orig).^2);
% [Xp,Yp,Zp]=sph2cart(THETA_,PHI_-pi/2,angle(Ymn_orig).^2);
plot_flag=1;
if plot_flag;
f=figure; axis off; hold on;
subplot(2,2,1);
surf(Xm,Ym,Zm,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim_orig_1 = xlim; ylim_orig_1 = ylim; zlim_orig_1 = zlim;
subplot(2,2,2);
surf(Xr,Yr,Zr,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim_orig_2 = xlim; ylim_orig_2 = ylim; zlim_orig_2 = zlim;
subplot(2,2,3);
surf(Xi,Yi,Zi,'linestyle','none'); 
%    surf(Xp,Yp,Zp,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim_orig_3 = xlim; ylim_orig_3 = ylim; zlim_orig_3 = zlim;
end;%if plot_flag;
[X1,Y1,Z1]=sph2cart(THETA_,PHI_-pi/2,1.0);
cra = colormap('hsv'); ncra = size(cra,1);
y_min = 0; y_max = prctile(abs(Ymn_orig(:)),85);
C1 = zeros(res_(1),res_(2),3);
for nr=1:res_(1); for nc=1:res_(2);
y_tmp = Ymn_orig(nr,nc);
y_ang = angle(y_tmp); y_nrm = abs(y_tmp);
nba = max(1,min(ncra,floor(ncra*(y_ang+pi)/(2*pi))));
dbn = max(0,min(1,(y_nrm-y_min)/(y_max-y_min)));
C1(nr,nc,:) = cra(nba,:)*dbn;
end;end;%for nr=1:res_(1); for nc=1:res_(2);
plot_flag=1;
if plot_flag;
subplot(2,2,4);
s=surf(X1,Y1,Z1,C1);set(s,'EdgeColor','none');
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
%light; lighting phong;
end;%if plot_flag;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ; 
% rotated by beta about y-axis ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ; 
cb = cos(-beta); sb = sin(-beta); sg = -1;
Xn_ = sin(PHI_).*cos(THETA_);
Yn_ = sin(PHI_).*sin(THETA_);
Zn_ = cos(PHI_);
Xt_ = +cb*Xn_ + sg*sb*Zn_;
Yt_ = Yn_;
Zt_ = -sg*sb*Xn_ + cb*Zn_;
THETA_Y_ = atan2(Yt_,Xt_);
PHI_Y_ = acos(Zt_);
[Xm,Ym,Zm]=sph2cart(THETA_Y_,PHI_Y_-pi/2,abs(Ymn_orig).^2);
[Xr,Yr,Zr]=sph2cart(THETA_Y_,PHI_Y_-pi/2,real(Ymn_orig).^2);
[Xi,Yi,Zi]=sph2cart(THETA_Y_,PHI_Y_-pi/2,imag(Ymn_orig).^2);
% [Xp,Yp,Zp]=sph2cart(THETA_Y_,PHI_Y_-pi/2,angle(Ymn_orig).^2);
plot_flag=1;
if plot_flag;
f=figure; axis off; hold on;
subplot(2,2,1);
surf(Xm,Ym,Zm,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim(xlim_orig_1); ylim(ylim_orig_1); zlim(zlim_orig_1);
subplot(2,2,2);
surf(Xr,Yr,Zr,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim(xlim_orig_2); ylim(ylim_orig_2); zlim(zlim_orig_2);
subplot(2,2,3);
surf(Xi,Yi,Zi,'linestyle','none'); 
%    surf(Xp,Yp,Zp,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim(xlim_orig_3); ylim(ylim_orig_3); zlim(zlim_orig_3);
end;%if plot_flag;
[X1,Y1,Z1]=sph2cart(THETA_Y_,PHI_Y_-pi/2,1.0);
cra = colormap('hsv'); ncra = size(cra,1);
y_min = 0; y_max = prctile(abs(Ymn_orig(:)),85);
C1 = zeros(res_(1),res_(2),3);
for nr=1:res_(1); for nc=1:res_(2);
y_tmp = Ymn_orig(nr,nc);
y_ang = angle(y_tmp); y_nrm = abs(y_tmp);
nba = max(1,min(ncra,floor(ncra*(y_ang+pi)/(2*pi))));
dbn = max(0,min(1,(y_nrm-y_min)/(y_max-y_min)));
C1(nr,nc,:) = cra(nba,:)*dbn;
end;end;%for nr=1:res_(1); for nc=1:res_(2);
plot_flag=1;
if plot_flag;
subplot(2,2,4);
s=surf(X1,Y1,Z1,C1);set(s,'EdgeColor','none');
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
%light; lighting phong;
end;%if plot_flag;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ; 
% rotation via wigner-d ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ; 
[Xm,Ym,Zm]=sph2cart(THETA_,PHI_-pi/2,abs(Ymn_rota).^2);
[Xr,Yr,Zr]=sph2cart(THETA_,PHI_-pi/2,real(Ymn_rota).^2);
[Xi,Yi,Zi]=sph2cart(THETA_,PHI_-pi/2,imag(Ymn_rota).^2);
% [Xp,Yp,Zp]=sph2cart(THETA_,PHI_-pi/2,angle(Ymn_rota).^2);
plot_flag=1;
if plot_flag;
f=figure; axis off; hold on;
subplot(2,2,1);
surf(Xm,Ym,Zm,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim(xlim_orig_1); ylim(ylim_orig_1); zlim(zlim_orig_1);
subplot(2,2,2);
surf(Xr,Yr,Zr,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim(xlim_orig_2); ylim(ylim_orig_2); zlim(zlim_orig_2);
subplot(2,2,3);
surf(Xi,Yi,Zi,'linestyle','none'); 
%    surf(Xp,Yp,Zp,'linestyle','none'); 
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
light; lighting phong; camzoom(1.3);
xlim(xlim_orig_3); ylim(ylim_orig_3); zlim(zlim_orig_3);
end;%if plot_flag;
[X1,Y1,Z1]=sph2cart(THETA_,PHI_-pi/2,1.0);
cra = colormap('hsv'); ncra = size(cra,1);
y_min = 0; y_max = prctile(abs(Ymn_rota(:)),85);
C1 = zeros(res_(1),res_(2),3);
for nr=1:res_(1); for nc=1:res_(2);
y_tmp = Ymn_rota(nr,nc);
y_ang = angle(y_tmp); y_nrm = abs(y_tmp);
nba = max(1,min(ncra,floor(ncra*(y_ang+pi)/(2*pi))));
dbn = max(0,min(1,(y_nrm-y_min)/(y_max-y_min)));
C1(nr,nc,:) = cra(nba,:)*dbn;
end;end;%for nr=1:res_(1); for nc=1:res_(2);
plot_flag=1;
if plot_flag;
subplot(2,2,4);
s=surf(X1,Y1,Z1,C1);set(s,'EdgeColor','none');
xlabel('x'); ylabel('y'); zlabel('z');
axis equal; %rot3d;
axis vis3d;
%light; lighting phong;
end;%if plot_flag;

return


