%%%%%%%%;
% tests polar cap dilation. ;
%%%%%%%%;

clear;
%%%%%%%%;
platform = 'rusty';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
if (strcmp(platform,'eval1')); setup_eval1; string_root = 'home'; end;
if (strcmp(platform,'rusty')); setup_rusty; string_root = 'mnt/home'; end;
%%%%%%%%;

%%%%%%%%;
% First set up collection of templates. ;
%%%%%%%%;
verbose = 0; flag_disp=1; nf=0;
n_k_p_r = 1; k_p_r_max = 1.0; k_p_r_ = k_p_r_max; weight_3d_k_p_r_ = 1; l_max_ = 0; a_k_Y_ = 0;
viewing_k_eq_d = 0.5*k_p_r_max/(2*pi);;
template_k_eq_d = -1;
n_w_max = 64; n_w_0in_ = n_w_max;
gamma_z_ = linspace(0,2*pi,n_w_max+1); gamma_z_ = transpose(gamma_z_(1:n_w_max)); cc_ = cos(gamma_z_); sc_ = sin(gamma_z_);
[ ...
 S_k_p__ ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_k_w_ ...
,n_viewing_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,template_k_c_0_wS__ ...
,template_k_c_1_wS__ ...
,template_k_c_2_wS__ ...
] = ...
get_template_1( ...
 verbose ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_ ...
,viewing_k_eq_d ...
,template_k_eq_d ...
,n_w_0in_ ...
);
n_S = n_viewing_S;
template_k_r01_wS__ = sqrt(template_k_c_0_wS__.^2 + template_k_c_1_wS__.^2);
template_k_r012_wS__ = sqrt(template_k_c_0_wS__.^2 + template_k_c_1_wS__.^2 + template_k_c_2_wS__.^2);
template_azimu_b_wS__ = atan2(template_k_c_1_wS__,template_k_c_0_wS__);
template_polar_a_wS__ = atan2(template_k_r01_wS__,template_k_c_2_wS__);
viewing_k_c_0_S_ = cos(viewing_azimu_b_S_).*sin(viewing_polar_a_S_);
viewing_k_c_1_S_ = sin(viewing_azimu_b_S_).*sin(viewing_polar_a_S_);
viewing_k_c_2_S_ = cos(viewing_polar_a_S_);

n_test = 16;
for ntest=0:n_test-1;
nS = max(0,min(n_S-1,floor(n_S*ntest/n_test)));
[ ...
 template_k_c_0_w_ ...
,template_k_c_1_w_ ...
,template_k_c_2_w_ ...
,template_azimu_b_w_ ...
,template_polar_a_w_ ...
] = ...
get_template_single_ring_k_c_0( ...
 verbose ...
,1 ...
,viewing_azimu_b_S_(1+nS) ...
,viewing_polar_a_S_(1+nS) ...
,n_w_max ...
);
tmp_error = ...
 + fnorm(template_k_c_0_wS__(:,1+nS)-template_k_c_0_w_) ...
 + fnorm(template_k_c_1_wS__(:,1+nS)-template_k_c_1_w_) ...
 + fnorm(template_k_c_2_wS__(:,1+nS)-template_k_c_2_w_) ...
 + fnorm(template_azimu_b_wS__(:,1+nS)-template_azimu_b_w_) ...
 + fnorm(template_polar_a_wS__(:,1+nS)-template_polar_a_w_) ...
;
if (verbose>0); disp(sprintf(' %% ntest %d/%d tmp_error %0.16f;',ntest,n_test,tmp_error)); end;
end;%for ntest=0:n_test-1;

polar_cap_theta = pi/4; polar_cap_dilated_amplitude = 0.1;
index_polar_cap_ = efind(viewing_polar_a_S_<=polar_cap_theta);
n_viewing_polar_cap = numel(index_polar_cap_);
viewing_polar_cap_azimu_b_S_ = viewing_azimu_b_S_(1+index_polar_cap_);
%%%%;
viewing_polar_cap_polar_a_S_ = viewing_polar_a_S_(1+index_polar_cap_);
[ ...
 template_polar_cap_k_c_0_wS__ ...
,template_polar_cap_k_c_1_wS__ ...
,template_polar_cap_k_c_2_wS__ ...
,template_polar_cap_azimu_b_wS__ ...
,template_polar_cap_polar_a_wS__ ...
] = ...
get_template_single_ring_k_c_0( ...
 verbose ...
,n_viewing_polar_cap ...
,viewing_polar_cap_azimu_b_S_ ...
,viewing_polar_cap_polar_a_S_ ...
,n_w_max ...
);
%%%%;
viewing_polar_cap_dilated_polar_a_S_ = viewing_polar_cap_polar_a_S_ + polar_cap_dilated_amplitude*sin(2*viewing_polar_cap_polar_a_S_);
[ ...
 template_polar_cap_dilated_k_c_0_wS__ ...
,template_polar_cap_dilated_k_c_1_wS__ ...
,template_polar_cap_dilated_k_c_2_wS__ ...
,template_polar_cap_dilated_azimu_b_wS__ ...
,template_polar_cap_dilated_polar_a_wS__ ...
] = ...
get_template_single_ring_k_c_0( ...
 verbose ...
,n_viewing_polar_cap ...
,viewing_polar_cap_azimu_b_S_ ...
,viewing_polar_cap_dilated_polar_a_S_ ...
,n_w_max ...
);
%%%%;

flag_disp=0;
if flag_disp;
%%%%%%%%;
% Illustrate polar_cap and polar_cap_dilated. ;
%%%%%%%%;
figure(1+nf);nf=nf+1;clf;figmed;fig80s;
%%%%;
subplot(1,2,1);
hold on;
for nS=0:n_viewing_polar_cap-1;
surfline_0( ...
 template_polar_cap_k_c_0_wS__(:,1+nS) ...
,template_polar_cap_k_c_1_wS__(:,1+nS) ...
,template_polar_cap_k_c_2_wS__(:,1+nS) ...
,template_polar_cap_polar_a_wS__(:,1+nS) ...
);
end;%for nS=0:n_viewing_polar_cap-1;
xlim([-1,+1]); ylim([-1,+1]); zlim([-1,+1]); axis equal; axis vis3d;
%%%%;
subplot(1,2,2);
hold on;
for nS=0:n_viewing_polar_cap-1;
surfline_0( ...
 template_polar_cap_dilated_k_c_0_wS__(:,1+nS) ...
,template_polar_cap_dilated_k_c_1_wS__(:,1+nS) ...
,template_polar_cap_dilated_k_c_2_wS__(:,1+nS) ...
,template_polar_cap_dilated_polar_a_wS__(:,1+nS) ...
);
end;%for nS=0:n_viewing_polar_cap_dilated-1;
xlim([-1,+1]); ylim([-1,+1]); zlim([-1,+1]); axis equal; axis vis3d;
%%%%;
end;%if flag_disp;

Rz = @(azimu_b) ...
[ +cos(azimu_b) -sin(azimu_b) 0 ; ...
  +sin(azimu_b) +cos(azimu_b) 0 ; ...
   0             0            1 ; ...
] ;

Ry = @(polar_a) ...
[ +cos(polar_a) 0 +sin(polar_a) ; ...
   0            1  0            ; ...
  -sin(polar_a) 0 +cos(polar_a) ; ...
];


%%%%%%%%;
% Set parameters for polar cap dilation. ;
% We assume that each template is dilated (away from the pole) by g_dilation, ;
% corresponding to an overall mapping of viewing_polar_a via f_dilation. ;
% Note that, due to our strategy for constructing templates, ;
% the polar cap dilation corresponds to incrementing the viewing_polar_a by g_dilation, ;
% meaning that the template itself will remain indexed by gamma_z.
% This (canonical) indexing via gamma_z will typically result in a shift between the ;
% original gamma_z associated with a particular point (in a particular template) ;
% and the final gamma_z associated with that same point (in the predilated version of that template). ;
%%%%%%%%;
polar_cap_dilated_amplitude = 0.05;
g_dilation = @(point_pole_predilated_polar_a) polar_cap_dilated_amplitude*sin(2*point_pole_predilated_polar_a); %<-- approximation holds well for first nontrivial mode. ;
f_dilation = @(point_pole_predilated_polar_a) point_pole_predilated_polar_a + g_dilation(point_pole_predilated_polar_a);
%%%%%%%%;
% point_output is indexed by polar_a. ;
% point_pole is indexed by n_w_max. ;
%%%%%%%%;

flag_disp=1;
%%%%%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figbig;fig80s; c_hsv__ = colormap('hsv'); n_c_hsv = size(c_hsv__,1);
markersize_big = 8; markersize_use = 6; markersize_dot = 4; linewidth_use = 0.5;
plot_sphere_grid_0;
hold on;
end;%if flag_disp;
%%%%%%%%;
n_point = 1+64;
point_output_azimu_b_a_ = zeros(n_point,1);
point_output_polar_a_a_ = zeros(n_point,1);
point_pole_predilated_template_gammax_k_c_0_aw__ = zeros(n_point,n_w_max);
point_pole_predilated_template_gammax_k_c_1_aw__ = zeros(n_point,n_w_max);
point_pole_predilated_template_gammax_k_c_2_aw__ = zeros(n_point,n_w_max);
point_pole_predilated_template_gammax_azimu_b_aw__ = zeros(n_point,n_w_max);
point_pole_predilated_template_gammax_polar_a_aw__ = zeros(n_point,n_w_max);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
for npoint=0:n_point-1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
point_output_azimu_b = 0;%point_output_azimu_b = 2*pi*npoint/max(1,n_point);
point_output_polar_a = -pi/2 + pi/1*npoint/max(1,n_point-1);
point_output_gamma_z = 0;
point_output_k_c_ = Rz(point_output_azimu_b) * Ry(point_output_polar_a) * Rz(point_output_gamma_z) * [1;0;0];
point_pole_k_c__ = Rz(point_output_azimu_b) * Ry(point_output_polar_a) * Rz(point_output_gamma_z) * [zeros(1,n_w_max);transpose(sc_);transpose(cc_)];
point_output_azimu_b_a_(1+npoint) = point_output_azimu_b;
point_output_polar_a_a_(1+npoint) = point_output_polar_a;
%%%%%%%%;
if flag_disp;
plot3(point_output_k_c_(1+0),point_output_k_c_(1+1),point_output_k_c_(1+2),'mo','MarkerFaceColor',0.85*[1,1,1],'MarkerSize',markersize_use);
end;%if flag_disp;
%%%%%%%%%%%%%%%%;
for npole=0:n_w_max-1;
%%%%%%%%%%%%%%%%;
% Now we step through each of the templates associated with the point point_output. ;
%%%%%%%%;
if flag_disp;
nc_hsv = max(0,min(n_c_hsv-1,floor(n_c_hsv*(periodize(npole,0,n_w_max/2)/(n_w_max/2))))); %<-- note double winding (i.e., andipodal templates are the same). ;
end;%if flag_disp;
point_pole_k_c_ = point_pole_k_c__(:,1+npole);
point_pole_k_r01 = sqrt(point_pole_k_c_(1+0).^2 + point_pole_k_c_(1+1).^2);
point_pole_k_r012 = sqrt(point_pole_k_c_(1+0).^2 + point_pole_k_c_(1+1).^2 + point_pole_k_c_(1+2).^2);
point_pole_azimu_b = atan2(point_pole_k_c_(1+1),point_pole_k_c_(1+0));
point_pole_polar_a = atan2(point_pole_k_r01,point_pole_k_c_(1+2));
[ ...
 point_pole_template_k_c_0_w_ ...
,point_pole_template_k_c_1_w_ ...
,point_pole_template_k_c_2_w_ ...
,point_pole_template_azimu_b_w_ ...
,point_pole_template_polar_a_w_ ...
] = ...
get_template_single_ring_k_c_0( ...
 verbose ...
,1 ...
,point_pole_azimu_b ...
,point_pole_polar_a ...
,n_w_max ...
);
%%%%%%%%;
% Here we determine the predilated template that is associated with the original template mapped to point_output. ;
%%%%%%%%;
tmp_f_error = @(point_pole_predilated_polar_a) abs(f_dilation(point_pole_predilated_polar_a) - point_pole_polar_a).^2;
point_pole_predilated_polar_a = fminsearch(tmp_f_error,point_pole_polar_a);
tmp_point_pole_polar_a = point_pole_predilated_polar_a + polar_cap_dilated_amplitude*sin(2*point_pole_predilated_polar_a);
if (verbose>0); disp(sprintf(' %% npole %d/%d, fnorm(point_pole_polar_a-tmp_point_pole_polar_a): %0.16f',npole,n_w_max,fnorm(point_pole_polar_a-tmp_point_pole_polar_a))); end;
point_pole_predilated_k_c_ = [ ...
  cos(point_pole_azimu_b)*sin(point_pole_predilated_polar_a) ...
; sin(point_pole_azimu_b)*sin(point_pole_predilated_polar_a) ...
; cos(point_pole_predilated_polar_a) ...
];
[ ...
 point_pole_predilated_template_k_c_0_w_ ...
,point_pole_predilated_template_k_c_1_w_ ...
,point_pole_predilated_template_k_c_2_w_ ...
,point_pole_predilated_template_azimu_b_w_ ...
,point_pole_predilated_template_polar_a_w_ ...
] = ...
get_template_single_ring_k_c_0( ...
 verbose ...
,1 ...
,point_pole_azimu_b ...
,point_pole_predilated_polar_a ...
,n_w_max ...
);
%%%%%%%%;
point_pole_template_gamma0_k_c_ = [...
 +cos(point_pole_azimu_b)*cos(point_pole_polar_a) ...
;+sin(point_pole_azimu_b)*cos(point_pole_polar_a) ...
;-sin(point_pole_polar_a) ...
];
point_pole_template_sgx_k_c_ = cross(point_pole_template_gamma0_k_c_,point_output_k_c_);
point_pole_template_sgx = dot(point_pole_template_sgx_k_c_,point_pole_k_c_);
point_pole_template_cgx = dot(point_pole_template_gamma0_k_c_,point_output_k_c_);
point_pole_gx = atan2(point_pole_template_sgx,point_pole_template_cgx);
point_pole_template_gammax_k_c_ = [...
 +cos(point_pole_azimu_b)*cos(point_pole_polar_a)*cos(point_pole_gx) - sin(point_pole_azimu_b)*sin(point_pole_gx) ...
;+sin(point_pole_azimu_b)*cos(point_pole_polar_a)*cos(point_pole_gx) + cos(point_pole_azimu_b)*sin(point_pole_gx) ...
;-sin(point_pole_polar_a)*cos(point_pole_gx) ...
];
%%%%%%%%;
% Now we determine the gamma_z (denoted gammax) within predilated template that maps to point_output. ;
%%%%%%%%;
point_pole_predilated_template_gammax_k_c_ = [ ...
 +cos(point_pole_azimu_b)*cos(point_pole_predilated_polar_a)*cos(point_pole_gx) - sin(point_pole_azimu_b)*sin(point_pole_gx) ...
;+sin(point_pole_azimu_b)*cos(point_pole_predilated_polar_a)*cos(point_pole_gx) + cos(point_pole_azimu_b)*sin(point_pole_gx) ...
;-sin(point_pole_predilated_polar_a)*cos(point_pole_gx) ...
];
point_pole_predilated_template_gammax_k_c_0_aw__(1+npoint,1+npole) = point_pole_predilated_template_gammax_k_c_(1+0);
point_pole_predilated_template_gammax_k_c_1_aw__(1+npoint,1+npole) = point_pole_predilated_template_gammax_k_c_(1+1);
point_pole_predilated_template_gammax_k_c_2_aw__(1+npoint,1+npole) = point_pole_predilated_template_gammax_k_c_(1+2);
point_pole_predilated_template_gammax_k_r01 = sqrt(point_pole_predilated_template_gammax_k_c_(1+0).^2 + point_pole_predilated_template_gammax_k_c_(1+1).^2);
point_pole_predilated_template_gammax_k_r012 = sqrt(point_pole_predilated_template_gammax_k_c_(1+0).^2 + point_pole_predilated_template_gammax_k_c_(1+1).^2 + point_pole_predilated_template_gammax_k_c_(1+2).^2);
point_pole_predilated_template_gammax_azimu_b = atan2(point_pole_predilated_template_gammax_k_c_(1+1),point_pole_predilated_template_gammax_k_c_(1+0));
point_pole_predilated_template_gammax_polar_a = atan2(point_pole_predilated_template_gammax_k_r01,point_pole_predilated_template_gammax_k_c_(1+2));
point_pole_predilated_template_gammax_azimu_b_aw__(1+npoint,1+npole) = point_pole_predilated_template_gammax_azimu_b;
point_pole_predilated_template_gammax_polar_a_aw__(1+npoint,1+npole) = point_pole_predilated_template_gammax_polar_a;
%%%%%%%%;
if flag_disp;
%plot3(point_pole_k_c__(1+0,:),point_pole_k_c__(1+1,:),point_pole_k_c__(1+2,:),'k.','MarkerSize',markersize_dot);
%plot3(point_pole_k_c_(1+0),point_pole_k_c_(1+1),point_pole_k_c_(1+2),'co','MarkerFaceColor',c_hsv__(1+nc_hsv,:),'MarkerSize',markersize_use);
%plot3(point_pole_predilated_k_c_(1+0),point_pole_predilated_k_c_(1+1),point_pole_predilated_k_c_(1+2),'yo','MarkerFaceColor',c_hsv__(1+nc_hsv,:).^0.5,'MarkerSize',markersize_use);
%plot3(point_pole_template_k_c_0_w_,point_pole_template_k_c_1_w_,point_pole_template_k_c_2_w_,'g-','LineWidth',linewidth_use);
%plot3(point_pole_template_k_c_0_w_(1+0),point_pole_template_k_c_1_w_(1+0),point_pole_template_k_c_2_w_(1+0),'ko','MarkerSize',markersize_use);
%plot3(point_pole_template_gamma0_k_c_(1+0),point_pole_template_gamma0_k_c_(1+1),point_pole_template_gamma0_k_c_(1+2),'kx','MarkerSize',markersize_use);
plot3(point_pole_template_gammax_k_c_(1+0),point_pole_template_gammax_k_c_(1+1),point_pole_template_gammax_k_c_(1+2),'ko','MarkerSize',markersize_big);
plot3(point_pole_predilated_template_gammax_k_c_(1+0),point_pole_predilated_template_gammax_k_c_(1+1),point_pole_predilated_template_gammax_k_c_(1+2),'.','Color',c_hsv__(1+nc_hsv,:),'MarkerSize',markersize_dot);
end;%if flag_disp;
%%%%%%%%%%%%%%%%;
end;%for npole=0:n_w_max-1;
%%%%%%%%%%%%%%%%;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%for npoint=0:n_point-1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_disp;
xlim([-1,+1]); ylim([-1,+1]); zlim([-1,+1]); axis equal; axis vis3d;
xlabel('x'); ylabel('y'); zlabel('z');
hold off;
end;%if flag_disp;
%%%%%%%%;

disp(sprintf(' %% tmp_error: %0.16f',fnorm(point_pole_predilated_template_gammax_k_c_0_aw__ - cos(point_pole_predilated_template_gammax_azimu_b_aw__).*sin(point_pole_predilated_template_gammax_polar_a_aw__))));
disp(sprintf(' %% tmp_error: %0.16f',fnorm(point_pole_predilated_template_gammax_k_c_1_aw__ - sin(point_pole_predilated_template_gammax_azimu_b_aw__).*sin(point_pole_predilated_template_gammax_polar_a_aw__))));
disp(sprintf(' %% tmp_error: %0.16f',fnorm(point_pole_predilated_template_gammax_k_c_2_aw__ - cos(point_pole_predilated_template_gammax_polar_a_aw__))));
point_pole_predilated_template_gammax_k_c_0_avg_a_ = mean(point_pole_predilated_template_gammax_k_c_0_aw__,2);
point_pole_predilated_template_gammax_k_c_1_avg_a_ = mean(point_pole_predilated_template_gammax_k_c_1_aw__,2);
point_pole_predilated_template_gammax_k_c_2_avg_a_ = mean(point_pole_predilated_template_gammax_k_c_2_aw__,2);
point_pole_predilated_template_gammax_polar_a_avg_a_ = mean(point_pole_predilated_template_gammax_polar_a_aw__,2);
point_pole_predilated_template_gammax_polar_a_std_a_ = std(point_pole_predilated_template_gammax_polar_a_aw__,1,2);
point_pole_predilated_template_gammax_k_c_r_aw__ = ...
sqrt( ...
 bsxfun(@minus,point_pole_predilated_template_gammax_k_c_0_aw__,mean(point_pole_predilated_template_gammax_k_c_0_aw__,2)).^2 ...
+bsxfun(@minus,point_pole_predilated_template_gammax_k_c_1_aw__,mean(point_pole_predilated_template_gammax_k_c_1_aw__,2)).^2 ...
+bsxfun(@minus,point_pole_predilated_template_gammax_k_c_2_aw__,mean(point_pole_predilated_template_gammax_k_c_2_aw__,2)).^2 ...
);
%point_pole_predilated_template_gammax_k_c_r_avg_a_ = sqrt(mean(point_pole_predilated_template_gammax_k_c_r_aw__.^2,2)); %<-- take 2-norm, rather than mean norm. ;
point_pole_predilated_template_gammax_k_c_r_avg_a_ = mean(point_pole_predilated_template_gammax_k_c_r_aw__,2); %<-- take mean-norm, rather than 2-norm. ;

flag_disp=1;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;
%%%%;
subplot(1,3,1);
hold on;
plot(point_output_polar_a_a_+pi/2,point_pole_predilated_template_gammax_polar_a_avg_a_-point_output_polar_a_a_-pi/2,'ro-');
plot(point_output_polar_a_a_+pi/2,0.5*g_dilation(point_output_polar_a_a_+pi/2),'gx-');
hold off;
xlim([0,pi]); xlabel('point_output_polar_a_a_+pi/2','Interpreter','none'); ylabel('amplitude'); title('avg polar_a displacement amplitude','Interpreter','none');
%%%%;
subplot(1,3,2);
hold on;
plot(point_output_polar_a_a_+pi/2,+point_pole_predilated_template_gammax_polar_a_std_a_,'ro-');
plot(point_output_polar_a_a_+pi/2,-point_pole_predilated_template_gammax_polar_a_std_a_,'ro-');
plot(point_output_polar_a_a_+pi/2,(0.5/sqrt(2))*g_dilation(point_output_polar_a_a_+pi/2),'gx-');
hold off;
xlim([0,pi]); xlabel('point_output_polar_a_a_+pi/2','Interpreter','none'); ylabel('amplitude'); title('std polar_a displacement amplitude','Interpreter','none');
%%%%;
subplot(1,3,3);
hold on;
plot(point_output_polar_a_a_+pi/2,+point_pole_predilated_template_gammax_k_c_r_avg_a_,'mo-');
plot(point_output_polar_a_a_+pi/2,-point_pole_predilated_template_gammax_k_c_r_avg_a_,'mo-');
plot(point_output_polar_a_a_+pi/2,0.5*g_dilation(point_output_polar_a_a_+pi/2),'cx-');
hold off;
xlim([0,pi]); xlabel('point_output_polar_a_a_+pi/2','Interpreter','none'); ylabel('amplitude'); title('avg polar_a displacement radius','Interpreter','none');
%%%%;
end;%if flag_disp;
