function ...
[ ...
Error_l2 ...
Error_k1 ...
] = ...
test_MSA_sheres_error_0( ...
 q_max ...
,n_q ...
,q_ ...
,F_wq__ ...
,n_w ...
,gamma_ ...
,weight_ ...
,A_w_ ...
,A_q_ ...
,B_w_ ...
,B_q_ ...
);

if isempty(weight_); weight_ = 1/max(1,n_w); end;

A_q_l2 = sum(abs(A_q_).^2);
B_q_l2 = sum(abs(B_q_).^2);
AB_q_ = conj(A_q_(:)).*B_q_(:);
Error_l2 = sqrt(A_q_l2 + B_q_l2 - 2*max(real(F_wq__*AB_q_)));

tmp_index_ = knnsearch([real(B_w_(:)),imag(B_w_(:))],[real(A_w_(:)),imag(A_w_(:))],'K',1)-1;
Error_AB_k1 = sqrt(sum(abs(A_w_ - B_w_(1+tmp_index_)).^2));
tmp_index_ = knnsearch([real(A_w_(:)),imag(A_w_(:))],[real(B_w_(:)),imag(B_w_(:))],'K',1)-1;
Error_BA_k1 = sqrt(sum(abs(B_w_ - A_w_(1+tmp_index_)).^2));
Error_k1 = max(Error_AB_k1,Error_BA_k1);

