%%%%%%%%;
% Here we just check the sigma-normalizatin in CryoLike against the asymptotic formula from BioEM. ;
%%%%%%%%;

flag_verbose=1;
flag_disp=1; nf=0;
rng(0);

%%%%%%%%;
% Here we test a version of the integral in Gradshteyn and Ryzhik: 3.326.2 (just to make sure there are no typos). ;
%%%%%%%%;
M = 0.125; a = 10.325;
integrand = @(sigma) 1./sigma.^(2*M+1) .* exp(-a./sigma.^2);
lintegrand = @(sigma) -a./sigma.^2 - (2*M+1).*log(sigma);
dlintegrand = @(sigma) +2*a./sigma.^3 - (2*M+1)./sigma;
ddlintegrand = @(sigma) -6*a./sigma.^4 + (2*M+1)./sigma.^2;
I_form = 0.5 ./ a.^(M) * gamma(M);
sigma_opt = sqrt(2*a/(2*M+1));
sigma_max = 3*sigma_opt;
I_quad = integral(integrand,1e-9,sigma_max,'AbsTol',1e-9,'RelTol',1e-9,'WayPoints',[1e-9:1:sigma_max]);
q_lintegrand = @(sigma) lintegrand(sigma_opt) + dlintegrand(sigma_opt).*(sigma - sigma_opt) + 0.5*ddlintegrand(sigma_opt).*(sigma - sigma_opt).^2 ;
q_integrand = @(sigma) exp(q_lintegrand(sigma));
I_qqua = integral(q_integrand,1e-9,sigma_max,'AbsTol',1e-9,'RelTol',1e-9,'WayPoints',[1e-9:1:sigma_max]);
I_qfor = sqrt(pi) * exp(-(2*M+1)/2) ./ (2*a).^M .* (2*M+1).^(M-1/2) ;
fnorm_disp(flag_verbose,'I_qfor',I_qfor,'I_qqua',I_qqua,' %<-- can be difficult to resolve due to algebraic decay of integrand.');
%%%%;
if flag_disp;
sigma_ = linspace(0,sigma_max,1024);
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,2,1);
hold on;
plot(sigma_,lintegrand(sigma_),'r-','LineWidth',3);
plot(sigma_,q_lintegrand(sigma_),'g-','LineWidth',3);
hold off;
subplot(1,2,2);
hold on;
plot(sigma_,exp(lintegrand(sigma_)),'r-','LineWidth',3);
plot(sigma_,exp(q_lintegrand(sigma_)),'g-','LineWidth',3);
hold off;
end;%if flag_disp;
%%%%;
if flag_disp;
sigma_ = linspace(0,sigma_max,1024);
figure(1+nf);nf=nf+1;clf;figmed;
subplot(1,2,1);
hold on;
plot(sigma_,integrand(sigma_),'r-','LineWidth',3);
plot(sigma_opt,integrand(sigma_opt),'go','LineWidth',3);
hold off;
subplot(1,2,2);
hold on;
semilogy(sigma_,integrand(sigma_),'r-','LineWidth',3); %<-- you can plot the integrand to make sure the numerical integral is resolved. ;
semilogy(sigma_opt,integrand(sigma_opt),'go','LineWidth',3);
hold off;
end;%if flag_disp;
%%%%;
fnorm_disp(flag_verbose,'I_form',I_form,'I_quad',I_quad,' %<-- can be difficult to resolve due to algebraic decay of integrand.');
%%%%%%%%;

I_form = @(a,M) 0.5 ./ a.^(M) * gamma(M) ;
I_qfor = @(a,M) sqrt(pi) * exp(-(2*M+1)/2) ./ (2*a).^M .* (2*M+1).^(M-1/2) ;
I_lform = @(a,M) -log(2) - M.*log(a) + gammaln(M) ;
I_lqfor = @(a,M) 0.5*log(pi) - (2*M+1)/2 - M.*log(2) - M.*log(a) + (M-1/2).*log(2*M+1) ;
I_lform = @(la,M) -log(2) - M.*la + gammaln(M) ;
I_lqfor = @(la,M) 0.5*log(pi) - (2*M+1)/2 - M.*log(2) - M.*la + (M-1/2).*log(2*M+1) ;

%%%%%%%%;
n_la = 128+1;
la_max = 32;
la_ = transpose(linspace(-la_max,+la_max,n_la));
n_M = 128;
M_min = 0.001; M_max = 1.000;
%M_min = 1; M_max = 256^2;
M_ = transpose(linspace(M_min,M_max,n_M));
[la__,M__] = ndgrid(la_,M_);
I_lform__ = I_lform(la__,M__);
I_lqfor__ = I_lqfor(la__,M__);
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;figbeach;
Ilim_ = reshape(prctile(I_lform__,[ 1,99],'all'),[1,2]);
subplot(1,3,1);
imagesc(I_lform__,Ilim_);
axis image; axisnotick;
xlabel('M','Interpreter','none');
ylabel('log(a)','Interpreter','none');
title('I_lform__','Interpreter','none');
subplot(1,3,2);
imagesc(I_lqfor__,Ilim_);
axis image; axisnotick;
xlabel('M','Interpreter','none');
ylabel('log(a)','Interpreter','none');
title('I_lqfor__','Interpreter','none');
subplot(1,3,3);
imagesc((I_lform__ - I_lqfor__)./max(1e-12,abs(I_lform__)),[-1,+1]);
axis image; axisnotick;
xlabel('M','Interpreter','none');
ylabel('log(a)','Interpreter','none');
title('I_diff__','Interpreter','none');
sgtitle('M in [0,1]');
end;%if flag_disp;
%%%%;
%%%%%%%%;

%%%%%%%%;
n_la = 128+1;
la_max = 32;
la_ = transpose(linspace(-la_max,+la_max,n_la));
n_M = 128;
%M_min = 0.001; M_max = 1.000;
M_min = 1; M_max = 256^2;
M_ = transpose(linspace(M_min,M_max,n_M));
[la__,M__] = ndgrid(la_,M_);
I_lform__ = I_lform(la__,M__);
I_lqfor__ = I_lqfor(la__,M__);
%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;figbeach;
Ilim_ = reshape(prctile(I_lform__,[ 1,99],'all'),[1,2]);
subplot(1,3,1);
imagesc(I_lform__,Ilim_);
axis image; axisnotick;
xlabel('M','Interpreter','none');
ylabel('log(a)','Interpreter','none');
title('I_lform__','Interpreter','none');
subplot(1,3,2);
imagesc(I_lqfor__,Ilim_);
axis image; axisnotick;
xlabel('M','Interpreter','none');
ylabel('log(a)','Interpreter','none');
title('I_lqfor__','Interpreter','none');
subplot(1,3,3);
imagesc((I_lform__ - I_lqfor__)./max(1e-12,abs(I_lform__)),[-1,+1]);
axis image; axisnotick;
xlabel('M','Interpreter','none');
ylabel('log(a)','Interpreter','none');
title('I_diff__','Interpreter','none');
sgtitle('M in [1,256^2]');
end;%if flag_disp;
%%%%;
%%%%%%%%;
