% test 2d-fourier transform ; 
% attempting to test registration by |fhat| in 2d ;
% The tmplt S is perfectly centered ;
% The image M is slightly rotated and shifted ;

% generate tmplt S ;
ng = 64; max_x_c = 1; max_k_c = ng/max_x_c;
% realspace carte grid ; 
grid_x_c = linspace(0,max_x_c,ng+1); grid_x_c = grid_x_c(1:end-1); d_x_c = mean(diff(grid_x_c));
% freqspace carte grid ; 
grid_k_c = (0:ng-1)/max_x_c; d_k_c = mean(diff(grid_k_c));
% xxxxspace qring grid ;
grid_q = (0:ng-1) ; max_q = ng; qlim = [-2,+2]; grid_q2 = grid_q; grid_q2(ng/2:end) = grid_q2(ng/2:end)-ng;
% realspace carte meshgrid ;
[X_x_c,Y_x_c] = meshgrid(grid_x_c,grid_x_c); X_x_c(:,ng/2+1:end) = X_x_c(:,ng/2+1:end)-max_x_c; Y_x_c(ng/2+1:end,:) = Y_x_c(ng/2+1:end,:)-max_x_c;
R_x_c = sqrt(X_x_c.^2 + Y_x_c.^2); W_x_c = atan2(Y_x_c,X_x_c);
% freqspace carte meshgrid ;
[X_k_c,Y_k_c] = meshgrid(grid_k_c,grid_k_c); X_k_c(:,ng/2+1:end) = X_k_c(:,ng/2+1:end)-max_k_c; Y_k_c(ng/2+1:end,:) = Y_k_c(ng/2+1:end,:)-max_k_c;
R_k_c = sqrt(X_k_c.^2 + Y_k_c.^2); W_k_c = atan2(Y_k_c,X_k_c);
% realspace polar meshgrid ;
grid_x_r = linspace(0,max_x_c/2,ng+1); grid_x_r = grid_x_r(1:end-1); grid_x_w = linspace(0,2*pi,ng+1); grid_x_w = grid_x_w(1:end-1); 
[R_x_p,W_x_p] = meshgrid(grid_x_r,grid_x_w);
% freqspace polar meshgrid ;
grid_k_r = linspace(0,max_k_c/2,ng+1); grid_k_r = grid_k_r(1:end-1); grid_k_w = linspace(0,2*pi,ng+1); grid_k_w = grid_k_w(1:end-1); 
[R_k_p,W_k_p] = meshgrid(grid_k_r,grid_k_w);
% set up tmplt on realspace carte meshgrid ;
tmp_GA = imread('test_G6.png'); tmp_GB = imread('test_G7.png');
%tmp_GA = imread('test_G8.png'); tmp_GB = imread('test_G9.png');
tmp_Ax = (255-mean(tmp_GA,3))/255; tmp_Bx = (255-mean(tmp_GB,3))/255;
tmp_Ak = recenter2(fft2(recenter2(tmp_Ax))); tmp_Am = abs(tmp_Ak);
tmp_Bk = recenter2(fft2(recenter2(tmp_Bx))); tmp_Bm = abs(tmp_Bk);
disp_flag=1;
if (disp_flag);
figure;
subplot(2,3,1+0*3); imagesc(tmp_Ax);
subplot(2,3,2+0*3); imagesc(abs(tmp_Ak));
subplot(2,3,3+0*3); imagesc(angle(tmp_Ak));
subplot(2,3,1+1*3); imagesc(tmp_Bx);
subplot(2,3,2+1*3); imagesc(abs(tmp_Bk));
subplot(2,3,3+1*3); imagesc(angle(tmp_Bk));
end;%if (disp_flag);
S_x_c = recenter2(tmp_Am); Slim_x = max(0,mean(S_x_c(:)) + 1.0*std(S_x_c(:))*[-1,+1]);
L_S_x_c = sum(abs(S_x_c(:)).^2)*d_x_c*d_x_c;
% calculate tmplt values on realspace polar meshgrid ;
S_x_p = interp2(recenter2(X_x_c),recenter2(Y_x_c),recenter2(S_x_c),R_x_p.*cos(W_x_p),R_x_p.*sin(W_x_p));
% calculate tmplt values on realspace qring meshgrid ;
S_x_q = fft(S_x_p);
% calculate tmplt values on freqspace carte meshgrid ;
S_k_c = fft2(S_x_c) * d_x_c*d_x_c; Slim_k  = mean(abs(S_k_c(:))) + 1.0*std(abs(S_k_c(:)))*[-1,+1];
L_S_k_c = sum(abs(S_k_c(:)).^2)*d_k_c*d_k_c;
% calculate tmplt falues on freqspace polar meshgrid ;
S_k_p = interp2(recenter2(X_k_c),recenter2(Y_k_c),recenter2(S_k_c),R_k_p.*cos(W_k_p),R_k_p.*sin(W_k_p));
% calculate tmplt values on realspace qring meshgrid ;
S_k_q = fft(S_k_p);
disp(sprintf(' %% L_S_x_c %f L_S_k_c %f',L_S_x_c,L_S_k_c));

disp_flag=0;
if disp_flag;
figure;
% plot tmplt in realspace ;
subplot(3,3,1);imagesc(recenter2(real(S_x_c)),Slim_x);title('real(S_x_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c(1),grid_x_c(end/2+1),floor(10*grid_x_c(end))/10]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c(1),grid_x_c(end/2+1),floor(10*grid_x_c(end))/10]-max_x_c/2);
subplot(3,3,4);polarpatch(R_x_p,W_x_p,S_x_p,Slim_x);title('real(S_x_p)'); c = colorbar; %set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Slim_x(1),Slim_x(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(3,3,7);imagesc(abs(S_x_q([ng/2:ng,1:ng/2-1],:))); title('abs(S_x_q)'); colorbar; set(gca,'Ydir','normal'); set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[0,grid_x_r(end/2+1),grid_x_r(end)]); set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_q(1),grid_q(end/2+1),grid_q(end)]-max_q/2);
% plot tmplt in freqspace ;
subplot(3,3,2);imagesc(recenter2(real(S_k_c)),Slim_k);title('real(S_k_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);
subplot(3,3,3);imagesc(recenter2(imag(S_k_c)),Slim_k);title('imag(S_k_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);
subplot(3,3,5);polarpatch(R_k_p,W_k_p,real(S_k_p),Slim_k);title('real(S_k_p)'); c = colorbar; %set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Slim_k(1),Slim_k(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(3,3,6);polarpatch(R_k_p,W_k_p,imag(S_k_p),Slim_k);title('imag(S_k_p)'); c = colorbar; %set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Slim_k(1),Slim_k(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(3,3,8);imagesc(real(S_k_q([ng/2:ng,1:ng/2-1],:)),qlim); title('real(S_k_q)'); colorbar; set(gca,'Ydir','normal'); set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[0,grid_k_r(end/2+1),grid_k_r(end)]); set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_q(1),grid_q(end/2+1),grid_q(end)]-max_q/2);
subplot(3,3,9);imagesc(imag(S_k_q([ng/2:ng,1:ng/2-1],:)),qlim); title('imag(S_k_q)'); colorbar; set(gca,'Ydir','normal'); set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[0,grid_k_r(end/2+1),grid_k_r(end)]); set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_q(1),grid_q(end/2+1),grid_q(end)]-max_q/2);
end;%if disp_flag;

% generate image M ;
M_x_c = recenter2(tmp_Bm); Mlim_x = max(0,mean(M_x_c(:)) + 1.0*std(M_x_c(:))*[-1,+1]);
L_M_x_c = sum(abs(M_x_c(:)).^2)*d_x_c*d_x_c;
% calculate image values on realspace polar meshgrid ;
M_x_p = interp2(recenter2(X_x_c),recenter2(Y_x_c),recenter2(M_x_c),R_x_p.*cos(W_x_p),R_x_p.*sin(W_x_p));
% calculate image values on realspace qring meshgrid ;
M_x_q = fft(M_x_p);
% calculate image values on freqspace carte meshgrid ;
M_k_c = fft2(M_x_c) * d_x_c*d_x_c; Mlim_k  = mean(abs(M_k_c(:))) + 1.0*std(abs(M_k_c(:)))*[-1,+1];
L_M_k_c = sum(abs(M_k_c(:)).^2)*d_k_c*d_k_c;
% calculate image falues on freqspace polar meshgrid ;
M_k_p = interp2(recenter2(X_k_c),recenter2(Y_k_c),recenter2(M_k_c),R_k_p.*cos(W_k_p),R_k_p.*sin(W_k_p));
% calculate image values on realspace qring meshgrid ;
M_k_q = fft(M_k_p);
disp(sprintf(' %% L_M_x_c %f L_M_k_c %f',L_M_x_c,L_M_k_c));

disp_flag=0;
if disp_flag;
figure;
% plot image in realspace ;
subplot(3,3,1);imagesc(recenter2(real(M_x_c)),Mlim_x);title('real(M_x_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c(1),grid_x_c(end/2+1),floor(10*grid_x_c(end))/10]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c(1),grid_x_c(end/2+1),floor(10*grid_x_c(end))/10]-max_x_c/2);
subplot(3,3,4);polarpatch(R_x_p,W_x_p,M_x_p,Mlim_x);title('real(M_x_p)'); c = colorbar; %set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Mlim_x(1),Mlim_x(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(3,3,7);imagesc(abs(M_x_q([ng/2:ng,1:ng/2-1],:))); title('abs(M_x_q)'); colorbar; set(gca,'Ydir','normal'); set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[0,grid_x_r(end/2+1),grid_x_r(end)]); set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_q(1),grid_q(end/2+1),grid_q(end)]-max_q/2);
% plot image in freqspace ;
subplot(3,3,2);imagesc(recenter2(real(M_k_c)),Mlim_k);title('real(M_k_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);
subplot(3,3,3);imagesc(recenter2(imag(M_k_c)),Mlim_k);title('imag(M_k_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);
subplot(3,3,5);polarpatch(R_k_p,W_k_p,real(M_k_p),Mlim_k);title('real(M_k_p)'); c = colorbar; %set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Mlim_k(1),Mlim_k(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(3,3,6);polarpatch(R_k_p,W_k_p,imag(M_k_p),Mlim_k);title('imag(M_k_p)'); c = colorbar; %set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Mlim_k(1),Mlim_k(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(3,3,8);imagesc(real(M_k_q([ng/2:ng,1:ng/2-1],:)),qlim); title('real(M_k_q)'); colorbar; set(gca,'Ydir','normal'); set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[0,grid_k_r(end/2+1),grid_k_r(end)]); set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_q(1),grid_q(end/2+1),grid_q(end)]-max_q/2);
subplot(3,3,9);imagesc(imag(M_k_q([ng/2:ng,1:ng/2-1],:)),qlim); title('imag(M_k_q)'); colorbar; set(gca,'Ydir','normal'); set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[0,grid_k_r(end/2+1),grid_k_r(end)]); set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_q(1),grid_q(end/2+1),grid_q(end)]-max_q/2);
end;%if disp_flag;

% generate array of rotations ; 
n_gamma = 256;
gamma_ = linspace(0,1*pi,n_gamma+1); gamma_ = gamma_(1:end-1);

% direct calculation of all overlap integrals $C_k = \int\int \hat{M}\cdot\bar{\hat{S}}d\vec{k}$ for each gamma ;
C_x_ = zeros(n_gamma,1);
C_k_ = zeros(n_gamma,1);
disp_flag=0; if disp_flag; figure; end;
for ngamma = 1:n_gamma; 
gamma = gamma_(ngamma);
N_x_c = M_x_c;
N_x_c = recenter2(interp2(recenter2(X_x_c),recenter2(Y_x_c),recenter2(N_x_c),recenter2(X_x_c)*cos(gamma) - recenter2(Y_x_c)*sin(gamma),recenter2(X_x_c)*sin(gamma) + recenter2(Y_x_c)*cos(gamma),'linear',0));
C_x_(ngamma) = sum(abs(N_x_c(:) - S_x_c(:)).^2)*d_x_c*d_x_c;
if disp_flag;
clf;
subplot(1,3,1); imagesc(recenter2(S_x_c)); set(gca,'XTick',[],'YTick',[]); title('S');
subplot(1,3,2); imagesc(recenter2(M_x_c)); set(gca,'XTick',[],'YTick',[]); title('M');
subplot(1,3,3); imagesc(recenter2(N_x_c)); set(gca,'XTick',[],'YTick',[]); title(sprintf('N=R[%d/%d](M)',ngamma,n_gamma));
set(gcf,'Position',1+[0,0,1024,256]);
drawnow();
end;%if disp_flag;
%N_k_c = M_k_c;
%N_k_c = recenter2(interp2(recenter2(X_k_c),recenter2(Y_k_c),recenter2(N_k_c),recenter2(X_k_c)*cos(gamma) - recenter2(Y_k_c)*sin(gamma),recenter2(X_k_c)*sin(gamma) + recenter2(Y_k_c)*cos(gamma),'nearest',0));
%C_k_(ngamma) = sum(abs(N_k_c(:) - S_k_c(:)).^2)*d_k_c*d_k_c;
end;%for ngamma = 1:n_gamma; 

% show overlap integrals after calculation (gamma only) ;
disp_flag=1;
if disp_flag;
figure;
%plot(gamma_,C_x_,'k.-',gamma_,C_k_,'r.-');
plot(gamma_,C_x_,'k.-');
end;%if disp_flag;


