%%%%%%%%;
% indices. ;
%%%%%%%%;
n_k_all = ampm_.n_k_all;
n_k_all_csum_ = ampm_.n_k_all_csum_;
k_p_r_all_ = ampm_.k_p_r_all_;
k_p_azimu_b_all_ = ampm_.k_p_azimu_b_all_;
k_p_polar_a_all_ = ampm_.k_p_polar_a_all_;
weight_3d_k_all_ = ampm_.weight_3d_k_all_;
weight_shell_k_ = ampm_.weight_shell_k_;
n_k_p_r = ampm_.n_k_p_r;
k_p_r_ = ampm_.k_p_r_;
k_p_r_max = ampm_.k_p_r_max;
weight_3d_k_p_r_ = ampm_.weight_3d_k_p_r_;
l_max_ = ampm_.l_max_;
%%%%%%%%;
n_k_all = ampm_.n_k_all;
weight_3d_k_all_ = ampm_.weight_3d_k_all_;
k_c_0_all_ = ampm_.k_c_0_all_;
k_c_1_all_ = ampm_.k_c_1_all_;
k_c_2_all_ = ampm_.k_c_2_all_;
k_p_r_max = ampm_.k_p_r_max;
n_xxx_u = ampm_.n_xxx_u;
xxx_u_weight_ = ampm_.xxx_u_weight_;
x_u_0___ = ampm_.x_u_0___;
x_u_1___ = ampm_.x_u_1___;
x_u_2___ = ampm_.x_u_2___;
x_p_r_max = ampm_.x_p_r_max;
%%%%%%%%;

%%%%%%%%;
tmp_n_a = 24;
tmp_a_x_u_xxxa__ = zeros(n_xxx_u,tmp_n_a);
tmp_corr_a_ = zeros(tmp_n_a,1);
for tmp_na=0:tmp_n_a-1;
na = index_X_best_ampm_srt_(1+tmp_na);
%%%%%%%%;
[ ... 
 tmp_a_k_Y_ampm_alig_ ...
,tmp_corr_a_(1+tmp_na) ...
] = ...
spharm_register_and_rotate_2( ...
 n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,ampm_.a_k_Y_quad_ ...
,ampm_.a_k_Y_ampm_yka__(:,1+na) ...
,0 ...
,ampm_.X_best_ampm_ia__(end,1+na) ...
,ampm_.X_best_flag_flip_ampm_ia__(end,1+na) ...
,ampm_.polar_a_best_ampm_ia__(end,1+na) ...
,ampm_.azimu_b_best_ampm_ia__(end,1+na) ...
,ampm_.gamma_z_best_ampm_ia__(end,1+na) ...
,ampm_.delta_best_ampm_dia__(1+0,end,1+na) ...
,ampm_.delta_best_ampm_dia__(1+1,end,1+na) ...
,ampm_.delta_best_ampm_dia__(1+2,end,1+na) ...
);
%%%%%%%%
if ~exist('Ylm_klma___','var'); Ylm_klma___ = []; end;
tmp_t = tic();
[ ...
 tmp_a_k_p_ampm_alig_  ...
,Ylm_klma___ ...
] =  ...
convert_spharm_to_k_p_3( ...
 0*flag_verbose ...
,n_k_all ...
,n_k_all_csum_ ...
,k_p_r_all_ ...
,k_p_azimu_b_all_ ...
,k_p_polar_a_all_ ...
,weight_3d_k_all_ ...
,weight_shell_k_ ...
,n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,tmp_a_k_Y_ampm_alig_ ...
,Ylm_klma___ ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% convert_spharm_to_k_p_3: %0.6fs',tmp_t));
%%%%%%%%;
tmp_t = tic(); 
[ ...
 tmp_a_x_u_ampm_alig_ ...
] = ...
convert_k_p_to_x_c_1( ...
 0*flag_verbose ...
,n_k_all ...
,weight_3d_k_all_ ...
,k_c_0_all_ ...
,k_c_1_all_ ...
,k_c_2_all_ ...
,k_p_r_max ...
,n_xxx_u ...
,xxx_u_weight_ ...
,x_u_0___ ...
,x_u_1___ ...
,x_u_2___ ...
,x_p_r_max ...
,tmp_a_k_p_ampm_alig_ ...
);
tmp_t = toc(tmp_t); disp(sprintf(' %% convert_k_p_to_x_c_1: %0.6fs',tmp_t));
%%%%%%%%;
tmp_a_x_u_xxxa__(:,1+tmp_na) = tmp_a_x_u_ampm_alig_;
%%%%%%%%;
end;%for tmp_na=0:tmp_n_a-1;
%%%%%%%%;


