%%%%%%%%;
% testing discrete derivative for kappa_qpro_apply_2. ;
%%%%%%%%;
rng(7);
dtau_euler_polar_a_M_ = 2*pi*rand(n_M,1);
dtau_euler_azimu_b_M_ = 2*pi*rand(n_M,1);
dtau_euler_gamma_z_M_ = 2*pi*rand(n_M,1);
dtau_fnorm = fnorm([ dtau_euler_polar_a_M_ , dtau_euler_azimu_b_M_ , dtau_euler_gamma_z_M_ ]);
dtau_euler_polar_a_M_ = dtau_euler_polar_a_M_/max(1e-12,dtau_fnorm);
dtau_euler_azimu_b_M_ = dtau_euler_azimu_b_M_/max(1e-12,dtau_fnorm);
dtau_euler_gamma_z_M_ = dtau_euler_gamma_z_M_/max(1e-12,dtau_fnorm);
dtau = 1e-4;
%%%%%%%%;
parameter_ssnll = struct('type','parameter');
parameter_ssnll.n_order = 7;
%%%%%%%%;
parameter_KAPPA = struct('type','KAPPA');
parameter_KAPPA.flag_kernel_qpro_d0 = 1;
parameter_KAPPA.flag_kernel_qpro_d1 = 1;
parameter_KAPPA.kernel_qpro_polar_a_pole_north=4.5*pi/24;
parameter_KAPPA.kernel_qpro_polar_a_pole_south=3.5*pi/24;
parameter_KAPPA.kernel_qpro_l_max_use = l_max;
KAPPA = [];
%%%%%%%%;

%%%%%%%%;
[ ...
 ~ ...
,ssnll_mid_pwv_M_ ...
,ssnll_mid_pwv ...
,S_k_p_mid_pwv_wkS__ ...
,dvol_ssnll_mid_pwv_M_ ...
,dvol_ssnll_mid_pwv ...
,dvol_S_k_p_mid_pwv_wkS__ ...
,dvol_dvol_ssnll_mid_pwv ...
,dtau_ssnll_mid_pwv_M3__ ...
,dtau_ssnll_mid_pwv ...
,dtau_S_k_p_mid_pwv_wkS3___ ...
,dtau_dvol_ssnll_mid_pwv_M3__ ...
,dtau_dvol_ssnll_mid_pwv ...
,dtau_dvol_S_k_p_mid_pwv_wkS3___ ...
,dtau_dtau_ssnll_mid_pwv_M33___ ...
,dtau_dtau_ssnll_mid_pwv ...
,dtau_dtau_S_k_p_mid_pwv_wkS33____ ...
] = ...
ssnll_from_plane_wave_expansion_0( ...
 parameter_ssnll ...
,n_source_a ...
,v_source_a_ ...
,delta_a_c__ ...
,n_source_b ...
,v_source_b_ ...
,delta_b_c__ ...
,n_source_dvol_a ...
,v_source_dvol_a_ ...
,delta_dvol_a_c__ ...
,n_k_p_r ...
,k_p_r_ ...
,n_w_max ...
,weight_2d_wk_ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,n_eta ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,n_M ...
,euler_polar_a_M_ + 0*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + 0*dtau*dtau_euler_azimu_b_M_...
,0*euler_gamma_z_M_ + 0*dtau*dtau_euler_gamma_z_M_ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
,n_S ...
,index_nS_from_nM_ ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
%%%%%%%%;
[ ...
 ~ ...
,ssnll_pos_pwv_M_ ...
,ssnll_pos_pwv ...
] = ...
ssnll_from_plane_wave_expansion_0( ...
 parameter_ssnll ...
,n_source_a ...
,v_source_a_ ...
,delta_a_c__ ...
,n_source_b ...
,v_source_b_ ...
,delta_b_c__ ...
,n_source_dvol_a ...
,v_source_dvol_a_ ...
,delta_dvol_a_c__ ...
,n_k_p_r ...
,k_p_r_ ...
,n_w_max ...
,weight_2d_wk_ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,n_eta ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,n_M ...
,euler_polar_a_M_ + 1*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + 1*dtau*dtau_euler_azimu_b_M_...
,0*euler_gamma_z_M_ + 1*dtau*dtau_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_S ...
,index_nS_from_nM_ ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
%%%%%%%%;
[ ...
 ~ ...
,ssnll_neg_pwv_M_ ...
,ssnll_neg_pwv ...
] = ...
ssnll_from_plane_wave_expansion_0( ...
 parameter_ssnll ...
,n_source_a ...
,v_source_a_ ...
,delta_a_c__ ...
,n_source_b ...
,v_source_b_ ...
,delta_b_c__ ...
,n_source_dvol_a ...
,v_source_dvol_a_ ...
,delta_dvol_a_c__ ...
,n_k_p_r ...
,k_p_r_ ...
,n_w_max ...
,weight_2d_wk_ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,n_eta ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,n_M ...
,euler_polar_a_M_ - 1*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ - 1*dtau*dtau_euler_azimu_b_M_...
,0*euler_gamma_z_M_ - 1*dtau*dtau_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_S ...
,index_nS_from_nM_ ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
%%%%%%%%;
dtau_ssnll_dif_pwv = (ssnll_pos_pwv - ssnll_neg_pwv)/max(1e-12,2*dtau);
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_pwv vs dtau_ssnll_dif_pwv: %0.16f',fnorm(dtau_ssnll_mid_pwv - dtau_ssnll_dif_pwv)/max(1e-12,fnorm(dtau_ssnll_mid_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_pwv vs dtau_ssnll_dif_pwv: %0.16f',fnorm(dtau_ssnll_mid_pwv - dtau_ssnll_dif_pwv)/max(1e-12,fnorm(dtau_ssnll_mid_pwv)))); end;

%%%%%%%%;
[ ...
 ~ ...
,ssnll_mid_q2d_M_ ...
,ssnll_mid_q2d ...
,S_k_p_mid_q2d_wkS__ ...
,dvol_ssnll_mid_q2d_M_ ...
,dvol_ssnll_mid_q2d ...
,dvol_S_k_p_mid_q2d_wkS__ ...
,dvol_dvol_ssnll_mid_q2d ...
,dtau_ssnll_mid_q2d_M3__ ...
,dtau_ssnll_mid_q2d ...
,dtau_S_k_p_mid_q2d_wkS3___ ...
,dtau_dvol_ssnll_mid_q2d_M3__ ...
,dtau_dvol_ssnll_mid_q2d ...
,dtau_dvol_S_k_p_mid_q2d_wkS3___ ...
,dtau_dtau_ssnll_mid_q2d_M33___ ...
,dtau_dtau_ssnll_mid_q2d ...
,dtau_dtau_S_k_p_mid_q2d_wkS33____ ...
] = ...
ssnll_from_a_k_Y_12( ...
 parameter_ssnll ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_form_yk__ ...
,[] ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,euler_polar_a_M_ + 0*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + 0*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ + 0*dtau*dtau_euler_gamma_z_M_...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
);
if (flag_verbose>0); disp(sprintf(' %% ssnll_mid_pwv vs ssnll_mid_q2d: %0.16f',fnorm(ssnll_mid_pwv - ssnll_mid_q2d)/max(1e-12,fnorm(ssnll_mid_pwv)))); end;
%%%%%%%%;
[ ...
 ~ ...
,ssnll_pos_q2d_M_ ...
,ssnll_pos_q2d ...
] = ...
ssnll_from_a_k_Y_12( ...
 parameter_ssnll ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_form_yk__ ...
,[] ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,euler_polar_a_M_ + 1*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + 1*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ + 1*dtau*dtau_euler_gamma_z_M_...
,[] ...
,[] ...
,[] ...
);
if (flag_verbose>0); disp(sprintf(' %% ssnll_pos_pwv vs ssnll_pos_q2d: %0.16f',fnorm(ssnll_pos_pwv - ssnll_pos_q2d)/max(1e-12,fnorm(ssnll_pos_pwv)))); end;
%%%%%%%%;
[ ...
 ~ ...
,ssnll_neg_q2d_M_ ...
,ssnll_neg_q2d ...
] = ...
ssnll_from_a_k_Y_12( ...
 parameter_ssnll ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_form_yk__ ...
,[] ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,[] ...
,[] ...
,[] ...
,[] ...
,[] ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,euler_polar_a_M_ - 1*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ - 1*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ - 1*dtau*dtau_euler_gamma_z_M_...
,[] ...
,[] ...
,[] ...
);
if (flag_verbose>0); disp(sprintf(' %% ssnll_neg_pwv vs ssnll_neg_q2d: %0.16f',fnorm(ssnll_neg_pwv - ssnll_neg_q2d)/max(1e-12,fnorm(ssnll_neg_pwv)))); end;
%%%%%%%%;
dtau_ssnll_dif_q2d = (ssnll_pos_q2d - ssnll_neg_q2d)/max(1e-12,2*dtau);
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_pwv vs dtau_ssnll_dif_q2d: %0.16f',fnorm(dtau_ssnll_mid_pwv - dtau_ssnll_dif_q2d)/max(1e-12,fnorm(dtau_ssnll_mid_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_q2d vs dtau_ssnll_dif_q2d: %0.16f',fnorm(dtau_ssnll_mid_q2d - dtau_ssnll_dif_q2d)/max(1e-12,fnorm(dtau_ssnll_mid_q2d)))); end;

%%%%%%%%;
% Note that ssnll_from_a_k_Y_12 has difficulty interpolating over the poles. ;
% For this reason we avoid templates close to the poles. ;
%%%%%%%%;
nstep_dtau_ = -8:+8;
n_nstep_dtau = numel(nstep_dtau_);
%%%%%%%%;
ssnll_mid_pwv_s_ = zeros(n_nstep_dtau,1);
for nnstep_dtau=0:n_nstep_dtau-1;
nstep_dtau = nstep_dtau_(1+nnstep_dtau);
if (flag_verbose>0); disp(sprintf(' %% nnstep_dtau %+.3d/%+.3d nstep_dtau %+.3d',nnstep_dtau,n_nstep_dtau,nstep_dtau)); end;
[ ...
 ~ ...
,~ ...
,ssnll_mid_pwv_s_(1+nnstep_dtau) ...
] = ...
ssnll_from_plane_wave_expansion_0( ...
 parameter_ssnll ...
,n_source_a ...
,v_source_a_ ...
,delta_a_c__ ...
,n_source_b ...
,v_source_b_ ...
,delta_b_c__ ...
,n_source_dvol_a ...
,v_source_dvol_a_ ...
,delta_dvol_a_c__ ...
,n_k_p_r ...
,k_p_r_ ...
,n_w_max ...
,weight_2d_wk_ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,n_eta ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,n_M ...
,euler_polar_a_M_ + nstep_dtau*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + nstep_dtau*dtau*dtau_euler_azimu_b_M_...
,0*euler_gamma_z_M_ + nstep_dtau*dtau*dtau_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_S ...
,index_nS_from_nM_ ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_gamma_z_S_ ...
);
end;%for nnstep_dtau=0:n_nstep_dtau-1;
%%%%%%%%;
ssnll_mid_q3d = 0.0d0;
ssnll_mid_q3d_s_ = zeros(n_nstep_dtau,1);
for nnstep_dtau=0:n_nstep_dtau-1;
nstep_dtau = nstep_dtau_(1+nnstep_dtau);
if (flag_verbose>0); disp(sprintf(' %% nnstep_dtau %+.3d/%+.3d nstep_dtau %+.3d',nnstep_dtau,n_nstep_dtau,nstep_dtau)); end;
[ ...
 parameter_KAPPA ...
,KAPPA ...
,tmp_a_restore_mid_C2M0_k_Y_lmk__ ...
,tmp_a_restore_mid_C1M1_k_Y_lmk__ ...
,tmp_a_restore_mid_C0M2_k_Y_lmk__ ...
] = ...
kappa_qpro_apply_2( ...
 parameter_KAPPA ...
,KAPPA ...
,n_w_max ...
,n_M ...
,euler_polar_a_M_ + nstep_dtau*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + nstep_dtau*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ + nstep_dtau*dtau*dtau_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
);
ssnll_mid_q3d_s_(1+nnstep_dtau) = ...
 + 0.5 * sum( (conj(aa_k_Y_quad_yk__) .* tmp_a_restore_mid_C2M0_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_form_yk__).^1 .* tmp_a_restore_mid_C1M1_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( tmp_a_restore_mid_C0M2_k_Y_lmk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
ssnll_mid_q3d_s_(1+nnstep_dtau) = real( ssnll_mid_q3d_s_(1+nnstep_dtau) / scaling_volumetric ) ;
if nstep_dtau==0; ssnll_mid_q3d = ssnll_mid_q3d_s_(1+nnstep_dtau); end;
end;%for nnstep_dtau=0:n_nstep_dtau-1;
%%%%%%%%;
ssnll_mid_q2d_s_ = zeros(n_nstep_dtau,1);
for nnstep_dtau=0:n_nstep_dtau-1;
nstep_dtau = nstep_dtau_(1+nnstep_dtau);
if (flag_verbose>0); disp(sprintf(' %% nnstep_dtau %+.3d/%+.3d nstep_dtau %+.3d',nnstep_dtau,n_nstep_dtau,nstep_dtau)); end;
[ ...
 ~ ...
,~ ...
,ssnll_mid_q2d_s_(1+nnstep_dtau) ...
] = ...
ssnll_from_a_k_Y_12( ...
 parameter_ssnll ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,l_max_ ...
,a_k_Y_form_yk__ ...
,[] ...
,n_w_ ...
,weight_2d_k_p_r_ ...
,weight_2d_wk_ ...
,n_S ...
,S_k_p_mid_q2d_wkS__ ...
,[] ...
,[] ...
,[] ...
,[] ...
,viewing_polar_a_S_ ...
,viewing_azimu_b_S_ ...
,viewing_weight_S_ ...
,n_viewing_polar_a ...
,viewing_polar_a_ ...
,n_viewing_azimu_b_ ...
,n_M ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_wkC__ ...
,index_neta_from_nM_ ...
,eta_k_p_wke__ ...
,euler_polar_a_M_ + nstep_dtau*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + nstep_dtau*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ + nstep_dtau*dtau*dtau_euler_gamma_z_M_...
,[] ...
,[] ...
,[] ...
);
end;%for nnstep_dtau=0:n_nstep_dtau-1;
%%%%%%%%;
if flag_disp;
figure(1+nf);nf=nf+1;clf;figmed;
hold on;
plot(nstep_dtau_,ssnll_mid_pwv_s_,'ko');
plot(0,ssnll_mid_pwv,'kx');
plot(nstep_dtau_,ssnll_mid_q3d_s_,'go');
plot(0,ssnll_mid_q3d,'gx');
plot(nstep_dtau_,ssnll_mid_q2d_s_,'ro');
plot(0,ssnll_mid_q2d,'rx');
xlabel('nstep_dtau','Interpreter','none');
ylabel('ssnll_mid_xx','Interpreter','none');
end;%if flag_disp;
%%%%%%%%;

%%%%%%%%;
% Calculate volumetric terms. ;
%%%%%%%%;
tmp_t = tic();
[ ...
 parameter_KAPPA ...
,KAPPA ...
,a_restore_mid_C2M0_k_Y_lmk__ ...
,a_restore_mid_C1M1_k_Y_lmk__ ...
,a_restore_mid_C0M2_k_Y_lmk__ ...
,dtau_a_restore_mid_C2M0_k_Y_lmk__ ...
,dtau_a_restore_mid_C1M1_k_Y_lmk__ ...
,dtau_a_restore_mid_C0M2_k_Y_lmk__ ...
,dtau_dtau_a_restore_mid_C2M0_k_Y_lmk__ ...
,dtau_dtau_a_restore_mid_C1M1_k_Y_lmk__ ...
,dtau_dtau_a_restore_mid_C0M2_k_Y_lmk__ ...
] = ...
kappa_qpro_apply_2( ...
 parameter_KAPPA ...
,KAPPA ...
,n_w_max ...
,n_M ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,dtau_euler_polar_a_M_ ...
,dtau_euler_azimu_b_M_ ...
,dtau_euler_gamma_z_M_ ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% kappa_qpro_apply_2 (yes derivatives) time %0.2fs',tmp_t)); end;
%%%%%%%%;

tmp_t = tic();
[ ...
 parameter_KAPPA ...
,KAPPA ...
,a_restore_pos_C2M0_k_Y_lmk__ ...
,a_restore_pos_C1M1_k_Y_lmk__ ...
,a_restore_pos_C0M2_k_Y_lmk__ ...
] = ...
kappa_qpro_apply_2( ...
 parameter_KAPPA ...
,KAPPA ...
,n_w_max ...
,n_M ...
,euler_polar_a_M_ + 1*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ + 1*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ + 1*dtau*dtau_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% kappa_qpro_apply_2 (not derivatives) time %0.2fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
% Calculate volumetric terms. ;
%%%%%%%%;
tmp_t = tic();
[ ...
 parameter_KAPPA ...
,KAPPA ...
,a_restore_neg_C2M0_k_Y_lmk__ ...
,a_restore_neg_C1M1_k_Y_lmk__ ...
,a_restore_neg_C0M2_k_Y_lmk__ ...
] = ...
kappa_qpro_apply_2( ...
 parameter_KAPPA ...
,KAPPA ...
,n_w_max ...
,n_M ...
,euler_polar_a_M_ - 1*dtau*dtau_euler_polar_a_M_ ...
,euler_azimu_b_M_ - 1*dtau*dtau_euler_azimu_b_M_ ...
,euler_gamma_z_M_ - 1*dtau*dtau_euler_gamma_z_M_ ...
,[] ...
,[] ...
,[] ...
,n_k_p_r ...
,M_k_p_wkM__ ...
,n_CTF ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>0); disp(sprintf(' %% kappa_qpro_apply_2 (not derivatives) time %0.2fs',tmp_t)); end;
%%%%%%%%;

%%%%%%%%;
% Collect terms into ssnll. ;
%%%%%%%%;
ssnll_mid_q3d = ...
 + 0.5 * sum( (conj(aa_k_Y_quad_yk__) .* a_restore_mid_C2M0_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_form_yk__).^1 .* a_restore_mid_C1M1_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( a_restore_mid_C0M2_k_Y_lmk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
ssnll_mid_q3d = real( ssnll_mid_q3d / scaling_volumetric ) ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_pwv vs ssnll_mid_q3d: %0.16f',fnorm(ssnll_pwv - ssnll_mid_q3d)/max(1e-12,fnorm(ssnll_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% ssnll_q2d vs ssnll_mid_q3d: %0.16f',fnorm(ssnll_q2d - ssnll_mid_q3d)/max(1e-12,fnorm(ssnll_q2d)))); end;
if (flag_verbose>0); disp(sprintf(' %% ssnll_mid_pwv vs ssnll_mid_q3d: %0.16f',fnorm(ssnll_mid_pwv - ssnll_mid_q3d)/max(1e-12,fnorm(ssnll_mid_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% ssnll_mid_q2d vs ssnll_mid_q3d: %0.16f',fnorm(ssnll_mid_q2d - ssnll_mid_q3d)/max(1e-12,fnorm(ssnll_mid_q2d)))); end;
%%%%%%%%;
ssnll_pos_q3d = ...
 + 0.5 * sum( (conj(aa_k_Y_quad_yk__) .* a_restore_pos_C2M0_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_form_yk__).^1 .* a_restore_pos_C1M1_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( a_restore_pos_C0M2_k_Y_lmk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
ssnll_pos_q3d = real( ssnll_pos_q3d / scaling_volumetric ) ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_pos_pwv vs ssnll_pos_q3d: %0.16f',fnorm(ssnll_pos_pwv - ssnll_pos_q3d)/max(1e-12,fnorm(ssnll_pos_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% ssnll_pos_q2d vs ssnll_pos_q3d: %0.16f',fnorm(ssnll_pos_q2d - ssnll_pos_q3d)/max(1e-12,fnorm(ssnll_pos_q2d)))); end;
%%%%%%%%;
ssnll_neg_q3d = ...
 + 0.5 * sum( (conj(aa_k_Y_quad_yk__) .* a_restore_neg_C2M0_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_form_yk__).^1 .* a_restore_neg_C1M1_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( a_restore_neg_C0M2_k_Y_lmk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
ssnll_neg_q3d = real( ssnll_neg_q3d / scaling_volumetric ) ;
if (flag_verbose>0); disp(sprintf(' %% ssnll_neg_pwv vs ssnll_neg_q3d: %0.16f',fnorm(ssnll_neg_pwv - ssnll_neg_q3d)/max(1e-12,fnorm(ssnll_neg_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% ssnll_neg_q2d vs ssnll_neg_q3d: %0.16f',fnorm(ssnll_neg_q2d - ssnll_neg_q3d)/max(1e-12,fnorm(ssnll_neg_q2d)))); end;
%%%%%%%%;
dtau_ssnll_dif_q3d = (ssnll_pos_q3d - ssnll_neg_q3d)/max(1e-12,2*dtau);
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_pwv vs dtau_ssnll_dif_q3d: %0.16f',fnorm(dtau_ssnll_mid_pwv - dtau_ssnll_dif_q3d)/max(1e-12,fnorm(dtau_ssnll_mid_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_q2d vs dtau_ssnll_dif_q3d: %0.16f',fnorm(dtau_ssnll_mid_q2d - dtau_ssnll_dif_q3d)/max(1e-12,fnorm(dtau_ssnll_mid_q2d)))); end;
%%%%%%%%;
% Collect terms into dtau_ssnll. ;
%%%%%%%%;
dtau_ssnll_mid_q3d = ...
 + 0.5 * sum( (conj(aa_k_Y_quad_yk__) .* dtau_a_restore_mid_C2M0_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) ) ...
 - 0.5 * 2*real(sum( (conj(a_k_Y_form_yk__).^1 .* dtau_a_restore_mid_C1M1_k_Y_lmk__) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1]) )) ...
 + 0.5 * sum( dtau_a_restore_mid_C0M2_k_Y_lmk__(1+0,:) * reshape(weight_3d_riesz_k_p_r_,[n_k_p_r,1])*sqrt(4*pi) ) ...
;
dtau_ssnll_mid_q3d = real( dtau_ssnll_mid_q3d / scaling_volumetric ) ;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_pwv vs dtau_ssnll_mid_q3d: %0.16f',fnorm(dtau_ssnll_mid_pwv - dtau_ssnll_mid_q3d)/max(1e-12,fnorm(dtau_ssnll_mid_pwv)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_q2d vs dtau_ssnll_mid_q3d: %0.16f',fnorm(dtau_ssnll_mid_q2d - dtau_ssnll_mid_q3d)/max(1e-12,fnorm(dtau_ssnll_mid_q2d)))); end;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% dtau_ssnll_mid_q3d vs dtau_ssnll_dif_q3d: %0.16f',fnorm(dtau_ssnll_mid_q3d - dtau_ssnll_dif_q3d)/max(1e-12,fnorm(dtau_ssnll_mid_q3d)))); end;

%%%%%%%%;
dtau_a_restore_dif_C2M0_k_Y_lmk__ = (a_restore_pos_C2M0_k_Y_lmk__ - a_restore_neg_C2M0_k_Y_lmk__)/max(1e-12,2*dtau);
dtau_a_restore_dif_C1M1_k_Y_lmk__ = (a_restore_pos_C1M1_k_Y_lmk__ - a_restore_neg_C1M1_k_Y_lmk__)/max(1e-12,2*dtau);
dtau_a_restore_dif_C0M2_k_Y_lmk__ = (a_restore_pos_C0M2_k_Y_lmk__ - a_restore_neg_C0M2_k_Y_lmk__)/max(1e-12,2*dtau);
if (flag_verbose>0); disp(sprintf(' %% dtau_a_restore_dif_C2M0_k_Y_lmk__ vs dtau_a_restore_mid_C2M0_k_Y_lmk__: %0.16f',fnorm(dtau_a_restore_dif_C2M0_k_Y_lmk__ - dtau_a_restore_mid_C2M0_k_Y_lmk__)/max(1e-12,fnorm(dtau_a_restore_dif_C2M0_k_Y_lmk__)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_a_restore_dif_C1M1_k_Y_lmk__ vs dtau_a_restore_mid_C1M1_k_Y_lmk__: %0.16f',fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__ - dtau_a_restore_mid_C1M1_k_Y_lmk__)/max(1e-12,fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_a_restore_dif_C0M2_k_Y_lmk__ vs dtau_a_restore_mid_C0M2_k_Y_lmk__: %0.16f',fnorm(dtau_a_restore_dif_C0M2_k_Y_lmk__ - dtau_a_restore_mid_C0M2_k_Y_lmk__)/max(1e-12,fnorm(dtau_a_restore_dif_C0M2_k_Y_lmk__)))); end;
dtau_dtau_a_restore_dif_C2M0_k_Y_lmk__ = (a_restore_pos_C2M0_k_Y_lmk__ - 2*a_restore_mid_C2M0_k_Y_lmk__ + a_restore_neg_C2M0_k_Y_lmk__)/max(1e-12,dtau*dtau);
dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__ = (a_restore_pos_C1M1_k_Y_lmk__ - 2*a_restore_mid_C1M1_k_Y_lmk__ + a_restore_neg_C1M1_k_Y_lmk__)/max(1e-12,dtau*dtau);
dtau_dtau_a_restore_dif_C0M2_k_Y_lmk__ = (a_restore_pos_C0M2_k_Y_lmk__ - 2*a_restore_mid_C0M2_k_Y_lmk__ + a_restore_neg_C0M2_k_Y_lmk__)/max(1e-12,dtau*dtau);
if (flag_verbose>0); disp(sprintf(' %% dtau_dtau_a_restore_dif_C2M0_k_Y_lmk__ vs dtau_dtau_a_restore_mid_C2M0_k_Y_lmk__: %0.16f',fnorm(dtau_dtau_a_restore_dif_C2M0_k_Y_lmk__ - dtau_dtau_a_restore_mid_C2M0_k_Y_lmk__)/max(1e-12,fnorm(dtau_dtau_a_restore_dif_C2M0_k_Y_lmk__)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__ vs dtau_dtau_a_restore_mid_C1M1_k_Y_lmk__: %0.16f',fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__ - dtau_dtau_a_restore_mid_C1M1_k_Y_lmk__)/max(1e-12,fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__)))); end;
if (flag_verbose>0); disp(sprintf(' %% dtau_dtau_a_restore_dif_C0M2_k_Y_lmk__ vs dtau_dtau_a_restore_mid_C0M2_k_Y_lmk__: %0.16f',fnorm(dtau_dtau_a_restore_dif_C0M2_k_Y_lmk__ - dtau_dtau_a_restore_mid_C0M2_k_Y_lmk__)/max(1e-12,fnorm(dtau_dtau_a_restore_dif_C0M2_k_Y_lmk__)))); end;
%%%%%%%%;
figure(1+nf);nf=nf+1;clf;figmed;
markersize_use = 4;
l_max = KAPPA.l_max_use;
l_val_ = transpose(0:l_max);
%%%%;
subplot(1,2,1);
tmp_r_C2M0_ = zeros(1+l_max,1);
tmp_r_C1M1_ = zeros(1+l_max,1);
tmp_r_C0M2_ = zeros(1+l_max,1);
for l_val=0:l_max;
tmp_index_ = efind(KAPPA.Y_l_val_use_==l_val);
tmp_r_C2M0_num = fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:) - dtau_a_restore_mid_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C2M0_den = fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C2M0 = tmp_r_C2M0_num/max(1e-12,tmp_r_C2M0_den);
tmp_r_C2M0_(1+l_val) = tmp_r_C2M0;
tmp_r_C1M1_num = fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:) - dtau_a_restore_mid_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C1M1_den = fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C1M1 = tmp_r_C1M1_num/max(1e-12,tmp_r_C1M1_den);
tmp_r_C1M1_(1+l_val) = tmp_r_C1M1;
tmp_r_C0M2_num = fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:) - dtau_a_restore_mid_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C0M2_den = fnorm(dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C0M2 = tmp_r_C0M2_num/max(1e-12,tmp_r_C0M2_den);
tmp_r_C0M2_(1+l_val) = tmp_r_C0M2;
end;%for l_val=0:l_max;
hold on;
plot(l_val_,log10(tmp_r_C2M0_),'ko','MarkerSize',markersize_use,'MarkerFaceColor','g');
plot(l_val_,log10(tmp_r_C1M1_),'ko','MarkerSize',markersize_use,'MarkerFaceColor','r');
plot(l_val_,log10(tmp_r_C0M2_),'ko','MarkerSize',markersize_use,'MarkerFaceColor','m');
hold off;
xlim([0,l_max]);
xlabel('l_val','Interpreter','none');
ylabel('log10(relative error)','Interpreter','none');
title('dtau_relative_error','Interpreter','none');
%%%%;
subplot(1,2,2);
tmp_r_C2M0_ = zeros(1+l_max,1);
tmp_r_C1M1_ = zeros(1+l_max,1);
tmp_r_C0M2_ = zeros(1+l_max,1);
for l_val=0:l_max;
tmp_index_ = efind(KAPPA.Y_l_val_use_==l_val);
tmp_r_C2M0_num = fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:) - dtau_dtau_a_restore_mid_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C2M0_den = fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C2M0 = tmp_r_C2M0_num/max(1e-12,tmp_r_C2M0_den);
tmp_r_C2M0_(1+l_val) = tmp_r_C2M0;
tmp_r_C1M1_num = fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:) - dtau_dtau_a_restore_mid_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C1M1_den = fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C1M1 = tmp_r_C1M1_num/max(1e-12,tmp_r_C1M1_den);
tmp_r_C1M1_(1+l_val) = tmp_r_C1M1;
tmp_r_C0M2_num = fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:) - dtau_dtau_a_restore_mid_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C0M2_den = fnorm(dtau_dtau_a_restore_dif_C1M1_k_Y_lmk__(1+tmp_index_,:));
tmp_r_C0M2 = tmp_r_C0M2_num/max(1e-12,tmp_r_C0M2_den);
tmp_r_C0M2_(1+l_val) = tmp_r_C0M2;
end;%for l_val=0:l_max;
hold on;
plot(l_val_,log10(tmp_r_C2M0_),'ko','MarkerSize',markersize_use,'MarkerFaceColor','g');
plot(l_val_,log10(tmp_r_C1M1_),'ko','MarkerSize',markersize_use,'MarkerFaceColor','r');
plot(l_val_,log10(tmp_r_C0M2_),'ko','MarkerSize',markersize_use,'MarkerFaceColor','m');
hold off;
xlim([0,l_max]);
xlabel('l_val','Interpreter','none');
ylabel('log10(relative error)','Interpreter','none');
title('dtau_dtau_relative_error','Interpreter','none');
%%%%%%%%;
