function VUXM_lwnM____ = tpmh_VUXM_lwnM____3(FTK,n_k_p_r,n_w_,n_M,M_k_q__,n_UX_rank,UX__,X_weight_r_);

verbose=0;
n_w_max = max(n_w_); n_w_2 = round(n_w_max/2);
l_max = max(abs(FTK.svd_l_));
%%%%%%%%;

%%%%%%%%;
tmp_t = tic();
V_r__ = reshape(FTK.svd_polyval_V_r_,[FTK.n_svd_l,n_k_p_r]);
tmp_t = toc(tmp_t); if (verbose); disp(sprintf(' %% V_r__ %0.6fs',tmp_t)); end;
V_UX_lrn___ = zeros(FTK.n_svd_l,n_k_p_r,n_UX_rank);
for nUX_rank=0:n_UX_rank-1;
V_UX_lrn___(:,:,1+nUX_rank) = V_r__*diag(UX__(:,1+nUX_rank).*X_weight_r_(:));
end;%for nUX_rank=0:n_UX_rank-1;
%%%%%%%%;
index_nw_out__ = cell(1+2*l_max,1);
index_nw_0in__ = cell(1+2*l_max,1);
n_nw_ = zeros(1+2*l_max,1);
for l_shift=-l_max:+l_max;
index_nw_out_head_ = (0:n_w_2-1-max(0,+l_shift));
index_nw_0in_head_ = [ n_w_max+l_shift:n_w_max-1 , max(0,+l_shift):n_w_2-1-max(0,-l_shift) ];
index_nw_out_tail_ = (n_w_2+1+max(0,-l_shift):n_w_max-1);
index_nw_0in_tail_ = [ n_w_2+1+max(0,+l_shift):n_w_max-1-max(0,-l_shift), 0:+l_shift-1 ];
index_nw_out_ = [ index_nw_out_head_ , index_nw_out_tail_ ];
index_nw_0in_ = [ index_nw_0in_head_ , index_nw_0in_tail_ ];
n_nw = numel(index_nw_out_);
n_nw_(1+l_max+l_shift) = n_nw;
index_nw_out__{1+l_max+l_shift} = index_nw_out_;
index_nw_0in__{1+l_max+l_shift} = index_nw_0in_;
end;%for l_shift=-l_max:+l_max;
%%%%%%%%;
assert(mod(n_w_max,2)==0); %<-- assert that n_w_max is even. ;
index_nw_zerobased_from_centered_ = [ n_w_2:n_w_max-1 , 0:n_w_2-1 ]; %<-- note that we place n_w_2 mode first, ;
index_nw_centered_from_zerobased_ = [ n_w_2:n_w_max-1 , 0:n_w_2-1 ]; %<-- note that we place first mode at n_w_2. ;
index_nw_centered_out_start_ = zeros(1+2*l_max,1);
index_nw_centered_out_final_ = zeros(1+2*l_max,1);
index_nw_centered_0in_start_ = zeros(1+2*l_max,1);
index_nw_centered_0in_final_ = zeros(1+2*l_max,1);
for l_shift=-l_max:+l_max;
index_nw_centered_out_start_(1+l_max+l_shift) = 1+max(0,-l_shift);
index_nw_centered_out_final_(1+l_max+l_shift) = n_w_max-1+min(0,-l_shift);
index_nw_centered_0in_start_(1+l_max+l_shift) = 1+max(0,+l_shift);
index_nw_centered_0in_final_(1+l_max+l_shift) = n_w_max-1+min(0,+l_shift);
end;%for l_shift=-l_max:+l_max;
%%%%%%%%;
M_k_q_centered_rwM___ = permute(reshape(M_k_q__,[n_w_max,n_k_p_r,n_M]),[2,1,3]);
M_k_q_centered_rwM___ = M_k_q_centered_rwM___(:,1+index_nw_centered_from_zerobased_,:);
%%%%%%%%;
VUXM_centered_lwMn____ = zeros(FTK.n_svd_l,n_w_max,n_M,n_UX_rank);
for nl=0:FTK.n_svd_l-1;
l_shift = FTK.svd_l_(1+nl);
index_nw_centered_out_start = index_nw_centered_out_start_(1+l_max+l_shift);
index_nw_centered_out_final = index_nw_centered_out_final_(1+l_max+l_shift);
index_nw_centered_0in_start = index_nw_centered_0in_start_(1+l_max+l_shift);
index_nw_centered_0in_final = index_nw_centered_0in_final_(1+l_max+l_shift);
index_nw_centered_out_ = [index_nw_centered_out_start:index_nw_centered_out_final];
index_nw_centered_0in_ = [index_nw_centered_0in_start:index_nw_centered_0in_final];
n_nw = numel(index_nw_centered_out_);
for nUX_rank=0:n_UX_rank-1;
for nM=0:n_M-1;
VUXM_centered_lwMn____(1+nl,1+index_nw_centered_out_,1+nM,1+nUX_rank) = V_UX_lrn___(1+nl,:,1+nUX_rank)*M_k_q_centered_rwM___(:,1+index_nw_centered_0in_,1+nM) / n_w_max ;
end;%for nM=0:n_M-1;
end;%for nUX_rank=0:n_UX_rank-1;
end;%for nl=0:FTK.n_svd_l-1;
VUXM_lwnM____ = permute(VUXM_centered_lwMn____(:,1+index_nw_zerobased_from_centered_,:,:),[1,2,4,3]);

