function [Wt_,dWtdkd_out__,Wt_out___] = wignert_ODE_0(dWtdkd_0in__,Wt_0in___,n_k_p_r,k_p_r_,l_max_,kd_ratio);
%%%%%%%%;
n_lm_ = (l_max_+1).^2; n_lm_sum = sum(n_lm_);
l_max_max = max(l_max_); dWtdkd__l_max_max = 2*l_max_max;
%%%%%%%%;
if (~isempty(dWtdkd_0in__)); dWtdkd_out__ = dWtdkd_0in__; end;
if ( isempty(dWtdkd_0in__)); dWtdkd_out__ = dwignertdkd__(dWtdkd__l_max_max); end;
%%%%%%%%;
n_lm_sum = sum(n_lm_);
n_lm_csum_ = cumsum([0;n_lm_]);
%%%%%%%%;
if (~isempty(Wt_0in___)); Wt_out___ = Wt_0in___; end;
if ( isempty(Wt_0in___)); Wt_out___ = expm_dwignertdkd__(dWtdkd_out__,n_k_p_r,k_p_r_,l_max_,kd_ratio); end;
%%%%%%%%;

ns=0;
for nk_p_r = 0:n_k_p_r-1;
l_max = l_max_(1+nk_p_r);
n_m_max = 2*l_max+1;
for nm=0:n_m_max-1;
m_val = -l_max + nm; m_abs = abs(m_val);
%for l_val_a=m_abs:l_max;
%for l_val_b=m_abs:l_max;
%ns=ns+1;
%end;%for l_val_b=m_abs:l_max;
%end;%for l_val_a=m_abs:l_max;
ns = ns + (1 + l_max - m_abs)^2;
end;%for nm=0:n_m_max-1;
end;%for nk_p_r = 0:n_k_p_r-1;
n_s = ns;

Wt_row_ij_ = zeros(n_s,1);
Wt_col_ij_ = zeros(n_s,1);
Wt_val_ij_ = zeros(n_s,1);
ns=0;
for nk_p_r = 0:n_k_p_r-1;
k_p_r = k_p_r_(1+nk_p_r);
n_lm_csum = n_lm_csum_(1+nk_p_r);
l_max = l_max_(1+nk_p_r);
n_m_max = 2*l_max+1;
for nm=0:n_m_max-1;
m_val = -l_max + nm; m_abs = abs(m_val);
for l_val_a=m_abs:l_max;
nml_a = l_val_a^2 + (m_val+l_val_a);
for l_val_b=m_abs:l_max;
nml_b = l_val_b^2 + (m_val+l_val_b);
Wt_row_ij_(1+ns) = n_lm_csum + 1+nml_a;
Wt_col_ij_(1+ns) = n_lm_csum + 1+nml_b;
Wt_val_ij_(1+ns) = Wt_out___{1+nk_p_r}{1+m_abs}(1+l_val_a-m_abs,1+l_val_b-m_abs);
ns=ns+1;
end;%for l_val_b=m_abs:l_max;
end;%for l_val_a=m_abs:l_max;
end;%for nm=0:n_m_max-1;
end;%for nk_p_r = 0:n_k_p_r-1;
Wt_ = sparse(Wt_row_ij_,Wt_col_ij_,Wt_val_ij_,n_lm_sum,n_lm_sum);

