%%%%%%%%;
% Paraxial approximation to shrodinger-equation. ;
% Beam headed in z-direction. ;
% Using polar (i.e., radial) description of x-y-plane for now. ;
% Simple lens followed by concentric rings. ;
%%%%%%%%;

flag_verbose=1; nf=0;
flag_disp = 1; nf=0; flag_replot = 1;
str_thisfunction = 'test_bb_4';

%%%%%%%%;
platform = 'rusty';
if (exist('platform.type','file')); fp=fopen('platform.type'); platform = fscanf(fp,'%s'); fclose(fp); end;
if (strcmp(platform,'access1')); setup_access1; string_root = 'data'; end;
if (strcmp(platform,'OptiPlex')); setup_OptiPlex; string_root = 'home'; end;
if (strcmp(platform,'eval1')); setup_eval1; string_root = 'home'; end;
if (strcmp(platform,'rusty')); setup_rusty; string_root = 'mnt/home'; end;
%%%%%%%%;
dir_base = sprintf('/%s/rangan/dir_cryoem/dir_rangan_besselbeam',string_root);
dir_fig = sprintf('%s/dir_besselbeam_fig',dir_base);

%%%%%%%%;
% Redefine grids. ;
%%%%%%%%;
half_diameter_x_c = 1.0d0;
diameter_x_c = 2.0d0*half_diameter_x_c;
%%%%%%%%;
x_res = 2;
x_int = 48*x_res;
x_eq_d_double = 0.5*(x_res/2);
%%%%%%%%;
k_res = 2*8; %<-- be careful with the aliasing associated with n_x_M_u. ;
k_int = 48*k_res;
k_eq_d_double = 0.5*(k_res/2);
%%%%%%%%;
x_p_r_max = half_diameter_x_c;
k_p_r_max = k_int/(2*pi);
x_eq_d = x_eq_d_double/(2*pi)/64 * 1.05; %<-- to check dimensions. ;
k_eq_d = k_eq_d_double/(2*pi)/32 * 1.00; %<-- to check dimensions. ;
%%%%%%%%;
[ ...
 n_x_p_r ...
,x_p_r_ ...
,weight_3d_x_p_r_ ...
,weight_2d_x_p_r_ ...
] = ...
get_weight_3d_1( ...
 max(0,flag_verbose-1) ...
,x_p_r_max ...
,x_eq_d ...
);
fnorm_disp(flag_verbose,'sum(weight_3d_x_p_r_)*4*pi',sum(weight_3d_x_p_r_)*4*pi,'volume',4/3*pi*x_p_r_max^3,' %<-- should be small.');
fnorm_disp(flag_verbose,'sum(weight_2d_x_p_r_)',sum(weight_2d_x_p_r_),'area',pi*x_p_r_max^2,' %<-- should be small.');
%%%%%%%%;
[ ...
 n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
] = ...
get_weight_3d_1( ...
 max(0,flag_verbose-1) ...
,k_p_r_max ...
,k_eq_d ...
);
fnorm_disp(flag_verbose,'sum(weight_3d_k_p_r_)*4*pi',sum(weight_3d_k_p_r_)*4*pi,'volume',4/3*pi*k_p_r_max^3,' %<-- should be small.');
fnorm_disp(flag_verbose,'sum(weight_2d_k_p_r_)',sum(weight_2d_k_p_r_),'area',pi*k_p_r_max^2,' %<-- should be small.');
%%%%%%%%;

%%%%%%%%;
% set units. ;
%%%%%%%%;
unit = struct('type','unit');
unit.m = 1.0;
unit.cm=1e-2*unit.m;
unit.mm=1e-3*unit.m;
unit.um=1e-6*unit.m;
unit.nm=1e-9*unit.m;
unit.rad=1.0;
unit.mrad=1e-3*unit.rad;
unit.urad=1e-6*unit.rad;
unit.deg=(2*pi*unit.rad)/360;
unit.W = 1.0;
unit.mW = 1e-3*unit.W;
%%%%%%%%;
lightpipe = struct('type','lightpipe');
lightpipe.wavelength = 405 * unit.nm ; % wavelength ;
lightpipe.lam = lightpipe.wavelength ; % lambda = wavelength. ;
lightpipe.size       = 20  * unit.mm ; % simulation window size ;
lightpipe.N          = 5096 ; % grid resolution ;
lightpipe.Kmax       = k_p_r_max/max(1e-12,lightpipe.size) ; % bandlimit (max spatial-frequency) for x-y-plane in 1/unit.m. i.e., exp(\pm i*2*pi*k_p_r_max*x_p_r_) are the highest-frequency components;
lightpipe.z          = 1  * unit.m ; % long distance for Fraunhofer approx ;
lightpipe.a          = 15.0  * unit.mm ; % slit width ;
%%%%%%%%;
% circular aperture. ;
% Note (6.561.5 in TISPISMIGR): ;
% \int_{x=0}^{x=1} x^{q+1} besselj(q,a*x) dx = besselj(q+1,a)/a ;
% \int_{x=0}^{x=1}dx (\pm i).^(q0) .* x^{q0+1} .* besselj(q0,2*pi*k*x) = besselj(q0+1,(2*pi*k))/(2*pi*k) ;
% \int_{x=0}^{x=x_cut}dx x^{1} .* besselj(0,2*pi*k*x) = ...
% \int_{y=0}^{y=1}dy x_cut*x_cut*y^{1} .* besselj(0,2*pi*k*x_cut*y) = x_cut^2 * besselj(1,(2*pi*k*x_cut))/(2*pi*k*x_cut) ;
%%%%%%%%;
lambda = lightpipe.wavelength;
z_max = 2*10^8*lambda ; % here we think of z in terms of number of wavelengths. ;

x_cut = ( (lightpipe.a/2) / (lightpipe.size/2) ) * x_p_r_max ;
M_x_q_x_form_ = []; %M_x_q_x_form_ = 1.0*(x_p_r_ <= x_cut) ;
M_k_q_k_form_ = []; %M_k_q_k_form_ = 2*pi*x_cut * besselj(1,(2*pi*k_p_r_*x_cut)) ./ max(1e-12,2*pi*k_p_r_) ;
x_step = x_cut/32;
M_x_q_x_orig_ = ...
 0 ...
 - 0.5*(1 + erf((x_p_r_ - 1.00*x_cut)/x_step)) ...
 + 0.5*(1 + erf((x_p_r_ - 0.85*x_cut)/x_step)) ...
 - 0.5*(1 + erf((x_p_r_ - 0.50*x_cut)/x_step)) ...
 + 0.5*(1 + erf((x_p_r_ - 0.35*x_cut)/x_step)) ...
;
lightpipe.focal_length = z_max / 8 ;
M_x_q_x_orig_ = M_x_q_x_orig_.*exp(-i*2*pi/lambda .* (x_p_r_*lightpipe.size/2).^2 / (2*lightpipe.focal_length));
%lightpipe.axicon_theta = 1/2048;
%M_x_q_x_orig_ = M_x_q_x_orig_.*exp( -i*2*pi/lambda .* lightpipe.axicon_theta .* (x_p_r_*lightpipe.size/2).^1 );
tmp_t = tic();
flag_sign = -1; q_val = 0;
[ ...
 ~ ...
,M_k_q_k_fht2_ ...
] = ...
fht_2( ...
 [] ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,M_x_q_x_orig_ ...
,q_val ...
,flag_sign ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% fht_2: time %0.6fs',tmp_t)); end;
tmp_t = tic();
[ ...
 ~ ...
,M_k_q_k_sht1_ ...
] = ...
sht_1( ...
 [] ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,M_x_q_x_orig_ ...
,q_val ...
,flag_sign ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% sht_1: time %0.6fs',tmp_t)); end;
tmp_t = tic();
flag_sign = +1; q_val = 0;
[ ...
 ~ ...
,M_x_q_x_fht2_ ...
] = ...
fht_2( ...
 [] ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
,M_k_q_k_sht1_ ...
,q_val ...
,flag_sign ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% fht_2: time %0.6fs',tmp_t)); end;
tmp_t = tic();
flag_sign = +1; q_val = 0;
[ ...
 ~ ...
,M_x_q_x_sht1_ ...
] = ...
sht_1( ...
 [] ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
,M_k_q_k_sht1_ ...
,q_val ...
,flag_sign ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% sht_1: time %0.6fs',tmp_t)); end;
fnorm_disp(flag_verbose,'M_k_q_k_sht1_',M_k_q_k_sht1_,'M_k_q_k_fht2_',M_k_q_k_fht2_,'%<-- should be small.');
fnorm_disp(flag_verbose,'M_x_q_x_orig_',M_x_q_x_orig_,'M_x_q_x_sht1_',M_x_q_x_sht1_,'%<-- should be small.');
fnorm_disp(flag_verbose,'M_x_q_x_orig_',M_x_q_x_orig_,'M_x_q_x_fht2_',M_x_q_x_fht2_,'%<-- should be small.');
%%%%%%%%;


if flag_disp>0;
%%%%%%%%;
figure(1+nf);nf=nf+1;clf;figmed;
M_x_lim_ = prctile(real(M_x_q_x_orig_),[  0, 100]); M_x_lim_ = mean(M_x_lim_) + 1.25*0.5*diff(M_x_lim_)*[-1,+1];
M_k_lim_ = prctile(real(M_k_q_k_fht2_),[  0, 100]); M_k_lim_ = mean(M_k_lim_) + 1.25*0.5*diff(M_k_lim_)*[-1,+1];
subplot(3,1,1);
plot(x_p_r_,max(-12,log10(abs(M_x_q_x_orig_-M_x_q_x_sht1_))),'go',x_p_r_,max(-12,log10(abs(M_x_q_x_orig_-M_x_q_x_fht2_))),'ro');
xlim([0,x_p_r_max]); ylim([-12,+1]);
xlabel('x_p_r_','Interpreter','none'); ylabel('log10(errorabs)');
subplot(3,1,2);
plot(x_p_r_,real(M_x_q_x_orig_),'kx',x_p_r_,real(M_x_q_x_sht1_),'go',x_p_r_,real(M_x_q_x_fht2_),'ro');
xlim([0,x_p_r_max]); ylim(M_x_lim_);
xlabel('x_p_r_','Interpreter','none'); ylabel('M_x_q_x_','Interpreter','none');
subplot(3,1,3); hold on;
if ~isempty(M_k_q_k_form_); plot(k_p_r_,real(M_k_q_k_form_),'kx'); end;
plot(k_p_r_,real(M_k_q_k_sht1_),'go',k_p_r_,real(M_k_q_k_fht2_),'ro');
xlim([0,k_p_r_max]); ylim(M_k_lim_);
xlabel('k_p_r_','Interpreter','none'); ylabel('M_k_q_k_','Interpreter','none');
%%%%%%%%;
fname_fig_pre = sprintf('%s/test_bb_6_FIGA',dir_fig);
fname_fig_jpg = sprintf('%s.jpg',fname_fig_pre);
if flag_replot | ~exist(fname_fig_jpg,'file');
disp(sprintf(' %% Writing %s',fname_fig_pre));
sgtitle(fname_fig_pre,'Interpreter','none');
print('-djpeg',fname_fig_jpg);
end;%if ~exist(fname_fig_jpg,'file');
%close(gcf);
%%%%%%%%;
end;%if flag_disp>0;

%disp('returning');return;

flag_check=1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
%%%%%%%%;
% evolve radial waveform. ;
%%%%%%%%;
n_z = 1+2.0*1024; z_ = transpose(linspace(0,z_max,n_z)); dz = mean(diff(z_));
P_k_p_r_ = exp(-i*pi*lambda*dz*(k_p_r_/lightpipe.size).^2); %<-- radial fourier propagator ;
M_x_q_xz__ = zeros(n_x_p_r,n_z);
M_x_q_xz__(:,1+0) = M_x_q_x_orig_;
M_k_q_kz__ = zeros(n_k_p_r,n_z);
M_k_q_kz__(:,1+0) = M_k_q_k_fht2_;
fA_form_orig_z_ = [];
parameter = struct('type','parameter');
for nz=1:n_z-1;
if (flag_verbose>0); if mod(nz,128)==0; disp(sprintf(' %% nz %.4d/%.4d',nz,n_z)); end; end;
M_k_q_kz__(:,1+nz+0) = M_k_q_kz__(:,1+nz-1).*P_k_p_r_;
tmp_t = tic();
flag_sign = +1; q_val = 0;
[ ...
 parameter ...
,M_x_q_xz__(:,1+nz+0) ...
,fA_form_orig_z_ ...
] = ...
fht_2( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
,M_k_q_kz__(:,1+nz+0) ...
,q_val ...
,flag_sign ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,[] ...
,fA_form_orig_z_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% fht_2: time %0.6fs',tmp_t)); end;
end;%for nz=1:n_z-1;
if (flag_verbose>0); parameter_timing_printf(parameter); end;
%%%%%%%%;

if flag_disp>0;
%%%%%%%%;
figure(1+nf);nf=nf+1;clf;figbig;
l10lim_ = [-4,+1]; ilim_ = [0,prctile(abs(M_x_q_xz__).^1,[99],'all')];
x_p_r_2x_ = [-flipud(x_p_r_) ; x_p_r_];
n_y = 2*2*n_x_p_r; y_p_r_2y_ = transpose(linspace(min(x_p_r_2x_),max(x_p_r_2x_),n_y));
subplot_{1} = subplot(3,1,1);
tmp_xz__ = M_x_q_xz__;
tmp_2xz__ = [+flipud(tmp_xz__) ; +tmp_xz__];
tmp_2yz__ = abs(interp1(x_p_r_2x_,tmp_2xz__,y_p_r_2y_)).^1;
imagesc(tmp_2yz__,ilim_);
set(gca,'ydir','normal'); axisnotick; title('abs(M_x_q_xz__).^1','Interpreter','none');
subplot_{2} = subplot(3,1,2);
tmp_xz__ = M_x_q_xz__;
tmp_2xz__ = [+flipud(tmp_xz__) ; +tmp_xz__];
tmp_2yz__ = log10(abs(interp1(x_p_r_2x_,tmp_2xz__,y_p_r_2y_)));
imagesc(tmp_2yz__,l10lim_);
set(gca,'ydir','normal'); axisnotick; title('log10(abs(M_x_q_xz__))','Interpreter','none');
subplot_{3} = subplot(3,1,3);
tmp_xz__ = M_x_q_xz__;
tmp_2xz__ = [+flipud(tmp_xz__) ; +tmp_xz__];
tmp_2yz__ = angle(interp1(x_p_r_2x_,tmp_2xz__,y_p_r_2y_));
imagesc(tmp_2yz__,[-pi,+pi]);
set(gca,'ydir','normal'); axisnotick; title('angle(M_x_q_xz__)','Interpreter','none');
colormap(subplot_{3},colormap_phase2);
colormap(subplot_{2},colormap_80s());
colormap(subplot_{1},colormap_81s());
%%%%%%%%;
fname_fig_pre = sprintf('%s/test_bb_6_FIGB',dir_fig);
fname_fig_jpg = sprintf('%s.jpg',fname_fig_pre);
if flag_replot | ~exist(fname_fig_jpg,'file');
disp(sprintf(' %% Writing %s',fname_fig_pre));
sgtitle(fname_fig_pre,'Interpreter','none');
print('-djpeg',fname_fig_jpg);
end;%if ~exist(fname_fig_jpg,'file');
close(gcf);
%%%%%%%%;
end;%if flag_disp>0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%if flag_check;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;


