
flag_verbose=1;
flag_disp=1;nf=0;
%%%%%%%%;
% Redefine grids. ;
%%%%%%%%;
half_diameter_x_c = 1.0d0;
diameter_x_c = 2.0d0*half_diameter_x_c;
%%%%%%%%;
x_res = 2;
x_int = 48*x_res;
x_eq_d_double = 0.5*(x_res/2);
%%%%%%%%;
k_res = 2*8*2; %<-- be careful with the aliasing associated with n_x_M_u. ;
k_int = 48*k_res;
k_eq_d_double = 0.5*(k_res/2);
%%%%%%%%;
x_p_r_max = half_diameter_x_c;
k_p_r_max = k_int/(2*pi);
x_eq_d = x_eq_d_double/(2*pi)/32 * 1.05; %<-- to check dimensions. ;
k_eq_d = k_eq_d_double/(2*pi)/ 4 * 1.00; %<-- to check dimensions. ;
%%%%%%%%;
[ ...
 n_x_p_r ...
,x_p_r_ ...
,weight_3d_x_p_r_ ...
,weight_2d_x_p_r_ ...
] = ...
get_weight_3d_1( ...
 max(0,flag_verbose-1) ...
,x_p_r_max ...
,x_eq_d ...
);
fnorm_disp(flag_verbose,'sum(weight_3d_x_p_r_)*4*pi',sum(weight_3d_x_p_r_)*4*pi,'volume',4/3*pi*x_p_r_max^3,' %<-- should be small.');
fnorm_disp(flag_verbose,'sum(weight_2d_x_p_r_)',sum(weight_2d_x_p_r_),'area',pi*x_p_r_max^2,' %<-- should be small.');
%%%%%%%%;
[ ...
 n_k_p_r ...
,k_p_r_ ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
] = ...
get_weight_3d_1( ...
 max(0,flag_verbose-1) ...
,k_p_r_max ...
,k_eq_d ...
);
fnorm_disp(flag_verbose,'sum(weight_3d_k_p_r_)*4*pi',sum(weight_3d_k_p_r_)*4*pi,'volume',4/3*pi*k_p_r_max^3,' %<-- should be small.');
fnorm_disp(flag_verbose,'sum(weight_2d_k_p_r_)',sum(weight_2d_k_p_r_),'area',pi*k_p_r_max^2,' %<-- should be small.');
%%%%%%%%;

%%%%%%%%;
% set units. ;
%%%%%%%%;
unit = struct('type','unit');
unit.m = 1.0;
unit.cm=1e-2*unit.m;
unit.mm=1e-3*unit.m;
unit.um=1e-6*unit.m;
unit.nm=1e-9*unit.m;
unit.rad=1.0;
unit.mrad=1e-3*unit.rad;
unit.urad=1e-6*unit.rad;
unit.deg=(2*pi*unit.rad)/360;
unit.W = 1.0;
unit.mW = 1e-3*unit.W;
%%%%%%%%;
lightpipe = struct('type','lightpipe');
lightpipe.wavelength = 405 * unit.nm ; % wavelength ;
lightpipe.lam = lightpipe.wavelength ; % lambda = wavelength. ;
lightpipe.size       = 20  * unit.mm ; % simulation window size ;
lightpipe.N          = 5096 ; % grid resolution ;
lightpipe.Kmax       = k_p_r_max/max(1e-12,lightpipe.size) ; % bandlimit (max spatial-frequency) for x-y-plane in 1/unit.m. i.e., exp(\pm i*2*pi*k_p_r_max*x_p_r_) are the highest-frequency components;
lightpipe.z          = 1  * unit.m ; % long distance for Fraunhofer approx ;
lightpipe.a          = 1.5  * unit.mm ; % slit width ;
%%%%%%%%;
% circular aperture. ;
% Note (6.561.5 in TISPISMIGR): ;
% \int_{x=0}^{x=1} x^{q+1} besselj(q,a*x) dx = besselj(q+1,a)/a ;
% \int_{x=0}^{x=1}dx (\pm i).^(q0) .* x^{q0+1} .* besselj(q0,2*pi*k*x) = besselj(q0+1,(2*pi*k))/(2*pi*k) ;
% \int_{x=0}^{x=x_cut}dx x^{1} .* besselj(0,2*pi*k*x) = ...
% \int_{y=0}^{y=1}dy x_cut*x_cut*y^{1} .* besselj(0,2*pi*k*x_cut*y) = x_cut^2 * besselj(1,(2*pi*k*x_cut))/(2*pi*k*x_cut) ;
%%%%%%%%;

x_cut = ( (lightpipe.a/2) / (lightpipe.size/2) ) * x_p_r_max ;
M_x_q_x_form_ = 1.0*(x_p_r_ <= x_cut) ;
M_k_q_k_form_ = 2*pi*x_cut * besselj(1,(2*pi*k_p_r_*x_cut)) ./ max(1e-12,2*pi*k_p_r_) ;
x_step = x_cut/32;
M_x_q_x_orig_ = 1 - 0.5*(1 + erf((x_p_r_ - x_cut)/x_step));

%{
%%%%%%%%;
% diagnostic from fht_2. ;
%%%%%%%%;
flag_sign = -1; q_val = 0;
[ ...
 ~ ...
,M_k_q_k_fht1_ ...
] = ...
fht_2( ...
 struct('flag_verbose',1,'flag_disp',1) ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,M_x_q_x_orig_ ...
,q_val ...
,flag_sign ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
);
return;
%}

%{
%%%%%%%%;
% diagnostic from fht_1. ;
%%%%%%%%;
flag_sign = -1; q_val = 0;
[ ...
 ~ ...
,M_k_q_k_fht1_ ...
] = ...
fht_1( ...
 struct('flag_verbose',1,'flag_disp',1) ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,M_x_q_x_orig_ ...
,q_val ...
,flag_sign ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
);
return;
 %}

tmp_t = tic();
flag_sign = -1; q_val = 0;
[ ...
 ~ ...
,M_k_q_k_fht2_ ...
] = ...
fht_2( ...
 [] ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,M_x_q_x_orig_ ...
,q_val ...
,flag_sign ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% fht_2: time %0.6fs',tmp_t)); end;
tmp_t = tic();
[ ...
 ~ ...
,M_k_q_k_sht1_ ...
] = ...
sht_1( ...
 [] ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
,M_x_q_x_orig_ ...
,q_val ...
,flag_sign ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% sht_1: time %0.6fs',tmp_t)); end;
tmp_t = tic();
flag_sign = +1; q_val = 0;
[ ...
 ~ ...
,M_x_q_x_fht2_ ...
] = ...
fht_2( ...
 [] ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
,M_k_q_k_sht1_ ...
,q_val ...
,flag_sign ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% fht_2: time %0.6fs',tmp_t)); end;
tmp_t = tic();
flag_sign = +1; q_val = 0;
[ ...
 ~ ...
,M_x_q_x_sht1_ ...
] = ...
sht_1( ...
 [] ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_2d_k_p_r_ ...
,M_k_q_k_sht1_ ...
,q_val ...
,flag_sign ...
,n_x_p_r ...
,x_p_r_ ...
,x_p_r_max ...
,weight_2d_x_p_r_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose); disp(sprintf(' %% sht_1: time %0.6fs',tmp_t)); end;
fnorm_disp(flag_verbose,'M_k_q_k_sht1_',M_k_q_k_sht1_,'M_k_q_k_fht2_',M_k_q_k_fht2_,'%<-- should be small.');
fnorm_disp(flag_verbose,'M_x_q_x_orig_',M_x_q_x_orig_,'M_x_q_x_sht1_',M_x_q_x_sht1_,'%<-- should be small.');
fnorm_disp(flag_verbose,'M_x_q_x_orig_',M_x_q_x_orig_,'M_x_q_x_fht2_',M_x_q_x_fht2_,'%<-- should be small.');
%%%%;
if flag_disp>0;
M_x_lim_ = prctile(real(M_x_q_x_form_),[ 1,99]); M_x_lim_ = mean(M_x_lim_) + 1.25*0.5*diff(M_x_lim_)*[-1,+1];
M_k_lim_ = prctile(real(M_k_q_k_form_),[ 1,99]); M_k_lim_ = mean(M_k_lim_) + 1.25*0.5*diff(M_k_lim_)*[-1,+1];
subplot(1,2,1);
plot(x_p_r_,real(M_x_q_x_orig_),'kx',x_p_r_,real(M_x_q_x_sht1_),'go',x_p_r_,real(M_x_q_x_fht2_),'ro');
xlim([0,x_p_r_max]); ylim(M_x_lim_);
subplot(1,2,2);
plot(k_p_r_,real(M_k_q_k_form_),'kx',k_p_r_,real(M_k_q_k_sht1_),'go',k_p_r_,real(M_k_q_k_fht2_),'ro');
xlim([0,k_p_r_max]); ylim(M_k_lim_);
end;%if flag_disp>0;

