function test_transforms_3_dr(n_r);
% test transforms: ;
%%%%%%%%;
% When not explicitly mentioned, we assume that all array indices are zero-based. ;
% Assumes that images are defined on a grid of: ;
% dx = diameter_x_c_1/n_x; dy = diameter_y_c/n_y;
% x_max = dx*floor(n_x/2); y_max = dy*floor(n_y/2);
% grid_x_c_1_ = transpose( -x_max + dx*[0:n_x-1] );
% grid_y_c_ = transpose( -y_max + dy*[0:n_y-1] );
% In addition, we assume that the image is defined in terms of: ;
% S_x_c_(nx + ny*n_x) = pixel nx,ny. ;
%%%%%%%%;
if nargin<1; n_r = 32; end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% Generating initial S_x_c_ ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
n_x = 2*n_r; n_y = 2*n_r+1;
diameter_x_c_1 = 2.0; diameter_y_c = 2.0;
half_diameter_x_c_1 = diameter_x_c_1/2.0d0; half_diameter_y_c = diameter_y_c/2.0d0;
dx = diameter_x_c_1/n_x; dy = diameter_y_c/n_y;
x_max = dx*floor(n_x/2); y_max = dy*floor(n_y/2);
grid_x_c_1_ = transpose( -x_max + dx*[0:n_x-1] );
grid_y_c_ = transpose( -y_max + dy*[0:n_y-1] );
%%%%%%%%;
grid_x_p_r_ = zeros(n_x*n_y,1);
grid_x_p_w_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
grid_x_p_r_(1+na) = sqrt(grid_x_c_(1+nx).^2 + grid_y_c_(1+ny).^2);
grid_x_p_w_(1+na) = atan2(grid_y_c_(1+ny),grid_x_c_(1+nx));
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
S_x_c_ = zeros(n_x*n_y,1);
S_x_c_ = S_x_c_ - 0.50*exp(-grid_x_p_r_.^2./(2*(1/16 * (2+cos(5*(grid_x_p_w_-pi/1.0)))).^2));
S_x_c_ = S_x_c_ + 0.75*exp(-grid_x_p_r_.^2./(2*(1/16 * (2+cos(6*(grid_x_p_w_-pi/2.5)))).^2));
S_x_c_ = S_x_c_ + 0.75*exp(-grid_x_p_r_.^2./(2*(1/16 * (2+cos(7*(grid_x_p_w_-pi/5.0)))).^2));
S_x_c_ = reshape(S_x_c_,n_x,n_y);
S_x_c_(find(grid_x_c_==0),find(grid_y_c_==0))=-0.5;
%%%%%%%%;

flag_disp=0;
if flag_disp;
imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real((S_x_c_)),[],colormap(colormap_beach()));
xlim(half_diameter_x_c*[-1,1]);ylim(half_diameter_y_c*[-1,1]);
title('real(S_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image;
figbig;
end;%if flag_disp;

%%%%%%%%;
% say that m,n range from 0:6, with N=7 , dx = 2/7=2/N , x_max = -x_min = 6/7=dx*floor(N/2). ;
%   fft: fhat_m = \sum_n fori_n * exp(-i 2*pi*m*n/N) ;
% nufft: fhat_m = \sum_n fori_n * exp(-i k_m x_n) ;
% x_n = x_min + n*dx = -dx*floor(N/2) + n*dx = dx*(n-floor(N/2)) = 2/N*(n - (N-1)/2). ;
% k_m * x_n = (2*pi/N)*m*n ;
% so k_m = pi * (m - (N-1)/2) * (n - (N-1)/2) / (n - (N-1)/2) = pi * (m - (N-1)/2). ;
% Thus, the type-3 nufft can be run with the x_n, k_m above. ;
% However, the type-1 nufft assumes that k_m = -N/2:(N-1)/2, which should be interpreted as -floor(N/2):floor((N-1)/2). ;
% This means that the x_n for the type-1 nufft should be rescaled to (2*pi/N)*(n - (N-1)/2). ;
% Note also that the type-2 nufft assumes that x_n = -floor(N/2):floor((N-1)/2). ;
% This means that the k_m for the type-2 nufft should be rescaled to (2*pi/N)*(m - (N-1)/2). ;
%%%%%%%%;
S_k_c_ = decenter2( fft2(recenter2(S_x_c_/sqrt(n_x*n_y))));
T_x_c_ = decenter2(ifft2(recenter2(S_k_c_*sqrt(n_x*n_y))));
disp(sprintf(' norm(S_x_c_-T_x_c_) %0.16f',norm(S_x_c_-T_x_c_,'fro')));
%%%%%%%%;
% type-3. ;
%%%%%%%%;
tmp_grid_x_c_1_ = zeros(n_x*n_y,1);
tmp_grid_x_c_2_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
tmp_grid_x_c_1_(1+na) = grid_x_c_(1+nx);
tmp_grid_x_c_2_(1+na) = grid_y_c_(1+ny);
%tmp_grid_x_c_1_(1+na) = nx-floor(n_x/2);
%tmp_grid_x_c_2_(1+na) = ny-floor(n_y/2);
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
tmp_grid_k_c_1_ = zeros(n_x*n_y,1);
tmp_grid_k_c_2_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
tmp_grid_k_c_1_(1+na) = pi*(nx-floor(n_x/2));
tmp_grid_k_c_2_(1+na) = pi*(ny-floor(n_y/2));
%tmp_grid_k_c_1_(1+na) = 2*pi*(nx-floor(n_x/2))/n_x;
%tmp_grid_k_c_2_(1+na) = 2*pi*(ny-floor(n_y/2))/n_y;
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
iflag = -1; eps = 1e-12;
T_k_c_ = nufft2d3(n_x*n_y,tmp_grid_x_c_1_,tmp_grid_x_c_2_,S_x_c_,iflag,eps,n_x*n_y,tmp_grid_k_c_1_,tmp_grid_k_c_2_);
T_k_c_ = reshape(T_k_c_,n_x,n_y);
T_k_c_ = T_k_c_/sqrt(n_x*n_y); %<-- Note division. ;
disp(sprintf(' %% nufft2d3: norm(S_k_c_-T_k_c_) %0.16f',norm(S_k_c_-T_k_c_,'fro')));
%%%%%%%%;
% type-2. ;
%%%%%%%%;
tmp_grid_x_c_1_ = zeros(n_x*n_y,1);
tmp_grid_x_c_2_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
tmp_grid_x_c_1_(1+na) = (nx-floor(n_x/2));
tmp_grid_x_c_2_(1+na) = (ny-floor(n_y/2));
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
tmp_grid_k_c_1_ = zeros(n_x*n_y,1);
tmp_grid_k_c_2_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
tmp_grid_k_c_1_(1+na) = (2*pi/n_x)*(nx-floor(n_x/2));
tmp_grid_k_c_2_(1+na) = (2*pi/n_y)*(ny-floor(n_y/2));
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
iflag = -1; eps = 1e-12;
T_k_c_ = nufft2d2(n_x*n_y,tmp_grid_k_c_1_,tmp_grid_k_c_2_,iflag,eps,n_x,n_y,S_x_c_);
T_k_c_ = reshape(T_k_c_,n_x,n_y);
T_k_c_ = T_k_c_/sqrt(n_x*n_y); %<-- Note division. ;
disp(sprintf(' %% nufft2d2: norm(S_k_c_-T_k_c_) %0.16f',norm(S_k_c_-T_k_c_,'fro')));
%%%%%%%%;
% type-2. ;
%%%%%%%%;
tmp_grid_x_c_1_ = zeros(n_x*n_y,1);
tmp_grid_x_c_2_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
tmp_grid_x_c_1_(1+na) = (2*pi/n_x)*(nx-floor(n_x/2));
tmp_grid_x_c_2_(1+na) = (2*pi/n_y)*(ny-floor(n_y/2));
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
tmp_grid_k_c_1_ = zeros(n_x*n_y,1);
tmp_grid_k_c_2_ = zeros(n_x*n_y,1);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
tmp_grid_k_c_1_(1+na) = (nx-floor(n_x/2));
tmp_grid_k_c_2_(1+na) = (ny-floor(n_y/2));
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
iflag = -1; eps = 1e-12;
T_k_c_ = nufft2d1(n_x*n_y,tmp_grid_x_c_1_,tmp_grid_x_c_2_,S_x_c_,iflag,eps,n_x,n_y);
T_k_c_ = reshape(T_k_c_,n_x,n_y);
T_k_c_ = T_k_c_*sqrt(n_x*n_y); %<-- Note multiplication. ;
disp(sprintf(' %% nufft2d1: norm(S_k_c_-T_k_c_) %0.16f',norm(S_k_c_-T_k_c_,'fro')));

%%%%%%%%;
% Now produce S_k_p_ ;
%%%%%%%%;
diameter_k_c = 2.0*n_r/diameter_x_c;
grid_k_c_1_ = 0.5*([0:n_x-1]-floor(n_x/2));
grid_k_c_2_ = 0.5*([0:n_y-1]-floor(n_y/2));
half_diameter_k_c = diameter_k_c/2.0;
dtmp = half_diameter_k_c/n_r;
grid_k_p_ = linspace(dtmp,half_diameter_k_c,n_r); dr = mean(diff(grid_k_p_));
n_polar_a_ = zeros(n_r,1);
for nr=0:n_r-1; n_polar_a_(1+nr) = round(pi*(nr+1)); end;%for nr=0:n_r-1;
n_w_ = 2*n_polar_a_; n_A = sum(n_w_); n_w_max = max(n_w_);
grid_k_p_1_ = zeros(1,n_A); grid_k_p_2_ = zeros(1,n_A);
weight_ = zeros(n_A,1);
na=0;
for nr=0:n_r-1;
tmp_k = grid_k_p_(1+nr);
tmp_w_ = linspace(0,2*pi,n_w_(1+nr)+1);
for nw=0:n_w_(1+nr)-1;
grid_k_p_1_(1+na) = pi*tmp_k/half_diameter_k_c*cos(tmp_w_(1+nw));
grid_k_p_2_(1+na) = pi*tmp_k/half_diameter_k_c*sin(tmp_w_(1+nw));
weight_(1+na) = 2*pi*grid_k_p_(1+nr)*dr / n_w_(1+nr);
na=na+1;
end;%for nw=0:n_w_(1+nr)-1;
end;%for nr=0:n_r-1;
S_k_p_ = nufft2d2(n_A,grid_k_p_1_,grid_k_p_2_,-1,1e-12,n_x,n_y,(S_x_c_))/sqrt(n_x*n_y);
S_k_q_ = interp_p_to_q(n_r,n_w_,n_A,S_k_p_);
%%%%%%%%;
% Try and reproduce S_x_c_. ;
%%%%%%%%;
T_x_c_ = nufft2d1(n_A,grid_k_p_1_,grid_k_p_2_,S_k_p_.*weight_,+1,1e-12,n_x,n_y)*sqrt(n_x*n_y);

S_x_c_lim_ = 0 + 1.5*[-1,+1]*std(abs(S_x_c_(:)));
S_k_c_lim_ = 0 + 1.5*[-1,+1]*std(abs(S_k_c_(:)));
S_k_q_lim_ = 0 + 1.5*[-1,+1]*std(abs(S_k_q_(:)));

flag_disp=0;
if flag_disp;
%%%%%%%%;
% plot S_x_c_, S_k_c_, S_k_p_ and S_k_q_. ;
%%%%%%%%;
figure(1); pcols = 4;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,1+0*pcols); 
imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real((S_x_c_)),S_x_c_lim_,colormap(colormap_beach()));
xlim(diameter_x_c/2*[-1,1]);ylim(diameter_y_c/2*[-1,1]);
title('real(S_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,pcols,1+1*pcols); 
imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,imag((S_x_c_)),S_x_c_lim_,colormap(colormap_beach()));
xlim(diameter_x_c/2*[-1,1]);ylim(diameter_y_c/2*[-1,1]);
title('imag(S_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,2+0*pcols); 
imagesc_c(n_x,grid_k_c_1_,n_y,grid_k_c_2_,real((S_k_c_)),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(S_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,pcols,2+1*pcols); 
imagesc_c(n_x,grid_k_c_1_,n_y,grid_k_c_2_,imag((S_k_c_)),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('imag(S_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,3+0*pcols);
imagesc_p(n_r,grid_k_p_,n_w_,n_A,real(S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
subplot(2,pcols,3+1*pcols);
imagesc_p(n_r,grid_k_p_,n_w_,n_A,imag(S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('imag(S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,4+0*pcols);
imagesc_q(n_r,grid_k_p_,n_w_,n_A,real(S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(n_w_max/2*[-1,1]);
title('real(S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
subplot(2,pcols,4+1*pcols);
imagesc_q(n_r,grid_k_p_,n_w_,n_A,imag(S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(n_w_max/2*[-1,1]);
title('imag(S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
set(gcf,'Position',1+[0,0,1024*2,1024]);
dir_trunk = sprintf('/data/rangan/dir_cryoem/dir_rangan_playhouse');
tmp_fname = sprintf('%s/dir_freq_march/dir_jpg/test_transforms_3_dr_A',dir_trunk);
disp(sprintf(' %% writing %s',sprintf('%s.jpg',tmp_fname)));
print('-djpeg',sprintf('%s.jpg',tmp_fname));
disp('returning'); return;
end;%if flag_disp;

%%%%%%%%;
% define quadrature mesh. ;
%%%%%%%%;
quad_n_r = ceil(1.5*n_r);
[r_x_,r_w_] = jacpts(quad_n_r,0,1); r_w_ = transpose(r_w_);
r_x_ = 0.5*(r_x_ + 1)*half_diameter_k_c;
r_w_ = half_diameter_k_c^2 * r_w_ / sum(r_w_);
quad_grid_k_p_ = r_x_;
quad_weight_k_p_ = r_w_;
quad_n_polar_a_ = zeros(quad_n_r,1);
for nr=0:quad_n_r-1; quad_n_polar_a_(1+nr) = ceil(pi*(quad_grid_k_p_(1+nr)+1)); end;%for nr=0:quad_n_r-1;
quad_n_w_ = 2*quad_n_polar_a_; quad_n_A = sum(quad_n_w_); quad_n_w_max = max(quad_n_w_);
quad_grid_k_p_1_ = zeros(1,quad_n_A); quad_grid_k_p_2_ = zeros(1,quad_n_A);
quad_weight_ = zeros(quad_n_A,1);
na=0;
for nr=0:quad_n_r-1;
tmp_k = quad_grid_k_p_(1+nr);
tmp_w_ = linspace(0,2*pi,quad_n_w_(1+nr)+1);
for nw=0:quad_n_w_(1+nr)-1;
quad_grid_k_p_1_(1+na) = pi*tmp_k/half_diameter_k_c*cos(tmp_w_(1+nw));
quad_grid_k_p_2_(1+na) = pi*tmp_k/half_diameter_k_c*sin(tmp_w_(1+nw));
quad_weight_(1+na) = quad_weight_k_p_(1+nr) * pi/quad_n_w_(1+nr);
na=na+1;
end;%for nw=0:quad_n_w_(1+nr)-1;
end;%for nr=0:quad_n_r-1;
quad_S_k_p_ = nufft2d2(quad_n_A,quad_grid_k_p_1_,quad_grid_k_p_2_,-1,1e-12,n_x,n_y,(S_x_c_))/sqrt(n_x*n_y);
quad_S_k_q_ = interp_p_to_q(quad_n_r,quad_n_w_,quad_n_A,quad_S_k_p_);

flag_disp=0;
if flag_disp;
%%%%%%%%;
% plot S_k_p_ and S_k_q_, versus quad_S_k_p_ and quad_S_k_q_. ;
%%%%%%%%;
figure(1); pcols = 4;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,1+0*pcols);
imagesc_p(n_r,grid_k_p_,n_w_,n_A,real(S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
subplot(2,pcols,1+1*pcols);
imagesc_p(n_r,grid_k_p_,n_w_,n_A,imag(S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('imag(S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,2+0*pcols);
imagesc_q(n_r,grid_k_p_,n_w_,n_A,real(S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(n_w_max/2*[-1,1]);
title('real(S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
subplot(2,pcols,2+1*pcols);
imagesc_q(n_r,grid_k_p_,n_w_,n_A,imag(S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(n_w_max/2*[-1,1]);
title('imag(S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
subplot(2,pcols,3+0*pcols);
imagesc_p(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,real(quad_S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(quad_S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
subplot(2,pcols,3+1*pcols);
imagesc_p(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,imag(quad_S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('imag(quad_S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,4+0*pcols);
imagesc_q(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,real(quad_S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(quad_n_w_max/2*[-1,1]);
title('real(quad_S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
subplot(2,pcols,4+1*pcols);
imagesc_q(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,imag(quad_S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(quad_n_w_max/2*[-1,1]);
title('imag(quad_S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
set(gcf,'Position',1+[0,0,1024*2,1024]);
dir_trunk = sprintf('/data/rangan/dir_cryoem/dir_rangan_playhouse');
tmp_fname = sprintf('%s/dir_freq_march/dir_jpg/test_transforms_3_dr_B',dir_trunk);
disp(sprintf(' %% writing %s',sprintf('%s.jpg',tmp_fname)));
print('-djpeg',sprintf('%s.jpg',tmp_fname));
disp('returning'); return;
end;%if flag_disp;

%%%%%%%%;
% test quadrature with polynomial. ;
% P_k_p_ = tmp_k^tmp_p .* ( tmp_a + 0.5*cos(1*tmp_w) + 1.5*cos(2*tmp_w) + 2.5*cos(-3*tmp_w) ) ;
% integral should be 2*pi*tmp_a*half_diameter_k_c^(tmp_p+2)/(tmp_p+2). ;
%%%%%%%%;
tmp_p = 3.5; tmp_a = 1.2;
tmp_I = 2*pi*tmp_a*half_diameter_k_c^(tmp_p+2)/(tmp_p+2);
quad_P_k_p_ = zeros(quad_n_A,1);
na=0;
for nr=0:quad_n_r-1;
tmp_k = quad_grid_k_p_(1+nr);
tmp_w_ = linspace(0,2*pi,quad_n_w_(1+nr)+1);
for nw=0:quad_n_w_(1+nr)-1;
tmp_w = tmp_w_(1+nw);
quad_P_k_p_(1+na) = tmp_k^tmp_p .* ( tmp_a + 0.5*cos(1*tmp_w) + 1.5*cos(2*tmp_w) + 2.5*cos(-3*tmp_w) ) ;
na=na+1;
end;%for nw=0:quad_n_w_(1+nr)-1;
end;%for nr=0:quad_n_r-1;
quad_P_k_p_lim_ = mean(quad_P_k_p_(:)) + 1.5*std(quad_P_k_p_(:))*[-1,+1];
%imagesc_p(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,real(quad_P_k_p_),quad_P_k_p_lim_,colormap(colormap_beach()));
disp(sprintf(' %% testing quadrature: error %0.16f',(sum(quad_P_k_p_.*quad_weight_) - tmp_I)./tmp_I));
%%%%%%%%;
% test equispaced grid_k_p_ with polynomial. ;
%%%%%%%%;
P_k_p_ = zeros(n_A,1);
na=0;
for nr=0:n_r-1;
tmp_k = grid_k_p_(1+nr);
tmp_w_ = linspace(0,2*pi,n_w_(1+nr)+1);
for nw=0:n_w_(1+nr)-1;
tmp_w = tmp_w_(1+nw);
P_k_p_(1+na) = tmp_k^tmp_p .* ( tmp_a + 0.5*cos(1*tmp_w) + 1.5*cos(2*tmp_w) + 2.5*cos(-3*tmp_w) ) ;
na=na+1;
end;%for nw=0:n_w_(1+nr)-1;
end;%for nr=0:n_r-1;
P_k_p_lim_ = mean(P_k_p_(:)) + 1.5*std(P_k_p_(:))*[-1,+1];
%imagesc_p(n_r,grid_k_p_,n_w_,n_A,real(P_k_p_),P_k_p_lim_,colormap(colormap_beach()));
disp(sprintf(' %% testing uniform grid: error %0.16f',(sum(P_k_p_.*weight_) - tmp_I)./tmp_I));

%%%%%%%%;
% test quadrature with plane-wave. ;
% P_k_p_ = exp(i*2*pi*k*fix_delta*cos(psi-fix_omega));
% I = besselj(0,2*pi*half_diameter_k_c*fix_delta) + besselj(2,2*pi*half_diameter_k_c*fix_delta);
%%%%%%%%;
fix_delta_ = 4*[0.85;0.15]/half_diameter_k_c; 
fix_delta = sqrt(sum(fix_delta_.^2)); fix_omega = atan2(fix_delta_(2),fix_delta_(1));
fix_I = besselj(0,2*pi*half_diameter_k_c*fix_delta) + besselj(2,2*pi*half_diameter_k_c*fix_delta);
quad_P_k_p_ = zeros(quad_n_A,1);
na=0;
for nr=0:quad_n_r-1;
tmp_k = quad_grid_k_p_(1+nr);
tmp_w_ = linspace(0,2*pi,quad_n_w_(1+nr)+1);
for nw=0:quad_n_w_(1+nr)-1;
tmp_w = tmp_w_(1+nw);
quad_P_k_p_(1+na) = exp(i*2*pi*tmp_k*fix_delta*cos(tmp_w-fix_omega));
na=na+1;
end;%for nw=0:quad_n_w_(1+nr)-1;
end;%for nr=0:quad_n_r-1;
quad_P_k_p_lim_ = mean(quad_P_k_p_(:)) + 1.5*std(quad_P_k_p_(:))*[-1,+1];
%imagesc_p(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,real(quad_P_k_p_),quad_P_k_p_lim_,colormap(colormap_beach()));
disp(sprintf(' %% testing quadrature: error %0.16f',(sum(quad_P_k_p_.*quad_weight_)/(pi*half_diameter_k_c^2) - fix_I)./fix_I));
%%%%%%%%;
% test equispaced grid_k_p_ with plane-wave. ;
%%%%%%%%;
P_k_p_ = zeros(n_A,1);
na=0;
for nr=0:n_r-1;
tmp_k = grid_k_p_(1+nr);
tmp_w_ = linspace(0,2*pi,n_w_(1+nr)+1);
for nw=0:n_w_(1+nr)-1;
tmp_w = tmp_w_(1+nw);
P_k_p_(1+na) = exp(i*2*pi*tmp_k*fix_delta*cos(tmp_w-fix_omega));
na=na+1;
end;%for nw=0:n_w_(1+nr)-1;
end;%for nr=0:n_r-1;
P_k_p_lim_ = mean(P_k_p_(:)) + 1.5*std(P_k_p_(:))*[-1,+1];
%imagesc_p(n_r,grid_k_p_,n_w_,n_A,real(P_k_p_),P_k_p_lim_,colormap(colormap_beach()));
disp(sprintf(' %% testing uniform grid: error %0.16f',(sum(P_k_p_.*weight_)/(pi*half_diameter_k_c^2) - fix_I)./fix_I));

%%%%%%%%;
% convert P_k_p_ back into P_x_c_. ;
%%%%%%%%;
P_x_c_ = nufft2d1(quad_n_A,quad_grid_k_p_1_,quad_grid_k_p_2_,quad_P_k_p_.*quad_weight_,+1,1e-12,n_x,n_y) * quad_n_A / (pi*half_diameter_k_c^2);
I_x_c_ = zeros(n_x,n_y);
na=0;
for ny=0:n_y-1;
for nx=0:n_x-1;
test_delta_ = +fix_delta_ + [nx-floor(n_x/2) ; ny-floor(n_y/2)]/(2*half_diameter_k_c);
test_delta = sqrt(sum(test_delta_.^2)); test_omega = atan2(test_delta_(2),test_delta_(1));
I_x_c_(1+na) = besselj(0,2*pi*half_diameter_k_c*test_delta) + besselj(2,2*pi*half_diameter_k_c*test_delta);
na=na+1;
end;%for nx=0:n_x-1;
end;%for ny=0:n_y-1;
I_x_c_lim_ = mean(real(I_x_c_(:))) + 1.5*std(real(I_x_c_(:)))*[-1,+1];
flag_disp=0;
if flag_disp;
subplot(1,3,1); imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real((P_x_c_)),I_x_c_lim_,colormap(colormap_beach())); 
title('P_x_c_','Interpreter','none'); 
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image;
subplot(1,3,2); imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real((I_x_c_)),I_x_c_lim_,colormap(colormap_beach())); 
title('I_x_c_','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image;
subplot(1,3,3); imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,log10(abs((P_x_c_ - I_x_c_))),[-12,0],colormap(colormap_beach())); 
title('log10(abs(P_x_c_ - I_x_c_))','Interpreter','none'); 
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image; colorbar;
figbig;
end;%if flag_disp;

%%%%%%%%;
% Now test the transformations between x_c and k_p. ;
%%%%%%%%;
flag_disp=0;
if flag_disp;
T_k_p_ = nufft2d2(quad_n_A,quad_grid_k_p_1_,quad_grid_k_p_2_,-1,1e-12,n_x,n_y,(S_x_c_))/sqrt(n_x*n_y);
T_x_c_ = nufft2d1(quad_n_A,quad_grid_k_p_1_,quad_grid_k_p_2_,T_k_p_.*quad_weight_,+1,1e-12,n_x,n_y) * quad_n_A / sqrt(n_x*n_y);
subplot(1,3,1); imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,S_x_c_,S_x_c_lim_,colormap(colormap_beach())); 
title('S_x_c_','Interpreter','none'); 
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image;
subplot(1,3,2); imagesc_p(quad_n_r,quad_grid_k_p_,quad_n_w_,quad_n_A,real(T_k_p_),S_k_c_lim_,colormap(colormap_beach()));
title('T_k_p_','Interpreter','none'); 
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image;
subplot(1,3,3); imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real(T_x_c_),S_x_c_lim_,colormap(colormap_beach())); 
title('T_x_c_','Interpreter','none'); 
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis image;
figbig;
end;%if flag_disp;

%%%%%%%%;
% Now define an M_x_c_, etc. ; 
%%%%%%%%;
M_x_c_ = zeros(n_x*n_y,1);
M_x_c_ = M_x_c_ - 0.20*exp(-grid_x_p_r_.^2./(2*(1/16 * (2+cos(2*(grid_x_p_w_-pi/3.0)))).^2));
M_x_c_ = M_x_c_ + 0.15*exp(-grid_x_p_r_.^2./(2*(1/16 * (2+cos(3*(grid_x_p_w_-pi/5.5)))).^2));
M_x_c_ = M_x_c_ + 0.45*exp(-grid_x_p_r_.^2./(2*(1/16 * (2+cos(5*(grid_x_p_w_-pi/7.0)))).^2));
M_x_c_ = reshape(M_x_c_,n_x,n_y);
M_x_c_(find(grid_x_c_==0),find(grid_y_c_==0))=-0.5;
M_k_c_ = decenter2( fft2(recenter2(M_x_c_/sqrt(n_x*n_y))));
M_k_p_ = nufft2d2(n_A,grid_k_p_1_,grid_k_p_2_,-1,1e-12,n_x,n_y,(M_x_c_))/sqrt(n_x*n_y);
M_k_q_ = interp_p_to_q(n_r,n_w_,n_A,M_k_p_);
M_x_c_lim_ = 0 + 1.5*[-1,+1]*std(abs(M_x_c_(:)));
M_k_c_lim_ = 0 + 1.5*[-1,+1]*std(abs(M_k_c_(:)));
M_k_q_lim_ = 0 + 1.5*[-1,+1]*std(abs(M_k_q_(:)));
%%%%%%%%;
flag_disp=0;
if flag_disp;
%%%%%%%%;
% plot S_x_c_, etc. versus M_x_c_, etc. ;
%%%%%%%%;
figure(1); pcols = 4;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,1+0*pcols); 
imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real((S_x_c_)),S_x_c_lim_,colormap(colormap_beach()));
xlim(diameter_x_c/2*[-1,1]);ylim(diameter_y_c/2*[-1,1]);
title('real(S_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,pcols,1+1*pcols); 
imagesc_c(n_x,grid_x_c_,n_y,grid_y_c_,real((M_x_c_)),M_x_c_lim_,colormap(colormap_beach()));
xlim(diameter_x_c/2*[-1,1]);ylim(diameter_y_c/2*[-1,1]);
title('real(M_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,2+0*pcols); 
imagesc_c(n_x,grid_k_c_1_,n_y,grid_k_c_2_,real((S_k_c_)),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(S_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,pcols,2+1*pcols); 
imagesc_c(n_x,grid_k_c_1_,n_y,grid_k_c_2_,real((M_k_c_)),M_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(M_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,3+0*pcols);
imagesc_p(n_r,grid_k_p_,n_w_,n_A,real(S_k_p_),S_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(S_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
subplot(2,pcols,3+1*pcols);
imagesc_p(n_r,grid_k_p_,n_w_,n_A,real(M_k_p_),M_k_c_lim_,colormap(colormap_beach()));
xlim(half_diameter_k_c*[-1,1]);ylim(half_diameter_k_c*[-1,1]);
title('real(M_k_p_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); axis square;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
subplot(2,pcols,4+0*pcols);
imagesc_q(n_r,grid_k_p_,n_w_,n_A,real(S_k_q_),S_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(n_w_max/2*[-1,1]);
title('real(S_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
subplot(2,pcols,4+1*pcols);
imagesc_q(n_r,grid_k_p_,n_w_,n_A,real(M_k_q_),M_k_q_lim_,colormap(colormap_beach()));
xlim([0,half_diameter_k_c]);ylim(n_w_max/2*[-1,1]);
title('real(M_k_q_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
set(gcf,'Position',1+[0,0,1024*2,1024]);
dir_trunk = sprintf('/data/rangan/dir_cryoem/dir_rangan_playhouse');
tmp_fname = sprintf('%s/dir_freq_march/dir_jpg/test_transforms_3_dr_C',dir_trunk);
disp(sprintf(' %% writing %s',sprintf('%s.jpg',tmp_fname)));
print('-djpeg',sprintf('%s.jpg',tmp_fname));
disp('returning'); return;
end;%if flag_disp;
%%%%%%%%;

%%%%%%%%;
% Now test out rotations. ;
%%%%%%%%;
C_q0_= zeros(n_w_max,1);
for nw=0:n_w_max-1;
gamma_z = 2*pi*nw/n_w_max;
T_k_p_ = rotate_p2p_fx(n_r,n_w_,n_A,S_k_p_,gamma_z);
C_q0_(1+nw) = innerproduct_p(n_r,grid_k_p_,n_w_,n_A,T_k_p_,M_k_p_);
end;%for nw=0:n_w_max-1;
C_q1_ = zeros(n_w_max,1);
T_q1_ = innerproduct_q_k_stretch_0(n_r,grid_k_p_,n_w_,n_A,S_k_q_,M_k_q_);
C_q1_ = ifft(T_q1_)*n_w_max;
%%%%%%%%;
disp(sprintf(' %% fnorm(C_q0_-C_q1_)/fnorm(C_q0_) = %0.16f',fnorm(C_q0_-C_q1_)/fnorm(C_q0_)));

disp('returning');return;


