function orthopoly_test_3();
% calculate \int_{a=0}^{c=4} exp(-r^2/2) with weight of r. ;
% exact integral is 1-exp(-c^2/2). ;
a = 0; c = 2.5;
w_ = @(x) 1 + x; wv = [1 1];
disp(sprintf('setting [a,c] = [%d,%d]; Using wv = [1 1] --> w(x) = (1+x)',a,c));
%%%%%%%%%%%%%%%%;
f_ = @(x) exp(-x.^2/2);
I_exact = 1 - exp(-c^2/2);
%f_ = @(x) 1;
%I_exact = 12.5;
%%%%%%%%%%%%%%%%;
tmid = (c+a)/2; trad = (c-a)/2;
K_ = 2.^[1:4];
I_quad_= zeros(length(K_),1);
E_quad_= zeros(length(K_),1);
for nK=1:length(K_);
K = K_(nK);
[lx,lw,Lx,Lv] = orthopoly_node_weight_matrix_0(K,wv);
lt = lx*trad + tmid;
w_at_lx = w_(lx);
f_at_lt = f_(lt);
I_quad_(nK) = sum(f_at_lt.*lw)*(c.^2/4);
E_quad_(nK) = abs(I_quad_(nK) - I_exact);
end;%for nK=1:length(K_);
%%%%%%%%%%%%%%%%;
M_ = 2.^[1:10];
I_reim_= zeros(length(M_),1);
E_reim_= zeros(length(M_),1);
for nM=1:length(M_);
M = M_(nM);
xvals = linspace(-1,+1,M); tvals = linspace(a,c,M);
w_at_xv = w_(xvals);
f_at_tv = f_(tvals);
I_reim_(nM) = sum(f_at_tv.*w_at_xv)*2/M*(c.^2/4);
E_reim_(nM) = abs(I_reim_(nM) - I_exact);
end;%for nM=1:length(M_);
subplot(1,2,1);plot(log2(K_),log10(E_quad_),'ro-',log2(M_),log10(E_reim_),'k.-');
subplot(1,2,2);plot(1:K,lx,'x');xlim([1,K]);

