function save_f77data(n_A,A,str_type,vname,fp,sav_type);
% exports array A of length n_A as fortran data of type str_type ;
if (strcmp(str_type,'integer') | strcmp(str_type,'int')) ; 
if strcmp(sav_type,'decl');
if (n_A>1);
fprintf(fp,'      integer %s(0:%d)\n',vname,n_A-1);
 else;
fprintf(fp,'      integer %s\n',vname);
end;%if (n_A>1);
 elseif strcmp(sav_type,'data');
if (n_A>1);
nA=0;
fprintf(fp,'      data %s(%d)/ %d/\n',vname,nA,A(1+nA));
for nA=1:n_A-1;
fprintf(fp,'     $     , %s(%d)/ %d/\n',vname,nA,A(1+nA));
end;%for nA=1:n_A-1;
 else;
fprintf(fp,'      data %s/ %d/\n',vname,A);
end;%if (n_A>1);
end;% sav_type;
elseif (strcmp(str_type,'real') | strcmp(str_type,'double')) ; 
if strcmp(sav_type,'decl');
if (n_A>1);
fprintf(fp,'      real *8 %s(0:%d)\n',vname,n_A-1);
 else;
fprintf(fp,'      real *8 %s\n',vname);
end;%if (n_A>1);
 elseif strcmp(sav_type,'data');
if (n_A>1);
nA=0;
fprintf(fp,'      data %s(%d)/ %0.15f/\n',vname,nA,A(1+nA));
for nA=1:n_A-1;
fprintf(fp,'     $     , %s(%d)/ %0.15f/\n',vname,nA,A(1+nA));
end;%for nA=1:n_A-1;
 else;
fprintf(fp,'      data %s/ %0.15f/\n',vname,A);
end;%if (n_A>1);
end;% sav_type;
elseif (strcmp(str_type,'complex') | strcmp(str_type,'cmplx')) ; 
if strcmp(sav_type,'decl');
if (n_A>1);
fprintf(fp,'      complex *16 %s(0:%d)\n',vname,n_A-1);
 else;
fprintf(fp,'      complex *16 %s\n',vname);
end;%if (n_A>1);
 elseif strcmp(sav_type,'data');
if (n_A>1);
nA=0;
fprintf(fp,'      data %s(%d)/ ( %0.15f , %0.15f )/\n',vname,nA,real(A(1+nA)),imag(A(1+nA)));
for nA=1:n_A-1;
fprintf(fp,'     $     , %s(%d)/ ( %0.15f , %0.15f )/\n',vname,nA,real(A(1+nA)),imag(A(1+nA)));
end;%for nA=1:n_A-1;
 else;
fprintf(fp,'      data %s/ ( %0.15f , %0.15f )/\n',vname,real(A),imag(A));
end;%if (n_A>1);
end;% sav_type
 else;
disp(sprintf(' %% Warning! str_type %s not supported in export_f77dat; fname %s not written',str_type,fname));
end% if;
