% test functional svd-expansion. ;
% testing functional lsq. ;
% determining the overlap integral between two plane-waves on a disc: ;

verbose=1;
max_k_p = 64; N_pixel = 3.0;
R_target = max_k_p-0.5; z_target = N_pixel*pi*sqrt(2); D_target = z_target/(2*pi*R_target);
C = 2*pi*max_k_p;
tic;
n_d = 129;
dj_ = D_target*linspace(-2,+2,n_d);
h_ = zeros(n_d,1);
dh_ = zeros(n_d,1);
for nd=1:n_d;
dj = dj_(nd); gamma = C*dj;
if (dj==0); 
h4_(nd) = (2*pi).^2; 
h3_(nd) = (2*pi).^2; 
h2_(nd) = (2*pi).^2; 
h1_(nd) = (2*pi).^2; 
h_(nd) = (2*pi).^2; dh_(nd) = 0; 
end;
if (dj~=0); 
%h5_(nd) = dblquad( @(r,w) cos(r*dj*cos(w)).*r , 0,2*pi*max_k_p , 0,2*pi ) / (pi*max_k_p.^2) ; 
h4_(nd) = quad( @(w) ( cos((dj.*cos(w)).*C) + sin((dj.*cos(w)).*C).*C.*(dj.*cos(w)) - 1 ) ./ ((dj.*cos(w)).^2) , 0,2*pi ) / (pi*max_k_p.^2) ; 
h3_(nd) = quad( @(w) ( (C.*dj.*sin(w)).^2 .* cos(C.*dj.*cos(w)) ) ./ (dj.^2) , 0,2*pi ) / (pi*max_k_p.^2) ; 
h2_(nd) = quad( @(w) ( (C.*dj.*cos(w)) .* sin(C.*dj.*cos(w)) ) ./ (dj.^2) , 0,2*pi ) / (pi*max_k_p.^2) ; 
h1_(nd) = ( (gamma*pi/2) * ( besselj(1,gamma) - besselj(-1,gamma) - besselj(1,-gamma) + besselj(-1,-gamma) ) ./ (dj.^2) ) / (pi*max_k_p.^2) ; 
h_(nd) = gamma*2*pi*besselj(1,gamma) ./ (dj.^2) / (pi*max_k_p.^2) ; 
%dh_(nd) = quad( @(w) ( C.*C.*cos(w).^2.*dj.*cos(dj.*cos(w).*C) ) ./ ((dj.*cos(w)).^2) , 0,2*pi ) / (pi*max_k_p.^2) - 2./dj_(nd) * h_(nd); 
end;%if (dj~=0); 
end;%for nd=1:n_d;
toc;
subplot(1,1,1); plot(dj_,h_,'k-',dj_,h1_,'ro',dj_,h2_,'ro',dj_,h3_,'ro',dj_,h4_,'ro');
%subplot(2,1,1); plot(dj_,h_); xlim([min(dj_),max(dj_)]);
%subplot(2,1,2); ddj = mean(diff(dj_)); plot(dj_(1:end-1) + ddj/2,diff(h_)/ddj,'k.-',dj_,dh_,'ro-'); xlim([min(dj_),max(dj_)]);
