% test 2d-fourier transform, generating polar representation in realspace and freqspace ;

ng = 64; max_x_c = 1; max_k_c = ng/max_x_c;
% realspace carte grid ; 
grid_x_c = linspace(0,max_x_c,ng+1); grid_x_c = grid_x_c(1:end-1); d_x_c = mean(diff(grid_x_c));
% freqspace carte grid ; 
grid_k_c = (0:ng-1)/max_x_c; d_k_c = mean(diff(grid_k_c));
% realspace carte meshgrid ;
[X_x_c,Y_x_c] = meshgrid(grid_x_c,grid_x_c); X_x_c(:,ng/2+1:end) = X_x_c(:,ng/2+1:end)-max_x_c; Y_x_c(ng/2+1:end,:) = Y_x_c(ng/2+1:end,:)-max_x_c;
R_x_c = sqrt(X_x_c.^2 + Y_x_c.^2); W_x_c = atan2(Y_x_c,X_x_c);
% freqspace carte meshgrid ;
[X_k_c,Y_k_c] = meshgrid(grid_k_c,grid_k_c); X_k_c(:,ng/2+1:end) = X_k_c(:,ng/2+1:end)-max_k_c; Y_k_c(ng/2+1:end,:) = Y_k_c(ng/2+1:end,:)-max_k_c;
R_k_c = sqrt(X_k_c.^2 + Y_k_c.^2); W_k_c = atan2(Y_k_c,X_k_c);
% realspace polar meshgrid ;
grid_x_r = linspace(0,max_x_c/2,ng+1); grid_x_r = grid_x_r(1:end-1); grid_x_w = linspace(0,2*pi,ng+1); grid_x_w = grid_x_w(1:end-1); 
[R_x_p,W_x_p] = meshgrid(grid_x_r,grid_x_w);
% freqspace polar meshgrid ;
grid_k_r = linspace(0,max_k_c/2,ng+1); grid_k_r = grid_k_r(1:end-1); grid_k_w = linspace(0,2*pi,ng+1); grid_k_w = grid_k_w(1:end-1); 
[R_k_p,W_k_p] = meshgrid(grid_k_r,grid_k_w);
% set up function on realspace carte meshgrid ;
sx=0.1;mx=0.2-1*0.5;sy=0.2;my=0.2-1*0.5;tmp_a = 1/(2*pi*max_x_c*sx*max_x_c*sy)*exp(-(X_x_c - max_x_c*mx).^2/2/(max_x_c*sx).^2).*exp(-(Y_x_c - max_x_c*my).^2/2/(max_x_c*sy).^2);
sx=0.1;mx=0.6-1*0.5;sy=0.1;my=0.3-1*0.5;tmp_b = 1/(2*pi*max_x_c*sx*max_x_c*sy)*exp(-(X_x_c - max_x_c*mx).^2/2/(max_x_c*sx).^2).*exp(-(Y_x_c - max_x_c*my).^2/2/(max_x_c*sy).^2);
sx=0.1;mx=0.7-1*0.5;sy=0.2;my=0.8-1*0.5;tmp_c = 1/(2*pi*max_x_c*sx*max_x_c*sy)*exp(-(X_x_c - max_x_c*mx).^2/2/(max_x_c*sx).^2).*exp(-(Y_x_c - max_x_c*my).^2/2/(max_x_c*sy).^2);
sx=0.1;mx=0.2-1*0.5;sy=0.2;my=0.8-1*0.5;tmp_d = 1/(2*pi*max_x_c*sx*max_x_c*sy)*exp(-(X_x_c - max_x_c*mx).^2/2/(max_x_c*sx).^2).*exp(-(Y_x_c - max_x_c*my).^2/2/(max_x_c*sy).^2);
tmp_crop = 0.5*(1+erf(-16.0*(R_x_c-0.25*(1 + 0.5*cos(5*W_x_c)))));
%tmp_crop = R_x_c<0.25*(1 + 0.5*cos(5*W_x_c));
F_x_c = tmp_crop.*(tmp_a+tmp_b+tmp_c+tmp_d); Flim_x = max(0,mean(F_x_c(:)) + 1.0*std(F_x_c(:))*[-1,+1]);
L_x_c = sum(abs(F_x_c(:)).^2)*d_x_c*d_x_c;
% calculate function values on realspace polar meshgrid ;
F_x_p = interp2(recenter(X_x_c),recenter(Y_x_c),recenter(F_x_c),R_x_p.*cos(W_x_p),R_x_p.*sin(W_x_p));
figure;
subplot(2,3,1);imagesc(recenter(real(F_x_c)),Flim_x);title('real(F_x_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_x_c(1),grid_x_c(end/2+1),grid_x_c(end)]-max_x_c/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_x_c(1),grid_x_c(end/2+1),grid_x_c(end)]-max_x_c/2);
subplot(2,3,4);polarpatch(R_x_p,W_x_p,F_x_p,Flim_x);title('real(F_x_p)'); c = colorbar; set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Flim_x(1),Flim_x(2),4));set(gca,'XTick',[],'Ytick',[]);
% calculate function values on freqspace carte meshgrid ;
F_k_c = fft2(F_x_c) * d_x_c*d_x_c; Flim_k  = mean(abs(F_k_c(:))) + 1.0*std(abs(F_k_c(:)))*[-1,+1];
L_k_c = sum(abs(F_k_c(:)).^2)*d_k_c*d_k_c;
% calculate function falues on freqspace polar meshgrid ;
F_k_p = interp2(recenter(X_k_c),recenter(Y_k_c),recenter(F_k_c),R_k_p.*cos(W_k_p),R_k_p.*sin(W_k_p));
disp(sprintf(' %% L_x_c %f L_k_c %f',L_x_c,L_k_c));
subplot(2,3,2);imagesc(recenter(real(F_k_c)),Flim_k);title('real(F_k_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);
subplot(2,3,3);imagesc(recenter(imag(F_k_c)),Flim_k);title('imag(F_k_c)'); colorbar; set(gca,'Ydir','normal');
set(gca,'XTick',[1,ng/2+1,ng],'XTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);set(gca,'YTick',[1,ng/2+1,ng],'YTickLabel',[grid_k_c(1),grid_k_c(end/2+1),grid_k_c(end)]-ng/2);
subplot(2,3,5);polarpatch(R_k_p,W_k_p,real(F_k_p),Flim_k);title('real(F_k_p)'); c = colorbar; set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Flim_k(1),Flim_k(2),4));set(gca,'XTick',[],'Ytick',[]);
subplot(2,3,6);polarpatch(R_k_p,W_k_p,imag(F_k_p),Flim_k);title('imag(F_k_p)'); c = colorbar; set(c,'Ticks',0.025 + 0.95*linspace(0,1,4),'TickLabels',linspace(Flim_k(1),Flim_k(2),4));set(gca,'XTick',[],'Ytick',[]);

