% test functional svd-expansion. ;
% testing functional lsq. ;
% determining the overlap integral between two plane-waves on a disc, ;
% as well as the derivative of that overlap integral. : ;

verbose=1;
max_k_p = 64; N_pixel = 3.0;
R_target = max_k_p-0.5; z_target = N_pixel*pi*sqrt(2); D_target = z_target/(2*pi*R_target);
C = 2*pi*max_k_p;
ff_ = @(kd) 4*pi*besselj(1,2*pi*kd) ./ kd ; 
dff_ = @(kd) -4*pi*besselj(1,2*pi*kd)./kd.^2 + 4*pi^2*(besselj(0,2*pi*kd)-besselj(2,2*pi*kd))./kd ; 
tic;
n_d = 129;
dj_ = D_target*linspace(-2,+2,n_d);
h_ = zeros(n_d,1);
dh_ = zeros(n_d,1);
for nd=1:n_d;
dj = dj_(nd); gamma = C*dj; kd = dj*max_k_p;
if (dj==0); h_(nd) = (2*pi).^2; dh_(nd) = 0; end;
if (dj~=0); 
%h_(nd) = gamma*2*pi*besselj(1,gamma) ./ (dj.^2) / (pi*max_k_p.^2) ; 
h_(nd) = ff_(kd);
%dh_(nd) = ( 2*pi*C*besselj(1,gamma) + pi*C^2*dj*(besselj(0,gamma) - besselj(2,gamma)) ) ./ (dj.^2) / (pi*max_k_p.^2)  - 2./dj_(nd) * h_(nd);
dh_(nd) = dff_(kd)*max_k_p;
end;%if (dj~=0); 
end;%for nd=1:n_d;
toc;
subplot(2,1,1); plot(dj_,h_); xlim([min(dj_),max(dj_)]);
subplot(2,1,2); ddj = mean(diff(dj_)); plot(dj_(1:end-1) + ddj/2,diff(h_)/ddj,'k.-',dj_,dh_,'ro-'); xlim([min(dj_),max(dj_)]);
