% test svd-expansion. ;

verbose=1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% generate grids. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
n_point = 128; max_x_c = 1; 
[max_k_c,max_k_p,grid_x_c_,d_x_c,X_x_c_,Y_x_c_,R_x_c_,W_x_c_,grid_k_c_,d_k_c,X_k_c_,Y_k_c_,R_k_c_,W_k_c_,grid_x_r_,grid_x_w_,R_x_p_,W_x_p_,grid_k_r_,d_k_r,grid_k_w_,d_k_w,R_k_p_,W_k_p_,X_k_p_,Y_k_p_] = test_F_grid_0(n_point,max_x_c);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% Determine svd expansion ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
l_max = 16; eps_target = 1.0; N_pixel = 1.5; 
[n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_] = gen_Jsvd_2b(max_k_p,N_pixel,eps_target,l_max);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% compare T with cropped bessel-expansion. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
delta_d = svd_d_(end); delta_w = 1*pi/6; 
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
Tlim_k = [-1,+1];
phi_k_p_ = W_k_p_-delta_w;
rd_k_p_ = delta_d*2*pi*R_k_p_;
for l_max=[3:16];
[J_k_p_] = test_F_J_k_p_0(n_point,max_x_c,delta_d,delta_w,l_max);
Jlim_k = [-1,+1];
tmp_ = abs(T_k_p_-J_k_p_); Dlim_k = 2.5*std(tmp_(:))*[-1,+1];
cra = colormap_pm(64);
figure(1); clf;
subplot(2,3,1); clim = polarpatch(R_k_p_,W_k_p_,real(T_k_p_),Tlim_k,0,0,1,cra);  title(sprintf('real(T) [%0.1f,%0.1f]',Tlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Tlim_k); 
subplot(2,3,4); clim = polarpatch(R_k_p_,W_k_p_,imag(T_k_p_),Tlim_k,0,0,1,cra);  title(sprintf('imag(T) [%0.1f,%0.1f]',Tlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Tlim_k); 
subplot(2,3,2); clim = polarpatch(R_k_p_,W_k_p_,real(J_k_p_),Jlim_k,0,0,1,cra);  title(sprintf('real(T^{bes}) [%0.1f,%0.1f]',Jlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Jlim_k); 
subplot(2,3,5); clim = polarpatch(R_k_p_,W_k_p_,imag(J_k_p_),Jlim_k,0,0,1,cra);  title(sprintf('imag(T^{bes}) [%0.1f,%0.1f]',Jlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Jlim_k); 
subplot(2,3,3); clim = polarpatch(R_k_p_,W_k_p_,real(T_k_p_-J_k_p_),Dlim_k,0,0,1,cra);  title(sprintf('real(T-T^{bes}) [%f,%f]',Dlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Dlim_k); 
subplot(2,3,6); clim = polarpatch(R_k_p_,W_k_p_,imag(T_k_p_-J_k_p_),Dlim_k,0,0,1,cra);  title(sprintf('imag(T-T^{bes}) [%f,%f]',Dlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Dlim_k); 
%suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d  N^{pixel} %0.1f  eps %0.2f(%f)',n_point,max_k_p,N_pixel,eps_target,eps_target/svd_s_(1)));
suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d N^{pixel} %0.1f l_{max} %d',n_point,max_k_p,N_pixel,l_max));
set(gcf,'Position',1+[0,0,1024*1.5,1024]); 
fname_base = sprintf('J_n%d_K%d_N%.2d_l%d',n_point,max_k_p,round(10*N_pixel),l_max);
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));
end;%for l_max=[3:16];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% calculate real-space error for cropped bessel-expansion. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
delta_d = 2/n_point; delta_w = 0*pi/6; 
[T_k_c_] = test_F_T_k_c_0(n_point,max_x_c,delta_d,delta_w); T_x_c_ = ifft2((T_k_c_))./d_x_c./d_x_c;
Tlim_x = [-1,+1]; 
for l_max=[3:16];
[J_k_c_] = test_F_J_k_c_0(n_point,max_x_c,delta_d,delta_w,l_max); J_x_c_ = ifft2((J_k_c_))./d_x_c./d_x_c;
Jlim_x = [-1,+1];
figure(2); clf;
colormap('hot');
imagesc(abs(recenter2((T_x_c_-J_x_c_)))); colorbar; title(sprintf('abs(ifft(T-T^{bes}), l_{max} %d)',l_max));
set(gca,'XTick',[],'YTick',[]);
suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d N^{pixel} %0.2f l_{max} %d',n_point,max_k_p,N_pixel*delta_d/svd_d_(end),l_max));
set(gcf,'Position',1+[0,0,1024*1.5,1024]); 
fname_base = sprintf('J_Dx_n%d_K%d_N%.2d_l%d',n_point,max_k_p,round(10*N_pixel),l_max);
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));
end;%for l_max=[3:16];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% compare T with svd-expansion. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
delta_d = svd_d_(end); delta_w = 1*pi/6; 
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
Tlim_k = [-1,+1]; 
for eps_target=[10,1,0.1,0.01];
l_max = 16; N_pixel = 1.5; 
[n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_] = gen_Jsvd_2b(max_k_p,N_pixel,eps_target,l_max);
[X_k_p_] = test_F_X_k_p_0(n_point,max_x_c,delta_d,delta_w,n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_);
Xlim_k = [-1,+1];
tmp_ = abs(T_k_p_-X_k_p_).^2; tmp_ = tmp_*diag(2*pi*grid_k_r_); tmp = sum(tmp_(:)).*(2*pi*d_k_r)*d_k_w; tmp = sqrt(tmp/(pi*max_k_p.^2)); Dlim_k = 0.25*tmp*[-1,+1];
cra = colormap_pm(64);
figure(1); clf;
subplot(2,3,1); clim = polarpatch(R_k_p_,W_k_p_,real(T_k_p_),Tlim_k,0,0,1,cra);  title(sprintf('real(T) [%0.1f,%0.1f]',Tlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Tlim_k); 
subplot(2,3,4); clim = polarpatch(R_k_p_,W_k_p_,imag(T_k_p_),Tlim_k,0,0,1,cra);  title(sprintf('imag(T) [%0.1f,%0.1f]',Tlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Tlim_k); 
subplot(2,3,2); clim = polarpatch(R_k_p_,W_k_p_,real(X_k_p_),Xlim_k,0,0,1,cra);  title(sprintf('real(T^{svd}) [%0.1f,%0.1f]',Xlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Xlim_k); 
subplot(2,3,5); clim = polarpatch(R_k_p_,W_k_p_,imag(X_k_p_),Xlim_k,0,0,1,cra);  title(sprintf('imag(T^{svd}) [%0.1f,%0.1f]',Xlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Xlim_k); 
subplot(2,3,3); clim = polarpatch(R_k_p_,W_k_p_,real(T_k_p_-X_k_p_),Dlim_k,0,0,1,cra);  title(sprintf('real(T-T^{svd}) [%f,%f]',Dlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Dlim_k); 
subplot(2,3,6); clim = polarpatch(R_k_p_,W_k_p_,imag(T_k_p_-X_k_p_),Dlim_k,0,0,1,cra);  title(sprintf('imag(T-T^{svd}) [%f,%f]',Dlim_k)); axis equal;
%colorbar_handle = colorbar('v'); tmp = get(colorbar_handle,'Limits'); set(colorbar_handle,'XTick',[min(tmp),max(tmp)],'XTickLabel',Dlim_k); 
suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d  N^{pixel} %0.1f  eps %0.2f(%f)',n_point,max_k_p,N_pixel,eps_target,eps_target/svd_s_(1)));
set(gcf,'Position',1+[0,0,1024*1.5,1024]); 
fname_base = sprintf('X_n%d_K%d_N%.2d_e%.4d',n_point,max_k_p,round(10*N_pixel),round(100*eps_target));
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));
%%%%%%%%%%%%%%%% ;
end;%for eps_target=[10,1,0.1,0.01];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot stack of error-maps for various delta_d. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
figure(5); clf; hold on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
l_max = 16; eps_target = 1.0;
[n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_] = gen_Jsvd_2b(max_k_p,N_pixel,eps_target,l_max);
Dlim_k = 0.1*[0,1];
d_ij_ = 1:14:n_point;
for nd=1:length(d_ij_);
d_ij = d_ij_(nd);
%%%%%%%%%%%%%%%% ;
delta_d = svd_d_(d_ij);
delta_w = 1*pi/6;
delta_x = delta_d*cos(delta_w); delta_y = delta_d*sin(delta_w);
disp(sprintf(' %% delta_x_c (%f,%f) delta_x_p (%f,%f)',delta_x,delta_y,delta_d,delta_w));
%%%%%%%%%%%%%%%% ;
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
[X_k_p_] = test_F_X_k_p_0(n_point,max_x_c,delta_d,delta_w,n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_);
polarpatch_stack(R_k_p_,W_k_p_,abs(T_k_p_-X_k_p_),Dlim_k,1,[0,0,nd]); 
%%%%%%%%%%%%%%%% ;
end;%for nd=1:length(d_ij_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
hold off;
colorbar_handle = colorbar('h'); set(colorbar_handle,'XTick',0.5+0.499*[-1,+1],'XTickLabel',Dlim_k); 
title('abs(T-T^{svd})');
suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d  N^{pixel} %0.1f  eps %0.2f(%f)',n_point,max_k_p,N_pixel,eps_target,eps_target/svd_s_(1)));
set(gcf,'Position',1+[680 44 562 1051]);
view([29.2,7.6]);
fname_base = sprintf('X_Dx_stack_n%d_K%d_N%.2d_e%.4d',n_point,max_k_p,round(10*N_pixel),round(100*eps_target));
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% plot pages of error-maps for various delta_d. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
figure(6); clf; hold on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
l_max = 16; eps_target = 0.1;
[n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_] = gen_Jsvd_2b(max_k_p,N_pixel,eps_target,l_max);
Dlim_k = 0.01*[0,1];
d_ij_ = 1:4:125;
for nd=1:length(d_ij_);
d_ij = d_ij_(nd);
%%%%%%%%%%%%%%%% ;
delta_d = svd_d_(d_ij);
delta_w = 1*pi/6;
delta_x = delta_d*cos(delta_w); delta_y = delta_d*sin(delta_w);
disp(sprintf(' %% delta_x_c (%f,%f) delta_x_p (%f,%f)',delta_x,delta_y,delta_d,delta_w));
%%%%%%%%%%%%%%%% ;
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
[X_k_p_] = test_F_X_k_p_0(n_point,max_x_c,delta_d,delta_w,n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_);
subplot(4,8,nd);
%polarpatch_stack(R_k_p_,W_k_p_,abs(T_k_p_-X_k_p_),Dlim_k,1,[0,0,0]); 
polarpatch_stack(R_k_p_,W_k_p_,real(X_k_p_),Xlim_k,1,[0,0,0]); 
%%%%%%%%%%%%%%%% ;
end;%for nd=1:length(d_ij_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
hold off;
suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d  N^{pixel} %0.1f  eps %0.2f(%f) Dlim %f',n_point,max_k_p,N_pixel,eps_target,eps_target/svd_s_(1),max(Dlim_k)));
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('X_page_n%d_K%d_N%.2d_e%.4d',n_point,max_k_p,round(10*N_pixel),round(100*eps_target));
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% pages of error maps for brute-force + interpolation;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
figure(7); clf; hold on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
verbose=1;
Dlim_k = 0.1*[0,+1];
n_node = 8;
node_ij_ = round(linspace(1,127,n_node));
T_k_p__ = cell(length(node_ij_),1);
for nnode=1:length(node_ij_);
node_ij = node_ij_(nnode);
delta_d = svd_d_(node_ij); delta_w = 1*pi/6;
T_k_p__{nnode} = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
end;%for nnode=1:length(node_ij_);
d_ij_ = 1:4:125;
for nd=1:length(d_ij_);
d_ij = d_ij_(nd);
%%%%%%%%%%%%%%%% ;
delta_d = svd_d_(d_ij);
delta_w = 1*pi/6;
delta_x = delta_d*cos(delta_w); delta_y = delta_d*sin(delta_w);
disp(sprintf(' %% delta_x_c (%f,%f) delta_x_p (%f,%f)',delta_x,delta_y,delta_d,delta_w));
%%%%%%%%%%%%%%%% ;
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
%%%%%%%%%%%%%%%% ;
ij_par = find(abs(node_ij_-d_ij)<1e-7);
if (~isempty(ij_par)); 
if (verbose); disp(sprintf(' %% nd %d delta_d %f ij_par %d',nd,delta_d,ij_par)); end;
B_k_p_ = T_k_p__{ij_par};
end;%if (~isempty(ij_par)); 
if (isempty(ij_par));
ij_pre = max(find(node_ij_<d_ij));
ij_pos = min(find(node_ij_>d_ij));
if (verbose); disp(sprintf(' %% nd %d delta_d %f ij_pre %d ij_pos %d',nd,delta_d,ij_pre,ij_pos)); end;
d_pre = d_ij - node_ij_(ij_pre); d_pos = node_ij_(ij_pos) - d_ij;
w_pre = d_pos/(d_pos+d_pre); w_pos = d_pre/(d_pos+d_pre);
B_k_p_ = w_pre*T_k_p__{ij_pre} + w_pos*T_k_p__{ij_pos};
end;%if (isempty(ij_par));
subplot(4,8,nd);
%polarpatch_stack(R_k_p_,W_k_p_,abs(T_k_p_-B_k_p_),Dlim_k,1,[0,0,0]); 
polarpatch_stack(R_k_p_,W_k_p_,real(B_k_p_),Xlim_k,1,[0,0,0]); 
%%%%%%%%%%%%%%%% ;
end;%for nd=1:length(d_ij_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
hold off;
%colorbar_handle = colorbar('v'); set(colorbar_handle,'XTick',0.5+0.499*[-1,+1],'XTickLabel',Dlim_k); 
suptitle(sprintf('n_{point} %d  K_{max} 2*pi*%d  N^{pixel} %0.1f  n_{node} %d Dlim %f',n_point,max_k_p,N_pixel,n_node,max(Dlim_k)));
set(gcf,'Position',1+[0,0,1024*2,1024]);
fname_base = sprintf('I_page_n%d_K%d_N%.2d_n%d',n_point,max_k_p,round(10*N_pixel),n_node);
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% compare error for svd-expansion vs brute-force+linear-interpolation ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% First svd-expansion; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
verbose=1;
l_max = 16; 
N_pixel = 1.5; 
d_ij_ = 1:1:127;
eps_target_ = [10,1,0.1,0.01];
E_svd_ = zeros(length(d_ij_),length(eps_target_));
n_S_ = zeros(length(eps_target_),1);
for neps=1:length(eps_target_);
eps_target = eps_target_(neps);
[n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_] = gen_Jsvd_2b(max_k_p,N_pixel,eps_target,l_max);
n_S_(neps) = n_svd_l;
if (verbose); disp(sprintf(' %% eps_target %f',eps_target)); end;
for nd=1:length(d_ij_);
d_ij = d_ij_(nd);
delta_d = svd_d_(d_ij);
delta_w = 1*pi/6;
delta_x = delta_d*cos(delta_w); delta_y = delta_d*sin(delta_w);
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
[X_k_p_] = test_F_X_k_p_0(n_point,max_x_c,delta_d,delta_w,n_svd_r,svd_r_,n_svd_d,svd_d_,n_svd_l,svd_l_,svd_U_d_,svd_s_,svd_V_r_);
tmp_ = abs(T_k_p_-X_k_p_).^2; tmp_ = tmp_*diag(2*pi*grid_k_r_); tmp = sum(tmp_(:)).*(2*pi*d_k_r)*d_k_w; tmp = sqrt(tmp/(pi*max_k_p.^2)); 
E_svd_(nd,neps) = tmp;
end;%for nd=1:length(d_ij_);
end;%for neps=1:length(eps_target_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% Now brute-force + linear-interpolation;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
verbose=1;
n_node_ = [4,8,12,16];
for nnode=1:length(n_node_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
n_node = n_node_(nnode);
if (verbose); disp(sprintf(' %% n_node %f',n_node)); end;
node_ij_ = round(linspace(1,127,n_node));
T_k_p__ = cell(length(node_ij_),1);
for nij=1:length(node_ij_);
node_ij = node_ij_(nij);
delta_d = svd_d_(node_ij); delta_w = 1*pi/6;
T_k_p__{nij} = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
end;%for nij=1:length(node_ij_);
d_ij_ = 1:1:127;
for nd=1:length(d_ij_);
d_ij = d_ij_(nd);
%%%%%%%%%%%%%%%% ;
delta_d = svd_d_(d_ij);
delta_w = 1*pi/6;
delta_x = delta_d*cos(delta_w); delta_y = delta_d*sin(delta_w);
disp(sprintf(' %% delta_x_c (%f,%f) delta_x_p (%f,%f)',delta_x,delta_y,delta_d,delta_w));
%%%%%%%%%%%%%%%% ;
[T_k_p_] = test_F_T_k_p_0(n_point,max_x_c,delta_d,delta_w);
%%%%%%%%%%%%%%%% ;
ij_par = find(abs(node_ij_-d_ij)<1e-7);
if (~isempty(ij_par)); 
if (verbose); disp(sprintf(' %% nd %d delta_d %f ij_par %d',nd,delta_d,ij_par)); end;
B_k_p_ = T_k_p__{ij_par};
end;%if (~isempty(ij_par)); 
if (isempty(ij_par));
ij_pre = max(find(node_ij_<d_ij));
ij_pos = min(find(node_ij_>d_ij));
if (verbose); disp(sprintf(' %% nd %d delta_d %f ij_pre %d ij_pos %d',nd,delta_d,ij_pre,ij_pos)); end;
d_pre = d_ij - node_ij_(ij_pre); d_pos = node_ij_(ij_pos) - d_ij;
w_pre = d_pos/(d_pos+d_pre); w_pos = d_pre/(d_pos+d_pre);
B_k_p_ = w_pre*T_k_p__{ij_pre} + w_pos*T_k_p__{ij_pos};
end;%if (isempty(ij_par));
tmp_ = abs(T_k_p_-B_k_p_).^2; tmp_ = tmp_*diag(2*pi*grid_k_r_); tmp = sum(tmp_(:)).*(2*pi*d_k_r)*d_k_w; tmp = sqrt(tmp/(pi*max_k_p.^2)); 
E_int_(nd,nnode) = tmp;
%%%%%%%%%%%%%%%% ;
end;%for nd=1:length(d_ij_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
end;%for nnode=1:length(n_node_);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% Now plot. ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;

figure(8);clf;
hold on;
plot(svd_d_(d_ij_)*max_k_p,E_int_(:,1),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,E_int_(:,2),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,E_int_(:,3),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,E_int_(:,4),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,E_svd_(:,2),'--','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,E_svd_(:,3),'--','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,E_svd_(:,4),'--','LineWidth',2);
hold off;
xlim([0,max(svd_d_(d_ij_))*max_k_p]);
xlabel('displacement (in wavelengths)');
ylabel('l2-error in displacement');
n_node2_ = 1 + (n_node_-1).^2;
legend(...
sprintf('bf+li(%d/%d)',n_node_(1),n_node2_(1)),...
sprintf('bf+li(%d/%d)',n_node_(2),n_node2_(2)),...
sprintf('bf+li(%d/%d)',n_node_(3),n_node2_(3)),...
sprintf('bf+li(%d/%d)',n_node_(4),n_node2_(4)),...
sprintf('svd(%0.2f/%d)',eps_target_(2),n_S_(2)),...
sprintf('svd(%0.2f/%d)',eps_target_(3),n_S_(3)),...
sprintf('svd(%0.2f/%d)',eps_target_(4),n_S_(4)),...
'Location','NorthEast');
title(sprintf('error as function of displacement: n_{point} %d K_{max} %d N^{pixel} %0.1f',n_point,max_k_p,N_pixel));
set(gcf,'Position',1+[0,0,1024*1.5,1024]);
fname_base = sprintf('X_vs_I_error_n%d_K%d_N%.2d',n_point,max_k_p,round(10*N_pixel));
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));

figure(9);clf;
hold on;
plot(svd_d_(d_ij_)*max_k_p,log10(E_int_(:,1)),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,log10(E_int_(:,2)),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,log10(E_int_(:,3)),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,log10(E_int_(:,4)),'-','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,log10(E_svd_(:,2)),'--','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,log10(E_svd_(:,3)),'--','LineWidth',2);
plot(svd_d_(d_ij_)*max_k_p,log10(E_svd_(:,4)),'--','LineWidth',2);
hold off;
xlim([0,max(svd_d_(d_ij_))*max_k_p]);
xlabel('displacement (in wavelengths)');
ylabel('l2-error in displacement');
legend(...
sprintf('bf+li(%d/%d)',n_node_(1),n_node2_(1)),...
sprintf('bf+li(%d/%d)',n_node_(2),n_node2_(2)),...
sprintf('bf+li(%d/%d)',n_node_(3),n_node2_(3)),...
sprintf('bf+li(%d/%d)',n_node_(4),n_node2_(4)),...
sprintf('svd(%0.2f/%d)',eps_target_(2),n_S_(2)),...
sprintf('svd(%0.2f/%d)',eps_target_(3),n_S_(3)),...
sprintf('svd(%0.2f/%d)',eps_target_(4),n_S_(4)),...
'Location','SouthEast');
title(sprintf('log10(error) as function of displacement: n_{point} %d K_{max} %d N^{pixel} %0.1f',n_point,max_k_p,N_pixel));
set(gcf,'Position',1+[0,0,1024*1.5,1024]);
fname_base = sprintf('X_vs_I_l10error_n%d_K%d_N%.2d',n_point,max_k_p,round(10*N_pixel));
print('-djpeg',sprintf('./dir_svd/%s.jpg',fname_base));
print('-depsc',sprintf('./dir_svd/%s.eps',fname_base));

