function ...
[ ...
 parameter ...
,n_delta_p_r ...
,delta_p_r_ ...
,weight_2d_p_r_ ...
,n_delta_p_w ...
,delta_p_w_ ...
,delta_p_0_wr__ ...
,delta_p_1_wr__ ...
,weight_2d_p_wr__ ...
] = ....
get_delta_3( ....
 parameter ....
,delta_r_max ...
,n_delta_v_requested ...
);
% This function outputs an array of displacements delta_0_, delta_y_ ;
% that are supported on a disc of radius delta_r_max. ;
% The number of requested displacents n_delta_v_requested is a lower-bound on the actual number produced. ;
% In this case we return 

str_thisfunction = 'get_delta_3';
if nargin<1;
flag_verbose=1;
if (flag_verbose>0); disp(sprintf(' %% testing %s',str_thisfunction)); end;
k_p_r_max = 48.0/(2*pi); delta_r_max = 0.5/max(1e-12,k_p_r_max); svd_eps = 1e-6; n_delta_v_requested = 64; parameter=[];
[ ...
 parameter ...
,n_delta_p_r ...
,delta_p_r_ ...
,weight_2d_p_r_ ...
,n_delta_p_w ...
,delta_p_w_...
,delta_p_0_wr__ ...
,delta_p_1_wr__ ...
,weight_2d_p_wr__ ...
] = ....
get_delta_3( ....
 parameter ....
,delta_r_max ...
,n_delta_v_requested ...
);
figure(1);clf;figsml;
plot(delta_p_0_wr__,delta_p_1_wr__,'bo','MarkerFaceColor','g');
axis(1.25*delta_r_max*[-1,+1,-1,+1]); axis square; grid on;
xlabel('d_0','Interpreter','none'); ylabel('d_1','Interpreter','none');
disp(sprintf(' %% n_delta_v_requested %0.3d --> n_delta_v %0.3d',n_delta_v_requested,n_delta_p_r*n_delta_p_w));
disp(sprintf(' %% pi*delta_r_max^2: %0.6f sum(weight_2d_p_r_): %0.6f sum(weight_2d_p_wr__)*(2*pi)^2: %0.6f',pi*delta_r_max^2,sum(weight_2d_p_r_),sum(weight_2d_p_wr__,'all')*(2*pi)^2));
disp('returning'); return;
end;%if nargin<1;

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); delta_r_max=[]; end; na=na+1;
if (nargin<1+na); n_delta_v_requested=[]; end; na=na+1;

if isempty(parameter); parameter=struct('type','parameter'); end;

if isempty(n_delta_v_requested);
n_delta_p_r = 1; delta_p_r_ = 0;
n_delta_p_w = 1; delta_p_w_ = 0;
delta_p_0_wr__ = 0; delta_p_1_wr__ = 0; 
end;%if isempty(n_delta_v_requested);

tolerance_margin = 1e-6;
if n_delta_v_requested> 1;
n_delta_p_r = 0 + ceil(sqrt(n_delta_v_requested/(2*pi))); n_delta_p_w = ceil(2*pi*n_delta_p_r);
[a_jx_,a_jw_] = jacpts(n_delta_p_r,0,1); a_jw_=transpose(a_jw_);
weight_2d_p_r_ = delta_r_max^2 * pi*a_jw_/2;
delta_p_r_ = delta_r_max*(a_jx_ + 1)/2;
delta_p_w_ = linspace(0,2*pi,n_delta_p_w+1); delta_p_w_ = transpose(delta_p_w_(1:n_delta_p_w));
[delta_p_w_wr__,delta_p_r_wr__] = ndgrid(delta_p_w_,delta_p_r_);
delta_p_0_wr__ = delta_p_r_wr__.*cos(delta_p_w_wr__);
delta_p_1_wr__ = delta_p_r_wr__.*sin(delta_p_w_wr__);
weight_2d_p_wr__ = reshape(repmat(reshape(weight_2d_p_r_,[1,n_delta_p_r]),[n_delta_p_w,1]),[n_delta_p_w*n_delta_p_r,1])/n_delta_p_w/(2*pi)^2; %<-- to stay consistent with weight_2d_k_p_wk_. ;
end;%if n_delta_v_requested> 1;
