function  ...
[ ...
 parameter ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,image_delta_x_M_ ...
,image_delta_y_M_ ...
,image_I_value_M_ ...
,image_X_value_M_ ...
,image_S_index_M_ ...
] = ...
tfpmh_SM_uniform_2( ...
 parameter ...
,n_w_max ...
,n_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,n_M ...
,X_wSM___ ...
,delta_x_wSM___ ...
,delta_y_wSM___ ...
,gamma_z_wSM___ ...
,I_value_wSM___ ...
);

%%%%%%%%;
if nargin<1;
flag_verbose=1;
parameter = struct('type','parameter');
parameter.flag_deterministic = 1;
parameter.f_rand = 0.5;
n_w_max=8;
n_S=13;
viewing_azimu_b_S_=transpose(linspace(0,2*pi,n_S));
viewing_polar_a_S_=transpose(linspace(0,1*pi,n_S));
n_M=17;
%%%%;
n_wSM = n_w_max*n_S*n_M;
X_wSM___ = reshape(mod([0:n_wSM-1],19),[n_w_max,n_S,n_M]);
delta_x_wSM___ = reshape(mod([0:n_wSM-1],23),[n_w_max,n_S,n_M]);
delta_y_wSM___ = reshape(mod([0:n_wSM-1],29),[n_w_max,n_S,n_M]);
gamma_z_wSM___ = reshape(mod([0:n_wSM-1],31),[n_w_max,n_S,n_M]);
I_value_wSM___ = reshape(mod([0:n_wSM-1],37),[n_w_max,n_S,n_M]);
[ ...
 parameter ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,image_delta_x_M_ ...
,image_delta_y_M_ ...
,image_I_value_M_ ...
,image_X_value_M_ ...
,image_S_index_M_ ...
] = ...
tfpmh_SM_uniform_2( ...
 parameter ...
,n_w_max ...
,n_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,n_M ...
,X_wSM___ ...
,delta_x_wSM___ ...
,delta_y_wSM___ ...
,gamma_z_wSM___ ...
,I_value_wSM___ ...
);
%%%%;
dir_pymat = '/data/rangan/dir_cryoem/dir_rangan_python/dir_pymat' ;
fname_pymat = sprintf('%s/test_tfpmh_SM_uniform_2_wSM.mat',dir_pymat);
if ~exist(fname_pymat,'file'); disp(sprintf(' %% %s not found',fname_pymat)); end;
if  exist(fname_pymat,'file');
tmp_ = load(fname_pymat);
fnorm_disp(flag_verbose,'euler_polar_a_M_',euler_polar_a_M_,'tmp_.euler_polar_a_M_',tmp_.euler_polar_a_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'euler_azimu_b_M_',euler_azimu_b_M_,'tmp_.euler_azimu_b_M_',tmp_.euler_azimu_b_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'euler_gamma_z_M_',euler_gamma_z_M_,'tmp_.euler_gamma_z_M_',tmp_.euler_gamma_z_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_delta_x_M_',image_delta_x_M_,'tmp_.image_delta_x_M_',tmp_.image_delta_x_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_delta_y_M_',image_delta_y_M_,'tmp_.image_delta_y_M_',tmp_.image_delta_y_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_I_value_M_',image_I_value_M_,'tmp_.image_I_value_M_',tmp_.image_I_value_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_X_value_M_',image_X_value_M_,'tmp_.image_X_value_M_',tmp_.image_X_value_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_S_index_M_',image_S_index_M_,'double(tmp_.image_S_index_M_)',double(tmp_.image_S_index_M_),' %%<-- should be zero');
end;%if  exist(fname_pymat,'file');
%%%%;
n_SM = n_S*n_M;
X_SM__ = reshape(mod([0:n_SM-1],19),[n_S,n_M]);
delta_x_SM__ = reshape(mod([0:n_SM-1],23),[n_S,n_M]);
delta_y_SM__ = reshape(mod([0:n_SM-1],29),[n_S,n_M]);
gamma_z_SM__ = reshape(mod([0:n_SM-1],31),[n_S,n_M]);
I_value_SM__ = reshape(mod([0:n_SM-1],37),[n_S,n_M]);
[ ...
 parameter ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,image_delta_x_M_ ...
,image_delta_y_M_ ...
,image_I_value_M_ ...
,image_X_value_M_ ...
,image_S_index_M_ ...
] = ...
tfpmh_SM_uniform_2( ...
 parameter ...
,n_w_max ...
,n_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,n_M ...
,X_SM__ ...
,delta_x_SM__ ...
,delta_y_SM__ ...
,gamma_z_SM__ ...
,I_value_SM__ ...
);
%%%%;
dir_pymat = '/data/rangan/dir_cryoem/dir_rangan_python/dir_pymat' ;
fname_pymat = sprintf('%s/test_tfpmh_SM_uniform_2_SM.mat',dir_pymat);
if ~exist(fname_pymat,'file'); disp(sprintf(' %% %s not found',fname_pymat)); end;
if  exist(fname_pymat,'file');
tmp_ = load(fname_pymat);
fnorm_disp(flag_verbose,'euler_polar_a_M_',euler_polar_a_M_,'tmp_.euler_polar_a_M_',tmp_.euler_polar_a_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'euler_azimu_b_M_',euler_azimu_b_M_,'tmp_.euler_azimu_b_M_',tmp_.euler_azimu_b_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'euler_gamma_z_M_',euler_gamma_z_M_,'tmp_.euler_gamma_z_M_',tmp_.euler_gamma_z_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_delta_x_M_',image_delta_x_M_,'tmp_.image_delta_x_M_',tmp_.image_delta_x_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_delta_y_M_',image_delta_y_M_,'tmp_.image_delta_y_M_',tmp_.image_delta_y_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_I_value_M_',image_I_value_M_,'tmp_.image_I_value_M_',tmp_.image_I_value_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_X_value_M_',image_X_value_M_,'tmp_.image_X_value_M_',tmp_.image_X_value_M_,' %%<-- should be zero');
fnorm_disp(flag_verbose,'image_S_index_M_',image_S_index_M_,'double(tmp_.image_S_index_M_)',double(tmp_.image_S_index_M_),' %%<-- should be zero');
end;%if  exist(fname_pymat,'file');
%%%%;
disp('returning'); return;
end;%if nargin<1;
%%%%%%%%;

%%%%%%%%;
na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_w_max=[]; end; na=na+1;
if (nargin<1+na); n_S=[]; end; na=na+1;
if (nargin<1+na); viewing_azimu_b_S_=[]; end; na=na+1;
if (nargin<1+na); viewing_polar_a_S_=[]; end; na=na+1;
if (nargin<1+na); n_M=[]; end; na=na+1;
if (nargin<1+na); X_wSM___=[]; end; na=na+1;
if (nargin<1+na); delta_x_wSM___=[]; end; na=na+1;
if (nargin<1+na); delta_y_wSM___=[]; end; na=na+1;
if (nargin<1+na); gamma_z_wSM___=[]; end; na=na+1;
if (nargin<1+na); I_value_wSM___=[]; end; na=na+1;
%%%%%%%%;
if isempty(parameter); parameter = struct('type','parameter'); end;%if isempty(parameter);
if ~isfield(parameter,'flag_verbose'); parameter.flag_verbose = 0; end;
flag_verbose = parameter.flag_verbose;
if ~isfield(parameter,'flag_deterministic'); parameter.flag_deterministic = 0; end;
flag_deterministic = parameter.flag_deterministic;
if isempty(I_value_wSM___); I_value_wSM___ = ones(size(X_wSM___)); end;
%%%%%%%%;
if (~isfield(parameter,'f_rand')); parameter.f_rand = 0.05; end; %<-- parameter_bookmark. ;
f_rand = parameter.f_rand;
%%%%%%%%;
euler_polar_a_M_ = zeros(n_M,1);
euler_azimu_b_M_ = zeros(n_M,1);
euler_gamma_z_M_ = zeros(n_M,1);
image_delta_x_M_ = zeros(n_M,1);
image_delta_y_M_ = zeros(n_M,1);
image_I_value_M_ = zeros(n_M,1);
image_X_value_M_ = zeros(n_M,1);
image_S_index_M_ = zeros(n_M,1);
%%%%%%%%;
for nM=0:n_M-1;
tmp_image_X_value_S_ = zeros(n_S,1);
tmp_gamma_z_S_ = zeros(n_S,1);
tmp_delta_x_S_ = zeros(n_S,1);
tmp_delta_y_S_ = zeros(n_S,1);
tmp_I_value_S_ = zeros(n_S,1);
for nS=0:n_S-1;
if (ndims(X_wSM___)==3);
[tmp_X,nw] = max(squeeze(real(X_wSM___(:,1+nS,1+nM)))); nw = nw - 1;
tmp_gamma_z = gamma_z_wSM___(1+nw,1+nS,1+nM);
tmp_delta_x = delta_x_wSM___(1+nw,1+nS,1+nM);
tmp_delta_y = delta_y_wSM___(1+nw,1+nS,1+nM);
tmp_I_value = I_value_wSM___(1+nw,1+nS,1+nM);
end;%if (ndims(X_wSM___)==3);
if (ndims(X_wSM___)==2);
tmp_X = X_wSM___(1+nS,1+nM);
tmp_gamma_z = gamma_z_wSM___(1+nS,1+nM);
tmp_delta_x = delta_x_wSM___(1+nS,1+nM);
tmp_delta_y = delta_y_wSM___(1+nS,1+nM);
tmp_I_value = I_value_wSM___(1+nS,1+nM);
end;%if (ndims(X_wSM___)==2);
tmp_image_X_value_S_(1+nS) = tmp_X;
tmp_gamma_z_S_(1+nS) = tmp_gamma_z;
tmp_delta_x_S_(1+nS) = tmp_delta_x;
tmp_delta_y_S_(1+nS) = tmp_delta_y;
tmp_I_value_S_(1+nS) = tmp_I_value;
end;%for nS=0:n_S-1;
%%%%%%%%;
if (f_rand> 0); 
tmp_X_index_ = efind(tmp_image_X_value_S_>=prctile(tmp_image_X_value_S_,100-100*f_rand)); 
tmp_rand = 0.5; if flag_deterministic==0; tmp_rand = rand(); end;
tmp_X_index_index = max(0,min(numel(tmp_X_index_)-1,floor(numel(tmp_X_index_)*tmp_rand)));
nS_best = tmp_X_index_(1+tmp_X_index_index);
end;%if (f_rand> 0); 
if (f_rand<=0); 
[~,nS_best] = max(tmp_image_X_value_S_); nS_best = nS_best - 1; 
end;%if (f_rand<=0);
%%%%%%%%;
euler_polar_a_M_(1+nM) = viewing_polar_a_S_(1+nS_best);
euler_azimu_b_M_(1+nM) = viewing_azimu_b_S_(1+nS_best);
euler_gamma_z_M_(1+nM) = tmp_gamma_z_S_(1+nS_best);
image_delta_x_M_(1+nM) = tmp_delta_x_S_(1+nS_best);
image_delta_y_M_(1+nM) = tmp_delta_y_S_(1+nS_best);
image_I_value_M_(1+nM) = tmp_I_value_S_(1+nS_best);
image_X_value_M_(1+nM) = tmp_image_X_value_S_(1+nS_best);
image_S_index_M_(1+nM) = nS_best;
end;%for nM=0:n_M-1;
