function ...
parameter = ...
tfpmut_wrap_wrap_6( ...
 parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,weight_2d_k_p_wk_ ...
,l_max_ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,a_k_Y_true_yk_ ...
,euler_polar_a_true_M_ ...
,euler_azimu_b_true_M_ ...
,euler_gamma_z_true_M_ ...
,image_delta_x_true_M_ ...
,image_delta_y_true_M_ ...
);

str_thisfunction = 'tfpmut_wrap_wrap_6';

na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_k_p_r=[]; end; na=na+1;
if (nargin<1+na); k_p_r_=[]; end; na=na+1;
if (nargin<1+na); k_p_r_max=[]; end; na=na+1;
if (nargin<1+na); weight_3d_k_p_r_=[]; end; na=na+1;
if (nargin<1+na); weight_2d_k_p_r_=[]; end; na=na+1;
if (nargin<1+na); n_w_=[]; end; na=na+1;
if (nargin<1+na); weight_2d_k_p_wk_=[]; end; na=na+1;
if (nargin<1+na); l_max_=[]; end; na=na+1;
if (nargin<1+na); n_CTF=[]; end; na=na+1;
if (nargin<1+na); CTF_k_p_wkC__=[]; end; na=na+1;
if (nargin<1+na); index_nCTF_from_nM_=[]; end; na=na+1;
if (nargin<1+na); n_M=[]; end; na=na+1;
if (nargin<1+na); M_k_p_wkM__=[]; end; na=na+1;
if (nargin<1+na); a_k_Y_true_yk_=[]; end; na=na+1;
if (nargin<1+na); euler_polar_a_true_M_=[]; end; na=na+1;
if (nargin<1+na); euler_azimu_b_true_M_=[]; end; na=na+1;
if (nargin<1+na); euler_gamma_z_true_M_=[]; end; na=na+1;
if (nargin<1+na); image_delta_x_true_M_=[]; end; na=na+1;
if (nargin<1+na); image_delta_y_true_M_=[]; end; na=na+1;

if isempty(parameter); parameter = struct('type','parameter'); end;%if isempty(parameter);
%%%%%%%%;
if (~isfield(parameter,'flag_verbose')); parameter.flag_verbose = 0; end; %<-- parameter_bookmark. ;
flag_verbose=parameter.flag_verbose;
if (~isfield(parameter,'tolerance_master')); parameter.tolerance_master = 1e-2; end; %<-- parameter_bookmark. ;
tolerance_master = parameter.tolerance_master;
if (~isfield(parameter,'flag_gpu')); parameter.flag_gpu = 0; end; %<-- parameter_bookmark. ;
flag_gpu=parameter.flag_gpu;
if (~isfield(parameter,'flag_rank_vs_tolerance')); parameter.flag_rank_vs_tolerance = 0; end; %<-- parameter_bookmark. ;
flag_rank_vs_tolerance = parameter.flag_rank_vs_tolerance;
if (~isfield(parameter,'flag_clump_vs_cluster')); parameter.flag_clump_vs_cluster = parameter.flag_rank_vs_tolerance; end; %<-- parameter_bookmark. ;
parameter.flag_clump_vs_cluster = parameter.flag_rank_vs_tolerance; flag_clump_vs_cluster = parameter.flag_clump_vs_cluster; %<-- force;
if (~isfield(parameter,'tolerance_pm')); parameter.tolerance_pm = parameter.tolerance_master; end; %<-- parameter_bookmark. ;
tolerance_pm = parameter.tolerance_pm;
if (~isfield(parameter,'rank_pm')); parameter.rank_pm = 10; end; %<-- parameter_bookmark. ;
rank_pm = parameter.rank_pm;
if (~isfield(parameter,'rank_CTF')); parameter.rank_CTF=[]; end; %<-- parameter_bookmark. ;
rank_CTF = parameter.rank_CTF;
if (~isfield(parameter,'dir_tfpm')); parameter.dir_tfpm = pwd; end; %<-- parameter_bookmark. ;
dir_tfpm = parameter.dir_tfpm;
if (~isfield(parameter,'rseed')); parameter.rseed = 0; end; %<-- parameter_bookmark. ;
rseed = parameter.rseed;
if (~isfield(parameter,'k_p_r_max')); parameter.k_p_r_max = k_p_r_max; end; %<-- parameter_bookmark. ;
k_p_r_max = parameter.k_p_r_max;
if (~isfield(parameter,'sample_sphere_k_eq_d')); parameter.sample_sphere_k_eq_d = 1/(2*pi); end; %<-- parameter_bookmark. ;
sample_sphere_k_eq_d = parameter.sample_sphere_k_eq_d;
if (~isfield(parameter,'half_diameter_x_c')); parameter.half_diameter_x_c = 1.0; end; %<-- parameter_bookmark. ;
half_diameter_x_c = parameter.half_diameter_x_c;
if (~isfield(parameter,'n_x_u_pack')); parameter.n_x_u_pack = 64; end; %<-- parameter_bookmark. ;
n_x_u_pack = parameter.n_x_u_pack;
if (~isfield(parameter,'delta_r_max')); parameter.delta_r_max = 0.1; end; %<-- parameter_bookmark. ;
delta_r_max = parameter.delta_r_max;
if (~isfield(parameter,'delta_r_upb')); parameter.delta_r_upb = 0.2; end; %<-- parameter_bookmark. ;
delta_r_upb = parameter.delta_r_upb;
if (~isfield(parameter,'cg_lsq_n_order')); parameter.cg_lsq_n_order = 5; end; %<-- parameter_bookmark. ;
cg_lsq_n_order = parameter.cg_lsq_n_order;
if (~isfield(parameter,'date_diff_threshold')); parameter.date_diff_threshold = 0.25; end; %<-- parameter_bookmark. ;
date_diff_threshold = parameter.date_diff_threshold;
if (~isfield(parameter,'flag_force_create_mat')); parameter.flag_force_create_mat = 0; end; %<-- parameter_bookmark. ;
flag_force_create_mat = parameter.flag_force_create_mat;
if (~isfield(parameter,'flag_force_create_tmp')); parameter.flag_force_create_tmp = 0; end; %<-- parameter_bookmark. ;
flag_force_create_tmp = parameter.flag_force_create_tmp;
if (~isfield(parameter,'flag_alternate_MS_vs_SM')); parameter.flag_alternate_MS_vs_SM = 0; end; %<-- parameter_bookmark. ;
flag_alternate_MS_vs_SM = parameter.flag_alternate_MS_vs_SM;
if (~isfield(parameter,'flag_qbp_vs_lsq')); parameter.flag_qbp_vs_lsq = 1; end; %<-- parameter_bookmark. ;
parameter.flag_qbp_vs_lsq = 1; flag_qbp_vs_lsq = parameter.flag_qbp_vs_lsq; %<-- force. ;
if (~isfield(parameter,'qbp_eps')); parameter.qbp_eps = parameter.tolerance_master; end; %<-- parameter_bookmark. ;
qbp_eps = parameter.qbp_eps;
if (~isfield(parameter,'str_strategy_prefix')); parameter.str_strategy_prefix = ''; end; %<-- parameter_bookmark. ;
str_strategy = parameter.str_strategy_prefix;
if (~isfield(parameter,'n_complete_calculation')); parameter.n_complete_calculation = 0; end; %<-- parameter_bookmark. ;
%%%%%%%%;
if (flag_alternate_MS_vs_SM==0); str_strategy = sprintf('%sa0',str_strategy); end;
if (flag_alternate_MS_vs_SM==1); str_strategy = sprintf('%sa1',str_strategy); end;
string_root = dir_tfpm(2:strfind(dir_tfpm,'rangan')-2);
%%%%%%%%;
if (~isfield(parameter,'flag_compare_image_rank')); parameter.flag_compare_image_rank = 0; end; %<-- parameter_bookmark. ;
flag_compare_image_rank = parameter.flag_compare_image_rank;
if (~isfield(parameter,'flag_save_stage')); parameter.flag_save_stage = 0; end; %<-- parameter_bookmark. ;
flag_save_stage = parameter.flag_save_stage;

str_delta_r_max = sprintf('t%.4d',floor(1000*delta_r_max));
str_tolerance_pm = sprintf('p%.2d',floor(10*-log10(tolerance_pm)));
str_rank_pm = sprintf('n%.2d',rank_pm);
str_rseed = sprintf('r%d',rseed);
if (flag_rank_vs_tolerance==0); str_xfix = sprintf('%s%s%s%s',str_strategy,str_delta_r_max,str_tolerance_pm,str_rseed); end;
if (flag_rank_vs_tolerance==1); str_xfix = sprintf('%s%s%s%s',str_strategy,str_delta_r_max,str_rank_pm,str_rseed); end;

XA_fname_mat = sprintf('%s_mat/X_2d_Memp_d1_%s.mat',dir_tfpm,str_xfix);
XA_fname_align_a_k_Y_pre = sprintf('%s_mat/X_2d_Memp_d1_%s_align_a_k_Y_',dir_tfpm,str_xfix);
XA_fname_align_a_k_Y_jpg = sprintf('%s.jpg',XA_fname_align_a_k_Y_pre);
XA_fname_snapshot_pre = sprintf('%s_mat/X_2d_Memp_d1_%s_snapshot',dir_tfpm,str_xfix);
XA_fname_snapshot_jpg = sprintf('%s.jpg',XA_fname_snapshot_pre);
XA_fname_compare_image_rank_pre = sprintf('%s_mat/X_2d_Memp_d1_%s_compare_image_rank',dir_tfpm,str_xfix);
XA_fname_compare_image_rank_jpg = sprintf('%s.jpg',XA_fname_compare_image_rank_pre);
XB_fname_mat = sprintf('%s_mat/X_2d_xcor_d0_%s.mat',dir_tfpm,str_xfix);
XB_fname_align_a_k_Y_pre = sprintf('%s_mat/X_2d_xcor_d0_%s_align_a_k_Y_',dir_tfpm,str_xfix);
XB_fname_align_a_k_Y_jpg = sprintf('%s.jpg',XB_fname_align_a_k_Y_pre);
XB_fname_snapshot_pre = sprintf('%s_mat/X_2d_xcor_d0_%s_snapshot',dir_tfpm,str_xfix);
XB_fname_snapshot_jpg = sprintf('%s.jpg',XB_fname_snapshot_pre);
XB_fname_compare_image_rank_pre = sprintf('%s_mat/X_2d_xcor_d0_%s_compare_image_rank',dir_tfpm,str_xfix);
XB_fname_compare_image_rank_jpg = sprintf('%s.jpg',XB_fname_compare_image_rank_pre);
flag_skip_all = 0;
if flag_compare_image_rank==0;
if ( ...
        exist(XA_fname_mat,'file') ...
     &  exist(XA_fname_align_a_k_Y_jpg,'file') ...
     &  exist(XA_fname_snapshot_jpg,'file') ...
     &  exist(XB_fname_mat,'file') ...
     &  exist(XB_fname_align_a_k_Y_jpg,'file') ...
     &  exist(XB_fname_snapshot_jpg,'file') ...
   ); flag_skip_all = 1; end;
end;%if flag_compare_image_rank==0;
if flag_compare_image_rank==1;
if ( ...
        exist(XA_fname_mat,'file') ...
     &  exist(XA_fname_align_a_k_Y_jpg,'file') ...
     &  exist(XA_fname_snapshot_jpg,'file') ...
     &  exist(XB_fname_mat,'file') ...
     &  exist(XB_fname_align_a_k_Y_jpg,'file') ...
     &  exist(XB_fname_snapshot_jpg,'file') ...
     &  exist(XA_fname_compare_image_rank_jpg,'file') ...
     &  exist(XB_fname_compare_image_rank_jpg,'file') ...
   ); flag_skip_all = 1; end;
end;%if flag_compare_image_rank==1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
if ~flag_skip_all;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

if (flag_verbose>0); disp(sprintf(' %% [entering %s]',str_thisfunction)); end;

%%%%%%%%;
n_w_ = n_w_(1:n_k_p_r); n_w_sum = sum(n_w_); n_w_max = max(n_w_); n_w_csum_ = cumsum([0;n_w_]);
if (std(diff(n_w_csum_),1)>1e-6); disp(sprintf(' %% Warning, flag_uniform_over_n_k_p_r==1 expected in %s',str_thisfunction)); end;
n_w_max = n_w_csum_(1+1);
assert(n_w_sum==n_w_max*n_k_p_r);
if mod(n_w_max,2)~=0; disp(sprintf(' %% Warning, n_w_max %d in %s',n_w_max,str_thisfunction)); end;
l_max_max = n_w_max/2 - 1; assert(l_max_max==max(l_max_));
n_w_ = n_w_max*ones(n_k_p_r,1);
n_w_sum = sum(n_w_);
n_w_csum_ = cumsum([0;n_w_]);
n_lm_ = (l_max_+1).^2;
n_lm_max = max(n_lm_);
n_lm_sum = sum(n_lm_);
n_lm_csum_ = cumsum([0;n_lm_]);
%%%%%%%%;
CTF_k_p_r_kC__ = reshape(mean(reshape(CTF_k_p_wkC__,[n_w_max,n_k_p_r,n_CTF]),1+0),[n_k_p_r,n_CTF]);
if isempty(rank_CTF);
SCTF_ = svd(CTF_k_p_r_kC__(:,1+index_nCTF_from_nM_)); rank_CTF = max(find(SCTF_/max(SCTF_)>parameter.tolerance_master));
parameter.rank_CTF = rank_CTF; %<-- parameter_bookmark. ;
end;%if isempty(rank_CTF);

%%%%%%%%;
% Now run the basic tfpmut using the empirical-principal-modes. ;
%%%%%%%%;
XA_fname_pre = sprintf('%s_mat/X_2d_Memp_d1_%s',dir_tfpm,str_xfix);
[XA_flag_skip,XA_fname_mat] = open_fname_tmp(XA_fname_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp);
if ~XA_flag_skip;
%%%%%%%%;
disp(sprintf(' %% %s not found, creating',XA_fname_mat));
XA_parameter = struct('type','parameter');
XA_parameter = parameter; %<-- copy parameter and all its fields. ;
XA_parameter.fname_pre = XA_fname_pre;
tmp_t=tic();
tfpmut_wrap_6( ...
 XA_parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,weight_2d_k_p_wk_ ...
,l_max_ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% tfpmut_wrap_6: time %0.2fs',tmp_t)); end;
XA_parameter = parameter_timing_update(XA_parameter,sprintf('%s: tfpmut_wrap_6',str_thisfunction),tmp_t);
parameter.n_complete_calculation = parameter.n_complete_calculation + 1;
close_fname_tmp(XA_fname_pre);
end;%if ~XA_flag_skip;

%%%%%%%%;
if ( exist(XA_fname_mat,'file'));
%%%%%%%%;
% First collect statistics. ;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% %s found, aligning',XA_fname_mat)); end;
tmp_XA_ = load(XA_fname_mat);
if (~isfield(tmp_XA_.parameter,'fname_pre')); tmp_XA_.parameter.fname_pre = XA_fname_pre; end; %<-- parameter_bookmark. ;
%%%%%%%%;
%{
tmp_XA_fname_pre = sprintf('%s_align_a_CTF_avg_UX_Y_',tmp_XA_.parameter.fname_pre);
tmp_XA_fname_pre = rootswitch(tmp_XA_fname_pre,string_root,'rangan');
tmp_XA_.parameter.fname_align_a_CTF_avg_UX_Y_pre = tmp_XA_fname_pre;
[tmp_XA_flag_skip,tmp_XA_fname_mat] = open_fname_tmp(tmp_XA_fname_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp);
if ~tmp_XA_flag_skip;
% do nothing. ;
close_fname_tmp(tmp_XA_fname_pre);
end;%if ~tmp_XA_flag_skip;
%}
%%%%%%%%;
tmp_XA_fname_pre = sprintf('%s_align_a_k_Y_',tmp_XA_.parameter.fname_pre);
tmp_XA_fname_pre = rootswitch(tmp_XA_fname_pre,string_root,'rangan');
tmp_XA_.parameter.fname_align_a_k_Y_pre = tmp_XA_fname_pre;
[tmp_XA_flag_skip,tmp_XA_fname_mat] = open_fname_tmp(tmp_XA_fname_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp);
if ~tmp_XA_flag_skip;
%try;
disp(sprintf(' %% %s not found, creating',tmp_XA_fname_mat));
tmp_t=tic();
tfpmut_align_to_a_k_Y_2( ...
 tmp_XA_.parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,weight_2d_k_p_wk_ ...
,l_max_ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,a_k_Y_true_yk_ ...
,[] ...
,tmp_XA_.euler_polar_a_Mi__ ...
,tmp_XA_.euler_azimu_b_Mi__ ...
,tmp_XA_.euler_gamma_z_Mi__ ...
,tmp_XA_.image_delta_x_acc_Mi__ + tmp_XA_.image_delta_x_upd_Mi__ ...
,tmp_XA_.image_delta_y_acc_Mi__ + tmp_XA_.image_delta_y_upd_Mi__ ...
,euler_polar_a_true_M_ ...
,euler_azimu_b_true_M_ ...
,euler_gamma_z_true_M_ ...
,image_delta_x_true_M_ ...
,image_delta_y_true_M_ ...
);
%catch; disp(sprintf(' %% WARNING: error generating %s',tmp_XA_fname_mat)); end;%try;
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% tfpmut_align_to_a_k_Y_2: time %0.2fs',tmp_t)); end;
XA_parameter = parameter_timing_update(XA_parameter,sprintf('%s: tfpmut_align_to_a_k_Y_2',str_thisfunction),tmp_t);
close_fname_tmp(tmp_XA_fname_pre);
end;%if ~tmp_XA_flag_skip;
%%%%%%%%;
% Now use the final step to reconstruct the molecule. ;
%%%%%%%%;
tmp_XA_euler_polar_a_M_ = tmp_XA_.euler_polar_a_Mi__(:,end);
tmp_XA_euler_azimu_b_M_ = tmp_XA_.euler_azimu_b_Mi__(:,end);
tmp_XA_euler_gamma_z_M_ = tmp_XA_.euler_gamma_z_Mi__(:,end);
tmp_XA_image_delta_x_M_ = tmp_XA_.image_delta_x_acc_Mi__(:,end) + tmp_XA_.image_delta_x_upd_Mi__(:,end);
tmp_XA_image_delta_y_M_ = tmp_XA_.image_delta_y_acc_Mi__(:,end) + tmp_XA_.image_delta_y_upd_Mi__(:,end);
fname_XA_k_Y_mat = sprintf('%s_a_k_Y_.mat',tmp_XA_.parameter.fname_pre);
fname_XA_k_Y_mat = rootswitch(fname_XA_k_Y_mat,string_root,'rangan');
if (~exist(fname_XA_k_Y_mat,'file'));
if (flag_verbose>0); disp(sprintf(' %% %s not found, creating',fname_XA_k_Y_mat)); end;
if flag_qbp_vs_lsq==0; disp(sprintf(' %% Warning, flag_qbp_vs_lsq=%d in %s',flag_qbp_vs_lsq,str_thisfunction)); end;%if flag_qbp_vs_lsq==0;
if flag_qbp_vs_lsq==1;
tmp_t=tic();
a_k_Y_reco_yk_ = ...
qbp_uniform_over_n_k_p_r_10( ...
 qbp_eps ...
,n_k_p_r ...
,k_p_r_ ...
,l_max_ ...
,n_w_ ...
,n_M ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
,tmp_XA_euler_polar_a_M_ ...
,tmp_XA_euler_azimu_b_M_ ...
,tmp_XA_euler_gamma_z_M_ ...
,tmp_XA_image_delta_x_M_ ...
,tmp_XA_image_delta_y_M_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% qbp_uniform_over_n_k_p_r_10: time %0.2fs',tmp_t)); end;
XA_parameter = parameter_timing_update(XA_parameter,sprintf('%s: qbp_uniform_over_n_k_p_r_10',str_thisfunction),tmp_t);
end;%if flag_qbp_vs_lsq==1;
save(fname_XA_k_Y_mat,'a_k_Y_reco_yk_');
end;%if (~exist(fname_XA_k_Y_mat,'file'));

%%%%%%%%;
if ( exist(fname_XA_k_Y_mat,'file'));
%%%%%%%%;
tmp_ = load(fname_XA_k_Y_mat); tmp_XA_a_k_Y_reco_yk_ = tmp_.a_k_Y_reco_yk_; clear tmp_;

if (flag_save_stage>0);
%%%%%%%%;
% save temp file for python. ;
%%%%%%%%;
tmp_fname_mat = sprintf('%s_mat/test_tfpmut_wrap_6_%s.mat',dir_tfpm,str_xfix);
if ~exist(tmp_fname_mat,'file');
disp(sprintf(' %% %s not found, creating',tmp_fname_mat));
save(tmp_fname_mat ...
     ,'flag_rank_vs_tolerance' ...
     ,'flag_clump_vs_cluster' ...
     ,'tolerance_pm' ...
     ,'rank_pm' ...
     ,'rank_CTF' ...
     ,'dir_tfpm' ...
     ,'rseed' ...
     ,'sample_sphere_k_eq_d' ...
     ,'half_diameter_x_c' ...
     ,'n_x_u_pack' ...
     ,'delta_r_max' ...
     ,'delta_r_upb' ...
     ,'cg_lsq_n_order' ...
     ,'flag_alternate_MS_vs_SM' ...
     ,'flag_qbp_vs_lsq' ...
     ,'qbp_eps' ...
     ,'str_xfix' ...
     ,'n_k_p_r' ...
     ,'k_p_r_' ...
     ,'k_p_r_max' ...
     ,'weight_3d_k_p_r_' ...
     ,'weight_2d_k_p_r_' ...
     ,'n_w_' ...
     ,'weight_2d_k_p_wk_' ...
     ,'l_max_' ...
     ,'n_CTF' ...
     ,'CTF_k_p_wkC__' ...
     ,'CTF_k_p_r_kC__' ...
     ,'index_nCTF_from_nM_' ...
     ,'n_M' ...
     ,'M_k_p_wkM__' ...
     ,'tmp_XA_euler_polar_a_M_' ...
     ,'tmp_XA_euler_azimu_b_M_' ...
     ,'tmp_XA_euler_gamma_z_M_' ...
     ,'tmp_XA_image_delta_x_M_' ...
     ,'tmp_XA_image_delta_y_M_' ...
     ,'tmp_XA_a_k_Y_reco_yk_' ...
    );
end;%if ~exist(tmp_fname_mat,'file');
if  exist(tmp_fname_mat,'file');
disp(sprintf(' %% %s found, not creating',tmp_fname_mat));
end;%if  exist(tmp_fname_mat,'file');
%%%%%%%%;
end;%if (flag_save_stage>0);

%%%%%%%%;
% Now run tfpmut once again, this time using the updated-principal-modes. ;
%%%%%%%%;
XB_fname_pre = sprintf('%s_mat/X_2d_xcor_d0_%s',dir_tfpm,str_xfix);
[XB_flag_skip,XB_fname_mat] = open_fname_tmp(XB_fname_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp);
if ~XB_flag_skip;
%%%%%%%%;
%try;
disp(sprintf(' %% %s not found, creating',XB_fname_mat));
XB_parameter = struct('type','parameter');
XB_parameter = parameter; %<-- copy parameter and all its fields. ;
XB_parameter.fname_pre = XB_fname_pre;
tmp_t=tic();
tfpmut_wrap_6( ...
 XB_parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,weight_2d_k_p_wk_ ...
,l_max_ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,tmp_XA_euler_polar_a_M_ ...
,tmp_XA_euler_azimu_b_M_ ...
,tmp_XA_euler_gamma_z_M_ ...
,tmp_XA_image_delta_x_M_ ...
,tmp_XA_image_delta_y_M_ ...
,tmp_XA_a_k_Y_reco_yk_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% tfpmut_wrap_6: time %0.2fs',tmp_t)); end;
XB_parameter = parameter_timing_update(XB_parameter,sprintf('%s: tfpmut_wrap_6',str_thisfunction),tmp_t);
parameter.n_complete_calculation = parameter.n_complete_calculation + 1;
%catch; disp(sprintf(' %% WARNING: error generating %s',XB_fname_mat)); end;%try;
close_fname_tmp(XB_fname_pre);
end;%if ~XB_flag_skip;

%%%%%%%%;
if ( exist(XB_fname_mat,'file'));
%%%%%%%%;
% First collect statistics. ;
%%%%%%%%;
if (flag_verbose>0); disp(sprintf(' %% %s found, aligning',XB_fname_mat)); end;
tmp_XB_ = load(XB_fname_mat);
if (~isfield(tmp_XB_.parameter,'fname_pre')); tmp_XB_.parameter.fname_pre = XB_fname_pre; end; %<-- parameter_bookmark. ;
%%%%%%%%;
%{
tmp_XB_fname_pre = sprintf('%s_align_a_CTF_avg_UX_Y_',tmp_XB_.parameter.fname_pre);
tmp_XB_fname_pre = rootswitch(tmp_XB_fname_pre,string_root,'rangan');
tmp_XB_.parameter.fname_align_a_CTF_avg_UX_Y_pre = tmp_XB_fname_pre;
[tmp_XB_flag_skip,tmp_XB_fname_mat] = open_fname_tmp(tmp_XB_fname_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp);
if ~tmp_XB_flag_skip;
% do nothing. ;
close_fname_tmp(tmp_XB_fname_pre);
end;%if ~tmp_XB_flag_skip;
%}
%%%%%%%%;
tmp_XB_fname_pre = sprintf('%s_align_a_k_Y_',tmp_XB_.parameter.fname_pre);
tmp_XB_fname_pre = rootswitch(tmp_XB_fname_pre,string_root,'rangan');
tmp_XB_.parameter.fname_align_a_k_Y_pre = tmp_XB_fname_pre;
[tmp_XB_flag_skip,tmp_XB_fname_mat] = open_fname_tmp(tmp_XB_fname_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp);
if ~tmp_XB_flag_skip;
%try;
disp(sprintf(' %% %s not found, creating',tmp_XB_fname_mat));
tmp_t=tic();
tfpmut_align_to_a_k_Y_2( ...
 tmp_XB_.parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,weight_2d_k_p_wk_ ...
,l_max_ ...
,n_CTF ...
,CTF_k_p_wkC__ ...
,index_nCTF_from_nM_ ...
,n_M ...
,M_k_p_wkM__ ...
,a_k_Y_true_yk_ ...
,[] ...
,tmp_XB_.euler_polar_a_Mi__ ...
,tmp_XB_.euler_azimu_b_Mi__ ...
,tmp_XB_.euler_gamma_z_Mi__ ...
,tmp_XB_.image_delta_x_acc_Mi__ + tmp_XB_.image_delta_x_upd_Mi__ ...
,tmp_XB_.image_delta_y_acc_Mi__ + tmp_XB_.image_delta_y_upd_Mi__ ...
,euler_polar_a_true_M_ ...
,euler_azimu_b_true_M_ ...
,euler_gamma_z_true_M_ ...
,image_delta_x_true_M_ ...
,image_delta_y_true_M_ ...
);
%catch; disp(sprintf(' %% WARNING: error generating %s',tmp_XB_fname_mat)); end;%try;
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% tfpmut_align_to_a_k_Y_2: time %0.2fs',tmp_t)); end;
XB_parameter = parameter_timing_update(XB_parameter,sprintf('%s: tfpmut_align_to_a_k_Y_2',str_thisfunction),tmp_t);
close_fname_tmp(tmp_XB_fname_pre);
end;%if ~tmp_XB_flag_skip;
%%%%%%%%;
% Now use the final step to reconstruct the molecule. ;
%%%%%%%%;
tmp_XB_euler_polar_a_M_ = tmp_XB_.euler_polar_a_Mi__(:,end);
tmp_XB_euler_azimu_b_M_ = tmp_XB_.euler_azimu_b_Mi__(:,end);
tmp_XB_euler_gamma_z_M_ = tmp_XB_.euler_gamma_z_Mi__(:,end);
tmp_XB_image_delta_x_M_ = tmp_XB_.image_delta_x_acc_Mi__(:,end) + tmp_XB_.image_delta_x_upd_Mi__(:,end);
tmp_XB_image_delta_y_M_ = tmp_XB_.image_delta_y_acc_Mi__(:,end) + tmp_XB_.image_delta_y_upd_Mi__(:,end);
fname_XB_k_Y_mat = sprintf('%s_a_k_Y_.mat',tmp_XB_.parameter.fname_pre);
fname_XB_k_Y_mat = rootswitch(fname_XB_k_Y_mat,string_root,'rangan');
if (~exist(fname_XB_k_Y_mat,'file'));
if (flag_verbose>0); disp(sprintf(' %% %s not found, creating',fname_XB_k_Y_mat)); end;
if flag_qbp_vs_lsq==0; disp(sprintf(' %% Warning, flag_qbp_vs_lsq=%d in %s',flag_qbp_vs_lsq,str_thisfunction)); end;%if flag_qbp_vs_lsq==0;
if flag_qbp_vs_lsq==1;
tmp_t=tic();
a_k_Y_reco_yk_ = ...
qbp_uniform_over_n_k_p_r_10( ...
 qbp_eps ...
,n_k_p_r ...
,k_p_r_ ...
,l_max_ ...
,n_w_ ...
,n_M ...
,M_k_p_wkM__ ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
,tmp_XB_euler_polar_a_M_ ...
,tmp_XB_euler_azimu_b_M_ ...
,tmp_XB_euler_gamma_z_M_ ...
,tmp_XB_image_delta_x_M_ ...
,tmp_XB_image_delta_y_M_ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% qbp_uniform_over_n_k_p_r_10: time %0.2fs',tmp_t)); end;
XB_parameter = parameter_timing_update(XB_parameter,sprintf('%s: qbp_uniform_over_n_k_p_r_10',str_thisfunction),tmp_t);
end;%if flag_qbp_vs_lsq==1;
save(fname_XB_k_Y_mat,'a_k_Y_reco_yk_');
end;%if (~exist(fname_XB_k_Y_mat,'file'));
%tmp_ = load(fname_XB_k_Y_mat); tmp_XB_a_k_Y_reco_yk_ = tmp_.a_k_Y_reco_yk_; clear tmp_; %<-- not used. ;
%%%%%%%%;
end;%if ( exist(XB_fname_mat,'file'));
%%%%%%%%;

%%%%%%%%;
end;%if ( exist(fname_XA_k_Y_mat,'file'));
%%%%%%%%;
%%%%%%%%;
end;%if ( exist(XA_fname_mat,'file'));
%%%%%%%%;

%%%%%%%%;
if ( exist(XA_fname_mat,'file') & ~exist(XA_fname_snapshot_jpg) );
[XA_fname_snapshot_flag_skip,XA_fname_snapshot_jpg] = open_fname_tmp(XA_fname_snapshot_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp,'jpg');
if ~XA_fname_snapshot_flag_skip;
%%%%%%%%;
if (flag_verbose>0) disp(sprintf(' %% %s not found, creating',XA_fname_snapshot_jpg)); end;
tmp_XA_ = load(XA_fname_mat);
flag_found = 1; tmp_XA_align_a_k_Y_ = []; tmp_XA_a_k_Y_ = [];
%%%%;
tmp_XA_fname_pre = sprintf('%s_align_a_k_Y_',tmp_XA_.parameter.fname_pre);
tmp_XA_fname_pre = rootswitch(tmp_XA_fname_pre,string_root,'rangan');
tmp_XA_.parameter.fname_align_a_k_Y_pre = tmp_XA_fname_pre;
tmp_XA_fname_mat = sprintf('%s.mat',tmp_XA_fname_pre);
if (~exist(tmp_XA_fname_mat,'file'));
disp(sprintf(' %% Warning, %s not found in %s',tmp_XA_fname_mat,str_thisfunction));
flag_found = 0;
end;%if (~exist(tmp_XA_fname_mat,'file'));
if ( exist(tmp_XA_fname_mat,'file'));
tmp_XA_align_a_k_Y_ = load(tmp_XA_fname_mat);
end;%if ( exist(tmp_XA_fname_mat,'file'));
%%%%;
tmp_XA_fname_pre = sprintf('%s_a_k_Y_',tmp_XA_.parameter.fname_pre);
tmp_XA_fname_pre = rootswitch(tmp_XA_fname_pre,string_root,'rangan');
tmp_XA_.parameter.fname_a_k_Y_pre = tmp_XA_fname_pre;
tmp_XA_fname_mat = sprintf('%s.mat',tmp_XA_fname_pre);
if (~exist(tmp_XA_fname_mat,'file'));
disp(sprintf(' %% Warning, %s not found in %s',tmp_XA_fname_mat,str_thisfunction));
flag_found = 0;
end;%if (~exist(tmp_XA_fname_mat,'file'));
if ( exist(tmp_XA_fname_mat,'file'));
tmp_XA_a_k_Y_ = load(tmp_XA_fname_mat);
end;%if ( exist(tmp_XA_fname_mat,'file'));
%%%%;
if ( flag_found & ~isempty(tmp_XA_align_a_k_Y_) & ~isempty(tmp_XA_a_k_Y_) );
%%%%;
tmp_X_best = tmp_XA_align_a_k_Y_.X_best_i_(end);
tmp_flag_flip = tmp_XA_align_a_k_Y_.flag_flip_i_(end);
tmp_polar_a_best = tmp_XA_align_a_k_Y_.polar_a_best_i_(end);
tmp_azimu_b_best = tmp_XA_align_a_k_Y_.azimu_b_best_i_(end);
tmp_gamma_z_best = tmp_XA_align_a_k_Y_.gamma_z_best_i_(end);
tmp_delta_x_best = tmp_XA_align_a_k_Y_.delta_best_3i__(1+0,end);
tmp_delta_y_best = tmp_XA_align_a_k_Y_.delta_best_3i__(1+1,end);
tmp_delta_z_best = tmp_XA_align_a_k_Y_.delta_best_3i__(1+2,end);
tmp_a_k_Y_reco_yk_ = tmp_XA_a_k_Y_.a_k_Y_reco_yk_;
%%%%;
[ ... 
 tmp_b_k_Y_reco_yk_ ...
] = ...
spharm_register_and_rotate_2( ...
 n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_true_yk_ ...
,tmp_a_k_Y_reco_yk_ ...
,0 ...
,tmp_X_best ...
,tmp_flag_flip ...
,tmp_polar_a_best ...
,tmp_azimu_b_best ...
,tmp_gamma_z_best ...
,tmp_delta_x_best ...
,tmp_delta_y_best ...
,tmp_delta_z_best ...
);
%%%%;
[ ... 
  tmp_b_x_u_reco_xxx_ ...
] = ...
convert_spharm_to_x_c_uniform_over_n_k_p_r_5( ...
 max(0,flag_verbose-1) ...
,sample_sphere_k_eq_d ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,tmp_b_k_Y_reco_yk_ ...
,half_diameter_x_c ...
,n_x_u_pack ...
);
%%%%;
figure(5);clf;figbig;
subplot(1,2,1);
isosurface_f_x_u_1(struct('percent_threshold_',[90,95,99]),tmp_b_x_u_reco_xxx_);
title(sprintf('tmp_b_x_u_: corr %0.4f',tmp_X_best),'Interpreter','none');
subplot(1,2,2);
isosurface_f_x_u_1(struct('percent_threshold_',[98.5]),tmp_b_x_u_reco_xxx_);
title(sprintf('tmp_b_x_u_: corr %0.4f',tmp_X_best),'Interpreter','none');
sgtitle(XA_fname_snapshot_jpg,'Interpreter','none'); drawnow();
disp(sprintf(' %% writing %s',XA_fname_snapshot_jpg));
print('-djpeg',XA_fname_snapshot_jpg);
close(gcf);
%%%%%%%%;
end;%if ( flag_found & ~isempty(tmp_XA_align_a_k_Y_) & ~isempty(tmp_XA_a_k_Y_) );
%%%%%%%%;
close_fname_tmp(XA_fname_snapshot_pre);
end;%if ~XA_fname_snapshot_flag_skip;
end;%if ( exist(XA_fname_mat,'file') & ~exist(XA_fname_snapshot_jpg) );
%%%%%%%%;

%%%%%%%%;
if ( exist(XB_fname_mat,'file') & ~exist(XB_fname_snapshot_jpg) );
[XB_fname_snapshot_flag_skip,XB_fname_snapshot_jpg] = open_fname_tmp(XB_fname_snapshot_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp,'jpg');
if ~XB_fname_snapshot_flag_skip;
%%%%%%%%;
if (flag_verbose>0) disp(sprintf(' %% %s not found, creating',XB_fname_snapshot_jpg)); end;
tmp_XB_ = load(XB_fname_mat);
flag_found = 1; tmp_XB_align_a_k_Y_ = []; tmp_XB_a_k_Y_ = [];
%%%%;
tmp_XB_fname_pre = sprintf('%s_align_a_k_Y_',tmp_XB_.parameter.fname_pre);
tmp_XB_fname_pre = rootswitch(tmp_XB_fname_pre,string_root,'rangan');
tmp_XB_.parameter.fname_align_a_k_Y_pre = tmp_XB_fname_pre;
tmp_XB_fname_mat = sprintf('%s.mat',tmp_XB_fname_pre);
if (~exist(tmp_XB_fname_mat,'file'));
disp(sprintf(' %% Warning, %s not found in %s',tmp_XB_fname_mat,str_thisfunction));
flag_found = 0;
end;%if (~exist(tmp_XB_fname_mat,'file'));
if ( exist(tmp_XB_fname_mat,'file'));
tmp_XB_align_a_k_Y_ = load(tmp_XB_fname_mat);
end;%if ( exist(tmp_XB_fname_mat,'file'));
%%%%;
tmp_XB_fname_pre = sprintf('%s_a_k_Y_',tmp_XB_.parameter.fname_pre);
tmp_XB_fname_pre = rootswitch(tmp_XB_fname_pre,string_root,'rangan');
tmp_XB_.parameter.fname_a_k_Y_pre = tmp_XB_fname_pre;
tmp_XB_fname_mat = sprintf('%s.mat',tmp_XB_fname_pre);
if (~exist(tmp_XB_fname_mat,'file'));
disp(sprintf(' %% Warning, %s not found in %s',tmp_XB_fname_mat,str_thisfunction));
flag_found = 0;
end;%if (~exist(tmp_XB_fname_mat,'file'));
if ( exist(tmp_XB_fname_mat,'file'));
tmp_XB_a_k_Y_ = load(tmp_XB_fname_mat);
end;%if ( exist(tmp_XB_fname_mat,'file'));
%%%%;
if ( flag_found & ~isempty(tmp_XB_align_a_k_Y_) & ~isempty(tmp_XB_a_k_Y_) );
%%%%;
tmp_X_best = tmp_XB_align_a_k_Y_.X_best_i_(end);
tmp_flag_flip = tmp_XB_align_a_k_Y_.flag_flip_i_(end);
tmp_polar_a_best = tmp_XB_align_a_k_Y_.polar_a_best_i_(end);
tmp_azimu_b_best = tmp_XB_align_a_k_Y_.azimu_b_best_i_(end);
tmp_gamma_z_best = tmp_XB_align_a_k_Y_.gamma_z_best_i_(end);
tmp_delta_x_best = tmp_XB_align_a_k_Y_.delta_best_3i__(1+0,end);
tmp_delta_y_best = tmp_XB_align_a_k_Y_.delta_best_3i__(1+1,end);
tmp_delta_z_best = tmp_XB_align_a_k_Y_.delta_best_3i__(1+2,end);
tmp_a_k_Y_reco_yk_ = tmp_XB_a_k_Y_.a_k_Y_reco_yk_;
%%%%;
[ ... 
 tmp_b_k_Y_reco_yk_ ...
] = ...
spharm_register_and_rotate_2( ...
 n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,a_k_Y_true_yk_ ...
,tmp_a_k_Y_reco_yk_ ...
,0 ...
,tmp_X_best ...
,tmp_flag_flip ...
,tmp_polar_a_best ...
,tmp_azimu_b_best ...
,tmp_gamma_z_best ...
,tmp_delta_x_best ...
,tmp_delta_y_best ...
,tmp_delta_z_best ...
);
%%%%;
[ ... 
  tmp_b_x_u_reco_xxx_ ...
] = ...
convert_spharm_to_x_c_uniform_over_n_k_p_r_5( ...
 max(0,flag_verbose-1) ...
,sample_sphere_k_eq_d ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,l_max_ ...
,tmp_b_k_Y_reco_yk_ ...
,half_diameter_x_c ...
,n_x_u_pack ...
);
%%%%;
figure(5);clf;figbig;
subplot(1,2,1);
isosurface_f_x_u_1(struct('percent_threshold_',[90,95,99]),tmp_b_x_u_reco_xxx_);
title(sprintf('tmp_b_x_u_: corr %0.4f',tmp_X_best),'Interpreter','none');
subplot(1,2,2);
isosurface_f_x_u_1(struct('percent_threshold_',[98.5]),tmp_b_x_u_reco_xxx_);
title(sprintf('tmp_b_x_u_: corr %0.4f',tmp_X_best),'Interpreter','none');
sgtitle(XB_fname_snapshot_jpg,'Interpreter','none'); drawnow();
disp(sprintf(' %% writing %s',XB_fname_snapshot_jpg));
print('-djpeg',XB_fname_snapshot_jpg);
close(gcf);
%%%%%%%%;
end;%if ( flag_found & ~isempty(tmp_XB_align_a_k_Y_) & ~isempty(tmp_XB_a_k_Y_) );
%%%%%%%%;
close_fname_tmp(XB_fname_snapshot_pre);
end;%if ~XB_fname_snapshot_flag_skip;
end;%if ( exist(XB_fname_mat,'file') & ~exist(XB_fname_snapshot_jpg) );
%%%%%%%%;

%%%%%%%%%%%%%%%%;
if flag_compare_image_rank==0;
if (flag_verbose>0); disp(sprintf(' %% flag_compare_image_rank %d, skipping',flag_compare_image_rank)); end;
end;%if flag_compare_image_rank==0;
%%%%%%%%%%%%%%%%;
if flag_compare_image_rank==1;
%%%%%%%%%%%%%%%%;
%%%%%%%%;
if ( exist(XA_fname_mat,'file') & ~exist(XA_fname_compare_image_rank_jpg) );
[XA_fname_compare_image_rank_flag_skip,XA_fname_compare_image_rank_jpg] = open_fname_tmp(XA_fname_compare_image_rank_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp,'jpg');
if ~XA_fname_compare_image_rank_flag_skip;
%%%%%%%%;
if (flag_verbose>0) disp(sprintf(' %% %s not found, creating',XA_fname_compare_image_rank_jpg)); end;
tmp_XA_parameter = parameter;
[ ...
 tmp_XA_parameter ...
] = ...
ampmut_compare_image_rank_1( ...
 tmp_XA_parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,n_M ...
,M_k_p_wkM__ ...
,n_CTF ...
,1 ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
,l_max_ ...
,a_k_Y_true_yk_ ...
,euler_polar_a_true_M_ ...
,euler_azimu_b_true_M_ ...
,euler_gamma_z_true_M_ ...
,image_delta_x_true_M_ ...
,image_delta_y_true_M_ ...
,[] ...
,XA_fname_mat ...
,XA_fname_compare_image_rank_pre ...
);
%%%%%%%%;
close_fname_tmp(XA_fname_compare_image_rank_pre);
end;%if ~XA_fname_compare_image_rank_flag_skip;
end;%if ( exist(XA_fname_mat,'file') & ~exist(XA_fname_compare_image_rank_jpg) );
%%%%%%%%;
%%%%%%%%%%%%%%%%;
%%%%%%%%;
if ( exist(XB_fname_mat,'file') & ~exist(XB_fname_compare_image_rank_jpg) );
[XB_fname_compare_image_rank_flag_skip,XB_fname_compare_image_rank_jpg] = open_fname_tmp(XB_fname_compare_image_rank_pre,date_diff_threshold,flag_force_create_mat,flag_force_create_tmp,'jpg');
if ~XB_fname_compare_image_rank_flag_skip;
%%%%%%%%;
if (flag_verbose>0) disp(sprintf(' %% %s not found, creating',XB_fname_compare_image_rank_jpg)); end;
tmp_XB_parameter = parameter;
[ ...
 tmp_XB_parameter ...
] = ...
ampmut_compare_image_rank_1( ...
 tmp_XB_parameter ...
,n_k_p_r ...
,k_p_r_ ...
,k_p_r_max ...
,weight_3d_k_p_r_ ...
,weight_2d_k_p_r_ ...
,n_w_ ...
,n_M ...
,M_k_p_wkM__ ...
,n_CTF ...
,1 ...
,index_nCTF_from_nM_ ...
,CTF_k_p_r_kC__ ...
,l_max_ ...
,a_k_Y_true_yk_ ...
,euler_polar_a_true_M_ ...
,euler_azimu_b_true_M_ ...
,euler_gamma_z_true_M_ ...
,image_delta_x_true_M_ ...
,image_delta_y_true_M_ ...
,[] ...
,XB_fname_mat ...
,XB_fname_compare_image_rank_pre ...
);
%%%%%%%%;
close_fname_tmp(XB_fname_compare_image_rank_pre);
end;%if ~XB_fname_compare_image_rank_flag_skip;
end;%if ( exist(XB_fname_mat,'file') & ~exist(XB_fname_compare_image_rank_jpg) );
%%%%%%%%;
%%%%%%%%%%%%%%%%;
end;%if flag_compare_image_rank==1;
%%%%%%%%%%%%%%%%;

if (flag_verbose>0); disp(sprintf(' %% [finished %s]',str_thisfunction)); end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
end;%if ~flag_skip_all;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;
