function ...
[ ...
 parameter ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,image_delta_x_M_ ...
,image_delta_y_M_ ...
,image_I_value_M_ ...
,image_X_value_M_ ...
,image_S_index_M_ ...
] = ...
tfpmh_MS_vs_SM_2( ...
 parameter  ...
,n_w_max ...
,n_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,n_M ...
,X_SM__ ...
,delta_x_SM__ ...
,delta_y_SM__ ...
,gamma_z_SM__ ...
,I_value_SM__ ...
);
%%%%%%%%;
flag_verbose=0;
str_thisfunction = 'tfpmh_MS_vs_SM_2';
if (flag_verbose>0); disp(sprintf(' %% [entering %s],str_thisfunction')); end;
%%%%%%%%;
na=0;
if (nargin<1+na); parameter=[]; end; na=na+1;
if (nargin<1+na); n_w_max=[]; end; na=na+1;
if (nargin<1+na); n_S=[]; end; na=na+1;
if (nargin<1+na); viewing_azimu_b_S_=[]; end; na=na+1;
if (nargin<1+na); viewing_polar_a_S_=[]; end; na=na+1;
if (nargin<1+na); n_M=[]; end; na=na+1;
if (nargin<1+na); X_SM__=[]; end; na=na+1;
if (nargin<1+na); delta_x_SM__=[]; end; na=na+1;
if (nargin<1+na); delta_y_SM__=[]; end; na=na+1;
if (nargin<1+na); gamma_z_SM__=[]; end; na=na+1;
if (nargin<1+na); I_value_SM__=[]; end; na=na+1;
%%%%%%%%;
if isempty(parameter);
parameter = struct('type','parameter');
end;%if isempty(parameter);
if isempty(I_value_SM__); I_value_SM__ = ones(size(X_SM__)); end;
%%%%%%%%;
if (~isfield(parameter,'flag_MS_vs_SM')); parameter.flag_MS_vs_SM = 1; end; %<-- parameter_bookmark. ;
flag_MS_vs_SM = parameter.flag_MS_vs_SM;

%%%%%%%%%%%%%%%%;
if flag_MS_vs_SM==1; %<-- assign images to templates, ensuring a uniform distribution of viewing angles. ;
tmp_t = tic();
[ ...
 parameter ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,image_delta_x_M_ ...
,image_delta_y_M_ ...
,image_I_value_M_ ...
,image_X_value_M_ ...
,image_S_index_M_ ...
] = ...
tfpmh_MS_uniform_2( ...
 parameter ...
,n_w_max ...
,n_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,n_M ...
,X_SM__ ...
,delta_x_SM__ ...
,delta_y_SM__ ...
,gamma_z_SM__ ...
,I_value_SM__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% MS: update euler_polar_a_ euler_azimu_b_ euler_gamma_z_ : %0.3fs',tmp_t)); end;
end;%if flag_MS_vs_SM==1; %<-- assign images to templates, ensuring a uniform distribution of viewing angles. ;
if flag_MS_vs_SM==0; %<-- assign templates to images (uses leslie f_rand). ;
if (~isfield(parameter,'f_rand')); parameter.f_rand = 0.05; end; %<-- parameter_bookmark. ;
f_rand = parameter.f_rand;
tmp_t = tic();
[ ...
 parameter ...
,euler_polar_a_M_ ...
,euler_azimu_b_M_ ...
,euler_gamma_z_M_ ...
,image_delta_x_M_ ...
,image_delta_y_M_ ...
,image_I_value_M_ ...
,image_X_value_M_ ...
,image_S_index_M_ ...
] = ...
tfpmh_SM_uniform_3( ...
 parameter ...
,n_S ...
,viewing_azimu_b_S_ ...
,viewing_polar_a_S_ ...
,n_M ...
,X_SM__ ...
,delta_x_SM__ ...
,delta_y_SM__ ...
,gamma_z_SM__ ...
,I_value_SM__ ...
);
tmp_t = toc(tmp_t); if (flag_verbose>1); disp(sprintf(' %% SM: update euler_polar_a_ euler_azimu_b_ euler_gamma_z_ : %0.3fs',tmp_t)); end;
end;%if flag_MS_vs_SM==0; %<-- assign templates to images (uses leslie f_rand). ;
%%%%%%%%%%%%%%%%;

if (flag_verbose>0); disp(sprintf(' %% [finished %s],str_thisfunction')); end;

