/* File: get_angle_to_vp_module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Sep 20 18:29:05 2019
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *get_angle_to_vp__error;
static PyObject *get_angle_to_vp__module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = get_angle_to_vp__error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(get_angle_to_vp_,GET_ANGLE_TO_VP_)(double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** get_angle_to_vp_ ******************************/
static char doc_f2py_rout_get_angle_to_vp__get_angle_to_vp_[] = "\
Function signature:\n\
  get_angle_to_vp_(alpha_polar_a,alpha_azimu_b,vp_)\n\
Required arguments:\n"
"  alpha_polar_a : input float\n"
"  alpha_azimu_b : input float\n"
"  vp_ : input rank-1 array('d') with bounds (3)";
/* extern void F_FUNC_US(get_angle_to_vp_,GET_ANGLE_TO_VP_)(double*,double*,double*); */
static PyObject *f2py_rout_get_angle_to_vp__get_angle_to_vp_(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double alpha_polar_a = 0;
  PyObject *alpha_polar_a_capi = Py_None;
  double alpha_azimu_b = 0;
  PyObject *alpha_azimu_b_capi = Py_None;
  double *vp_ = NULL;
  npy_intp vp__Dims[1] = {-1};
  const int vp__Rank = 1;
  PyArrayObject *capi_vp__tmp = NULL;
  int capi_vp__intent = 0;
  PyObject *vp__capi = Py_None;
  static char *capi_kwlist[] = {"alpha_polar_a","alpha_azimu_b","vp_",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:get_angle_to_vp_.get_angle_to_vp_",\
    capi_kwlist,&alpha_polar_a_capi,&alpha_azimu_b_capi,&vp__capi))
    return NULL;
/*frompyobj*/
  /* Processing variable alpha_polar_a */
    f2py_success = double_from_pyobj(&alpha_polar_a,alpha_polar_a_capi,"get_angle_to_vp_.get_angle_to_vp_() 1st argument (alpha_polar_a) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vp_ */
  vp__Dims[0]=3;
  capi_vp__intent |= F2PY_INTENT_IN;
  capi_vp__tmp = array_from_pyobj(NPY_DOUBLE,vp__Dims,vp__Rank,capi_vp__intent,vp__capi);
  if (capi_vp__tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(get_angle_to_vp__error,"failed in converting 3rd argument `vp_' of get_angle_to_vp_.get_angle_to_vp_ to C/Fortran array" );
  } else {
    vp_ = (double *)(capi_vp__tmp->data);

  /* Processing variable alpha_azimu_b */
    f2py_success = double_from_pyobj(&alpha_azimu_b,alpha_azimu_b_capi,"get_angle_to_vp_.get_angle_to_vp_() 2nd argument (alpha_azimu_b) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&alpha_polar_a,&alpha_azimu_b,vp_);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of alpha_azimu_b*/
  /* End of cleaning variable alpha_azimu_b */
  if((PyObject *)capi_vp__tmp!=vp__capi) {
    Py_XDECREF(capi_vp__tmp); }
  }  /*if (capi_vp__tmp == NULL) ... else of vp_*/
  /* End of cleaning variable vp_ */
  } /*if (f2py_success) of alpha_polar_a*/
  /* End of cleaning variable alpha_polar_a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of get_angle_to_vp_ **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"get_angle_to_vp_",-1,{{-1}},0,(char *)F_FUNC_US(get_angle_to_vp_,GET_ANGLE_TO_VP_),(f2py_init_func)f2py_rout_get_angle_to_vp__get_angle_to_vp_,doc_f2py_rout_get_angle_to_vp__get_angle_to_vp_},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "get_angle_to_vp_",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_get_angle_to_vp_(void) {
#else
#define RETVAL
PyMODINIT_FUNC initget_angle_to_vp_(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = get_angle_to_vp__module = PyModule_Create(&moduledef);
#else
  m = get_angle_to_vp__module = Py_InitModule("get_angle_to_vp_", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module get_angle_to_vp_ (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'get_angle_to_vp_' is auto-generated with f2py (version:2).\nFunctions:\n"
"  get_angle_to_vp_(alpha_polar_a,alpha_azimu_b,vp_)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  get_angle_to_vp__error = PyErr_NewException ("get_angle_to_vp_.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"get_angle_to_vp_");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
