%%%%%%%%;
% generating inital volume as sum of gaussians. ;
%%%%%%%%;
n_source = 64;
source_x_ = zeros(n_source,1); source_y_ = zeros(n_source,1); source_z_ = zeros(n_source,1);
source_r_ = zeros(n_source,1); source_polar_a_ = zeros(n_source,1); source_azimu_b_ = zeros(n_source,1);
for nsource=1:n_source;
tmp_r = nsource/n_source;
tmp_w = 2*pi*nsource/n_source;
tmp_x = 0.75*tmp_r*cos(3*tmp_w);
tmp_y = 0.75*tmp_r*sin(3*tmp_w);
tmp_z = 0.75*(2*tmp_r-1);
source_x_(nsource) = tmp_x;
source_y_(nsource) = tmp_y;
source_z_(nsource) = tmp_z;
source_r_(nsource) = sqrt(tmp_x.^2 + tmp_y.^2 + tmp_z.^2); 
source_polar_a_(nsource) = atan2(sqrt(tmp_x.^2 + tmp_y.^2),tmp_z);
source_azimu_b_(nsource) = atan2(tmp_y,tmp_x);
end;%for nsource=1:n_source;
%%%%%%%%;
flag_plot=0;
if flag_plot;
hold on;
plot3(source_x_,source_y_,source_z_,'o'); 
plot3(source_r_.*cos(source_azimu_b_).*sin(source_polar_a_),source_r_.*sin(source_azimu_b_).*sin(source_polar_a_),source_r_.*cos(source_polar_a_),'.'); 
hold off;
axis vis3d;
disp('returning'); return;
end;%if flag_plot;
%%%%%%%%;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%;

%%%%%%%%;
% Now creating fourier values on shell of radius k_r.; 
%%%%%%%%;
sigma = 0.1;
k_r = 2;
Fk = (1/sqrt(2*pi).^3) / sigma.^3 * sigma.^3 * exp(-0.5 * k_r.^2 ./ (1 ./ sigma).^2 );
n_azimu_b = 128;
azimu_b_k_ = linspace(0,2*pi,n_azimu_b+1); azimu_b_k_ = azimu_b_k_(1:end-1);
n_polar_a = n_azimu_b/2;
polar_a_k_ = linspace(0,pi,n_polar_a);
F__ = zeros(n_azimu_b,n_polar_a);
for nazimu_b=1:n_azimu_b;
azimu_b_k = azimu_b_k_(nazimu_b);
for npolar_a=1:n_polar_a;
polar_a_k = polar_a_k_(npolar_a);
k_x = k_r*cos(azimu_b_k)*sin(polar_a_k);
k_y = k_r*sin(azimu_b_k)*sin(polar_a_k);
k_z = k_r*cos(polar_a_k);
for nsource=1:n_source;
F__(nazimu_b,npolar_a) = F__(nazimu_b,npolar_a) + Fk * exp( i* ( k_x*source_x_(nsource) + k_y*source_y_(nsource) + k_z*source_z_(nsource) ) ) ;
end;%for nsource=1:n_source;
end;%for npolar_a=1:n_polar_a;
end;%for nazimu_b=1:n_azimu_b;
%%%%%%%%;
%
%
%%%%%%%%;
flag_plot=1;
if flag_plot;
c_hsv_ = colormap('hsv');
%%%%%%%%;
subplot(1,2,1);
p_x_ = zeros(4,n_azimu_b*n_polar_a);
p_y_ = zeros(4,n_azimu_b*n_polar_a);
p_z_ = zeros(4,n_azimu_b*n_polar_a);
p_c_ = zeros(4,n_azimu_b*n_polar_a,3);
dazimu_b = mean(diff(azimu_b_k_));
na=0;
for nazimu_b=1:n_azimu_b;
azimu_b_k_pre = azimu_b_k_(nazimu_b) - dazimu_b/2;
azimu_b_k_cur = azimu_b_k_(nazimu_b);
azimu_b_k_pos = azimu_b_k_(nazimu_b) + dazimu_b/2;
for npolar_a=1:n_polar_a;
polar_a_k_pre = 0.5*(polar_a_k_(npolar_a) + polar_a_k_(max(1,npolar_a-1)));
polar_a_k_cur = polar_a_k_(npolar_a);
polar_a_k_pos = 0.5*(polar_a_k_(npolar_a) + polar_a_k_(min(n_polar_a,npolar_a+1)));
k_x_cur_cur = k_r*cos(azimu_b_k_cur)*sin(polar_a_k_cur); k_y_cur_cur = k_r*sin(azimu_b_k_cur)*sin(polar_a_k_cur); k_z_cur_cur = k_r*cos(polar_a_k_cur);
k_x_pre_pre = k_r*cos(azimu_b_k_pre)*sin(polar_a_k_pre); k_y_pre_pre = k_r*sin(azimu_b_k_pre)*sin(polar_a_k_pre); k_z_pre_pre = k_r*cos(polar_a_k_pre);
k_x_pre_pos = k_r*cos(azimu_b_k_pre)*sin(polar_a_k_pos); k_y_pre_pos = k_r*sin(azimu_b_k_pre)*sin(polar_a_k_pos); k_z_pre_pos = k_r*cos(polar_a_k_pos);
k_x_pos_pre = k_r*cos(azimu_b_k_pos)*sin(polar_a_k_pre); k_y_pos_pre = k_r*sin(azimu_b_k_pos)*sin(polar_a_k_pre); k_z_pos_pre = k_r*cos(polar_a_k_pre);
k_x_pos_pos = k_r*cos(azimu_b_k_pos)*sin(polar_a_k_pos); k_y_pos_pos = k_r*sin(azimu_b_k_pos)*sin(polar_a_k_pos); k_z_pos_pos = k_r*cos(polar_a_k_pos);
p_x_(:,1+na) = [k_x_pre_pre;k_x_pos_pre;k_x_pos_pos;k_x_pre_pos];
p_y_(:,1+na) = [k_y_pre_pre;k_y_pos_pre;k_y_pos_pos;k_y_pre_pos];
p_z_(:,1+na) = [k_z_pre_pre;k_z_pos_pre;k_z_pos_pos;k_z_pre_pos];
p_c_(:,1+na,:) = repmat(colorsphere_trio(polar_a_k_cur,azimu_b_k_cur,c_hsv_),4,1);
na=na+1;
end;%for npolar_a=1:n_polar_a;
end;%for nazimu_b=1:n_azimu_b;
p = patch(p_x_,p_y_,p_z_,p_c_); set(p,'EdgeColor','none');
axis vis3d; view(10,25);
end;%if flag_plot
%
%
%%%%%%%%;
flag_plot=1;
if flag_plot;
c_hsv_ = colormap('hsv');
subplot(1,2,2);
p_real_ = zeros(4,n_azimu_b*n_polar_a);
p_imag_ = zeros(4,n_azimu_b*n_polar_a);
p_c_ = zeros(4,n_azimu_b*n_polar_a,3);
dazimu_b = mean(diff(azimu_b_k_));
na=0;
for nazimu_b=1:n_azimu_b;
nazimu_b_pre = nazimu_b-1; if (nazimu_b_pre<1); nazimu_b_pre = n_azimu_b; end;
nazimu_b_cur = nazimu_b;
azimu_b_k_cur = azimu_b_k_(nazimu_b);
nazimu_b_pos = nazimu_b+1; if (nazimu_b_pos>n_azimu_b); nazimu_b_pos = 1; end;
for npolar_a=1:n_polar_a;
npolar_a_pre = max(1,npolar_a-1);
npolar_a_cur = npolar_a;
polar_a_k_cur = polar_a_k_(npolar_a);
polar_a_k_cur = polar_a_k_(npolar_a);
npolar_a_pos = min(n_polar_a,npolar_a+1);
k_real_cur_cur = real(F__(nazimu_b_cur,npolar_a_cur));
k_real_pre_pre = 0.5 * (real(F__(nazimu_b_pre,npolar_a_pre)) + real(F__(nazimu_b_cur,npolar_a_cur)));
k_real_pre_pos = 0.5 * (real(F__(nazimu_b_pre,npolar_a_pos)) + real(F__(nazimu_b_cur,npolar_a_cur)));
k_real_pos_pre = 0.5 * (real(F__(nazimu_b_pos,npolar_a_pre)) + real(F__(nazimu_b_cur,npolar_a_cur)));
k_real_pos_pos = 0.5 * (real(F__(nazimu_b_pos,npolar_a_pos)) + real(F__(nazimu_b_cur,npolar_a_cur)));
k_imag_cur_cur = imag(F__(nazimu_b_cur,npolar_a_cur));
k_imag_pre_pre = 0.5 * (imag(F__(nazimu_b_pre,npolar_a_pre)) + imag(F__(nazimu_b_cur,npolar_a_cur)));
k_imag_pre_pos = 0.5 * (imag(F__(nazimu_b_pre,npolar_a_pos)) + imag(F__(nazimu_b_cur,npolar_a_cur)));
k_imag_pos_pre = 0.5 * (imag(F__(nazimu_b_pos,npolar_a_pre)) + imag(F__(nazimu_b_cur,npolar_a_cur)));
k_imag_pos_pos = 0.5 * (imag(F__(nazimu_b_pos,npolar_a_pos)) + imag(F__(nazimu_b_cur,npolar_a_cur)));
p_real_(:,1+na) = [k_real_pre_pre;k_real_pos_pre;k_real_pos_pos;k_real_pre_pos];
p_imag_(:,1+na) = [k_imag_pre_pre;k_imag_pos_pre;k_imag_pos_pos;k_imag_pre_pos];
p_c_(:,1+na,:) = repmat(colorsphere_trio(polar_a_k_cur,azimu_b_k_cur,c_hsv_),4,1);
hold on; plot(k_real_cur_cur,k_imag_cur_cur,'.','Color',colorsphere_trio(polar_a_k_cur,azimu_b_k_cur,c_hsv_)); hold off;
na=na+1;
end;%for npolar_a=1:n_polar_a;
end;%for nazimu_b=1:n_azimu_b;
xl_ = [-1.5,5]; yl_ = 1.5*[-1,+1];
%hold on; p = patch(p_real_,p_imag_,p_c_); set(p,'EdgeColor','none'); plot(xl_,[0,0],'k:'); plot([0,0],yl_,'k:');
xlim(xl_); ylim(yl_); title(sprintf('k%0.2f',k_r));
%text(-1,+1,sprintf('k%0.2f',k_r));
set(gca,'Xtick',[],'Ytick',[]);
%%%%%%%%;
end;%if flag_plot;
%%%%%%%%;
set(gcf,'Position',1+[0,0,1024*2,1024]);
dir_trunk = sprintf('/data/rangan/dir_cryoem/dir_rangan_playhouse');
tmp_fname = sprintf('%s/dir_freq_march/freq_march_3_figC_k%d',dir_trunk,k_r);
disp(sprintf(' %% writing %s',sprintf('%s.jpg',tmp_fname)));
print('-djpeg',sprintf('%s.jpg',tmp_fname));

