%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
% Generating initial S_x_c_ ;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ;
tic;
n_r = 64;
n_x = 2*n_r+1; n_y = 2*n_r+1;
max_x_c = 1.0; max_y_c = 1.0;
grid_x_c_ = linspace(-max_x_c/2,+max_x_c/2,n_x);
x_c_ = linspace(-max_x_c/2,+max_x_c/2,n_x);
y_c_ = linspace(-max_y_c/2,+max_y_c/2,n_y);
X_c_ = ones(n_y,1)*x_c_;
Y_c_ = transpose(y_c_)*ones(1,n_x);
%nS_sample = 0; param_1 = nS_sample*sqrt(2.5d0); param_2 = 2*(nS_sample+2);
param_1 = sqrt(2.5d0); param_2 = 2*(1+2);
S_x_c_ = get_F2_x_c_(n_x,max_x_c/2+grid_x_c_,max_x_c,n_x,max_x_c/2+grid_x_c_,max_x_c,param_1,param_2);
S_x_c_ = reshape(S_x_c_,n_x,n_x);
tmp_kx_ij = -0.5 + n_x/2 + (-n_r:n_r); tmp_ky_ij = -0.5 + n_x/2 + (-n_r:n_r);
S_k_c_ = fft2(S_x_c_); S_k_c_ = recenter2(S_k_c_); S_k_c_ = S_k_c_(1+tmp_kx_ij,1+tmp_ky_ij); S_k_c_ = decenter2(S_k_c_);
max_k_c = 1.0*2*n_r/max_x_c;
half_diameter_k_c = max_k_c/2.0;
k_c_ = linspace(-max_k_c/2,+max_k_c/2,2*n_r+1);

%%%%%%%%;
% Now show the consequences of slice rearrangement. ;
%%%%%%%%;
flag_disp=1;
if flag_disp;
%%%%%%%%;
subplot(2,4,1);
imagesc_c(2*n_r+1,k_c_,2*n_r+1,k_c_,real(decenter2(S_k_c_)),[],colormap(colormap_beach()));
xlim(max_k_c/2*[-1,1]);ylim(max_k_c/2*[-1,1]);
title('real(S_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]);
%%%%%%%%;
tmp_w_ = linspace(-1,1,2*n_r+1);
tmp_z_ = pi*(1+tmp_w_);
tmp_s_ = transpose((0.5*(1+cos(tmp_z_))).^(0.5));
A_k_c_ = S_k_c_;
A_k_c_ = recenter2(A_k_c_);
A_k_c_ = A_k_c_.*(tmp_s_*transpose(tmp_s_));
A_k_c_ = decenter2(A_k_c_);
subplot(2,4,2);
imagesc_c(2*n_r+1,k_c_,2*n_r+1,k_c_,real(decenter2(A_k_c_)),[],colormap(colormap_beach()));
xlim(max_k_c/2*[-1,1]);ylim(max_k_c/2*[-1,1]);
title('real(A_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]);
%%%%%%%%;
B_k_c_ = A_k_c_;
B_k_c_ = recenter2(B_k_c_);
%for nr=0:n_r-1;for nc=0:n_r-1;
for nr=1:n_r;for nc=1:n_r;
tmp_d = B_k_c_(1+n_r+nr,1+n_r+nc); 
B_k_c_(1+n_r+nr,1+n_r+nc) = B_k_c_(1+n_r-nc,1+n_r+nr);
B_k_c_(1+n_r-nc,1+n_r+nr) = tmp_d; 
tmp_d = B_k_c_(1+n_r-nr,1+n_r-nc); 
B_k_c_(1+n_r-nr,1+n_r-nc) = B_k_c_(1+n_r+nc,1+n_r-nr);
B_k_c_(1+n_r+nc,1+n_r-nr) = tmp_d; 
end;end;%for nr=1:n_r;for nc=1:n_r;
%end;end;%for nr=0:n_r-1;for nc=0:n_r-1;
B_k_c_ = decenter2(B_k_c_);
subplot(2,4,3);
imagesc_c(2*n_r+1,k_c_,2*n_r+1,k_c_,real(decenter2(B_k_c_)),[],colormap(colormap_beach()));
xlim(max_k_c/2*[-1,1]);ylim(max_k_c/2*[-1,1]);
title('real(B_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]);
%%%%%%%%;
C_k_c_ = A_k_c_;
C_k_c_ = recenter2(C_k_c_);
C_k_c_(1+n_r+(1:n_r),1+n_r+(1:n_r)) = transpose(C_k_c_(1+n_r+(1:n_r),1+n_r+(1:n_r)));
C_k_c_(1+n_r-(1:n_r),1+n_r-(1:n_r)) = transpose(C_k_c_(1+n_r-(1:n_r),1+n_r-(1:n_r)));
C_k_c_ = decenter2(C_k_c_);
subplot(2,4,4);
imagesc_c(2*n_r+1,k_c_,2*n_r+1,k_c_,real(decenter2(C_k_c_)),[],colormap(colormap_beach()));
xlim(max_k_c/2*[-1,1]);ylim(max_k_c/2*[-1,1]);
title('real(C_k_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[]);
%%%%%%%%;
T_x_c_ = ifft2(S_k_c_);
A_x_c_ = ifft2(A_k_c_);
B_x_c_ = ifft2(B_k_c_);
C_x_c_ = ifft2(C_k_c_);
subplot(2,4,5);
imagesc_c(n_x,x_c_,n_y,y_c_,real(decenter2(T_x_c_)),[],colormap(colormap_beach()));
xlim(max_x_c/2*[-1,1]);ylim(max_y_c/2*[-1,1]);
title('real(T_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,4,6);
imagesc_c(n_x,x_c_,n_y,y_c_,real(decenter2(A_x_c_)),[],colormap(colormap_beach()));
xlim(max_x_c/2*[-1,1]);ylim(max_y_c/2*[-1,1]);
title('real(A_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,4,7);
imagesc_c(n_x,x_c_,n_y,y_c_,real(decenter2(B_x_c_)),[],colormap(colormap_beach()));
xlim(max_x_c/2*[-1,1]);ylim(max_y_c/2*[-1,1]);
title('real(B_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
subplot(2,4,8);
imagesc_c(n_x,x_c_,n_y,y_c_,real(decenter2(C_x_c_)),[],colormap(colormap_beach()));
xlim(max_x_c/2*[-1,1]);ylim(max_y_c/2*[-1,1]);
title('real(C_x_c_)','Interpreter','none');
set(gca,'XTick',[],'YTick',[],'Ydir','normal'); axis square;
%%%%%%%%;
figbig;
dir_trunk = sprintf('/data/rangan/dir_cryoem/dir_rangan_playhouse');
tmp_fname = sprintf('%s/dir_freq_march/test_2d_slice_0_P',dir_trunk);
disp(sprintf(' %% writing %s',sprintf('%s.jpg',tmp_fname)));
print('-djpeg',sprintf('%s.jpg',tmp_fname));
disp('returning'); return;
end;%if flag_disp;

